### ISSUE TITLE
looking for a way to create a pool(rbd) in ceph luminous on ceph cluster startup

### ISSUE THREAD

**Issue by jamstar** [ceph/ceph-container#1015]
So in our kubernetes cluster(s), i am switching from kracken to luminous.  with the change in luminous to no longer create a pool by default (such as rbd), i need to make one now when the ceph cluster starts.  

i have an ansible installer that provisions and configures everything for my ceph cluster. i can always use that to create the pool but im looking if there is something better. 

is there a switch, command line option, something that lets me specify the pool name to create when the cluster starts up if it doesn't exist?   I looked through the code but didn't see anything that allows me to create the rbd pool at startup if it doesnt exist.  I see that the start_mds.sh has where it creates the data pool and metadatapool but thats different. 

Thanks for your support.

**Comment by jamstar** [comment]
still looking for an answer if one exists.

**Comment by leseb** [comment]
There is no hook at the moment to do such thing. I'll personally implement this through an Ansible task for now.
I think we want to move away from what `start_mds.sh` does. These particular actions should be done externally by another entity. The problem with the current approach is that it'll require admin keys, which means putting it on almost all the nodes, which is clearly not a good idea.

Hope that helps.

**Comment by jamstar** [comment]
thanks. yes, it does does help. ill just keep doing the way i have it for now which is using ansible to do it.   Thank you for your reply.
