### ISSUE TITLE
BASE_IMAGE is not considered in  DAEMON_BASE_IMAGE & DAEMON_IMAGE

### ISSUE THREAD

**Issue by ErwanAliasr1** [ceph/ceph-container#1028]
When I build the arm64 code with a BASE_IMAGE override, DAEMON_BASE_IMAGE  & DAEMON_IMAGE consider the real name aka centos-arm64.

If I do force the BASE_IMAGE, it should be kept during the push too unless when I try to push it with the expected name, it fails.

++ make RELEASE=master-0026986 FLAVORS=luminous,centos-arm64,7 BASE_IMAGE=centos:7 push

  CEPH_VERSION      : luminous
  CEPH_POINT_RELEASE: 
  HOST_ARCH         : aarch64
  BASEOS_REGISTRY   : _
  BASEOS_REPO       : centos-arm64
  BASEOS_TAG        : 7
  IMAGES_TO_BUILD   : daemon-base daemon
  STAGING_DIR       : staging/luminous-centos-arm64-7-aarch64
  RELEASE           : master-0026986
  DAEMON_BASE_IMAGE : ceph/daemon-base:master-0026986-luminous-centos-arm64-7-aarch64
  DAEMON_IMAGE      : ceph/daemon:master-0026986-luminous-centos-arm64-7-aarch64

[...]
++ tag=ceph/daemon-base:master-0026986-luminous-centos-7-aarch64
++ docker tag ceph/daemon-base:master-0026986-luminous-centos-7-aarch64 ceph/daemon-base:latest-luminous
Error response from daemon: no such id: ceph/daemon-base:master-0026986-luminous-centos-7-aarch64

**Comment by ErwanAliasr1** [comment]
poke @BlaineEXE

**Comment by BlaineEXE** [comment]
I don't like `SOURCE_VERSION`, as that could be confused with the version of our source. Maybe the revised fields should just be `DISTRO` and `DISTRO_VERSION`.
