### ISSUE TITLE
rbd: failed to add secret 'client.admin' to kernel

### ISSUE THREAD

**Issue by Futvin** [ceph/ceph-container#1030]
I am getting this message when I am trying to run a container, mounting a volume.  I can rbd map and mount this volume on the host without a problem.  I am running Ubuntu 16.04 LTS, with the hwe kernel as my host.

Here is the docker command I am running to mount an rbd volume to a container:

```
# docker run -it --dns 10.0.0.1 --volume /etc/ceph:/etc/ceph --volume /var/lib/ceph:/var/lib/ceph -e RBD_IMAGE=vol01 -e RBD_POOL=vols ceph/rbd-volume /bin/bash
rbd: failed to add secret 'client.admin' to kernel
rbd: map failed: (1) Operation not permitted
# 
```

I have tried to create my own ubuntu container, installing all of the pieces, and I get the same error.  I think that the problem is that ceph cannot add_key from keyutils.h.  So I tried to install some different things into my strait ubuntu container, thinking that I might be missing what the keyutil talks to.

Any thoughts?

**Comment by idryomov** [comment]
docker blocks add_key(2) and other key management related system calls with seccomp because the kernel keyring is global.  See https://docs.docker.com/engine/security/seccomp/.
