### ISSUE TITLE
ceph-fuse mount error

### ISSUE THREAD

**Issue by jagerzhang** [ceph/ceph-container#1031]
Hi, when i use ceph-fuse to mount cephfs, it was report those error:
```
ceph-fuse -m 192.168.1.100:6789:/ /test
```
```
2018-04-22 13:37:11.147297 7f0916675780 -1 did not load config file, using default settings.
ceph-fuse[32483]: starting ceph client

ceph-fuse[32483]: ceph mount failed with (110) Connection timed out2018-04-22 13:42:11.164922 7f0916675780 -1 
monclient(hunting): authenticate NOTE: no keyring found; disabled cephx authentication
ceph-fuse[32479]: mount failed: (110) Connection timed out
```

and, when i replace it by mount , the error reported still:
mount -t ceph 192.169.1.100:6789:/ /test
```
mount error 5 = Input/output error
```

I don't know how to fix it, anyone could help me ?

### The Ceph Cluster info
docker exec mon ceph -s
```
  cluster:
    id:     a5d3dd48-dff4-4765-ba05-2b543e6b70e1
    health: HEALTH_OK
 
  services:
    mon:        3 daemons, quorum ceph1,ceph3,ceph2
    mgr:        ceph1(active), standbys: ceph2, ceph3
    mds:        iyunwei-1/1/1 up  {0=ceph3=up:active}, 2 up:standby
    osd:        29 osds: 29 up, 29 in
    rbd-mirror: 3 daemons active
    rgw:        3 daemons active
 
  data:
    pools:   6 pools, 1056 pgs
    objects: 240 objects, 3359 bytes
    usage:   6622 MB used, 53994 GB / 54001 GB avail
    pgs:     1056 active+clean
```

docker exec mon rados lspools
```
.rgw.root
default.rgw.control
default.rgw.meta
default.rgw.log
cephfs_data
cephfs_metadata
```

**Comment by gvikram18** [comment]
![Screenshot from 2019-05-30 11-22-43](https://user-images.githubusercontent.com/28858181/58611942-7e93cc80-82ce-11e9-82ea-7265e7d7d1fa.png)

Even i was facing the same error. I immediately removed the mds and cephfs pools and added them freshly. I followed these links. The second one for the entry in /etc/fstab

[1]http://docs.ceph.com/docs/mimic/start/quick-cephfs/

[2]https://www.howtoforge.com/tutorial/how-to-mount-cephfs-on-centos-7/#step-mount-cephfs-using-fstab

![Screenshot from 2019-05-30 11-34-11](https://user-images.githubusercontent.com/28858181/58612152-388b3880-82cf-11e9-81be-53f03eb70d3d.png)
![Screenshot from 2019-05-30 11-34-24](https://user-images.githubusercontent.com/28858181/58612156-3e811980-82cf-11e9-8aae-626b5a3442f7.png)

I have copied some files inside the mounted file to verify whether it's working or not. Seems good.
