### ISSUE TITLE
Data loss with luminous on Kubernetes

### ISSUE THREAD

**Issue by timn** [ceph/ceph-container#1040]
We are using Ceph 12.2.3 on Kubernetes 1.9 to pool storage from a (small) number of commodity machines and to ensure some robustness (erasure coding). This used to work perfectly with Kraken. Since our upgrade to Luminous, we experience frequent data loss.

The error occurs if a node goes down for some limited (but seemingly too long) time. The error is similar to this one:
ceph-4.1 |  ceph version 12.2.3 (2dab17a455c09584f2a85e6b10888337d1ec8949) luminous (stable)
ceph-4.1 |  1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x110) [0x562927a714f0]
ceph-4.1 |  2: (pi_compact_rep::add_interval(bool, PastIntervals::pg_interval_t const&)+0x3b2) [0x56292773e422]
ceph-4.1 |  3: (PastIntervals::check_new_interval(int, int, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, int, int, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, unsigned int, unsigned int, std::shared_ptr<OSDMap const>, std::shared_ptr<OSDMap const>, pg_t, IsPGRecoverablePredicate*, PastIntervals*, std::ostream*)+0x380) [0x562927725640]
ceph-4.1 |  4: (OSD::build_past_intervals_parallel()+0x9ff) [0x5629274e776f]
ceph-4.1 |  5: (OSD::load_pgs()+0x545) [0x5629274ea055]
ceph-4.1 |  6: (OSD::init()+0x2169) [0x562927508999]
ceph-4.1 |  7: (main()+0x2d07) [0x56292740cd97]
ceph-4.1 |  8: (__libc_start_main()+0xf5) [0x7f4470553c05]
ceph-4.1 |  9: (()+0x4b53a3) [0x5629274ab3a3]

The following ceph bug looks related:
http://tracker.ceph.com/issues/21142

More detailed setup:
Developer/student desktops are used as a cluster when not in use on Fedora 27, kubeadm created cluster K8s 1.9. Sometimes, nodes will drop out and must be restarted. If this does not happen within a short time (e.g., over the weekend), the error occurs.

For now, we will go back to Kraken, as this was far more stable for our use case. While this may not be the typical anticipated ceph scenario, it does provide us with powerful storage features allowing us to more effectively pool commodity hardware. I would assume that this should still work with luminous.

Question, and why I'm posting this here, is there something that can be done, e.g., parameter-wise, to make K8s-based ceph clusters more robust against this sort of error?

**Comment by jamstar** [comment]
i hit this same issue.    we run our devel clusters on vms.  well the machine one of our clusters was on crashed and when it came back up, 2/5 osds had this issue. 

the bug says how to fix it but im not sure exatly how to apply this to ceph-container.  my OSD run as deamonsets.

**Comment by hunter** [comment]
We also ran into the same [issue](http://tracker.ceph.com/issues/21142#note-11). Despite the work around we had to rebuild the cluster completely.
