### ISSUE TITLE
CEPH_POINT_RELEASE is not populated

### ISSUE THREAD

**Issue by leseb** [ceph/ceph-container#1044]
Extracted from `env`:
```
PWD=/
CEPH_VERSION=luminous
LANG=en_US.UTF-8
SHLVL=1
HOME=/root
CEPH_POINT_RELEASE=
_=/usr/bin/env
```

**Comment by ErwanAliasr1** [comment]
I did a fresh build and checked before & after the build and this variable doesn't pop.
Note that this variable is not directly used as the version is encoded in the ceph version.

The sole code to expose it is the testing : tests/stage-test/test_staging.sh

I don't see a big issue here.
