### ISSUE TITLE
staging dir owned by root:root

### ISSUE THREAD

**Issue by djgalloway** [ceph/ceph-container#1048]
ceph-container nightly Jenkins jobs are failing on static slaves because the staging dir gets created and is owned (recursively) by root:root.  The jobs fail immediately when they try to wipe out the workspace.

I'm wondering if the staging dir needs to be owned by root.  If not, I will try to find a way to use sudo to clean it up.

E.g., https://2.jenkins.ceph.com/job/ceph-container-nightly-ceph_ansible-luminous-xenial-bluestore_osds_container/178/console

**Comment by BlaineEXE** [comment]
@djgalloway I can't say if there is a reason the Jenkins jobs are running builds as root (I think perhaps they use `sudo make ...`), but as a general statement about the project, there is no need for staging to be owned by root or for make to be run with sudo; that may be a constraint of the test environment?

**Comment by djgalloway** [comment]
I wouldn't know why sudo is used.  I'm guessing it's this line: https://github.com/ceph/ceph-container/blob/9845b508b90514bb625d33fd96a67374b0c60224/tests/tox.sh#L96

@ErwanAliasr1 is sudo needed there?

**Comment by djgalloway** [comment]
I've filed https://github.com/ceph/ceph-container/pull/1173 to chown the staging dir to the Jenkins user at the end of a test.
