### ISSUE TITLE
Running RGW standalone

### ISSUE THREAD

**Issue by andor44** [ceph/ceph-container#1051]
I have an existing Ceph cluster. I'd like to run RGW separate of that, in a docker container. I figured I could just do the stuff in [here](https://github.com/ceph/ceph-container/blob/cd6fb098aa764807d7ee51c0c5323b54dc0adad4/src/daemon/start_rgw.sh#L14-L27) by hand and then mount the keyring file into the container, plus override `RGW_KEYRING`. Unfortunately [this part](https://github.com/ceph/ceph-container/blob/cd6fb098aa764807d7ee51c0c5323b54dc0adad4/src/daemon/variables_entrypoint.sh#L105) unconditionally overwrites that. It is rather silly that the location of the keyring is hardcoded like that.

**Comment by leseb** [comment]
It's not silly, just because that's the way keyring are declared in a best practice deployment. Not sure what's the issue here, why don't you let the container create that key for you? Or create it yourself and put it in the right location.

**Comment by leseb** [comment]
I guess we enforced them because we thought they didn't have to change. Feel free to submit a PR to make them overwritable :).
