### ISSUE TITLE
Reduce the number of default `FLAVORS` in Makefile

### ISSUE THREAD

**Issue by BlaineEXE** [ceph/ceph-container#1068]
It seems to me that there are too many default `FLAVORS` set in the `Makefile`. In my mind, the `FLAVORS` variable should actually by default only build a single set of daemon{,-base} images, which would be luminous,centos,7 I would think. I think that for most users, who pull down this project, they will just want to build enough containers to try the project out without building too many things.

`ALL_BUILDABLE_FLAVORS` then can be considered a list of ceph+distro builds that are supported by the ceph-container project and which, because they are supported, will be built and pushed upstream.

**Comment by BlaineEXE** [comment]
@ErwanAliasr1 @leseb

**Comment by leseb** [comment]
I agree default should represent only one flavor and centos sounds like a good candidate. If we go that path we will have to update our CI scripts which shouldn't be a problem.

**Comment by BlaineEXE** [comment]
@ErwanAliasr1 : #1069 changes the build/push process to build/push `ALL_BUILDABLE_FLAVORS`, which now is building opensuse. =)
