### ISSUE TITLE
`latest-luminous-centos-7-<arch>` for use as Rook base

### ISSUE THREAD

**Issue by BlaineEXE** [ceph/ceph-container#1070]
Currently for Rook, I am using `ceph/daemon-base:v3.0.5-stable-3.0-luminous-centos-7-$(PLATFORM_ARCH)` as Rook's base image, but I think it would be good to have something to use as `latest` while still being certain that it is a particular centos distro and arch.

I propose to also build `latest-luminous-centos-7-{x86_64,aarch64}` images that Rook can use as their development base image. This can be overridden in Rook's makefile to build a particular stable release if desired.

@leseb @bassam @travisn

**Comment by leseb** [comment]
I configured a manifest on the Docker Hub registry so using `ceph/daemon-base:v3.0.5-stable-3.0-luminous-centos-7` should be sufficient. Depending on the arch the client will send to registry, the registry will respond with the right image so if amd64 it will fetch `ceph/daemon-base:v3.0.5-stable-3.0-luminous-centos-7-x86_64`. 

We already have a `latest` which points to `centos7-luminous`, which also has a manifest configured. So this should normally work out of the box. Presently we have `ceph/daemon-base:master-9fd629c-luminous-centos-7`, which will respond to either `master-9fd629c-luminous-centos-7-aarch64` or `master-9fd629c-luminous-centos-7-x86_64` depending on the client arch.

We also have `latest-luminous`, `latest-kraken`, `latest-jewel`, however, the last 2 don't have arm64 support. This only started with Luminous.

**Comment by BlaineEXE** [comment]
What I mean to say is that I think in the Rook main, it might be best to use the latest ceph-container without having to change the image every time there is an update as is necessary with the `vX-stable-Y-luminous-centos-7`. This will make less work managing ceph-container's images in Rook's master branch. For Rook's versioned branches, the ceph-container image can be specified exactly as above. 

It makes sense to me that there should be a `latest-luminous-centos-7` image so that the Rook main has the latest, but it is limited to luminous, and the distro is guaranteed to be centos 7. As you said above, the arch should be able to be inferred. We may want instead to have a tag like `latest-stable-luminous-centos-7` which points to the latest stable.

**Comment by leseb** [comment]
Right, we don't have a `latest-stable-luminous-centos-7` yet but the rest is already present.

**Comment by leseb** [comment]
After some discussions, it appears that the need for a `latest-stable-luminous-centos-7` is not immediately needed, it might never be, so we agreed on not building one.
