### ISSUE TITLE
Support RGW SSL

### ISSUE THREAD

**Issue by rawipfel** [ceph/ceph-container#1074]
Hi, unless I missed it, it doesn't look like https://hub.docker.com/r/ceph/daemon/ supports SSL configuration for RGW. I think it should be fairly simple to add an option given a self-signed certificate if also setup by entrypoint.sh, e.g. http://www.ksingh.co.in/blog/2017/09/14/ceph-rgw-ssl/. 

Rationale: SSL (https) is necessary if testing AWS S3 Server-Side-Encryption with Customer-provided Keys (SSE-C) which Ceph supports. I'd like to be able to use ceph-container for testing an SSE-C app.

**Comment by pixdrift** [comment]
I have a similar requirement.

What is the current suggested solution for enabling SSL/TLS on the containerized RGW? Should this be done external to the container?

**Comment by pixdrift** [comment]
I have done first cut of this in my own fork, but the container build (make) is failing consistently for me in CentOS 7 (with and without my changes). Going to raise a new issue for this.

**Comment by leseb** [comment]
@pixdrift mind sending a PR from your fork? Thanks!

**Comment by pixdrift** [comment]
@leseb, I've got a fairly major problem with the build scripts currently, the 'make' for a centos based container fails pretty seriously.

It looks like it's somewhere in the cleanup snippet (that strips the image/reduces size). Haven't had time to narrow it down, but want a clean build + test before submitting the PR back.

**Comment by pixdrift** [comment]
Raised separate bug for the build issue in #1091

**Comment by pixdrift** [comment]
Put in initial PR #1092, @rawipfel, are you able to test this by mounting a cert into the container with a volume? or is it only of use for you if the container generates the cert?

Alternatively generate the cert as you were and pass in `RGW_SSL_CERTIFICATE=/etc/ssl/certs/ceph-rgw.crt`

**Comment by leseb** [comment]
@pixdrift I think we want to move away as much as possible from the containers doing too many things. The cert generation should happen outside of the container and then be exposed to the container. This cert would have to be distributed also so we better leave this task to an orchestration (k8s, ansible etc...)

**Comment by pixdrift** [comment]
@leseb, No problem.

If that's the case, the PR #1092 should cover off the basic requirement to expose the option in the container entrypoint script so it can be passed to the daemon start.

**Comment by leseb** [comment]
@pixdrift thanks will review soon =)

**Comment by pixdrift** [comment]
Sorry, just added a new PR. #1093 with the minor change.

**Comment by rawipfel** [comment]
Thanks for the PR @pixdrift I'll take a look after typing this. 

Also agree with @leseb's comment, it's normal to create the cert outside, and for e.g. k8s make it accessible to the container via a secret volume.
