### ISSUE TITLE
luminous mon logs to /var/log/ceph/ceph.log

### ISSUE THREAD

**Issue by Raboo** [ceph/ceph-container#1094]
**Bug Report**

What happened:
Ceph mon is spamming
```
2018-06-19 13:44:01.542990 7ff75b024700  1 mon.vm02@1(peon).log v57928205 unable to write to '/var/log/ceph/ceph.log' for channel 'cluster': (2) No such file or directory
```

What you expected to happen:
Not to write to /var/log/ceph/ceph.log, only to stdout and let docker handle logging.

How to reproduce it:
I upgraded from jewel to luminous, and now the mon spams about trying to write to `/var/log/ceph/ceph.log`

**Environment**:
* OS: Ubuntu Xenial
* Docker version: 17.10.0-ce
* Ceph version: 12.2.5 luminous
* ceph-container version: v3.0.5-luminous-ubuntu-16.04-x86_64

**Comment by leseb** [comment]
It's strange because `log file` is already set to `/dev/null` so I'm not sure why the mon is complaining.

**Comment by leseb** [comment]
How does your `ceph.conf` look like?

**Comment by Raboo** [comment]
I have no `log file` entry in my ceph.conf. 

```
# Created and Maintained by Confd

[global]
  fsid = xxx

  max_open_files = 131072
  mon_osd_full_ratio = .95
  mon_osd_nearfull_ratio = .85
  osd_pool_default_min_size = 1
  osd_pool_default_pg_num = 128
  osd_pool_default_pgp_num = 128
  osd_pool_default_size = 3

[mon]

  mon_clock_drift_allowed = .15
  mon_clock_drift_warn_backoff = 30
  mon_osd_down_out_interval = 300
  mon_osd_min_down_reporters = 1
  mon_osd_min_down_reports = 2
  mon_osd_report_timeout = 300
  osd_heartbeat_grace = 15
  osd_heartbeat_interval = 3

    [mon.vm01]
      host = vm01
      mon_addr = 10.3.60.25
    [mon.vm02]
      host = vm02
      mon_addr = 10.3.60.23
    [mon.vm03]
      host = vm03
      mon_addr = 10.3.60.21

[osd]

  filestore_max_sync_interval = 5
  filestore_merge_threshold = 40
  filestore_op_threads = 8
  filestore_split_multiple = 8
  journal_size = 100
  ms_bind_port_max = 7100
  ms_bind_port_min = 6800
  osd_client_op_priority = 63
  osd_crush_update_on_start = true
  osd_heartbeat_grace = 15
  osd_heartbeat_interval = 3
  osd_max_backfills = 1
  osd_max_scrubs = 1
  osd_mkfs_options_btrfs = "-f"
  osd_mkfs_options_xfs = "-f -i size=2048"
  osd_mkfs_type = xfs
  osd_mon_heartbeat_interval = 30
  osd_objectstore = filestore
  osd_op_threads = 8
  osd_recovery_max_active = 5
  osd_recovery_max_chunk = 1048576
  osd_recovery_op_priority = 2
  osd_recovery_threads = 1
  osd_scrub_begin_hour = 0
  osd_scrub_end_hour = 6
  osd_scrub_load_threshold = 15.0
  pool_default_crush_rule = 0

[mds]

  mds_cache_size = 100000

[client]

  rbd_cache_enabled = true
  rbd_cache_writethrough_until_flush = true
```

**Comment by leseb** [comment]
If you add `log file = /dev/null` in the `[global]` of your `ceph.conf` you should be good.

**Comment by Raboo** [comment]
Ok thanks, I added `log_file = /dev/null` in the `[global]` section and `mon_cluster_log_file = /dev/null` to the `[mon]` section. `log_file` alone wasn't enough.

**Comment by leseb** [comment]
@Raboo thanks!

**Comment by snowolfhawk** [comment]
> Ok thanks, I added `log_file = /dev/null` in the `[global]` section and `mon_cluster_log_file = /dev/null` to the `[mon]` section. `log_file` alone wasn't enough.

How could ceph.conf fixs take effect immediately?

 what ceph container command do you use?
