### ISSUE TITLE
ceph-container image for ppc64le

### ISSUE THREAD

**Issue by Pensu** [ceph/ceph-container#1111]
Hi all,

As the ceph-container daemon docker image is not supported on ppc64le, I would like to know what changes would be required to make that happen? There are no ppc64le packages in download.ceph.com, but the noarch pacakges in the same repo work for ppc64le, moreover other distros like Ubuntu ship ceph packages for ppc64le: https://packages.ubuntu.com/artful/ceph

**Comment by leseb** [comment]
When it comes to bringing support for a new arch we likely need a machine that runs on ppc64le to achieve that (just like we did for arm64). We don't have any, and we are not planning on providing images for it at the moment. Also, we don't do much with Ubuntu packages because we don't have any official maintainer for an Ubuntu-based image.

**Comment by Pensu** [comment]
@leseb Thanks for the response. Regarding machines, do you need the physical machines with you to work with or just a couple of workers that are hosted elsewhere would be ok?

**Comment by leseb** [comment]
@Pensu the build process is triggered on each PR merge via Jenkins, this https://github.com/ceph/ceph-container/blob/master/contrib/build-push-ceph-container-imgs.sh gets executed in a slave. The script builds the images on the machine, builds the manifest (Docker arch) and pushes them on the Docker Hub. The tricky part I guess for ppc64le is the manifest part, to build the manifest we must ensure the image is present on the Docker hub already. I don't know how we can integrate an external machine to our JJB that would run ppc64le.

I guess the easiest option, for now, would be to write a script similar to this one https://github.com/ceph/ceph-container/blob/master/contrib/build-push-ceph-container-imgs-arm64.sh but for ppc64le and execute it from time to time so you can push an image but you would need write access to the registry, sounds complicated...
