### ISSUE TITLE
Creating OSD Directory OSD: 0 has not been bootstrapped yet 

### ISSUE THREAD

**Issue by mnkdstock** [ceph/ceph-container#1114]
Objective: is to have RBD running on the container and have the RBD be accessible to container and host at same time, so we can create iSCSI target for the rbd at host level.

I have a /dev/sdb drive that I'm looking to mount as directory to OSD container

Step 1: Clean the disk
docker run -d --privileged=true-v /dev/:/dev/-e OSD_DEVICE=/dev/sdb ceph/daemon zap_device

Step 2: partitioned the drive, (the whole drive)
fdisk /dev/sdb
mkfs.xfs /dev/sdb1 /// to install the filesystem
// then mount the drive manually to the host
/dev/sdb1 /var/lib/ceph/osd/ceph-0 xfs rw,relatime,attr2,inode64,noquota 0 0

Step 3: 
docker exec ceph osd create /// as the instructions say  to add a osd directory  (link below)

Step 4: Create the OSD container using the directory based storage
docker run -d --net=host--pid=host--privileged=true -v /etc/ceph:/etc/ceph -v /var/lib/ceph/osd/:/var/lib/ceph/osd/ -v /dev/:/dev/ -e OSD_TYPE=directory ceph/daemon osd_directory_single

The Logs of running the container below

# docker logs 92066c685d2b
2018-07-16 21:30:57 /entrypoint.sh: static: does not generate config
2018-07-16 21:30:57 /entrypoint.sh: Looks like OSD: 0 has not been bootstrapped yet, doing nothing, moving on to the next discoverable OSD
2018-07-16 21:30:57 /entrypoint.sh: Looks like all the OSDs are already running, doing nothing
2018-07-16 21:30:57 /entrypoint.sh: Exiting the container
2018-07-16 21:30:57 /entrypoint.sh: SUCCESS
root@st5:#

Currently getting error: "**OSD: 0 has not been bootstrapped yet**"Is there any good tutorial that explains how to mount a directory to the OSD container?
I been following https://hub.docker.com/r/ceph/daemon/
Thanks
This setup is being done using Ceph Containers.

**Comment by mnkdstock** [comment]
2nd try: now I'm getting missing keyring issues. I did prepare the drive before mounting it.  Please see steps below. 

Step 1:

ZAP the /etc/sdb drive 

Step 2: 

docker run -d --net=host \
--privileged=true \
--pid=host \
-v /etc/ceph:/etc/ceph \
-v /var/lib/ceph/:/var/lib/ceph/ \
-v /dev/:/dev/ \
-e OSD_DEVICE=/dev/sdb \
-e OSD_TYPE=prepare \
ceph/daemon osd


Step 3:
docker exec <mon-container-id> ceph osd create
chown -R 64045:64045 /var/lib/ceph/osd/
docker exec <mon-container-id> ceph osd in 0 
Step 4:
docker run -d --net=host \
--pid=host \
--privileged=true \
-v /etc/ceph:/etc/ceph \
-v /var/lib/ceph/osd/ceph-0/:/var/lib/ceph/osd/ \
-v /dev/:/dev/ \
ceph/daemon osd_directory_single


New issue: 
exec: PID 11197: spawning /usr/local/bin/forego start -f /etc/forego/ceph/Procfile
forego   | starting ceph-0.1 on port 5000
ceph-0.1 | 2018-07-17 18:15:43.320 7f0aefb5b1c0 -1 auth: unable to find a keyring on /var/lib/ceph/osd/ceph-0//keyring: (2) No such file or directory
ceph-0.1 | 2018-07-17 18:15:43.320 7f0aefb5b1c0 -1 monclient: ERROR: missing keyring, cannot use cephx for authentication
ceph-0.1 | failed to fetch mon config (--no-mon-config to skip)
exec: PID 11197: exit 0
root@host:/var/lib/ceph/osd/ceph-0#

**Comment by mnkdstock** [comment]
Is there any guide how to setup iSCSI in Ceph container? I see we can select options tcmu_runner rbd_target_api rbd_target_gw when running the ceph/daemon image.

**Comment by nuqz** [comment]
@mnkdstock please, take a look at [this page](http://eturnerx.blogspot.com/2014/08/how-i-added-my-lvm-volumes-as-osds-in.html). I used this guide to prepare OSDs to avoid "auth" and "keyring" errors. But I'm still getting `ceph-0.1 | failed to fetch mon config (--no-mon-config to skip)` error. Do you have any ideas how to fix this?
