### ISSUE TITLE
demo crashed when specifying CEPH_DEMO_BUCKET

### ISSUE THREAD

**Issue by pashinin** [ceph/ceph-container#1132]
**Bug Report**

What happened:

I started `demo` container with `CEPH_DEMO_BUCKET=qqq`. Everything was ok until line 

```
/entrypoint.sh: Creating bucket...
```
After that - nothing. Only:

```
"/entrypoint.sh demo"    2 minutes ago       Exited (12) 2 minutes ago
```

What you expected to happen:

Create bucket and just work. Not crash.

How to reproduce it (minimal and precise):

Happens only when I add `-e CEPH_DEMO_BUCKET=qqq`. I does not crash when I remove it. But obviously does not create a bucket.

```
sudo docker run \
         -d \
         --name cephbox --net=host \
         -e MON_IP=192.168.43.223  \
         -e CEPH_PUBLIC_NETWORK=192.168.43.0/24 \
         -e CEPH_DEMO_UID=qqq \
         -e CEPH_DEMO_ACCESS_KEY=qqq \
         -e CEPH_DEMO_SECRET_KEY=qqq \
         -e CEPH_DEMO_BUCKET=qqq \
         -v `pwd`/etc/:/etc/ceph \
         -v `pwd`/lib/:/var/lib/ceph \
         ceph/daemon demo
```

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 18.04
* Kernel (e.g. `uname -a`): `Linux X510UA 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
* Docker version (e.g. `docker version`):
```
Client:
 Version:	17.12.1-ce
 API version:	1.35
 Go version:	go1.10.1
 Git commit:	7390fc6
 Built:	Wed Apr 18 01:23:11 2018
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.1-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.10.1
  Git commit:	7390fc6
  Built:	Wed Feb 28 17:46:05 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```
* Ceph version (e.g. `ceph -v`): not installed on host

**Comment by leseb** [comment]
Can you run with `-e DEBUG=verbose`? And paste the output?
Thanks!

**Comment by aanbrn** [comment]
As I can see in the log, it's because:

demo.sh: line 273: ceph-rest-api: command not found

And ceph-rest-api really doesn't exist in the image.

**Comment by aanbrn** [comment]
It's my log [demo.log](https://github.com/ceph/ceph-container/files/2356966/demo.log).

**Comment by leseb** [comment]
@aanbrn do you still this issue with the latest version of the container image? Thanks

**Comment by pashinin** [comment]
As I remember I just removed CEPH_DEMO_BUCKET and then created a bucket manually when service was running. It was ok for me.
