### ISSUE TITLE
output from  `ceph mgr services` is empty if run in started demo container

### ISSUE THREAD

**Issue by level420** [ceph/ceph-container#1158]
Is this a bug report or feature request?
* Bug Report

**Bug Report**

What happened:

when inspecting ceph manager services in a running demo container via
```
docker exec -ti demo ceph mgr services
```
results in the output `{}` e.g. there are no services listed.

What you expected to happen:

`docker exec -ti demo ceph mgr services` should list the dashboard URL.
Additionally the dashboard is unreachable at `http://192.168.0.160:7000/` or whatever URL would normally be displayed.

How to reproduce it (minimal and precise):

1. pull ceph/daemon:latest image (Tue Aug 14 18:20:11 CEST 2018) from docker hub via 
```
docker pull ceph/daemon
```
2. Start a simple container via
```
docker run -d \
--name demo \
-e MON_IP=192.168.0.160 \
-e CEPH_PUBLIC_NETWORK=192.168.0.0/24 \
--net=host \
-v /var/lib/ceph:/var/lib/ceph \
-v /etc/ceph:/etc/ceph \
-e CEPH_DEMO_UID=qqq \
-e CEPH_DEMO_ACCESS_KEY=qqq \
-e CEPH_DEMO_SECRET_KEY=qqq \
-e CEPH_DEMO_BUCKET=qqq \
ceph/daemon \
demo
```
3. display running services via 
```
docker exec -ti demo ceph mgr services
```
4. see the empty output
```
{}
```

**Environment**:

* OS (e.g. from /etc/os-release):
CentOS Linux release 7.5.1804 (Core) 
* Kernel (e.g. `uname -a`):
Linux sphen 3.10.0-862.9.1.el7.x86_64 #1 SMP Mon Jul 16 16:29:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Docker version (e.g. `docker version`):
Package version: docker-1.13.1-68.gitdded712.el7.centos.x86_64
* Ceph version (e.g. `ceph -v`):
ceph version 13.2.1 (5533ecdc0fda920179d7ad84e0aa65a127b20d77) mimic (stable)

**Comment by level420** [comment]
@jenspiek thank you for the hint. It seems that the following command is sufficient (username and password both set to `demo`):
```
ceph dashboard create-self-signed-cert
ceph dashboard set-login-credentials demo demo
```
After this dashboard is showing up in services:
```
[root@testhost /]# ceph mgr services
{
    "dashboard": "https://192.168.0.160:8443/"
}
```
In contrary to your command sequence the dashboard module must stay enabled for `ceph dashboard create-self-signed-cert` to work. 

It would be nice if both steps are automatically run in case of starting a container with the `demo` endpoint or documenting this somewhere.

**Comment by leseb** [comment]
I'm closing this as the issue appears resolved. Feel free to re-open if you have any more concerns, thanks.

**Comment by lanmingle** [comment]
槽糕啊！设置 ceph config set mgr mgr/dashboard/ssl false 无法去掉 https 的方式，应该由于 ssl 是否启用，现在 ssl 这个配置是无效的。
