### ISSUE TITLE
ceph-mon docker container constantly restarting

### ISSUE THREAD

**Issue by hesco** [ceph/ceph-container#1177]
Is this a bug report or feature request?
* Bug Report

**Bug Report**

What happened:

CONTAINER ID        IMAGE                         COMMAND                CREATED             STATUS                          PORTS               NAMES
dda487089252        ceph/daemon:latest-luminous   "/entrypoint.sh mon"   24 minutes ago      Restarting (1) 24 seconds ago                       ceph-mon

What you expected to happen:

to have a stable ceph-mon running, to not see: 
Cluster connection interrupted or timed out

How to reproduce it (minimal and precise):

ceph_stable_release=luminous
ceph_mon_ip=$(hostname -I | sed "s,^.*192.168.51,192.168.51,;s,\ .*$,,")
ceph_public_network=$(ip route show | grep ${ceph_mon_ip} | awk '{ print $1 }')

function launch_ceph_monitor () {
  docker ps | grep -q ceph-mon
  monitor_running=$?
  if [[ "${monitor_running}" -ne 0 ]];
  then
    docker run -d --net=host \
      --restart always \
      -v /etc/ceph:/etc/ceph \
      -v /var/lib/ceph/:/var/lib/ceph/ \
      -e MON_IP=${ceph_mon_ip} \
      -e CEPH_PUBLIC_NETWORK=${ceph_public_network} \
      --name="ceph-mon" \
      ceph/daemon:latest-luminous mon
  fi
}

launch_ceph_monitor

**Environment**:
* OS (e.g. from /etc/os-release):  PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
* Kernel (e.g. `uname -a`): Linux dessalines011 3.16.0-4-amd64 #1 SMP Debian 3.16.51-3 (2017-12-13) x86_64 GNU/Linux 
* Docker version (e.g. `docker version`): Version:          18.06.0-ce 
* Ceph version (e.g. `ceph -v`): ceph version 12.2.8 (ae699615bac534ea496ee965ac6192cb7e0e07c0) luminous (stable)

**Comment by jeevadotnet** [comment]
Did anyone ever get a fix for this ?

- Docker version 18.09.2
- Ceph Version: 12.2.4

`CONTAINER ID        IMAGE                                                        COMMAND             CREATED             STATUS              PORTS               NAMES
d1b41ba89b64        ceph/daemon:v3.0.1-stable-3.0-luminous-ubuntu-16.04-x86_64   "/entrypoint.sh"    32 seconds ago      Up 30 seconds                           ceph-osd-A-08-02-storage-ctl-sdal
e70296461d8d        ceph/daemon:v3.0.1-stable-3.0-luminous-ubuntu-16.04-x86_64   "/entrypoint.sh"    2 days ago          Up 2 days                               ceph-mon-A-08-02-storage-ctl
9db56642367a        ceph/daemon:v3.0.1-stable-3.0-luminous-ubuntu-16.04-x86_64   "/entrypoint.sh"    3 days ago          Up 3 days                               ceph-mgr-A-08-02-storage-ctl
218b808b794d        ceph/daemon:v3.0.1-stable-3.0-luminous-ubuntu-16.04-x86_64   "/entrypoint.sh"    6 days ago          Up 6 days                               ceph-osd-A-08-02-storage-ctl-sdq
52e5c2b132f3        ceph/daemon:v3.0.1-stable-3.0-luminous-ubuntu-16.04-x86_64   "/entrypoint.sh"    6 days ago          Up 6 days                               ceph-osd-A-08-02-storage-ctl-sdam
0242b606b85a        ceph/daemon:v3.0.1-stable-3.0-luminous-ubuntu-16.04-x86_64   "/entrypoint.sh"    7 days ago          Up 7 days                               ceph-mds-A-08-02-storage-ctl
677128e41f5c        ceph/daemon:v3.0.1-stable-3.0-luminous-ubuntu-16.04-x86_64   "/entrypoint.sh"    7 days ago          Up 7 days                               ceph-osd-A-08-02-storage-ctl-sdai
0b1072dd9c6b        ceph/daemon:v3.0.1-stable-3.0-luminous-ubuntu-16.04-x86_64   "/entrypoint.sh"    7 days ago          Up 7 days                               ceph-osd-A-08-02-storage-ctl-sdaj
db546198c937        ceph/daemon:v3.0.1-stable-3.0-luminous-ubuntu-16.04-x86_64   "/entrypoint.sh"    7 days ago          Up 7 days                               ceph-osd-A-08-02-storage-ctl-sdah
a0d245f50903        ceph/daemon:v3.0.1-stable-3.0-luminous-ubuntu-16.04-x86_64   "/entrypoint.sh"    7 days ago          Up 7 days                               ceph-osd-A-08-02-storage-ctl-sdak
0433702c5786        ceph/daemon:v3.0.1-stable-3.0-luminous-ubuntu-16.04-x86_64   "/entrypoint.sh"    7 days ago          Up 7 days                               ceph-osd-A-08-02-storage-ctl-sdao
dc94d79995d1        ceph/daemon:v3.0.1-stable-3.0-luminous-ubuntu-16.04-x86_64   "/entrypoint.sh"    7 days ago          Up 7 days                               ceph-osd-A-08-02-storage-ctl-sdan
ee7ab3e3c17e        ceph/daemon:v3.0.1-stable-3.0-luminous-ubuntu-16.04-x86_64   "/entrypoint.sh"    7 days ago          Up 7 days                               ceph-osd-A-08-02-storage-ctl-sdaa
`

One container on each of the 3 ceph nodes keeps on restarting - therefore I cannot upgrade
