### ISSUE TITLE
integrate ceph-volume in ceph-container

### ISSUE THREAD

**Issue by ktdreyer** [ceph/ceph-container#1184]
Please remove all references to `ceph-disk` and use `ceph-volume` instead.

`ceph-disk` is deprecated, and `ceph-volume` has more testing.

**Comment by jared-hardy** [comment]
This is a big problem and deserves way more attention. This pervasive use of deprecated `ceph-disk` commands renders any OSD container after Ceph version 13 effectively useless, especially with Bluestore block devices and new installations. My Docker logs are full of this line now:

> /opt/ceph-container/bin/osd_disk_prepare.sh: line 40: ceph-disk: command not found

**Comment by leseb** [comment]
This was fixed in: https://github.com/ceph/ceph-container/pull/1325
@jared-hardy are you running the image with this code?

@dsavineau FYI

**Comment by jared-hardy** [comment]
@leseb the latest match for my environment as of install was 
docker.io/ceph/daemon:master-12ab4d2-nautilus-centos-7-x86_64

**Comment by osegarra** [comment]
https://github.com/ceph/ceph-container/pull/1325
