### ISSUE TITLE
PR #1175 broken make build.parallel

### ISSUE THREAD

**Issue by ErwanAliasr1** [ceph/ceph-container#1191]
We merged PR 1175 but discover that it brakes make build.parallel while make build is fine.

erwan@mr-meeseeks:~/ceph-container (master)$ sudo make FLAVORS=luminous,centos,7 build.parallel
make[1] : on entre dans le répertoire « /home/erwan/ceph-container »
make[2] : on entre dans le répertoire « /home/erwan/ceph-container/staging/luminous-centos-7-x86_64/daemon-base »
=== docker build ceph/daemon-base:master-luminous-centos-7-x86_64

  CEPH_VERSION      : luminous
  CEPH_POINT_RELEASE: 
  DISTRO            : centos
  DISTRO_VERSION    : 7
  HOST_ARCH         : x86_64
  BASEOS_REGISTRY   : 
  BASEOS_REPO       : centos
  BASEOS_TAG        : 7
  IMAGES_TO_BUILD   : daemon-base daemon
  STAGING_DIR       : staging/luminous-centos-7-x86_64
  RELEASE           : master
  DAEMON_BASE_IMAGE : ceph/daemon-base:master-luminous-centos-7-x86_64
  DAEMON_IMAGE      : ceph/daemon:master-luminous-centos-7-x86_64

Computed:
  BASE_IMAGE        : centos:7

make : on entre dans un répertoire inconnu
make: *** staging/luminous-centos-7-x86_64/daemon : Aucun fichier ou dossier de ce type. Arrêt.
make : on quitte un répertoire inconnu
make[1]: *** [daemon.x86_64,luminous,centos,7] Erreur 2
make[1]: *** Attente des tâches non terminées....
unable to prepare context: unable to get absolute context directory of given context directory ".": getwd: no such file or directory
make[2]: *** [build] Erreur 1
make[2] : on quitte le répertoire « /home/erwan/ceph-container/staging/luminous-centos-7-x86_64/daemon-base »
make[1]: *** [daemon-base.x86_64,luminous,centos,7] Erreur 2
make[1] : on quitte le répertoire « /home/erwan/ceph-container »
make: *** [build.parallel] Erreur 2

https://2.jenkins.ceph.com/job/ceph-container-prs-ceph_ansible-luminous-centos7-cluster/525/consoleText

**Comment by ErwanAliasr1** [comment]
@BlaineEXE We still have the same kind of issues as in 
https://2.jenkins.ceph.com/job/ceph-container-build-ceph-base-push-imgs/4/console
make[1]: *** staging/kraken-11.0.1-centos-7-x86_64/daemon: No such file or directory.  Stop.

Can you have a look on why the build.parallel fails ?

**Comment by BlaineEXE** [comment]
I finally got around to being able to look at this. Thanks for your patience. I think this issue resulted from my misinterpretation of Make's [order-only prerequisites](https://www.gnu.org/software/make/manual/make.html#Prerequisite-Types).
