### ISSUE TITLE
Restapi container fail - /usr/bin/ceph-rest-api: No such file or directory

### ISSUE THREAD

**Issue by micromachine** [ceph/ceph-container#1194]
Hi, I try to setup a rgw and restapi, and I found some errors. In new docker images there is no /usr/bin/ceph-rest-api. I try to use latest image and v3.1.0-stable-3.1-mimic-centos-7 but without luck. 
Logs from my container : 
```2018-10-04 04:22:57  /entrypoint.sh: static: does not generate config
2018-10-04 04:22:57  /entrypoint.sh: static: does not generate the admin key, so we can not get it.
2018-10-04 04:22:57  /entrypoint.sh: static: make it available with the help of your configuration management system.
2018-10-04 04:22:57  /entrypoint.sh: static: ceph-ansible is a good candidate to deploy a containerized version of Ceph.
2018-10-04 04:22:57  /entrypoint.sh: static: ceph-ansible will help you fetching the keys and push them on the right nodes.
2018-10-04 04:22:57  /entrypoint.sh: static: if you're interested, please visit: https://github.com/ceph/ceph-ansible
2018-10-04 04:22:57  /entrypoint.sh: SUCCESS
exec: PID 240: spawning /usr/bin/ceph-rest-api --cluster ceph -n client.admin
docker_exec.sh: line 53: /usr/bin/ceph-rest-api: No such file or directory
```
**Environment**:
* OS (e.g. from /etc/os-release):
[root@fs05 /]# cat  /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

* Kernel (e.g. `uname -a`): 
4.4.156-1.el7.elrepo.x86_64
* Docker version (e.g. `docker version`):
[root@fs05 ~]# docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:23:03 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:25:29 2018
  OS/Arch:          linux/amd64
  Experimental:     false

* Ceph version (e.g. `ceph -v`):
ceph version 13.2.2 (02899bfda814146b021136e9d8e80eba494e1126) mimic (stable)

**Comment by leseb** [comment]
`/usr/bin/ceph-rest-api` is deprecated and has been removed from mimic. We should add a meaningful message about that in the code.

**Comment by micromachine** [comment]
Thanks for info.
