### ISSUE TITLE
produce containers for non-released Ceph versions

### ISSUE THREAD

**Issue by alfredodeza** [ceph/ceph-container#1200]
For CI testing, it is going to be required to produce nightly containers from un-released Ceph releases. At this time, it would be required to have:

* master
* mimic
* luminous

This is going to be needed by the Rook project so that it can schedule nightly tests.

/cc @travisn

**Comment by travisn** [comment]
@leseb @ErwanAliasr1 @BlaineEXE what would it take to publish the master builds? This will help test nautilus and other future coming changes.

**Comment by leseb** [comment]
Response from @ErwanAliasr1 coming from an email.

```
That would mean consuming the latest centos/7/default build on 
https://shaman.ceph.com/repos/ceph/master/ and use it for installing 
packages.

Two options, harcoding the latest code name like nautilus to this trick, 
or having a virtual "latest" or "master" code release name that points 
to it and which is stable over time (no need to make patches for every 
release code name).

I'm more likely on option 2 here for its stability over time.

I can have a look how complex it is to get it.
```

**Comment by alfredodeza** [comment]
I would like to see naming be directly correlated to the branch name. In the case of `master` this would mean using `master` as the name (vs. `latest`).

**Comment by ErwanAliasr1** [comment]
I've just completed a PR to have containers running on the master version of ceph & ganesha.
Looks good to me.
Reviews welcome.

**Comment by alfredodeza** [comment]
I am not clear where are the new containers at? Are they being produced nightly? Were is that job (or jobs)? The idea is that those are produced and pushed to some registry (docker hub?) so that they can be used by other projects like Rook.

If that part is not done yet, we need to re-open this ticket to keep track of that work

**Comment by ErwanAliasr1** [comment]
You can find builds on https://hub.docker.com/r/ceph/daemon-base/tags/
Latest one is then master-4cab875-master-centos-7-x86_64
I'm checking with sebastien what is necessary to have a latest-master tag so it's easier for you to consume it

**Comment by travisn** [comment]
What is the difference between the `ceph/ceph` and `ceph/daemon-base` repos? I was thinking the master images would also be pushed to `ceph/ceph`

**Comment by ErwanAliasr1** [comment]
ceph/ceph is the work done by @BlaineEXE and built daily
ceph/daemon-base is the previous way of building images

Both are still enabled so until the daily is done, alfredo can make a try on the daemon-base images.
