### ISSUE TITLE
Add client-only container

### ISSUE THREAD

**Issue by yselkowitz** [ceph/ceph-container#1221]
Is this a bug report or feature request?
* Feature Request

Rough first draft: https://github.com/multi-arch/ceph-container/commits/client-container

Are there any similar features already existing:
Not to my limited knowledge.

What should the feature do:
Provide a client-only container with ceph-common, which could also serve as the base of daemon-base.

What would be solved through this feature:
This would provide the client-only container allowed for in https://github.com/ceph/ceph-ansible/pull/3200.

Does this have an impact on existing features:
In this form, the client container becomes the base of the daemon-base container.

**Comment by leseb** [comment]
Not sure to understand the difference between the client container and `daemon-base`, can you clarify?

**Comment by yselkowitz** [comment]
daemon-base includes server bits (ceph-mon, ceph-osd, etc.). client is just ceph-common.

**Comment by leseb** [comment]
This looks a bit overkill (all the extra code, CI jobs and build images) for only having the client tools. Are you concerned about the container size?

**Comment by yselkowitz** [comment]
We have gone with a different approach in #1227.
