### ISSUE TITLE
get 'unable to find any IP address in networks' while trying to deploy a monitor

### ISSUE THREAD

**Issue by MrRyeS** [ceph/ceph-container#1234]
When I tried to deploy a monitor as daemon/README instructed, I got an error:

> ➜ /tmp/var/lib/ceph >sudo docker run -d --net=host  --name=mon \
-v /tmp/etc/ceph:/etc/ceph \
-v /tmp/var/lib/ceph/:/var/lib/ceph \
-e MON_IP=10.66.4.115 \
-e CEPH_PUBLIC_NETWORK=10.66.4.0/24 \
ceph/daemon mon
bba3de9db8cb2ba283a1c537a2671dd5797b5f995704ce17a92926c89224c948
➜ /tmp/var/lib/ceph >docker container ls
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
➜ /tmp/var/lib/ceph >docker logs -f mon
creating /etc/ceph/ceph.client.admin.keyring
creating /etc/ceph/ceph.mon.keyring
creating /var/lib/ceph/bootstrap-osd/ceph.keyring
creating /var/lib/ceph/bootstrap-mds/ceph.keyring
creating /var/lib/ceph/bootstrap-rgw/ceph.keyring
creating /var/lib/ceph/bootstrap-rbd/ceph.keyring
monmaptool: monmap file /etc/ceph/monmap-ceph
monmaptool: set fsid to 6dca646a-b1ce-4aa7-9275-152d6b524205
monmaptool: writing epoch 0 to /etc/ceph/monmap-ceph (1 monitors)
importing contents of /var/lib/ceph/bootstrap-osd/ceph.keyring into /etc/ceph/ceph.mon.keyring
importing contents of /var/lib/ceph/bootstrap-mds/ceph.keyring into /etc/ceph/ceph.mon.keyring
importing contents of /var/lib/ceph/bootstrap-rgw/ceph.keyring into /etc/ceph/ceph.mon.keyring
importing contents of /var/lib/ceph/bootstrap-rbd/ceph.keyring into /etc/ceph/ceph.mon.keyring
importing contents of /etc/ceph/ceph.client.admin.keyring into /etc/ceph/ceph.mon.keyring
2018-11-05 01:50:56.581 7fdd05c3a140 -1 unable to find any IP address in networks '10.66.4.0/24' interfaces ''

The host IP is 10.66.4.115, and the /etc/ceph and /lib/var/ceph directories are all empty. I've got no idea how to fix this. Could you pls give me some instructions?

**Comment by leseb** [comment]
`ip -4 -a`?

**Comment by mminisha** [comment]
Does this issue resolved?
