### ISSUE TITLE
RGW_ZONEGROUP ignored

### ISSUE THREAD

**Issue by ralfonso** [ceph/ceph-container#1247]
Is this a bug report or feature request?
* Bug Report

**Bug Report**

What happened: `RGW_ZONEGROUP` is documented in https://github.com/ceph/ceph-container/blob/master/src/daemon/README.md#deploy-a-rados-gateway, but seems to be ignored by `ceph/daemon`. 

I'm using the container in demo mode and setting up mon,mgr,osd,rgw. 

What you expected to happen:

I expected the default zonegroup to be set up with the `name` and `api_name` of `dev`

How to reproduce it (minimal and precise):

```bash
$ docker run --rm \
  -e DEBUG=verbose \
  -e CEPH_DAEMON=demo \
  -e CEPH_PUBLIC_NETWORK=10.43.0.0/24 \
  -e MON_IP=10.43.0.200 \
  -e NETWORK_AUTO_DETECT=4 \
  -e DEMO_DAEMONS=mon,mgr,osd,rgw \
  -e RGW_CIVETWEB_PORT=8000 \
  -e SREE_PORT=5000 \
  -e CEPH_DEMO_UID=MY_UID \
  -e CEPH_DEMO_ACCESS_KEY=MY_ACCESS_KEY \
  -e CEPH_DEMO_SECRET_KEY=MY_SECRET_KEY \
  -e RGW_ZONEGROUP=dev \
  --ip 10.43.0.200 \
  --network MY_NETWORK \
  -p 5000 \
  -p 8000 \
  -it ceph/daemon:latest-luminous

# enter container

$ radosgw-admin realm list
{
    "default_info": "",
    "realms": []
}

$ radosgw-admin zonegroup get
{
    "id": "e6a65f3f-21a0-4f82-9f5c-a882fec17b09",
    "name": "default",
    "api_name": "",
    "is_master": "true",
    "endpoints": [],
    "hostnames": [],
    "hostnames_s3website": [],
    "master_zone": "b07d6533-4da2-4b48-b711-f45273636fdd",
    "zones": [
        {
            "id": "b07d6533-4da2-4b48-b711-f45273636fdd",
            "name": "default",
            "endpoints": [],
            "log_meta": "false",
            "log_data": "false",
            "bucket_index_max_shards": 0,
            "read_only": "false",
            "tier_type": "",
            "sync_from_all": "true",
            "sync_from": []
        }
    ],
    "placement_targets": [
        {
            "name": "default-placement",
            "tags": []
        }
    ],
    "default_placement": "default-placement",
    "realm_id": ""
}
```

**Environment**:
* OS (e.g. from /etc/os-release): Linux
* Kernel (e.g. `uname -a`): 4.18.15
* Docker version (e.g. `docker version`): 18.06.1-ce
* Ceph version (e.g. `ceph -v`): `ceph version 12.2.9 (9e300932ef8a8916fb3fda78c58691a6ab0f4217) luminous (stable)`

**Comment by leseb** [comment]
Sorry about the confusion, you will need to edit your `ceph.conf` file directly to put the `RGW_ZONEGROUP` value.
