### ISSUE TITLE
Monmap management

### ISSUE THREAD

**Issue by hunter** [ceph/ceph-container#126]
I was speaking with @TelanJ earlier about what happens in a dynamic environment (like K8s) with multiple Mons. Cases where a Mon being started with a different hostname and/or IP.

For a quick test, 7 mon containers were started, then 2 stopped and another 2 started. The monmap contained 9 mons of which 2 were down. This would have been my expectation but I don't think it's an ideal option for live environments.

It's not easy to know if a mon is temporarily offline of it's been migrated to a different hostname or IP. Ceph also makes it very hard as updating a monmap means all mons need to be restarted (http://ceph.com/docs/master/rados/operations/add-or-rm-mons).

To throw out a few incomplete ideas:
- Manual - Entry command/arg that cleans up missing mons (doesn't handle stop/injection/starting of all mons)
- Use the KV store for tracking active mons. Removing old mons when starting a new mon. Use confd to track changed keys and stop/start the mon inside the container.
- Give mons fixed IDs (similar to OSDs). If the ID is the same then check the IP (in monmap dump?) and remove/add as needed

None are really complete solutions since there needs to be ways of ensuring quorum, injecting the updated monmaps and regenerating the ceph.conf. Any thoughts on the best way to handle the monmap?

**Comment by Ulexus** [comment]
This is absolutely a problem, and as best I know, there is no good solution.  The Ceph Monitors are the weak link, in terms of a fully dynamic Ceph cluster.  As with any such cluster, quorum must be maintained or the cluster fails to operate.  With indeterminate down-vs-retirement states, only outside logic can be used to add or remove monitors safely.  Usually, this means user intervention.

However, with Docker and orchestration tools, this could (potentially) be handled better.  If you operate on the premise that every _execution_ instance of a mon is a complete lifecycle of that mon (there is no such thing as a down mon which is not to be removed from the cluster), and you have an external infrastructure which adds and removes monitors accordingly (simply attaching the add/remove commands to the monitor unit execution is too fragile), this should be most achievable.  To my knowledge, no one is working on such an administrative framework, but I have thought about it more than a few times.
