### ISSUE TITLE
Debian cannot find nfs-ganesha-rgw

### ISSUE THREAD

**Issue by ErwanAliasr1** [ceph/ceph-container#1262]
@herbert-li The current CI is broken since a few days because of a missing package.
I've been forced to remove the build of debian.
Can you fix it ?

cf https://2.jenkins.ceph.com/job/ceph-container-build-push-imgs/283/consoleFull

**Comment by dsavineau** [comment]
We don't build ubuntu images anymore but the nfs-ganesha-rgw deb package is still present in nfs-ganesha 2.5/2.6/2.7 in the repository.
