### ISSUE TITLE
activate previously prepared OSD

### ISSUE THREAD

**Issue by maxilee** [ceph/ceph-container#1266]
I've reinstalled OS on my hosts but disks used as OSD ( I've used OSD_TYPE=disk ) was preserved.
also configuration of all daemons was preserver. 
then I've deployed all deamons : mon, mgr, mds and finaly OSD.

but OSD won't run.
logs from OSD container: 

> [root@h-192 ~]# docker logs 0cf7afb53757 
> 2018-12-01 15:49:56  /opt/ceph-container/bin/entrypoint.sh: static: does not generate config
> /opt/ceph-container/bin/osd_disk_activate.sh: line 4: disk_list.sh: No such file or directory

I've modified file osd_disk_activate.sh and recreated new container - now osd was activated correctly.

in file "src/daemon/osd_scenarios/osd_disk_activate.sh" in line 4 full path to include file is missing.

orginal is 
`source disk_list.sh`

but should be 
`source /opt/ceph-container/bin/disk_list.sh`

**Comment by fward1208** [comment]
Confirmed. This solved my osd container issue:

2018-12-02 07:23:30  /opt/ceph-container/bin/entrypoint.sh: static: does not generate config
2018-12-02 07:23:30  /opt/ceph-container/bin/entrypoint.sh: Device detected, assuming ceph-disk scenario is desired
2018-12-02 07:23:30  /opt/ceph-container/bin/entrypoint.sh: Preparing and activating /dev/sdb
/opt/ceph-container/bin/osd_disk_activate.sh: line 4: disk_list.sh: No such file or directory

**Comment by cmsalmeida** [comment]
I have same problem but in osd_common.sh, I'll do a PR

**Comment by dsavineau** [comment]
Fixes with https://github.com/ceph/ceph-container/pull/1270
