### ISSUE TITLE
run rbd_target_api  Automatically quit .

### ISSUE THREAD

**Issue by mclitao** [ceph/ceph-container#1268]
Rbd_target_api container always exits when I run rbd_target_api container.Is it a lack of configuration?
Who can help me solve it, thank you.

iscsi-gateway.cfg
ceph.client.admin.keyring
The above two files should be configured correctly.

# docker run -d \
--restart always \
--privileged \
--cap-add=ALL \
--net=host \
--name=rbd-target-api \
-v /etc/localtime:/etc/localtime:ro \
-v /dev:/dev \
-v /data/ceph/lib:/var/lib/ceph \
-v /data/ceph/logs:/var/log/ceph \
-v /lib/modules:/lib/modules \
-v /data/ceph/etc:/etc/ceph \
-e CLUSTER=ceph \
-e CEPH_DAEMON=RBD_TARGET_API \
 ceph/daemon:travis-build-master-c70822e820e8baf98e713e5f5cb68950862170da-mimic-centos-7-x86_64 rbd_target_api

docker logs -f rbd-target-api
2018-12-04 11:36:59  /entrypoint.sh: static: does not generate config
2018-12-04 11:37:00  /entrypoint.sh: SUCCESS
exec: PID 96: spawning /usr/bin/rbd-target-api
exec: Waiting 96 to quit
teardown: managing teardown after SIGCHLD
teardown: Waiting PID 96 to terminate 
teardown: Process 96 is terminated
teardown: Bye Bye, container will die with return code -1

**Comment by leseb** [comment]
Did you forget /etc/ceph in the bindmoint? Do the container have access to the cluster?

**Comment by mclitao** [comment]
I put the cephi configuration in this path /data/ceph/etc: mount it inside the container /etc/ceph and see 2018-12-04 11:37:00 /entrypoint.sh: SUCCESS should be a successful connection

**Comment by leseb** [comment]
You can use `-e DEBUG=stayalive` so the container will survive the crash, you can get into the container and look at the rbd-target-api logs.

**Comment by mclitao** [comment]
Thank you. I'll give it a try

**Comment by mclitao** [comment]
[root@ceph-2 ~]# docker run --rm -e DEBUG=verbose -v /etc/localtime:/etc/localtime:ro --privileged --cap-add=ALL --net=host  -v /dev:/dev -v /lib/modules:/lib/modules -v /data/ceph/etc/:/etc/ceph --name=rbd-target-api ceph/daemon:travis-build-master-c70822e820e8baf98e713e5f5cb68950862170da-mimic-centos-7-x86_64 rbd_target_api
2018-12-10 14:49:28  /entrypoint.sh: VERBOSE: activating bash debugging mode.
2018-12-10 14:49:28  /entrypoint.sh: To run Ceph daemons in debugging mode, pass the CEPH_ARGS variable like this:
2018-12-10 14:49:28  /entrypoint.sh: -e CEPH_ARGS='--debug-ms 1 --debug-osd 10'
2018-12-10 14:49:28  /entrypoint.sh: This container environement variables are: HOSTNAME=ceph-2
LC_ALL=C
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
CEPH_VERSION=mimic
SHLVL=1
HOME=/root
CEPH_POINT_RELEASE=
DEBUG=verbose
_=/usr/bin/env
+/entrypoint.sh:19: case "$KV_TYPE" in
+/entrypoint.sh:29: source /config.static.sh
++/config.static.sh:2: set -e
++/entrypoint.sh:39: to_lowercase rbd_target_api
++common_functions.sh:189: to_lowercase(): echo rbd_target_api
+/entrypoint.sh:39: CEPH_DAEMON=rbd_target_api
+/entrypoint.sh:41: create_mandatory_directories
+common_functions.sh:64: create_mandatory_directories(): for keyring in '$OSD_BOOTSTRAP_KEYRING' '$MDS_BOOTSTRAP_KEYRING' '$RGW_BOOTSTRAP_KEYRING' '$RBD_MIRROR_BOOTSTRAP_KEYRING'
++common_functions.sh:65: create_mandatory_directories(): dirname /var/lib/ceph/bootstrap-osd/ceph.keyring
+common_functions.sh:65: create_mandatory_directories(): mkdir -p /var/lib/ceph/bootstrap-osd
+common_functions.sh:64: create_mandatory_directories(): for keyring in '$OSD_BOOTSTRAP_KEYRING' '$MDS_BOOTSTRAP_KEYRING' '$RGW_BOOTSTRAP_KEYRING' '$RBD_MIRROR_BOOTSTRAP_KEYRING'
++common_functions.sh:65: create_mandatory_directories(): dirname /var/lib/ceph/bootstrap-mds/ceph.keyring
+common_functions.sh:65: create_mandatory_directories(): mkdir -p /var/lib/ceph/bootstrap-mds
+common_functions.sh:64: create_mandatory_directories(): for keyring in '$OSD_BOOTSTRAP_KEYRING' '$MDS_BOOTSTRAP_KEYRING' '$RGW_BOOTSTRAP_KEYRING' '$RBD_MIRROR_BOOTSTRAP_KEYRING'
++common_functions.sh:65: create_mandatory_directories(): dirname /var/lib/ceph/bootstrap-rgw/ceph.keyring
+common_functions.sh:65: create_mandatory_directories(): mkdir -p /var/lib/ceph/bootstrap-rgw
+common_functions.sh:64: create_mandatory_directories(): for keyring in '$OSD_BOOTSTRAP_KEYRING' '$MDS_BOOTSTRAP_KEYRING' '$RGW_BOOTSTRAP_KEYRING' '$RBD_MIRROR_BOOTSTRAP_KEYRING'
++common_functions.sh:65: create_mandatory_directories(): dirname /var/lib/ceph/bootstrap-rbd/ceph.keyring
+common_functions.sh:65: create_mandatory_directories(): mkdir -p /var/lib/ceph/bootstrap-rbd
+common_functions.sh:69: create_mandatory_directories(): for directory in mon osd mds radosgw tmp mgr
+common_functions.sh:70: create_mandatory_directories(): mkdir -p /var/lib/ceph/mon
+common_functions.sh:69: create_mandatory_directories(): for directory in mon osd mds radosgw tmp mgr
+common_functions.sh:70: create_mandatory_directories(): mkdir -p /var/lib/ceph/osd
+common_functions.sh:69: create_mandatory_directories(): for directory in mon osd mds radosgw tmp mgr
+common_functions.sh:70: create_mandatory_directories(): mkdir -p /var/lib/ceph/mds
+common_functions.sh:69: create_mandatory_directories(): for directory in mon osd mds radosgw tmp mgr
+common_functions.sh:70: create_mandatory_directories(): mkdir -p /var/lib/ceph/radosgw
+common_functions.sh:69: create_mandatory_directories(): for directory in mon osd mds radosgw tmp mgr
+common_functions.sh:70: create_mandatory_directories(): mkdir -p /var/lib/ceph/tmp
+common_functions.sh:69: create_mandatory_directories(): for directory in mon osd mds radosgw tmp mgr
+common_functions.sh:70: create_mandatory_directories(): mkdir -p /var/lib/ceph/mgr
+common_functions.sh:74: create_mandatory_directories(): mkdir -p /var/lib/ceph/mon/ceph-ceph-2
+common_functions.sh:77: create_mandatory_directories(): mkdir -p /var/run/ceph
+common_functions.sh:80: create_mandatory_directories(): mkdir -p /var/lib/ceph/radosgw/ceph-rgw.ceph-2
+common_functions.sh:83: create_mandatory_directories(): mkdir -p /var/lib/ceph/mds/ceph-ceph-2
+common_functions.sh:86: create_mandatory_directories(): mkdir -p /var/lib/ceph/mgr/ceph-ceph-2
+common_functions.sh:89: create_mandatory_directories(): chown --verbose -R ceph. /var/run/ceph/
ownership of '/var/run/ceph/' retained as ceph:ceph
+common_functions.sh:90: create_mandatory_directories(): find -L /var/lib/ceph/ -mindepth 1 -maxdepth 3 -exec chown --verbose ceph. '{}' ';'
ownership of '/var/lib/ceph/bootstrap-mds' retained as ceph:ceph
ownership of '/var/lib/ceph/bootstrap-mgr' retained as ceph:ceph
ownership of '/var/lib/ceph/bootstrap-osd' retained as ceph:ceph
ownership of '/var/lib/ceph/bootstrap-rbd' retained as ceph:ceph
ownership of '/var/lib/ceph/bootstrap-rgw' retained as ceph:ceph
ownership of '/var/lib/ceph/mds' retained as ceph:ceph
changed ownership of '/var/lib/ceph/mds/ceph-ceph-2' from root:root to ceph:ceph
ownership of '/var/lib/ceph/mgr' retained as ceph:ceph
changed ownership of '/var/lib/ceph/mgr/ceph-ceph-2' from root:root to ceph:ceph
ownership of '/var/lib/ceph/mon' retained as ceph:ceph
changed ownership of '/var/lib/ceph/mon/ceph-ceph-2' from root:root to ceph:ceph
ownership of '/var/lib/ceph/osd' retained as ceph:ceph
changed ownership of '/var/lib/ceph/radosgw' from root:root to ceph:ceph
changed ownership of '/var/lib/ceph/radosgw/ceph-rgw.ceph-2' from root:root to ceph:ceph
ownership of '/var/lib/ceph/tmp' retained as ceph:ceph
changed ownership of '/var/lib/ceph/tmp/tmp.aJyuNqO8hK' from root:root to ceph:ceph
+/entrypoint.sh:45: case "$CEPH_DAEMON" in
+/entrypoint.sh:178: is_redhat
+common_functions.sh:214: is_redhat(): get_package_manager
+common_functions.sh:207: get_package_manager(): is_available rpm
+common_functions.sh:58: is_available(): command -v rpm
+common_functions.sh:208: get_package_manager(): OS_VENDOR=redhat
+common_functions.sh:215: is_redhat(): [[ redhat == \r\e\d\h\a\t ]]
+/entrypoint.sh:179: source start_rbd_target_api.sh
++start_rbd_target_api.sh:2: set -e
+/entrypoint.sh:180: start_rbd_target_api
+start_rbd_target_api.sh:5: start_rbd_target_api(): get_config
+/config.static.sh:116: get_config(): log 'static: does not generate config'
+common_functions.sh:7: log(): '[' -z 'static: does not generate config' ']'
+common_functions.sh:11: log(): local timestamp
++common_functions.sh:12: log(): date '+%F %T'
+common_functions.sh:12: log(): timestamp='2018-12-10 14:49:28'
2018-12-10 14:49:28  /entrypoint.sh: static: does not generate config
+common_functions.sh:13: log(): echo '2018-12-10 14:49:28  /entrypoint.sh: static: does not generate config'
+common_functions.sh:14: log(): return 0
+start_rbd_target_api.sh:6: start_rbd_target_api(): check_config
+common_functions.sh:30: check_config(): [[ ! -e /etc/ceph/ceph.conf ]]
+start_rbd_target_api.sh:8: start_rbd_target_api(): '[' 0 -eq 1 ']'
+start_rbd_target_api.sh:14: start_rbd_target_api(): ceph_health client.admin /etc/ceph/ceph.client.admin.keyring
+common_functions.sh:321: ceph_health(): local bootstrap_user=client.admin
+common_functions.sh:322: ceph_health(): local bootstrap_key=/etc/ceph/ceph.client.admin.keyring
+common_functions.sh:324: ceph_health(): timeout 10 ceph --cluster ceph --name client.admin --keyring /etc/ceph/ceph.client.admin.keyring health
HEALTH_WARN mon ceph-1 is low on available space
+start_rbd_target_api.sh:17: start_rbd_target_api(): mount -t configfs none /sys/kernel/config
+start_rbd_target_api.sh:19: start_rbd_target_api(): log SUCCESS
+common_functions.sh:7: log(): '[' -z SUCCESS ']'
+common_functions.sh:11: log(): local timestamp
++common_functions.sh:12: log(): date '+%F %T'
+common_functions.sh:12: log(): timestamp='2018-12-10 14:49:28'
+common_functions.sh:13: log(): echo '2018-12-10 14:49:28  /entrypoint.sh: SUCCESS'
+common_functions.sh:14: log(): return 0
+start_rbd_target_api.sh:21: start_rbd_target_api(): exec /usr/bin/rbd-target-api
+docker_exec.sh:132: exec(): trap _int SIGINT
+docker_exec.sh:133: exec(): trap _ill SIGILL
+docker_exec.sh:134: exec(): trap _abrt SIGABRT
+docker_exec.sh:135: exec(): trap _fpe SIGFPE
+docker_exec.sh:136: exec(): trap _segv SIGSEGV
+docker_exec.sh:137: exec(): trap _term SIGTERM
+docker_exec.sh:138: exec(): trap _bus SIGBUS
+docker_exec.sh:139: exec(): trap _chld SIGCHLD
+docker_exec.sh:140: exec(): trap _kill SIGKILL
2018-12-10 14:49:28  /entrypoint.sh: SUCCESS
exec: PID 106: spawning /usr/bin/rbd-target-api
exec: Waiting 106 to quit                     #<-- (this is terminated for some reason)
+docker_exec.sh:144: exec(): child_for_exec=106
+docker_exec.sh:146: exec(): echo 'exec: PID 106: spawning /usr/bin/rbd-target-api'
+docker_exec.sh:147: exec(): echo 'exec: Waiting 106 to quit'
+docker_exec.sh:148: exec(): wait 106
+docker_exec.sh:143: exec(): /usr/bin/rbd-target-api
++docker_exec.sh:1: exec(): _chld
++docker_exec.sh:121: _chld(): teardown SIGCHLD -1
++docker_exec.sh:38: teardown(): trap - SIGINT SIGILL SIGABRT SIGFPE SIGSEGV SIGTERM SIGBUS SIGCHLD SIGKILL
++docker_exec.sh:43: teardown(): local signal_name=SIGCHLD
++docker_exec.sh:44: teardown(): local exit_code=-1
++docker_exec.sh:45: teardown(): echo 'teardown: managing teardown after SIGCHLD'
++docker_exec.sh:50: teardown(): NOTRAP=yes
++docker_exec.sh:54: teardown(): '[' SIGCHLD = SIGTERM ']'
++docker_exec.sh:61: teardown(): '[' -e /proc/106 ']'
++docker_exec.sh:63: teardown(): echo -n 'teardown: Waiting PID 106 to terminate '
++docker_exec.sh:64: teardown(): local MAX_TIMEOUT=50
++docker_exec.sh:65: teardown(): local timeout=0
++docker_exec.sh:66: teardown(): '[' -e /proc/106 ']'
++docker_exec.sh:77: teardown(): echo
++docker_exec.sh:78: teardown(): echo 'teardown: Process 106 is terminated'  
++docker_exec.sh:80: teardown(): '[' SIGCHLD = SIGTERM ']'
++docker_exec.sh:85: teardown(): declare -F trap_exec_failure
++docker_exec.sh:88: teardown(): echo 'teardown: Bye Bye, container will die with return code -1'
++docker_exec.sh:89: teardown(): exit -1
teardown: managing teardown after SIGCHLD
teardown: Waiting PID 106 to terminate 
teardown: Process 106 is terminated
teardown: Bye Bye, container will die with return code -1
