### ISSUE TITLE
Disable ability to push directly to master

### ISSUE THREAD

**Issue by alfredodeza** [ceph/ceph-container#1277]
Is this a bug report or feature request?
* Bug Report

**Bug Report**

What happened: Changes are being pushed directly to master, without reviews or testing 

What you expected to happen: 
Pushing commits to master like this should be not allowed, so that code can be reviewed, changes can have better visibility, and patches can be verified by running tests. In the project configuration, pushing directly to production branches should be disabled.

Adhere to the contributing guidelines for fixing bugs and adding features, which state that a PR is expected: https://github.com/ceph/ceph-container/blob/master/CONTRIBUTING.md#fixing-a-bug

How to reproduce it (minimal and precise): See https://github.com/ceph/ceph-container/commit/52deba5151a534578b9ea4cbb6db7131ace19be8

**Comment by ErwanAliasr1** [comment]
Ok. I did that push quickly to master as 
- it was obvious
- typo fixing
- unlock a broken builds for everyone

I agree that should be avoided but I don't think I put the project in danger in any way.
As a core-maintainer of the project, I do think I have enough experience on this part to use this emergency commit on purpose.

**Comment by alfredodeza** [comment]
Maybe the contributing guidelines should add a section that if a fix is: obvious, fixes a typo, or unlocks a broken build, then it can go straight to master.

Additionally, we could have some sort of metric to indicate how dangerous a change is, and if the submitter has enough experience. That would raise confidence in the project as it accepts patches directly without any sort of checks or reviews.

However, one thing that pushing directly to master does (regardless of the skills of the developer) is that it hinders the visibility for the rest of the development team. No email update or any notification whatsoever is created. This causes that changes are obscured, and do not help the wider audience following the project's updates.
