### ISSUE TITLE
windows docker 

### ISSUE THREAD

**Issue by SWJTU-ZhangLei** [ceph/ceph-container#1285]
I try to deploy ceph with windows docker , but i don't know how to run docker image, can you help me?

**Comment by leseb** [comment]
What's your use case? An all in one container?

**Comment by SWJTU-ZhangLei** [comment]
Can all in one container? one container can only run one process?  I have successed in deploying a cluster on windows hyper-v virtual machine. 
I find that maybe windows docker cannot support deploying a cluster, because it cannot get access  to disk when deploy a osd.
By the way , I have a cluster like this and how to expand another mon.   Thank you very much.
================================
[root@node01 ~]# docker exec -it mon01 ceph -s
  cluster:
    id:     a0489c51-b10f-43a9-b7ac-2b45ac7b2232
    health: HEALTH_OK
 
  services:
    mon: 1 daemons, quorum node01
    mgr: node01(active)
    osd: 4 osds: 4 up, 4 in
    rgw: 1 daemon active
 
  data:
    pools:   3 pools, 192 pgs
    objects: 2.44k objects, 1.07GiB
    usage:   6.18GiB used, 67.2GiB / 73.4GiB avail
    pgs:     192 active+clean
 ================================

**Comment by leseb** [comment]
If you use docker on windows then I recommend deploying an all in one cluster with the 'demo' scenario. You can do multiple containers but this won't make much sense since docker on windows is only a single VM.

**Comment by rockers7414** [comment]
@leseb I run the ceph all in one (demo scenario).
I cannot use `rados` to put the file into pool. And below is the ceph status:
```
[root@b963045691c6 /]# ceph -s
  cluster:
    id:     39443fb3-eba4-4f99-ad5a-cf2e7d477345
    health: HEALTH_WARN
            1 MDSs report slow metadata IOs
            Reduced data availability: 160 pgs inactive, 16 pgs peering

  services:
    mon: 1 daemons, quorum b963045691c6
    mgr: b963045691c6(active)
    mds: cephfs-1/1/1 up  {0=0=up:creating}
    osd: 1 osds: 1 up, 1 in

  data:
    pools:   6 pools, 160 pgs
    objects: 0 objects, 0B
    usage:   1.00GiB used, 9.00GiB / 10GiB avail
    pgs:     90.000% pgs unknown
             10.000% pgs not active
             144 unknown
             16  creating+peering
```

**Comment by leseb** [comment]
`ceph osd dump`? You have PGs stuck, I think you have pool we higher replica than expected.

**Comment by rockers7414** [comment]
I use the demo scenario. I didn’t change anything yet. But I use another version of image, the issue is gone.
