### ISSUE TITLE
Sree web ui is misconfigured

### ISSUE THREAD

**Issue by vpavlin** [ceph/ceph-container#1294]
* Bug Report

**Bug Report**

What happened:
Sree web client calls to localhost (127.0.0.1) when trying to list buckets which will fail when Ceph Nano is running on a remote (kubernetes/openshift) cluster, as the localhost != cluster IP

What you expected to happen:

Correct URL/IP is configured here:

++/opt/ceph-container/bin/demo.sh:318: bootstrap_sree(): sed -i 's|ENDPOINT|http://127.0.0.1:8000|'  static/js/base.js

How to reproduce it (minimal and precise):

Following https://gist.github.com/mmgaggle/b30612122bae076ac3f3fe396f2c033a and exposing the port 5001 in addition to already exposed 8000, then accessing the Web UI, creating buccket and trying to list the contents.

**Environment**:
* OpenShift 3.11

**Comment by leseb** [comment]
Unfortunately, that's a known issue, we are working on using the dashboard differently, see: https://github.com/ceph/cn-core/issues/4, hopefully, that will make things easier in the future and for OpenShift too.

This is the new project that replaces `demo.sh` to bootstrap `cn`.
