### ISSUE TITLE
Ceph Nano container uses virtual addressing style

### ISSUE THREAD

**Issue by vpavlin** [ceph/ceph-container#1295]
**Bug Report**

What happened:
When running Ceph Nano on OpenShift a user cannot use internal service discovery mechanisms which allow addressing services by its name. This is (IMO) due to the fact that when a hostname (like a service name or route) is used to address Ceph Nano container it tries to resolve the hostname into a bucket name (and hostname). As the internal DNS (and routes) do not allow/use wildcards (thus the bucket.hostname will not be able to resolve), clients will fall back to using path style addressing - which Ceph Nano will not recognize and will assume the given hostname as a bucket name.

This results in an error `NoSuchBucket` for all requests.

The workaround is to use the service IP address, but that is not a good user experience and breaks best practices (as service IP can change, but the the name will be consistent)

What you expected to happen:
If not by default, I'd like to be able to change the addressing style by environment variable. This will also enable using routes easily which will be  very useful for people to simply expose Ceph Nano route and then use AWS CLI tools to work with Ceph Nano Object storage

How to reproduce it (minimal and precise):
Deploy Ceph Nano to OpenShift/Kubernetes using f.e. https://gist.github.com/mmgaggle/b30612122bae076ac3f3fe396f2c033a

Try to run following command from the ceph-nano-0 pod:

```
curl http://localhost:8000
```
result:

```
sh-4.2# curl http://localhost:8000
<?xml version="1.0" encoding="UTF-8"?><Error><Code>NoSuchBucket</Code><BucketName>localhost</BucketName><RequestId>tx000000000000000000039-005c419dc9-104c-default</RequestId><HostId>104c-default-default</HostId></Error>
```

Then run

```
curl 127.0.0.1:800
```

result:

```
sh-4.2# curl http://127.0.0.1:8000
<?xml version="1.0" encoding="UTF-8"?><ListAllMyBucketsResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Owner><ID>anonymous</ID><DisplayName></DisplayName></Owner><Buckets></Buckets></ListAllMyBucketsResult>sh-4.2#
```

In the first case there is the above mentioned error as the `localhost` hostname is assumed to be a bucket name, the second case returns empty list of buckets as expected

**Environment**:
* OpenShift 3.11

**Comment by leseb** [comment]
How would like to see this being solved? We can have a new variable for addressing the gateway but do we know it in advance?
The container hostname also works, but do we know the service name before running nano?

**Comment by vpavlin** [comment]
I think you might have misunderstood the problem.

This is from S3 CLI documentation:

> addressing_style - Specifies which addressing style to use. This controls if the bucket name is in the hostname or part of the URL. Value values are: path, virtual, and auto. The default value is auto.
payload_signing_enabled - Refers to whether or not to SHA256 sign sigv4 payloads. By default, this is disabled for streaming uploads (UploadPart and PutObject) when using https.

The problem is that Ceph is trying to use subdomain as a bucket name. There should be a configuration option in Ceph (I think) which would make it prefer the bucket name in path, but I am don't have the Ceph knowledge to be able to figure out the configuration option. 

Does it make more sense?

**Comment by leseb** [comment]
Hum, I understand now, isn't this something you have to configure in the AWS client?
For instance setting `addressing_style` to `path` instead of `auto`?

Thanks.

**Comment by vpavlin** [comment]
Sadly, that does not seem to do the trick

```
cat ~/.aws/config
[default]
s3 =
  addressing_style = path

sh-4.2$ echo $S3_ENDPOINT_URL
http://ceph:8000
sh-4.2$ aws s3 ls --endpoint-url=$S3_ENDPOINT_URL

An error occurred (NoSuchBucket) when calling the ListBuckets operation: Unknown
```

on the other hand, this works

```
sh-4.2$ aws s3 ls --endpoint-url=http://$CEPH_SERVICE_HOST:$CEPH_SERVICE_PORT
sh-4.2$ echo http://$CEPH_SERVICE_HOST:$CEPH_SERVICE_PORT
http://172.30.19.80:8000
```

I am open to other ideas

**Comment by LandoCalrizzian** [comment]
I found the issue with the [demo ceph-container](https://gist.github.com/mmgaggle/b30612122bae076ac3f3fe396f2c033a) is that the ceph-container is expecting the base dns name to match the container hostname since the env var RGW_NAME is not set. Including the env var RGW_NAME=${ceph service name} in the container config allows other pods to access the S3 endpoint using dns.

**Comment by vpavlin** [comment]
@LandoCalrizzian Great catch:) I guess we can close this now
