### ISSUE TITLE
docker hub instructions create race condition for OSD startup

### ISSUE THREAD

**Issue by nealey** [ceph/ceph-container#1304]
Around line 30 of `osd_disk_activate.sh` ([link](https://github.com/ceph/ceph-container/blob/dcfbe1316a332feb7b8161ab3d6d5a9772d8c9e1/src/daemon/osd_scenarios/osd_disk_activate.sh#L30)), there is a call to `udevadm trigger`, and then a call to `udevadm settle`.

The `udevadm settle` returns immediately if there is no `udev` socket inside the container. This is causing my systems to occasionally (and, frustratingly, non-deterministically) complain:

    Could not locate appropriate symlink for partition ${osd_partition} of ${osd_device}

This is causing a weird race condition for my machines where sometimes the container fails to find the correct partition device. I presume because the host udev is still rebuilding `/dev` and hasn't gotten to that device yet, but I stopped looking into this once I found the workaround: **bind-mount `/run/udev` into the container**. It takes longer to start up the osd container this way, probably because it is (correctly, now) blocking until udev (in the container's host) has settled.

The instructions on docker hub (https://hub.docker.com/r/ceph/daemon) should ask to also bind mount `/run/udev` in addition to `/dev`, so that udev inside the container can contact the right udevd in order to block pending population of `/dev`. Something like this:

```
docker run -d --net=host \
--pid=host \
--privileged=true \
-v /etc/ceph:/etc/ceph \
-v /var/lib/ceph/:/var/lib/ceph/ \
-v /dev/:/dev/ \
-v /run/udev/:/run/udev/ \
-e OSD_DEVICE=/dev/vdd \
ceph/daemon osd
```

Of course this would need to be repeated a number of times for all the examples.

**Comment by doransmestad** [comment]
Just ran into this myself.  Thanks for the solution @nealey!   Mounting /run/udev into my osd containers solved the issue and brought the osds back online after a host restart.

**Comment by AndrewwHummer** [comment]
So, this solves issues in the centos container regarding udev, not only the official ceph container...
Thanks for the hint.
I had some troubles with hanging LVM commands in a centOS container, had.

**Comment by nealey** [comment]
This text still needs to be changed, as outlined in the original bug report.
