### ISSUE TITLE
ceph/daemon:latest-mimic image violates containerization concepts

### ISSUE THREAD

**Issue by mazzystr** [ceph/ceph-container#1313]
Is this a bug report or feature request?
* Bug Report

**Bug Report**

What happened:
I currently have osd 0,1,3,4 containerized.  osd 2,5,6,7 are traditional processes on the host.  As an experiment I commented ceph-osd4-{db, wal} from /etc/crypttab and rebooted the host.  Containers osd0, osd1, osd3, osd4 and their ceph-osd daemons crashed.  I manually started container osd0.  It would fail straight away complaining about /var/lib/ceph/osd/ceph-4/block.{db, wal} not being found.

Here is my systemd unit...
```
/etc/systemd/system/podman-ceph-osd-0.service
[Unit]
Description=Podman container - Ceph osd 0
After=network.target

[Service]
Type=simple
WorkingDirectory=/var/lib/ceph/osd/ceph-0
TimeoutStartSec=300
ExecStart=-/usr/bin/podman run -t --rm --privileged --pid=host --name osd0 --hostname osd0 -v /etc/ceph:/etc/ceph/ -v /var/lib/ceph/osd/:/var/lib/ceph/osd/ -v /dev/:/dev/ -e OSD_DEVICE=/dev/mapper/ceph-0block -e OSD_BLUESTORE=1 ceph/daemon:latest-mimic osd_directory_single
ExecStop=-/usr/bin/podman rm -f osd0
Restart=false
RestartSec=30

[Install]
WantedBy=multi-user.target
```

Sample log...
```
Feb 21 09:34:45 cube systemd: Started Podman container - Ceph osd 0.
Feb 21 09:34:45 cube kernel: IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
Feb 21 09:34:45 cube kernel: IPv6: ADDRCONF(NETDEV_UP): vethe0da2414: link is not ready
Feb 21 09:34:45 cube kernel: IPv6: ADDRCONF(NETDEV_CHANGE): vethe0da2414: link becomes ready
Feb 21 09:34:45 cube kernel: IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
Feb 21 09:34:45 cube kernel: cni0: port 2(vethe0da2414) entered blocking state
Feb 21 09:34:45 cube kernel: cni0: port 2(vethe0da2414) entered disabled state
Feb 21 09:34:45 cube kernel: device vethe0da2414 entered promiscuous mode
Feb 21 09:34:45 cube kernel: cni0: port 2(vethe0da2414) entered blocking state
Feb 21 09:34:45 cube kernel: cni0: port 2(vethe0da2414) entered forwarding state
Feb 21 09:34:45 cube NetworkManager[6021]: <info>  [1550759685.6686] device (vethe0da2414): carrier: link connected
Feb 21 09:34:45 cube NetworkManager[6021]: <info>  [1550759685.6689] manager: (vethe0da2414): new Veth device (/org/freedesktop/NetworkManager/Devices/19)
Feb 21 09:34:45 cube systemd: Started libpod-conmon-a4c70b403b2dd64df73316d45b66049d3423d451396b85468dcfa0ac69153719.scope.
Feb 21 09:34:45 cube systemd: Scope libcontainer-29959-systemd-test-default-dependencies.scope has no PIDs. Refusing.
Feb 21 09:34:45 cube systemd: Scope libcontainer-29959-systemd-test-default-dependencies.scope has no PIDs. Refusing.
Feb 21 09:34:45 cube systemd: Created slice libcontainer_29959_systemd_test_default.slice.
Feb 21 09:34:45 cube systemd: Removed slice libcontainer_29959_systemd_test_default.slice.
Feb 21 09:34:45 cube systemd: Created slice libcontainer_29959_systemd_test_default.slice.
Feb 21 09:34:45 cube systemd: Removed slice libcontainer_29959_systemd_test_default.slice.
Feb 21 09:34:45 cube systemd: Started libcontainer container a4c70b403b2dd64df73316d45b66049d3423d451396b85468dcfa0ac69153719.
Feb 21 09:34:45 cube podman: chown: cannot dereference '/var/lib/ceph/osd/osd-4-block.db': No such file or directory
Feb 21 09:34:45 cube podman: chown: cannot dereference '/var/lib/ceph/osd/osd-4-bock.wal': No such file or directory
Feb 21 09:34:45 cube podman: 2019-02-21 14:34:45  /opt/ceph-container/bin/entrypoint.sh: static: does not generate config
Feb 21 09:34:45 cube podman: 2019-02-21 14:34:45  /opt/ceph-container/bin/entrypoint.sh: Looks like OSD: 4 is not started, starting it...
Feb 21 09:34:45 cube podman: 2019-02-21 14:34:45  /opt/ceph-container/bin/entrypoint.sh: SUCCESS
Feb 21 09:34:45 cube podman: exec: PID 30151: spawning ceph-osd --cluster ceph --setuser ceph --setgroup ceph -d -i 4 -k /var/lib/ceph/osd/ceph-4//keyring
Feb 21 09:34:45 cube podman: exec: Waiting 30151 to quit
Feb 21 09:34:45 cube podman: 2019-02-21 14:34:45.902 7ff8b22001c0 -1 WARNING: the following dangerous and experimental features are enabled: bluestore,rocksdb
Feb 21 09:34:45 cube podman: 2019-02-21 14:34:45.921 7ff8b22001c0 -1 WARNING: the following dangerous and experimental features are enabled: bluestore,rocksdb
Feb 21 09:34:45 cube podman: 2019-02-21 14:34:45.921 7ff8b22001c0  0 set uid:gid to 167:167 (ceph:ceph)
Feb 21 09:34:45 cube podman: 2019-02-21 14:34:45.921 7ff8b22001c0  0 ceph version 13.2.4 (b10be4d44915a4d78a8e06aa31919e74927b142e) mimic (stable), process ceph-osd, pid 30151
```

How to reproduce it (minimal and precise):
1) Take down osdX and damage it's directory so that it can't restart
2) Restart container osdY on same host as osdX
3) The container osdY will fail bitching about a damaged directory of osdX

What you expected to happen:
I expect osd containers to start their pertaining ceph-osd processes.

This containerization method is insanity...
1) The entrypoint scripts scans the /var/lib/ceph/osd directory for osds then starts the first osd and/or multiples osds that currently are not running.  First multiple processes inside a single container is a big no-no!  The entrypoint scripts can also create a scenario where osd ids run within unexpected containers.  For the sake of sanity I want osd id X to run in container cephosdX on host cephX... NOT osd id X within container cephosdY on host cephX
- Fixed by passing -v /var/lib/ceph/osd/ceph-%i:/var/lib/ceph/osd/ceph-%i:z directly to the container)
- Process tree looks correct but host/osds apear crisscrossed according to `ceph osd status`
2) ~~It's advertised to pass the entire /var/lib/ceph/ directory to a _priveledged_ container.  Is there a mons on this host?  Yes in this case.  There's potential for damage to an entire cluster.~~
- Fixed by passing -v /var/lib/ceph/osd/ceph-%i:/var/lib/ceph/osd/ceph-%i:z directly to the container)
3) It's advertised to pass the entire /dev directory  to a _priveledged_ container.  This has potential to severely damage the host and and all the physical disks of a host.
4) It's advertised to pass /etc/ceph read-write to a _priveledged_ container.  Why does a mon,osd,mds,mgr container need rw access to /etc/ceph?  Should this not be ro?

Surely we can do better folks!

**Environment**:
* OS (e.g. from /etc/os-release): CentOS Linux release 7.6.1810 (Core)
* Kernel (e.g. `uname -a`): 3.10.0-957.5.1.el7.x86_64 #1 SMP
* Docker version (e.g. `docker version`): podman version 0.11.2-dev
* Ceph version (e.g. `ceph -v`): ceph-13.2.4-0.el7.x86_64

**Comment by mazzystr** [comment]
> * The entrypoint scripts scans the /var/lib/ceph/osd directory for osds then starts the first osd and/or multiples osds that currently are not running.  First multiple processes inside a single container is a big no-no!  The entrypoint scripts can also create a scenario where osd ids run within unexpected containers.  For the sake of sanity I want osd id X to run in container cephosdX on host cephX... NOT osd id X within container cephosdY on host cephX
> 
> * It's advertised to pass the entire /var/lib/ceph/ directory to a _priveledged_ container.  Is there a mons on this host?  Yes in this case.  There's potential for damage to an entire cluster.

The above is absolutely frightening.  I've adjusted my run command to the following...
```
/usr/bin/podman run -t --rm --privileged --pid=host --name osd0 --hostname osd0 -v /etc/ceph:/etc/ceph/ -v /var/lib/ceph/osd/ceph-0:/var/lib/ceph/osd/ceph-0 -v /dev/:/dev/ -e /var/log/ceph:/var/log/ceph -e OSD_DEVICE=/dev/mapper/ceph-0block -e OSD_BLUESTORE=1 ceph/daemon:latest-mimic osd_directory_single
```

**Comment by devster31** [comment]
This seems more of a problem with how you're using the container more than what the container itself can do.
Following some examples from `ceph-ansible` the containers are rune with a `ceph-osd@.service` and instantiated singularly.
```
# Please do not change this file directly since it is managed by Ansible and will be overwritten
[Unit]
Description=Ceph OSD
After=docker.service

[Service]
EnvironmentFile=-/etc/environment
ExecStartPre=-/usr/bin/docker stop ceph-osd-%i
ExecStartPre=-/usr/bin/docker rm -f ceph-osd-%i
ExecStart=/usr/bin/docker run \
  --rm \
  --net=host \
  --privileged=true \
  --pid=host \
  --memory=64389m \
  --cpus=1 \
  -v /dev:/dev \
  -v /etc/localtime:/etc/localtime:ro \
  -v /var/lib/ceph/osd/ceph-%i:/var/lib/ceph/osd/ceph-%i:z \
  -v /etc/ceph:/etc/ceph:z \
  -v /var/run/ceph:/var/run/ceph:z \
  -v /var/run/udev/:/var/run/udev/:z \
  --security-opt apparmor:unconfined \
  -e OSD_DMCRYPT=0 \
  -e OSD_BLUESTORE=1 \
  -e CLUSTER=ceph \
  -v /run/lvm/lvmetad.socket:/run/lvm/lvmetad.socket \
  -e CEPH_DAEMON=OSD_CEPH_VOLUME_ACTIVATE \
  -e OSD_ID=%i \
  --name=ceph-osd-%i \
  ceph/daemon:latest-mimic
ExecStop=-/usr/bin/docker stop ceph-osd-%i
Restart=always
RestartSec=10s
TimeoutStartSec=120
TimeoutStopSec=15

[Install]
WantedBy=multi-user.target
```
just as an example of what could be done.
This is the `docker top` of the above:
```
UID                 PID                 PPID                C                   STIME               TTY                 TIME                CMD
root                14781               14749               0                   00:17               ?                   00:00:00            /bin/bash /opt/ceph-container/bin/entrypoint.sh
167                 19700               14781               0                   00:17               ?                   00:00:09            /usr/bin/ceph-osd --cluster ceph --setuser ceph --setgroup ceph -d -i 1
```

**Comment by mazzystr** [comment]
I'm running podman and runc....without Docker docker binary or daemon.

My container is running better....
```
# podman ps | grep osd0
61a0a628eb51  registry.hub.docker.com/ceph/daemon:latest-mimic        /opt/ceph-contain...  12 minutes ago  Up 12 minutes ago                          osd0
```
```
# ps -ef | grep 61a0a628eb51
root     2681404       1  0 08:54 ?        00:00:00 /usr/libexec/podman/conmon -s -c 61a0a628eb51d2d619a4609cd134cc3d1502aee51cb7f2574b40746e55679ca2 -u 61a0a628eb51d2d619a4609cd134cc3d1502aee51cb7f2574b40746e55679ca2 -r /usr/bin/runc -b /var/lib/containers/storage/overlay-containers/61a0a628eb51d2d619a4609cd134cc3d1502aee51cb7f2574b40746e55679ca2/userdata -p /var/run/containers/storage/overlay-containers/61a0a628eb51d2d619a4609cd134cc3d1502aee51cb7f2574b40746e55679ca2/userdata/pidfile -l /var/lib/containers/storage/overlay-containers/61a0a628eb51d2d619a4609cd134cc3d1502aee51cb7f2574b40746e55679ca2/userdata/ctr.log --exit-dir /var/run/libpod/exits --socket-dir-path /var/run/libpod/socket -t --log-level error

# ps -ef | grep 2681404
root     2681404       1  0 08:54 ?        00:00:00 /usr/libexec/podman/conmon -s -c 61a0a628eb51d2d619a4609cd134cc3d1502aee51cb7f2574b40746e55679ca2 -u 61a0a628eb51d2d619a4609cd134cc3d1502aee51cb7f2574b40746e55679ca2 -r /usr/bin/runc -b /var/lib/containers/storage/overlay-containers/61a0a628eb51d2d619a4609cd134cc3d1502aee51cb7f2574b40746e55679ca2/userdata -p /var/run/containers/storage/overlay-containers/61a0a628eb51d2d619a4609cd134cc3d1502aee51cb7f2574b40746e55679ca2/userdata/pidfile -l /var/lib/containers/storage/overlay-containers/61a0a628eb51d2d619a4609cd134cc3d1502aee51cb7f2574b40746e55679ca2/userdata/ctr.log --exit-dir /var/run/libpod/exits --socket-dir-path /var/run/libpod/socket -t --log-level error
root     2681417 2681404  0 08:54 pts/2    00:00:00 /bin/bash /opt/ceph-container/bin/entrypoint.sh osd_directory_single

# ps -ef | grep 2681417
root     2681417 2681404  0 08:54 pts/2    00:00:00 /bin/bash /opt/ceph-container/bin/entrypoint.sh osd_directory_single
ceph     2681516 2681417  2 08:54 pts/2    00:00:17 ceph-osd --cluster ceph --setuser ceph --setgroup ceph -d -i 0 -k /var/lib/ceph/osd/ceph-0//keyring
```


Curiously `ceph osd status` shows crisscrossed host/osds whereas `ceph osd tree` does not
```
# ceph osd status
+----+------+-------+-------+--------+---------+--------+---------+-----------+
| id | host |  used | avail | wr ops | wr data | rd ops | rd data |   state   |
+----+------+-------+-------+--------+---------+--------+---------+-----------+
| 0  | osd1 | 1568G | 1272G |    0   |     0   |    0   |     0   | exists,up |
| 1  | osd3 | 1618G | 1223G |    0   |     0   |    0   |     0   | exists,up |
| 2  | host | 4932G |  702G |    0   |     0   |    0   |     0   | exists,up |
| 3  | osd4 | 2238G |  602G |    0   |     0   |    0   |     0   | exists,up |
| 4  | osd0 | 1340G | 1452G |    0   |     0   |    0   |     0   | exists,up |
| 5  | host | 5118G |  468G |    0   |     0   |    0   |     0   | exists,up |
| 6  | host | 1269G | 1522G |    0   |     0   |    0   |     0   | exists,up |
+----+------+------
```
# ceph osd tree
ID  CLASS WEIGHT   TYPE NAME         STATUS REWEIGHT PRI-AFF
 -1       17.00000 root default
 -5       13.00000     host host
  2   hdd  6.00000         osd.2         up  1.00000 1.00000
  5   hdd  6.00000         osd.5         up  1.00000 1.00000
  6   hdd  1.00000         osd.6         up  1.00000 1.00000
-11        4.00000     rack rack1
 -7        1.00000         host osd0
  0   hdd  1.00000             osd.0     up  1.00000 1.00000
-13        1.00000         host osd1
  1   hdd  1.00000             osd.1     up  1.00000 1.00000
 -2        1.00000         host osd3
  3   hdd  1.00000             osd.3     up  1.00000 1.00000
 -9        1.00000         host osd4
  4   hdd  1.00000             osd.4     up  1.00000 1.00000

**Comment by mazzystr** [comment]
Rebooting hosts cleaned up `ceph osd tree`

**Comment by leseb** [comment]
@mazzystr let me clarify something, the method you're using to bootstrap Ceph is not the recommended one anymore. I was planning on removing some of that code but I haven't had the time to do this.
Basically, it's not expected anymore to deploy Ceph "manually" but via an orchestration such as ceph-ansible or Rook.
So the osd_* scenarios will disappear soon, I'm not even sure people are still using it given that most the methods rely on ceph-disk which is deprecated and won't be part of the next Ceph release. 

I'm sorry for the confusion that the current doc/repo might bring. I'll try to fix that soon.

@dsavineau, ping me when you have time, we need to discuss this and take action.
