### ISSUE TITLE
Possible to reduce image sizes by using different base image?

### ISSUE THREAD

**Issue by F21** [ceph/ceph-container#132]
It might be possible to reduce the size of the docker images by using a different base image such as [alpine](https://registry.hub.docker.com/_/alpine/).

**Comment by leseb** [comment]
Yup, I don't see why we couldn't, I'll give it a shot.
This will likely be a new branch just like the centos one.

**Comment by leseb** [comment]
@F21 by any chance, do you know how to add a new repo to the image?
I'm having trouble adding the ceph repo. I'm not sure if it's possible.
We might have to add all the packages and their dependancies manually, not really handy.

**Comment by F21** [comment]
@leseb I don't think it's possible to reuse the ubuntu and centos repos. An apk repo would need to be created: http://wiki.alpinelinux.org/wiki/Alpine_Linux_package_management#Packages_and_Repositories

**Comment by leseb** [comment]
@F21 do you think you can come up with something for this?

**Comment by F21** [comment]
@leseb Leave it with me. I will do some research to see what we can do. I only just found out about alpine today as well, but am interested in using it as a base image for deploying my microservices. I am sure this problem has already been solved by the community as it should be a pretty common issue for people moving from ubuntu or some other distro to alpine.

**Comment by leseb** [comment]
@F21 Ok thanks, looking forward to seing a PR :)

**Comment by F21** [comment]
I think the best approach is to build ceph within alpine-linux. Unfortunately, I have hit a dead-end and it refuses to build.

This is the dockerfile for those interested:

```
FROM alpine

RUN echo "@testing http://nl.alpinelinux.org/alpine/edge/testing" >>/etc/apk/repositories \
  && echo "@edge-main http://nl.alpinelinux.org/alpine/edge/main" >>/etc/apk/repositories \
  && apk update \
  && apk add bash yasm libtool util-linux-dev udev-dev automake autoconf build-base git perl keyutils keyutils-dev crypto++@testing snappy@edge-main snappy-dev@edge-main \
  && wget -O ceph.tar.gz http://ceph.com/download/ceph-9.0.2.tar.gz \
  && tar xvzf ceph.tar.gz \
  && cd ceph-9.0.2 \
  && ./autogen.sh \
  && ./configure \
  && make \
  && rm -rf /var/cache/apk/*
```

It will complain that libsnappy doesn't exist, even though is installed:
```
checking for snappy_compress in -lsnappy... no
configure: error: in `/ceph-9.0.2':
configure: error: libsnappy not found
See `config.log' for more details
```

Seems like others are having the same issue too: http://bugs.alpinelinux.org/issues/3241

Not sure if building on alpine linux is something the ceph team will support since it's pretty esoteric (at least at the moment).

**Comment by Ulexus** [comment]
I've worked a lot with Alpine, and for something as complex as Ceph, I'm dubious about whether you'll be able to get it to work.  There are a number of common issues that stem from Alpine's use of musl libc, busybox-based utils, and its commonly-defaulted polarSSL.  It's a really excellent distribution for what it does, but using it requires very standards-compliant code.  musl libc is much more strict/"limited" than glibc.

**Comment by hookenz** [comment]
Probably not worth the effort.   Maybe a debian base would be a better alternative.  According to this link (now a little outdated, debian has nearly half the fat).  http://blog.javabien.net/2014/06/18/size-of-docker-images-which-linux-is-smaller/

**Comment by Ulexus** [comment]
@hookenz 
*  debian:jessie  - ~125MB
*  ubuntu:trusty  - ~188MB

It's less, but not by all that much.  I don't know whether it's worth changing, since Ubuntu is explicitly tested and supported by Ceph (to my knowledge, Debian is not) _and_ it tends to have more up-to-date packages.

**Comment by hookenz** [comment]
@Ulexus - Agreed.  Ubuntu has the best support.

**Comment by F21** [comment]
@dx9 has started patching ceph to work on alpine.

https://github.com/dx9/ceph
https://github.com/dx9/build-alpine-ceph

**Comment by Ulexus** [comment]
Very interesting.  Until the patches are upstreamed, I don't see it becoming the primary distribution path... but it could certainly be an optional branch/tag.

**Comment by F21** [comment]
xref ceph redmine: http://tracker.ceph.com/issues/12406#change-59870

**Comment by dx9** [comment]
Saw this chat the other day. I'm definitely up for hacking on this line to see where it goes. The port uses the new CMake build. Packed it based on the rpm layout. Probably some missing deps and other issues.

**Comment by Ulexus** [comment]
Thanks @dx9.  I definitely look forward to it.  Have you checked that the pieces actually run?  In particular, I've had the Alpine crypo libraries be a problem with other projects (not _really_ Alpine's fault; just glibc-isms in the other packages).  So, particularly cephx?

**Comment by dx9** [comment]
Nope I haven't even run it yet! ;) It's fresh. Real fresh. Been focused on the build and packaging. It does build the tests. Haven't spent any time testing yet though.

**Comment by Ulexus** [comment]
@dx9  Heh.  Yeah, I see.  Thanks

**Comment by streamnsight** [comment]
talking about base images... does anyone know if Ceph works on armv7 ?

**Comment by natostanco** [comment]
Since alpine build is not ready yet, I have made a slimmed version (with `docker-slim`) with this couple of scripts of `ceph/daemon` `560MB->230MB` , if someone wanna test it out and tell if there is some critical stuff missing, gotta `chown -R ceph:ceph /var/log/ceph` before running the entrypoint, there might be other permission quirks due to the rebuild process:
```
#!/bin/bash
#slimceph
docker pull ceph/daemon
export SAVE=${PWD}
mkdir -p ${SAVE}/etc ${SAVE}/var
sudo ./docker-slim --debug build \
--continue-after 60 \
--http-probe \
--mount ${SAVE}/etc:/etc/ceph \
--mount ${SAVE}/var:/var/lib/ceph \
--mount ${SAVE}/scripts:/scripts \
--include-path /etc/confd \
--include-path /var/log/ceph \
--include-path /tmp \
ceph/daemon &> /dev/null &

sleep 5

docker exec -it $(docker ps | grep dockerslim | awk '{print $1}') /scripts/testceph

while [[ $( docker images | grep "ceph/daemon.slim" | wc -l ) -ne 1 ]]
do 
sleep 5
done

```

```
#!/bin/bash
#testceph
export MON_IP=172.17.0.1 CEPH_PUBLIC_NETWORK=172.17.0.0/24
/entrypoint.sh mon &> /dev/null &
sleep 5
mkdir -p /var/lib/ceph/osd
export OSD_FORCE_ZAP=1 OSD_DIRECTORY=/var/lib/ceph/osd
/entrypoint.sh osd_directory &> /dev/null &
sleep 5
export CEPHFS_CREATE=1
/entrypoint.sh mds &> /dev/null &
sleep 5
ceph osd pool set rbd size 1
ceph osd pool set rbd min_size 1
ceph osd pool set cephfs_data size 1
ceph osd pool set cephfs_data min_size 1
ceph osd pool set cephfs_metadata size 1
ceph osd pool set cephfs_metadata min_size 1
sleep 5
/entrypoint.sh rgw &> /dev/null &
sleep 5
/entrypoint.sh restapi &> /dev/null &
sleep 5

include=( "/usr/bin/ceph*" \
          "/usr/bin/rbd*" \
          "/usr/bin/rados*" \
          "/usr/local/bin/*" \
          "/bin/bash" \
          "/bin/cat" \
          "/bin/grep" \
          "/bin/ls" \
          "/sbin/my_init" \
          "/usr/bin/uuidgen" \
          "/usr/bin/awk" \
          "/usr/bin/crushtool" \
          "/bin/mount" \
          "/sbin/mkfs" \
          )

for n in ${!include[*]}
do
find ${include[n]} | xargs -I {} ldd {} | awk '{print $3}' | grep '/' | sort -u | xargs -I {} touch {}
done

```

**Comment by leseb** [comment]
@natostanco thanks for giving it a try, will see how we can possibility integrate that.

**Comment by natostanco** [comment]
I was running a stable (rbd and cephfs) infernalis image which was 260MB (unzipped) . On jewel the same script pulled 550MB and for whatever reason rbd gave `operation not supported` errors. Ended up with a  750MB which only spares 200MB from the base :(
