### ISSUE TITLE
v13.2.4-20190109 mgr memory leak

### ISSUE THREAD

**Issue by sepich** [ceph/ceph-container#1320]
Is this a bug report or feature request?
* Bug Report

**Bug Report**

What happened:
Running latest v13.2.4-20190109 i see that mgr has memory leak and constantly writes to stdout:
```
debug 2019-03-05 16:48:57.569 7f2a900ec700  0 client.0 ms_handle_reset on 192.168.0.7:6804/1
debug 2019-03-05 16:48:58.553 7f2a938f3700  0 -- 192.168.0.7:6804/1 >> 192.168.0.7:0/1 conn(0x559a438a9800 :6804 s=STATE_ACCEPTING_WAIT_CONNECT_MSG_AUTH pgs=0 cs=0 l=1).handle_connect_msg accept replacing existing (lossy) channel (new one lossy=1)
debug 2019-03-05 16:48:58.573 7f2a948f5700  0 -- 192.168.0.7:6804/1 >> 192.168.0.7:0/1 conn(0x559a438a9e00 :6804 s=STATE_ACCEPTING_WAIT_CONNECT_MSG_AUTH pgs=0 cs=0 l=1).handle_connect_msg accept replacing existing (lossy) channel (new one lossy=1)
debug 2019-03-05 16:48:58.573 7f2a900ec700  0 client.0 ms_handle_reset on 192.168.0.7:6804/1
debug 2019-03-05 16:48:59.469 7f2a938f3700  0 -- 192.168.0.7:6804/1 >> 192.168.0.7:0/1 conn(0x559a438aa400 :6804 s=STATE_ACCEPTING_WAIT_CONNECT_MSG_AUTH pgs=0 cs=0 l=1).handle_connect_msg accept replacing existing (lossy) channel (new one lossy=1)
debug 2019-03-05 16:48:59.573 7f2a948f5700  0 -- 192.168.0.7:6804/1 >> 192.168.0.7:0/1 conn(0x559a438aaa00 :6804 s=STATE_ACCEPTING_WAIT_CONNECT_MSG_AUTH pgs=0 cs=0 l=1).handle_connect_msg accept replacing existing (lossy) channel (new one lossy=1)
debug 2019-03-05 16:48:59.573 7f2a900ec700  0 client.0 ms_handle_reset on 192.168.0.7:6804/1
```
![image](https://user-images.githubusercontent.com/1803804/53823945-d9de4900-3f83-11e9-8497-db65b15d205a.png)

What you expected to happen:
I see these could be related and seems already fixed
https://bugzilla.redhat.com/show_bug.cgi?id=1624646  
https://github.com/ceph/ceph/pull/23890

How to reproduce it (minimal and precise):
Could be repro on minikube etc with rook:
`kubectl apply -f https://github.com/rook/rook/raw/master/cluster/examples/kubernetes/ceph/operator.yaml`
And then use such rook obj:
```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v13.2.4-20190109
  dataDirHostPath: /var/lib/rook
  dashboard:
    enabled: true
  network:
    hostNetwork: true
  mon:
    count: 1
  storage:
    useAllNodes: true
    useAllDevices: false
    directories:
      - path: /mnt/ceph
    config:
      databaseSizeMB: "1024"  # Mb
      journalSizeMB: "1024"   # Mb
  resources:
    mgr:
      limits:
        cpu: 0.1
        memory: 100Mi
      requests:
        memory: 100Mi
---
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: cephfs
  namespace: rook-ceph
spec:
  metadataPool:
    replicated:
      size: 3
  dataPools:
    - replicated:
        size: 2
  metadataServer:
    activeCount: 1
    activeStandby: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-config-override
  namespace: rook-ceph
data:
  config: |
    [global]
    debug default = 0/5
    debug mgr = 0/5
    debug mgrc = 0/5
    debug mon = 0/5
    debug monc = 0/5
    debug mds = 0/5
    debug rocksdb = 0/5
```

**Environment**:
* OS (e.g. from /etc/os-release): debian 9
* Kernel (e.g. `uname -a`): Linux debian 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
* Docker version (e.g. `docker version`): 18.06.2-ce
* Ceph version (e.g. `ceph -v`): ceph version 13.2.4 (b10be4d44915a4d78a8e06aa31919e74927b142e) mimic (stable)

**Comment by kpolszewski** [comment]
:+1: same issue

**Comment by carletes** [comment]
I've reported a similar issue at https://tracker.ceph.com/issues/40260

**Comment by carletes** [comment]
For info: Now that @leseb found a way to solve https://github.com/rook/rook/issues/3140#issuecomment-502641354, I now run my Ceph cluster with `hostNetwork: true`, and the memory leak of the `ceph-mgr` deployment is gone.

**Comment by sepich** [comment]
Unfortunately `ceph/daemon:latest-master` is v15 octopus.
Tried to change `mgr` image to `ceph/daemon:latest-bis-nautilus` but memory is still leaking there.
(Yes, `hostNetwork: true` is already being used)
