### ISSUE TITLE
ceph-disk command not found

### ISSUE THREAD

**Issue by DSUB-dpico** [ceph/ceph-container#1324]
Latest version of ceph/daemon seems has a problem with ceph-disk command

[root@node1 ~]# fdisk -l
Disk /dev/sda: 17.2 GB, 17179869184 bytes, 33554432 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk label type: dos
Disk identifier: 0x000bc101

   Device Boot      Start         End      Blocks   Id  System
/dev/sda1   *        2048     2099199     1048576   83  Linux
/dev/sda2         2099200    33554431    15727616   8e  Linux LVM

Disk /dev/sdb: 1073 MB, 1073741824 bytes, 2097152 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
[...]

[root@node1 ~]# docker exec -it b9b23e14591f ceph --version
ceph version 14.1.1 (ae1b3cf8e2e29118c0682f0895e3f48a79895cbc) nautilus (rc)

[root@node1 ~]# docker run -d --net=host --pid=host --privileged=true -v /etc/ceph:/etc/ceph -v /var/lib/ceph/:/var/lib/ceph/ -v /dev/:/dev/ -e OSD_FORCE_ZAP=1 -e OSD_DEVICE=/dev/sdb ceph/daemon osd
d0adb6fbd79bfa8fc4ae0f13b841e30471038a5403845b468db939ad95f2123f

[root@node1 ~]# docker logs d0adb6fbd79b
2019-03-14 14:55:22  /opt/ceph-container/bin/entrypoint.sh: static: does not generate config
HEALTH_WARN clock skew detected on mon.node2
Error: /dev/sdb: unrecognised disk label
/opt/ceph-container/bin/osd_disk_prepare.sh: line 40: ceph-disk: command not found

**Comment by dsavineau** [comment]
Ceph nautilus release doesn't support ceph-disk anymore, you have to use ceph-volume instead.

ceph/daemon:latest is now based on nautilus. If you need to use mimic you can use the latest-mimic tag instead.

**Comment by DSUB-dpico** [comment]
Is a problem with entrypoint.sh script on ceph/daemon:latest, than it try to execute ceph-disk




> Ceph nautilus release doesn't support ceph-disk anymore, you have to use ceph-volume instead.
> 
> ceph/daemon:latest is now based on nautilus. If you need to use mimic you can use the latest-mimic tag instead.


Is a problem with entrypoint.sh script on ceph/daemon:latest, than it try to execute ceph-disk

**Comment by DSUB-dpico** [comment]
Ok, I see a pull request to change it

 PR: daemon/osd: Migrate ceph-disk to ceph-volume #1325

**Comment by poelzi** [comment]
reopen !

**Comment by Misaka19993** [comment]
still unresolved

**Comment by PepperJo** [comment]
Please reopen. Not fixed!

**Comment by willzhang** [comment]
not fixed!

**Comment by duchnoun** [comment]
no news about this issue ?

**Comment by krzystooof** [comment]
Issue is not resolved:
```
user@DESKTOP-2O4V8VB:/mnt/c/BeOne/ceph-osd/main$ docker run --rm -v $(pwd)/etc/ceph:/etc/ceph -v $(pwd)/var/lib/ceph/:/var/lib/ceph/  -e OSD_DEVICE=/dev/sda --net=host --privileged=true --name=osd1 ceph/daemon osd
2020-08-19 09:52:38  /opt/ceph-container/bin/entrypoint.sh: static: does not generate config
2020-08-19 09:52:38  /opt/ceph-container/bin/entrypoint.sh: Device detected, assuming ceph-disk scenario is desired
2020-08-19 09:52:38  /opt/ceph-container/bin/entrypoint.sh: Preparing and activating /dev/sda
HEALTH_OK
/opt/ceph-container/bin/osd_disk_prepare.sh: line 46: ceph-disk: command not found
```

**Comment by tutugreen** [comment]
still.. not fixed?
