### ISSUE TITLE
Question: where to specify the physical storage

### ISSUE THREAD

**Issue by useltmann** [ceph/ceph-container#1331]
Hi all,

I want to deploy ceph with helm but i cannot find where to set the storage-device for the osd's.
I found the docker-image takes an env var `OSD_DEVICE` on for different stages, but it is not included in the helm-charts. also there is no `OSD_TYPE` specified. What does it mean?

Thanks in advance for any help.

**Comment by dsavineau** [comment]
https://github.com/ceph/ceph-container/blob/master/src/daemon/README.md#deploy-an-osd

**Comment by useltmann** [comment]
so its not supported when using helm? is that what you want to say?

**Comment by dsavineau** [comment]
No, I'm saying that this project is only about container image.
It you want to use it with helm, you probably need to take a look to
- http://docs.ceph.com/docs/master/start/kube-helm/
- https://github.com/ceph/ceph-helm/

Which consume the ceph container images.
Maybe you could be interesseting to take a look at [rook](https://github.com/rook/rook) too

**Comment by useltmann** [comment]
all right. thanks
