### ISSUE TITLE
Facing Issues to bringup the ceph cluster

### ISSUE THREAD

**Issue by kannanvr** [ceph/ceph-container#1355]
Hi All,
   I am trying to bring up the ceph as a container on my kubernetes cluster.
We are really facing some issues to bringup ceph as a container. Request you to help us to narrow down the issue and fixing it.

kubernetes version: 1.13.2
Ceph Version - 13.2.5
container Image  Name: **ceph/daemon:latest**
I am following the instruction mentioned on the URL https://github.com/ceph/ceph-container/tree/master/examples/kubernetes
  We are creating the secret name as ceph-mon for mon pods. 
Generators creating the ceph.conf as below for mon_host parameter

```
# auth
max_open_files = 131072
osd_pool_default_pg_num = 128
osd_pool_default_pgp_num = 128
osd_pool_default_size = 3
osd_pool_default_min_size = 1

mon_osd_full_ratio = .95
mon_osd_nearfull_ratio = .85

**mon_host = ceph-mon**

````
As per the instruction, mon_host is mentioned as the service name. But When we brought up the OSD, it is showing the below error

```
++/opt/ceph-container/bin/osd_directory.sh:16: osd_directory(): ceph --cluster ceph osd new 1b05706e-790f-406d-8159-ee5291dbd510 -i - -n client.bootstrap-osd -k /var/lib/ceph/bootstrap-osd/ceph.keyring
unable to parse addrs in 'ceph-mon'
2019-04-23 17:52:42.832 7f6ee19c5700 -1 monclient: get_monmap_and_config cannot identify monitors to contact
[errno 22] error connecting to the cluster
+/opt/ceph-container/bin/osd_directory.sh:16: osd_directory(): OSD_ID='server name not found: ceph-mon (Name or service not known)'
```
It seems, osd is expecting the IPaddress of container and port number rather than service name.

How to resolve this issue ?
Is it recommended to use Host network rather than container networking technologies?
Am i using the correct container image?

Your valuable reply will help us to solve my prolem

**Comment by dsavineau** [comment]
> As per the instruction, mon_host is mentioned as the service name. But When we brought up the OSD, it is showing the below error

mon_host option is the list of monitor ip addresses or hostnames.

Using `mon_host = ceph-mon` means you can communicate  with the mon via ceph-mon hostname so it should be resolvable from the other daemons.

**Comment by kannanvr** [comment]
@dsavineau , Thanks for your guidance. 
I have added host alias on the deployment of OSD to resolve ceph-mon as a host IP. But all the ceph pod is not enabled with HOST Networks. 

I have observed that OSD is stuck in the below log for a long time and OSD pod is getting restarted
```
++/opt/ceph-container/bin/osd_directory.sh:16: osd_directory(): echo '{"cephx_secret": "AQABvL9cnqc0HBAAJgSp6DPnZH+UH94pP7XrIg=="}'
++/opt/ceph-container/bin/osd_directory.sh:16: osd_directory(): ceph --cluster ceph osd new 6fdc9eda-4ac6-40bf-9b8a-f7e330981f6f -i - -n client.bootstrap-osd -k /var/lib/ceph/bootstrap-osd/ceph.keyring
```
Can you please provide your suggestion to solve the problem?
