### ISSUE TITLE
change "rhel8" to "ubi8"

### ISSUE THREAD

**Issue by ktdreyer** [ceph/ceph-container#1370]
Currently our RHEL 8 Dockerfile has the following FROM line:

```
FROM rhel8:8-released
```

We're trying to base all our RHEL 8 images on Red Hat's [Universal Base Image](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/building_running_and_managing_containers/index), so we will need to change this to:
```
FROM ubi8:8-released
```

The goal of this change is to base our images on a smaller base and to make it easier to redistribute container images.

**Comment by dsavineau** [comment]
I think there's no `8-released` tag on ubi8 image but only `8.0` or `latest`. Can you confirm that ?

Also using UBI with RHEL 8 requires to switch to microdnf insteaf of yum right ?

**Comment by ktdreyer** [comment]
It's really unfortunate that `8-released` is an internal tag in Red Hat's buildsystem, and it's not public :(

Yum is available in the main "ubi" image, and only microdnf is in "ubi-minimal".

**Comment by ktdreyer** [comment]
@dsavineau is this simply a matter of renaming the "rhel8" directory to "ubi8", or is it something more complicated?

**Comment by dsavineau** [comment]
@ktdreyer not sure we need to rename the rhel8 directory but only change the FROM statement in the dockerfile.
I thought that the tag from the source image was supposed to be public, that's why I didn't made the change

**Comment by mykaul** [comment]
@dsavineau - can we use ubi8-minimal ?

**Comment by dsavineau** [comment]
@mykaul what would be the benefit for using the minimal image ?
Because even if the base image is smaller with the minimal image, the final ceph image size will almost be the same than with the classic ubi image

```console
# podman images
REPOSITORY                                    TAG      IMAGE ID       CREATED              SIZE
localhost/rhceph-minimal                      4        73f1be2bdad7   About a minute ago   947 MB
localhost/rhceph                              4        3d1da73b9f84   15 minutes ago       970 MB
registry.access.redhat.com/ubi8/ubi-minimal   latest   9c9faa7498e5   5 weeks ago          91.7 MB
registry.access.redhat.com/ubi8/ubi           latest   c7a62535df3c   5 weeks ago          216 MB
```
@ktdreyer any thoughts on this ?
