### ISSUE TITLE
Update Documentation: OSD_TYPE=disk does not work in nautilus

### ISSUE THREAD

**Issue by osegarra** [ceph/ceph-container#1406]
Documentation available in docker-hub shows how to deploy an OSD using OSD_TYPE=disk and it does not work any more.

Anybody know how to deploy an OSD in the latest nautilus version?

thanks a lot in advance

**Comment by redtex** [comment]
# fdisk /dev/mapper/osd0

:n
:p
Enter
Enter
t
8e
:wq

# kpartx -a /dev/mapper/osd0

# pvcreate /dev/mapper/osd0p1

# vgcreate osd0 /dev/mapper/osd0p1

# lvcreate -n data -l 100%FREE osd0

$ CEPH_TAG=master-8763b14-nautilus-centos-7-x86_64

$ docker run --privileged=true -d --pid=host -v /etc/ceph:/etc/ceph -v /var/lib/ceph:/var/lib/ceph -v /dev:/dev --entrypoint sleep ceph/daemon:${CEPH_TAG} 10000
  # ceph-volume lvm prepare --bluestore --data osd0/data

$ docker run --privileged=true -d --net=host --pid=host  -v /etc/ceph:/etc/ceph -v /var/lib/ceph:/var/lib/ceph -v /dev:/dev -e OSD_ID=0 ceph/daemon:${CEPH_TAG} osd_ceph_volume_activate

**Comment by bloodstars** [comment]
same issue,, only directory is ok......

**Comment by bloodstars** [comment]
solved  ,use this 


`
sleep 5;
            chmod 777 /opt/ceph-container/bin/*;
            cephid=`cat /etc/passwd | grep ceph | awk -F':' '{print $3}'`;
            chown -R $cephid:$cephid /var/lib/ceph/osd/ &
            
            echo \"***************************\";
            ceph-volume lvm list;
            echo \"***************************\";
            
            existing=`ls /var/lib/ceph/osd/ | grep ceph | rev | cut -b 1`;
            
            if [ ! -z $existing ]; then
                echo \"osd exist, starting.......\";
                /usr/bin/ceph-osd -f -i ${existing};
            else
                while [ `ceph osd ls | wc -l` -ne ${HOSTNAME:0-1:1} ] \n
                do \n
                   echo `ceph osd ls | wc -l`\" vs \"${HOSTNAME:0-1:1};
                   echo \"not enough osd started, wating 3 seconds.......\"; 
                   sleep 3;
                done;
                
                success=false;
                ceph-volume lvm create --data ${OSD_DEVICE} --no-systemd && success=true;
                
                echo \"******************************\";
                echo \"******************************\";
                echo \"******************************\";
                echo \"******************************\";
                echo \"initializing result is :[\" $success \"].\";
                echo \"******************************\";
                echo \"******************************\";
                echo \"******************************\";
                echo \"******************************\";
                
                if [ $success ]; then
                    mv /var/lib/ceph/osd/ceph-${HOSTNAME:0-1:1}/* /var/lib/ceph/osd/;
                    umount -l /var/lib/ceph/osd/ceph-${HOSTNAME:0-1:1};
                    mv /var/lib/ceph/osd/* /var/lib/ceph/osd/ceph-${HOSTNAME:0-1:1}/;
                fi;
            
                /usr/bin/ceph-osd -f -i ${HOSTNAME:0-1:1};
            fi
`

**Comment by bloodstars** [comment]
> sleep 5;
            chmod 777 /opt/ceph-container/bin/*;
            cephid=`cat /etc/passwd | grep ceph | awk -F':' '{print $3}'`;
            chown -R $cephid:$cephid /var/lib/ceph/osd/ &
            
            echo \"***************************\";
            ceph-volume lvm list;
            echo \"***************************\";
            
            existing=`ls /var/lib/ceph/osd/ | grep ceph | rev | cut -b 1`;
            
            if [ ! -z $existing ]; then
                echo \"osd exist, starting.......\";
                /usr/bin/ceph-osd -f -i ${existing};
            else
                while [ `ceph osd ls | wc -l` -ne ${HOSTNAME:0-1:1} ] \n
                do \n
                   echo `ceph osd ls | wc -l`\" vs \"${HOSTNAME:0-1:1};
                   echo \"not enough osd started, wating 3 seconds.......\"; 
                   sleep 3;
                done;
                
                success=false;
                ceph-volume lvm create --data ${OSD_DEVICE} --no-systemd && success=true;
                
                echo \"******************************\";
                echo \"******************************\";
                echo \"******************************\";
                echo \"******************************\";
                echo \"initializing result is :[\" $success \"].\";
                echo \"******************************\";
                echo \"******************************\";
                echo \"******************************\";
                echo \"******************************\";
                
                if [ $success ]; then
                    mv /var/lib/ceph/osd/ceph-${HOSTNAME:0-1:1}/* /var/lib/ceph/osd/;
                    umount -l /var/lib/ceph/osd/ceph-${HOSTNAME:0-1:1};
                    mv /var/lib/ceph/osd/* /var/lib/ceph/osd/ceph-${HOSTNAME:0-1:1}/;
                fi;
            
                /usr/bin/ceph-osd -f -i ${HOSTNAME:0-1:1};
            fi

**Comment by bloodstars** [comment]
**sleep 5;
            chmod 777 /opt/ceph-container/bin/*;
            cephid=`cat /etc/passwd | grep ceph | awk -F':' '{print $3}'`;
            chown -R $cephid:$cephid /var/lib/ceph/osd/ &
            
            echo \"***************************\";
            ceph-volume lvm list;
            echo \"***************************\";
            
            existing=`ls /var/lib/ceph/osd/ | grep ceph | rev | cut -b 1`;
            
            if [ ! -z $existing ]; then
                echo \"osd exist, starting.......\";
                /usr/bin/ceph-osd -f -i ${existing};
            else
                while [ `ceph osd ls | wc -l` -ne ${HOSTNAME:0-1:1} ] \n
                do \n
                   echo `ceph osd ls | wc -l`\" vs \"${HOSTNAME:0-1:1};
                   echo \"not enough osd started, wating 3 seconds.......\"; 
                   sleep 3;
                done;
                
                success=false;
                ceph-volume lvm create --data ${OSD_DEVICE} --no-systemd && success=true;
                
                echo \"******************************\";
                echo \"******************************\";
                echo \"******************************\";
                echo \"******************************\";
                echo \"initializing result is :[\" $success \"].\";
                echo \"******************************\";
                echo \"******************************\";
                echo \"******************************\";
                echo \"******************************\";
                
                if [ $success ]; then
                    mv /var/lib/ceph/osd/ceph-${HOSTNAME:0-1:1}/* /var/lib/ceph/osd/;
                    umount -l /var/lib/ceph/osd/ceph-${HOSTNAME:0-1:1};
                    mv /var/lib/ceph/osd/* /var/lib/ceph/osd/ceph-${HOSTNAME:0-1:1}/;
                fi;
            
                /usr/bin/ceph-osd -f -i ${HOSTNAME:0-1:1};
            fi**

**Comment by bloodstars** [comment]
`" sleep 5;
            chmod 777 /opt/ceph-container/bin/*;
            cephid=`cat /etc/passwd | grep ceph | awk -F':' '{print $3}'`;
            chown -R $cephid:$cephid /var/lib/ceph/osd/ &
            
            echo \"***************************\";
            ceph-volume lvm list;
            echo \"***************************\";
            
            existing=`ls /var/lib/ceph/osd/ | grep ceph | rev | cut -b 1`;
            
            if [ ! -z $existing ]; then
                echo \"osd exist, starting.......\";
                /usr/bin/ceph-osd -f -i ${existing};
            else
                while [ `ceph osd ls | wc -l` -ne ${HOSTNAME:0-1:1} ] \n
                do \n
                   echo `ceph osd ls | wc -l`\" vs \"${HOSTNAME:0-1:1};
                   echo \"not enough osd started, wating 3 seconds.......\"; 
                   sleep 3;
                done;
                
                success=false;
                ceph-volume lvm create --data ${OSD_DEVICE} --no-systemd && success=true;
                
                echo \"******************************\";
                echo \"******************************\";
                echo \"******************************\";
                echo \"******************************\";
                echo \"initializing result is :[\" $success \"].\";
                echo \"******************************\";
                echo \"******************************\";
                echo \"******************************\";
                echo \"******************************\";
                
                if [ $success ]; then
                    mv /var/lib/ceph/osd/ceph-${HOSTNAME:0-1:1}/* /var/lib/ceph/osd/;
                    umount -l /var/lib/ceph/osd/ceph-${HOSTNAME:0-1:1};
                    mv /var/lib/ceph/osd/* /var/lib/ceph/osd/ceph-${HOSTNAME:0-1:1}/;
                fi;
            
                /usr/bin/ceph-osd -f -i ${HOSTNAME:0-1:1};
            fi
          "`

**Comment by bloodstars** [comment]
solved  , use this to init:

`
ceph-volume lvm create --data ${OSD_DEVICE} --no-systemd;
ceph-volume lvm list;

mv /var/lib/ceph/osd/ceph-${OSD_ID}/* /var/lib/ceph/osd/;
umount -l /var/lib/ceph/osd/ceph-${OSD_ID};
mv /var/lib/ceph/osd/* /var/lib/ceph/osd/ceph-${OSD_ID}/;

/usr/bin/ceph-osd -f -i ${OSD_ID};
`

**Comment by bloodstars** [comment]
solved, use this.......

`ceph-volume lvm create --data ${OSD_DEVICE} --no-systemd;
ceph-volume lvm list;

mv /var/lib/ceph/osd/ceph-${OSD_ID}/* /var/lib/ceph/osd/;
umount -l /var/lib/ceph/osd/ceph-${OSD_ID};
mv /var/lib/ceph/osd/* /var/lib/ceph/osd/ceph-${OSD_ID}/;

/usr/bin/ceph-osd -f -i ${OSD_ID};`

**Comment by bloodstars** [comment]
solved, use this in docker :

> ceph-volume lvm create --data ${OSD_DEVICE} --no-systemd;
ceph-volume lvm list;

mv /var/lib/ceph/osd/ceph-${OSD_ID}/* /var/lib/ceph/osd/;
umount -l /var/lib/ceph/osd/ceph-${OSD_ID};
mv /var/lib/ceph/osd/* /var/lib/ceph/osd/ceph-${OSD_ID}/;

/usr/bin/ceph-osd -f -i ${OSD_ID};

**Comment by bloodstars** [comment]
solved,  use this in docker:

`ceph-volume lvm create --data ${OSD_DEVICE} --no-systemd;
ceph-volume lvm list;
mv /var/lib/ceph/osd/ceph-${OSD_ID}/* /var/lib/ceph/osd/;
umount -l /var/lib/ceph/osd/ceph-${OSD_ID};
mv /var/lib/ceph/osd/* /var/lib/ceph/osd/ceph-${OSD_ID}/;
/usr/bin/ceph-osd -f -i ${OSD_ID};`

**Comment by bloodstars** [comment]
solved, use this in nautilus docker: 

> ceph-volume lvm create --data ${OSD_DEVICE} --no-systemd;
> ceph-volume lvm list;
> mv /var/lib/ceph/osd/ceph-${OSD_ID}/* /var/lib/ceph/osd/;
> umount -l /var/lib/ceph/osd/ceph-${OSD_ID};
> mv /var/lib/ceph/osd/* /var/lib/ceph/osd/ceph-${OSD_ID}/;
> /usr/bin/ceph-osd -f -i ${OSD_ID};

**Comment by ChenJiafu-s** [comment]
docker exec mon(your container's name) ceph osd create
