### ISSUE TITLE
Support WWNs for OSD device containers

### ISSUE THREAD

**Issue by AndrewwHummer** [ceph/ceph-container#1423]
Is this a bug report or feature request?
* Feature Request

**Feature Request**

Are there any similar features already existing:
Nothing that we are aware of.

What should the feature do:
It should enable us to use WWNs for our CEPH Deployment.

What would be solved through this feature:
The lack of WWN Support for OSD Devices

Does this have an impact on existing features:
It has none in our deployment

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu Server 16.04.1
* Kernel (e.g. `uname -a`): 4.15.0-48-generic #51~16.04.1-Ubuntu
* Docker version (e.g. `docker version`): 1.13.1
* Ceph version (e.g. `ceph -v`): ceph version 10.2.11 (e4b061b47f07f583c92a050d9e84b1813a35671e)

We added this to the ceph/ceph-container/src/daemon/variables_entrypoint.sh
```
#We have to use WWNs, but the container doesn't start with WWN as device
if [ "x$OSD_DEVICE" != "x" ]; then
  OSD_DEVICE=$(readlink -f $OSD_DEVICE)
fi

if [ "x$OSD_JOURNAL" != "x" ]; then
  OSD_JOURNAL=$(readlink -f $OSD_JOURNAL)
fi
```

This bascally acts as a workaround and reads the link in in /dev/disk/by-id/<wwn> -> /dev/sd... pointing to the device path.
So the OSD container still works as usual with a device path, but we can supply fixed wwns for the OSD.

Any thoughts on this approach?
Thanks! :)

**Comment by dsavineau** [comment]
On a first thought I would say this is already supported [1]

Could you share some logs, configuration, etc.. ?

Also I noticed that the ceph version is 10.x so jewel which is not supported anymore (so ceph-container too, there's no new jewel container image). What's the container image you are using ?

[1] https://github.com/ceph/ceph-container/blob/master/src/daemon/common_functions.sh#L93-L140

**Comment by AndrewwHummer** [comment]
Thanks for your reply! :)

I will look into the code you linked. And will try to provide additional information.

Ah, I accidentally copied the output of the ceph client that was installed on our old mon node, so we are actually trying to update from luminous to nautilus. So currently running 12.x 

Please disregard the ceph version in my post.

**Comment by dsavineau** [comment]
So I tried with the latest stable-3.2 container image (v3.2.4 luminous) and it seems to work as expected

```console
# docker images
REPOSITORY              TAG                                   IMAGE ID            CREATED             SIZE
docker.io/ceph/daemon   v3.2.4-stable-3.2-luminous-centos-7   bf949da76b18        3 hours ago         746 MB
```
The disks layout :
```console
# ls -hl /dev/disk/by-id/
total 0
lrwxrwxrwx. 1 root root  9 Jul 10 14:27 scsi-0QEMU_QEMU_HARDDISK_2d3d7b94-af69-407a-a -> ../../sdf
lrwxrwxrwx. 1 root root  9 Jul 10 18:06 scsi-0QEMU_QEMU_HARDDISK_602c5b7c-87b7-42ad-9 -> ../../sdb
lrwxrwxrwx. 1 root root  9 Jul 10 18:06 scsi-0QEMU_QEMU_HARDDISK_609b3b61-ce92-4f20-9 -> ../../sde
lrwxrwxrwx. 1 root root  9 Jul 10 18:06 scsi-0QEMU_QEMU_HARDDISK_dc518569-615f-4858-8 -> ../../sdd
lrwxrwxrwx. 1 root root  9 Jul 10 14:27 scsi-0QEMU_QEMU_HARDDISK_drive-scsi0-0-0-0 -> ../../sda
lrwxrwxrwx. 1 root root 10 Jul 10 14:27 scsi-0QEMU_QEMU_HARDDISK_drive-scsi0-0-0-0-part1 -> ../../sda1
lrwxrwxrwx. 1 root root  9 Jul 10 18:06 scsi-0QEMU_QEMU_HARDDISK_f05a6263-9459-4bb1-8 -> ../../sdc
```

Create an OSD with filestore data on /dev/sdb and journal on /dev/sde using the wwn path

```console
# docker run --net=host --ulimit nofile=1024:1024 --pid=host --privileged=true --name=ceph-osd-prepare-sdb -v /etc/ceph:/etc/ceph:z -v /var/lib/ceph/:/var/lib/ceph/:z -v /dev:/dev -v /etc/localtime:/etc/localtime:ro -e DEBUG=verbose -e CLUSTER=ceph -e CEPH_DAEMON=OSD_CEPH_DISK_PREPARE -e OSD_DEVICE=/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_602c5b7c-87b7-42ad-9 -e OSD_JOURNAL=/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_609b3b61-ce92-4f20-9 -e OSD_BLUESTORE=0 -e OSD_FILESTORE=1 -e OSD_DMCRYPT=0 -e OSD_JOURNAL_SIZE=5120 docker.io/ceph/daemon:v3.2.4-stable-3.2-luminous-centos-7
(...)
see full log at https://gist.github.com/dsavineau/26a02e318707753e13c81d6392d8e495
```
Partitions are correctly created

```console
# blkid /dev/sdb1 /dev/sde1
/dev/sdb1: UUID="cbb125e1-ca25-40b1-8d41-c094c8e2a781" TYPE="xfs" PARTLABEL="ceph data" PARTUUID="dd85066e-303a-46e1-8d22-388a834d5902" 
/dev/sde1: PARTLABEL="ceph journal" PARTUUID="737d05ac-32f6-4710-b175-da73596f0441"

# docker run --net=host --ulimit nofile=1024:1024 --pid=host --privileged=true --rm -v /etc/ceph:/etc/ceph:z -v /var/lib/ceph/:/var/lib/ceph/:z -v /dev:/dev -v /etc/localtime:/etc/localtime:ro --entrypoint=ceph-disk docker.io/ceph/daemon:v3.2.4-stable-3.2-luminous-centos-7 list
/dev/sda :
 /dev/sda1 other, xfs, mounted on /etc/ceph
/dev/sdb :
 /dev/sdb1 ceph data, prepared, cluster ceph, journal /dev/sde1
/dev/sdc other, unknown
/dev/sdd other, unknown
/dev/sde :
 /dev/sde1 ceph journal, for /dev/sdb1
/dev/sdf other, unknown
```

Finally activate and start the OSD

```console
# docker run --net=host --ulimit nofile=1024:1024 --pid=host --ipc=host --privileged=true --name=ceph-osd-sdb -v /etc/ceph:/etc/ceph:z -v /var/lib/ceph/:/var/lib/ceph/:z -v /dev:/dev -v /etc/localtime:/etc/localtime:ro -v /var/run/ceph:/var/run/ceph:z -v /var/run/udev/:/var/run/udev/ -e DEBUG=verbose -e CLUSTER=ceph -e CEPH_DAEMON=OSD_CEPH_DISK_ACTIVATE -e OSD_DEVICE=/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_602c5b7c-87b7-42ad-9 -e OSD_JOURNAL=/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_609b3b61-ce92-4f20-9 -e OSD_BLUESTORE=0 -e OSD_FILESTORE=1 -e OSD_DMCRYPT=0 docker.io/ceph/daemon:v3.2.4-stable-3.2-luminous-centos-7
(...)
see full log at https://gist.github.com/dsavineau/f88a6b74e621cd5d4b7cacb36c5458fc
```

**Comment by AndrewwHummer** [comment]
Thank you very much, for this detailed break down. :) 
We will try to replicate this in our environment.
We will post our results as soon as possible.

**Comment by dsavineau** [comment]
Any update on this ? otherwise I will close the issue.

**Comment by AndrewwHummer** [comment]
Thank you for your help, we just saw your commit. This should fix our latest issue with the wwn implementaion. 
https://github.com/dsavineau/ceph-container/commit/9fa89866c3282c0a86bd4c106c17298e424aa782
