### ISSUE TITLE
Manager dies because of SIGCHLD

### ISSUE THREAD

**Issue by CoRfr** [ceph/ceph-container#1443]
Is this a bug report or feature request?
* Bug Report

**Bug Report**

What happened:

When running ceph/daemon:latest-luminous with 'mgr', it dies:
```
exec: PID 345: spawning /usr/bin/ceph-mgr --cluster ceph --setuser ceph --setgroup ceph -d -i carmd-ev-lxcim1
exec: Waiting 345 to quit
2019-07-30 12:05:17.551226 7f130ee117c0  0 set uid:gid to 167:167 (ceph:ceph)
2019-07-30 12:05:17.551255 7f130ee117c0  0 ceph version 12.2.12 (1436006594665279fe734b4c15d7e08c13ebd777) luminous (stable), process ceph-mgr, pid 345
2019-07-30 12:05:17.551481 7f130ee117c0  0 pidfile_write: ignore empty --pid-file
2019-07-30 12:05:17.581382 7f130ee117c0  1 mgr send_beacon standby
2019-07-30 12:05:17.594502 7f1305f5e700  1 mgr init Loading python module 'balancer'
2019-07-30 12:05:17.620033 7f1305f5e700  1 mgr init Loading python module 'dashboard'
2019-07-30 12:05:17.730189 7f1305f5e700  1 mgr init Loading python module 'restful'
2019-07-30 12:05:17.912855 7f1305f5e700  1 mgr init Loading python module 'status'
2019-07-30 12:05:17.943302 7f1305f5e700  1 mgr handle_mgr_map Activating!
2019-07-30 12:05:17.943568 7f1305f5e700  1 mgr handle_mgr_map I am now activating
2019-07-30 12:05:17.955751 7f12eff66700  1 mgr load Constructed class from module: balancer
2019-07-30 12:05:17.957345 7f12eff66700  1 mgr load Constructed class from module: dashboard
2019-07-30 12:05:17.957927 7f12eff66700  1 mgr load Constructed class from module: restful
2019-07-30 12:05:17.958592 7f12eff66700  1 mgr load Constructed class from module: status
2019-07-30 12:05:17.960023 7f12eff66700  1 mgr send_beacon active
2019-07-30 12:05:17.963034 7f12eff66700  1 mgr[restful] Unknown request ''
2019-07-30 12:05:17.964117 7f12eff66700  1 mgr[restful] Unknown request ''
[30/Jul/2019:12:05:17] ENGINE Bus STARTING
[30/Jul/2019:12:05:17] ENGINE Started monitor thread '_TimeoutMonitor'.
[30/Jul/2019:12:05:18] ENGINE Serving on :::7000
[30/Jul/2019:12:05:18] ENGINE Bus STARTED
2019-07-30 12:05:18.669895 7f12ef765700  0 log_channel(cluster) log [DBG] : pgmap v2: 164 pgs: 164 active+clean; 148GiB data, 459GiB used, 3.50TiB / 3.94TiB avail
2019-07-30 12:05:19.583054 7f1302f58700  1 mgr send_beacon active
2019-07-30 12:05:19.584021 7f1302f58700  0 log_channel(cluster) log [DBG] : pgmap v3: 164 pgs: 164 active+clean; 148GiB data, 459GiB used, 3.50TiB / 3.94TiB avail
teardown: managing teardown after SIGCHLD
teardown: Sending SIGTERM to PID 345
2019-07-30 12:05:20.455799 7f1302757700 -1 received  signal: Terminated from  PID: 387 task name: /bin/bash /opt/ceph-container/bin/entrypoint.sh mgr  UID: 0
2019-07-30 12:05:20.455819 7f1302757700 -1 mgr handle_signal *** Got signal Terminated ***
```
I used `-e STAYALIVE=1` and can see that `/usr/bin/ceph-mgr --cluster ceph --setuser ceph --setgroup ceph -d -i carmd-ev-lxcim1` is still running as PID 345, so I'm not sure why it received a SIGCHLD.

If I do `docker exec ceph-mgr /opt/ceph-container/bin/entrypoint.sh mgr`, it works.

After that, two ceph-mgr are running:
```
docker exec ceph-mgr ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0  11960  3164 ?        Ss   12:05   0:00 /bin/bash /opt/ceph-container/bin/entrypoint.sh mgr
ceph       345  0.0  0.8 693836 72696 ?        Sl   12:05   0:00 /usr/bin/ceph-mgr --cluster ceph --setuser ceph --setgroup ceph -d -i carmd-ev-lxcim1
root       449  0.0  0.0   4372   640 ?        S    12:05   0:00 sleep infinity
root      1143  0.0  0.0  11832  2940 pts/1    Ss+  12:08   0:00 bash
root      1776  2.5  0.0  11960  3108 ?        Ss   12:15   0:00 /bin/bash /opt/ceph-container/bin/entrypoint.sh mgr
ceph      2121  7.1  0.9 824980 76400 ?        Sl   12:15   0:00 /usr/bin/ceph-mgr --cluster ceph --setuser ceph --setgroup ceph -d -i carmd-ev-lxcim1
root      2180  0.0  0.0  51752  3532 ?        Rs   12:15   0:00 ps aux
```

What you expected to happen:

Container to start and work.

How to reproduce it (minimal and precise):

I'm not sure what's uncommon about my system that would trigger this.
AFAIK this is normal operation.

**Environment**:
* OS (e.g. from /etc/os-release): CoreOS 2135.5.0
* Kernel (e.g. `uname -a`): 4.19.50-coreos-r1
* Docker version (e.g. `docker version`): 17.06.2-ce
* Ceph version (e.g. `ceph -v`): 12.2.12

**Comment by dsavineau** [comment]
Could you share the docker command used, ceph configuration, container image version and any information that could be useful ?

**Comment by doransmestad** [comment]
I started experiencing the same issue when upgrading from `ceph/daemon:v3.0.7-stable-3.0-mimic-centos-7-x86_64` to `ceph/daemon:v4.0.2-stable-4.0-nautilus-centos-7-x86_64`

I realized the same thing as @CoRfr  - it seemed that the ceph binary wasn't the one that exited and caused the SIGCHLD.   So I installed strace and watched the process and signal calls - it looked to be coming from an etcdctl process exiting (I use etcd as KV store for the configuration).

To test if that was true, I built a quick docker container:

```
FROM ceph/daemon:v4.0.2-stable-4.0-nautilus-centos-7-x86_64

RUN sed -i '20i  pstree -g && while [ "$(ps aux | grep etcd | wc -l)" -gt "1" ]; do date "+%F %T %N"; pstree -g ; sleep 1; done' /opt/ceph-container/bin/start_mgr.sh
```

^ that sed command inserts a while loop that waits until all processes with 'etcd' in the name have disappeared.  This is what the output looked like (I also added `set -x` to the entrypoint to trace the bash commands):

```
++ ps aux
++ grep etcd
++ wc -l
+ '[' 8 -gt 1 ']'
+ date '+%F %T %N'
2019-08-04 22:52:19 480278252
+ pstree -g
entrypoint.sh(1)-+-confd(600)---sleep(600)
                 |-etcdctl(578)---sleep(578)
                 |-etcdctl(623)---sleep(623)
                 |-etcdctl(647)---sleep(647)
                 |-etcdctl(671)---sleep(671)
                 |-etcdctl(695)---sleep(695)
                 |-etcdctl(720)---sleep(720)
                 `-pstree(769)
+ sleep 1
++ ps aux
++ wc -l
++ grep etcd
+ '[' 5 -gt 1 ']'
+ date '+%F %T %N'
2019-08-04 22:52:20 491981371
+ pstree -g
entrypoint.sh(1)-+-etcdctl(647)---sleep(647)
                 |-etcdctl(671)---sleep(671)
                 |-etcdctl(695)---sleep(695)
                 |-etcdctl(720)---sleep(720)
                 `-pstree(779)
```
That went on for about about 6 to 7 seconds before all etcdctl processes cleaned up and the mgr started up fine (and stayed running) after that point.

My docker config for the mgr container:   (it's managed by salt-stack, please excuse the syntax):

```
mgr:
  docker_container.running:
    - image: {{ceph_image}}
    - environment:
      - KV_TYPE: etcd
      - KV_IP: {{ etcd_n2_ip }}
    - network_mode: host
    - binds:
      - /mgr_data:/var/lib/ceph
    - restart_policy: always
    - cap_add: SYS_PTRACE
    - command: mgr
```

@dsavineau   please let me know if any other information would be helpful here.  I can reliably recreate this issue on my end.   I'm happy to open a PR if you think something like my wait loop is desired as a more permanent fix - but I'd also be interested in any thoughts you may have on why these etcdctl processes are lingering around (or maybe it is something confd is doing?).  It's quite possible my etcd cluster is slow (it only supports ceph and runs on old HDDs)... maybe that could cause this?

Thanks!

**Comment by radek-senfeld** [comment]
Well, this one gave me a headache as well.

The root cause is that /usr/local/bin/confd is compressed and wrapped in a shell script which is emitting the SIGCHLD signal.

I replaced the compressed version with the proper release from https://github.com/kelseyhightower/confd/releases and.. Voila.. The problem is gone. Nasty..

Version: ceph/daemon:latest-octopus

**Comment by qrpike** [comment]
This still seems to be an issue. Even when replacing confd I still am seeing this issue.

**Comment by bjozet** [comment]
I'm also experiencing issues with manager dying with SIGCHLD both while upgrading from luminous to nautilus, and then also from nautilus to pacific, all while using ETCD as kvstore with my test-clusters.

The `ceph/daemon` images contains the compressed version of some executables (like `confd`, `kubectl`, `etcdctl`(in nautilus, not pacific)), which is generated at docker build time by `gzexe`.  I guess this is because someone wanted to shave off some of the size in the final image. These scripts contains mechanisms to clean up after itself in weird ways, for example this line (from /usr/local/bin/confd, but is similar in all compressed execs):

```
(sleep 5; rm -fr "$gztmpdir") 2>/dev/null &
 ```
This `sleep` interferes with the `exec ceph-mgr` commands from `start_mgr.sh`, and I can reliably reproduce a SIGCHLD after 5 seconds after starting my container (or if i modify it to `sleep 7` it will SIGCHLD after 7 seconds).
Like others suggested, I've tried to replace the compressed `confd` and `etcdctl` versions with uncompressed ones, then I do not have this problem anymore. Another workaround, is to add a `sleep 10` command directly before `exec` stanza in `start_mgr.sh`.
 
@dsavineau Sorry for hijacking this ticket which was closed by Stalebot, but i think it was premature to close it. The problems very much still exists in ceph/daemon:v6.0.3 also. I'll be more than happy to try and explain it further, I can even do a screenshare, to show exactly what's going on :) (if that helps)
