### ISSUE TITLE
docker: Error response from daemon: VolumeDriver.Mount: docker-legacy: Mount: mysql_data: failed: unable to map rbd.

### ISSUE THREAD

**Issue by kervin521** [ceph/ceph-container#1444]
Is this a bug report or feature request?
* Bug Report

**Bug Report**

What happened:
```
root@dbs-server10:/opt/ceph# docker plugin ls
ID                  NAME                DESCRIPTION            ENABLED
99c7c1d7a22e        rexray/rbd:latest   REX-Ray for Ceph RBD   true
root@dbs-server10:/opt/ceph# docker volume ls
DRIVER              VOLUME NAME
rexray/rbd:latest   mysql_data
rexray/rbd:latest   mysql_data1

root@dbs-server10:/opt/ceph# docker run -d \
> --name mysql \
> --publish 3306:3306 \
> --env MYSQL_ROOT_PASSWORD=SqlPwd1@ \
> --label com.docker.stack.namespace=dbs \
> --mount type=volume,src=mysql_data,dst=/var/lib/mysql,volume-driver=rexray/rbd:latest \
> --network=host \
> 172.21.32.31:5000/mysql-canal:5.7.22
docker: Error response from daemon: VolumeDriver.Mount: docker-legacy: Mount: mysql_data: failed: unable to map rbd.

```
What you expected to happen:

How to reproduce it (minimal and precise):

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Docker version (e.g. `docker version`):
* Ceph version (e.g. `ceph -v`):

**Comment by kervin521** [comment]
![image](https://user-images.githubusercontent.com/9798724/62360037-8aa83e80-b54a-11e9-97da-8b1f7bf096a3.png)

**Comment by dsavineau** [comment]
Honestly I don't understand why your issue is related to ceph-container.
According to your inforation it seems to come from docker and/or your volume driver (rexray)
