### ISSUE TITLE
Question: OSDs are not utilizing full disk space of hard disks

### ISSUE THREAD

**Issue by jahnestacado** [ceph/ceph-container#1447]
I've managed to setup a ceph cluster/cephfs using the provided docker containers in an ARM cluster. I used the _master-a61f2e2-nautilus-centos-7-aarch64_ version

The only problem that I encounter is that all the OSDs are listed as 10GB each which is not the case.

I have 2 SSD disks of 128GB and one HDD of 500GB and all of the are recognized by the cluster as 10GB.

Running ```ceph df ```  outputs
```
RAW STORAGE:
    CLASS     SIZE       AVAIL      USED        RAW USED     %RAW USED 
    hdd       30 GiB     25 GiB     2.4 GiB      5.4 GiB         18.16 
    TOTAL     30 GiB     25 GiB     2.4 GiB      5.4 GiB         18.16 
 
POOLS:
    POOL                ID     STORED      OBJECTS     USED        %USED     MAX AVAIL 
    cephfs_data          1     797 MiB         219     2.3 GiB      9.21       7.7 GiB 
    cephfs_metadata      2      31 MiB          30      93 MiB      0.39       7.7 GiB 
```

Running ```rados df``` outputs:
```
POOL_NAME          USED OBJECTS CLONES COPIES MISSING_ON_PRIMARY UNFOUND DEGRADED RD_OPS      RD WR_OPS      WR USED COMPR UNDER COMPR                                                        
cephfs_data     2.3 GiB     219      0    657                  0       0        0    922 2.1 GiB   9674 3.0 GiB        0 B         0 B                                                        
cephfs_metadata  93 MiB      30      0     90                  0       0        0    396 418 KiB  20839  44 MiB        0 B         0 B                                                        

total_objects    249
total_used       5.4 GiB
total_avail      25 GiB
total_space      30 GiB
```
The volume mounts for the physical disks on the containers are working fine. I can see the actual size of the hard disks from within the container but somehow ceph thinks that they only have 10GB available each.

I didn't create any partitions on the hard drives so I expected to be fully utilized by ceph.

I already spend a lot of time searching online and I thought to also ask you in case you have encountered something similar in the past. 

Cheers!

**Comment by dsavineau** [comment]
What entrypoint are you using for the OSDs ? Could you share some container logs (docker, podman, etc...), the container version, the container command line, the OS version or any useful information ?

**Comment by jahnestacado** [comment]
For the OSDs entrypoint I  use a script that handles the secrets of the ceph cluster and in the end it executes:
```exec /opt/ceph-container/bin/entrypoint.sh "$@"```

As I mentioned above I use the _ master-a61f2e2-nautilus-centos-7-aarch64 version_ version and for deployment I use docker swarm and docker engine version 18.09.7

The operating system is Armbian5.59 with Kernel 5.2.5-sunxi64

All OSD containers have the exact same logs:
```
forego   | starting ceph-0.1 on port 5000
ceph-0.1 | 2019-08-06 16:05:08.684 ffff83629010 -1 bdev(0xaaaafadd8000 /var/lib/ceph/osd/ceph-0/block) unable to get device name for /var/lib/ceph/osd/ceph-0/block: (22) Invalid argument
ceph-0.1 | 2019-08-06 16:05:08.684 ffff83629010 -1 bdev(0xaaaafadd8e00 /var/lib/ceph/osd/ceph-0/block) unable to get device name for /var/lib/ceph/osd/ceph-0/block: (22) Invalid argument
ceph-0.1 | 2019-08-06 16:05:09.216 ffff83629010 -1 Falling back to public interface
ceph-0.1 | 2019-08-06 16:05:09.256 ffff83629010 -1 bdev(0xaaaafadd8000 /var/lib/ceph/osd/ceph-0/block) unable to get device name for /var/lib/ceph/osd/ceph-0/block: (22) Invalid argument
ceph-0.1 | 2019-08-06 16:05:09.544 ffff83629010 -1 bdev(0xaaaafadd8000 /var/lib/ceph/osd/ceph-0/block) unable to get device name for /var/lib/ceph/osd/ceph-0/block: (22) Invalid argument
ceph-0.1 | 2019-08-06 16:05:09.548 ffff83629010 -1 bdev(0xaaaafadd8e00 /var/lib/ceph/osd/ceph-0/block) unable to get device name for /var/lib/ceph/osd/ceph-0/block: (22) Invalid argument
ceph-0.1 | 2019-08-06 16:05:28.316 ffff83629010 -1 bdev(0xaaaafadd8e00 /var/lib/ceph/osd/ceph-0/block) unable to get device name for /var/lib/ceph/osd/ceph-0/block: (22) Invalid argument
ceph-0.1 | 2019-08-06 16:05:53.727 ffff83629010 -1 osd.0 48 log_to_monitors {default=true}
ceph-0.1 | 2019-08-06 16:05:53.771 ffff7c93cbd0 -1 osd.0 48 set_numa_affinity unable to identify public interface 'eth0' numa node: (2) No such file or directory
```

Note that the cluster is healthy and operational

```
  cluster:
    id:     fc1a3043-f4e5-4a13-b495-6622bd673656
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum minion-1,minion-6,minion-3 (age 100s)
    mgr: minion-6(active, since 86s), standbys: minion-1, minion-3
    mds: cephfs:1 {0=minion-4=up:active} 1 up:standby
    osd: 3 osds: 3 up (since 32s), 3 in (since 45h)
 
  data:
    pools:   2 pools, 128 pgs
    objects: 204 objects, 662 MiB
    usage:   5.0 GiB used, 25 GiB / 30 GiB avail
    pgs:     128 active+clean
 
  io:
    client:   596 B/s wr, 0 op/s rd, 0 op/s wr

```

**Comment by dsavineau** [comment]
> For the OSDs entrypoint I use a script that handles the secrets of the ceph cluster and in the end it executes:
> `exec /opt/ceph-container/bin/entrypoint.sh "$@"`

So what's the value of `$@` for the OSDs ?

**Comment by jahnestacado** [comment]
> > For the OSDs entrypoint I use a script that handles the secrets of the ceph cluster and in the end it executes:
> > `exec /opt/ceph-container/bin/entrypoint.sh "$@"`
> 
> So what's the value of `$@` for the OSDs ?

It is just ```osd```

**Comment by dsavineau** [comment]
Without using `OSD_DEVICE` env variable then the OSD will be created in a directory [1][2].

If you want to use dedicated devices for OSDs you need to create the OSD using `ceph-volume` and then use the `osd_ceph_volume_activate` entrypoint with the` OSD_ID` value in the env variable.

```console
$ docker run ... -e OSD_ID=0 -e CEPH_DAEMON=OSD_CEPH_VOLUME_ACTIVATE ...
```

[1] https://github.com/ceph/ceph-container/blob/master/src/daemon/common_functions.sh#L144-L147
[2] https://github.com/ceph/ceph-container/blob/master/src/daemon/osd_scenarios/osd_directory.sh

**Comment by wtj** [comment]
I encountered the same issue with `v4.0.3-stable-4.0-nautilus-centos-7-x86_64.tar`, containers created with variables `OSD_DEVICE ='/path/to/a/dir'`, `OSD_TYPE=directory`

This way works in `ceph-daemon-v4.0.0-stable-4.0-luminous-centos-7-x86_64.tar`, it will show the real volume size the directory located, but in `v4.0.3-stable-4.0-nautilus-centos-7-x86_64.tar` only show max to 10GB each OSD.

**Comment by umagmrit** [comment]
To increase the size of OSD from 10GB, set parameter bluestore_block_size in ceph.conf
For example bluestore_block_size = 536870912000 , this will create OSD with 500 GB. You have to specify in bytes.
