### ISSUE TITLE
KV store problems

### ISSUE THREAD

**Issue by Ulexus** [ceph/ceph-container#146]
I'm just starting to play with the KV setup, and I am finding it's pretty rough.  I'm adding this issue as much for my own notes as for anything else.  Also, these are just my opinions, so feel free to provide feedback/arguments.

Problems (update the following as necessary or discovered):
- The default schema for the `ceph.conf` construction doesn't get populated in a usable way
- The schema for `ceph.conf` isn't documented
- Some segments in the KV schema are directory-separated; others are `_`-separated
- Some schema changes I would prefer:
  - `/auth/fsid` should be `/fsid` (IMO, this is is only tertiarily auth: it's the cluster id)
  - Keyrings should be in `/keyrings`; examples:  `/keyrings/mon`, `/keyrings/bootstrapOsd` (maybe even `/keyrings/bootstrap/osd`
  - `/auth/cephx_*` should be `/auth/cephx/*` (though this seems redundant with the `/globals/` section)
- If mandatory directories in the KV store don't exist, the config construction dies -- need valid defaults
- Public and Cluster networks should be stored in the KV
- It doesn't appear the bootstrap keyrings actually get added to the auth database
- I also _really_ like the idea of merging a user-supplied, whole `ceph.conf` with a confd-generated one.

_NOTE_:  Many of these would be _breaking_ changes, so I would also like to get an idea of how many people are actually using the KV backend so that we can see if we need to add backward compatibility shims.

**Comment by leseb** [comment]
Could you elaborate a bit on the first point? What's not usable?
Are you sure that ceph networks are not stored? https://github.com/ceph/ceph-docker/blob/master/examples/confd/populate.sh#L36-L37

**Comment by Ulexus** [comment]
Thanks @leseb ; I see the population script, but so far as I can tell, it is not called anywhere in the container.  That's left up to the user to execute.  That's fine, and you can populate it manually, as well.  

I just think the default execution should have at least a bare-bones, functional config.

**Comment by leseb** [comment]
@Ulexus oh yes, last time I tried I did:

* bootstrap ceph/demo container
* make sure etcd is reachable
* run a 'bash' container and execute populate.sh
* run ceph/daemon mon/osd/mds/rgw

**Comment by Ulexus** [comment]
Yep; that's what I'm talking about it being "rough".  We just need to figure out how to make it clean and easy, with acceptable, workable defaults.

**Comment by klausenbusk** [comment]
> Yep; that's what I'm talking about it being "rough". We just need to figure out how to make it clean and easy, with acceptable, workable defaults.

Couldn't we create a etcd key "populated", and if not exists run populate.sh?

**Comment by JrCs** [comment]
Hi all dev,
is it possible to add some key/values in the kvstore to populate new entries in ceph.conf (generated from confd) ?
I explain: i want to add a client config like this in the generated ceph.conf:
```
[client.radosgw.myinstance]
  rgw dns name = s3.mydomain.com
```
I don't thing it's possible currently with the current confd template.
We need to find a way to create toml section and key/values under section that is an "image" of the kv store.

**Comment by leseb** [comment]
Correct we do not support adding new sections dynamically since they are hardcoded.
Perhaps we can work with include if they exist...
