### ISSUE TITLE
[question] NETWORK_AUTO_DETECT on specific network

### ISSUE THREAD

**Issue by eleaner** [ceph/ceph-container#1471]
I try to use NETWORK_AUTO_DETECT to build ceph cluster in a docker swarm on host network
The cluster is built over wireguard, so I would like to specify this network for autodetection.
Currently, container insists on using eth0 and all fails

how do I do that? is it possible at all?

**Comment by dsavineau** [comment]
When using the network auto detect configuration, the container will try to find the right interface based on the network traffic [1].
If for some reason that's not working with wireguard setup, you can try to override the nic name via the `CEPH_NIC` env variable [2].

Could you give it a try ?

[1] https://github.com/ceph/ceph-container/blob/master/src/daemon/start_mon.sh#L95
[2] https://github.com/ceph/ceph-container/blob/master/src/daemon/start_mon.sh#L96

**Comment by eleaner** [comment]
awesome!
that's what I needed
