### ISSUE TITLE
Let us run ceph/daemon demo for development

### ISSUE THREAD

**Issue by CodeSteele** [ceph/ceph-container#1475]
**Feature Request**

_Are there any similar features already existing:_
Yes, the `demo` daemon runs well, outside of restarting it.

_What should the feature do:_
Let us re-start a demo instance and pick up where we left off.

_What would be solved through this feature:_
If I want a simple Ceph instance for doing development on without creating a bunch of complex containers interconnected for doing some basic S3-like storage.

_Does this have an impact on existing features:_
Will allow users to re-up demo instances when maybe they shouldn't?

I am running this on docker for windows, so things are generally slower than expected.

---

I have a simple docker-compose setup that looks something like this:

```
  ceph:
    image: "ceph/daemon:latest-master"
    ports:
      - "8000:5000"
      - "8080:8080"
    environment:
      MON_IP: "127.0.0.1"
      CEPH_DAEMON: "DEMO"
      CEPH_PUBLIC_NETWORK: "0.0.0.0/0"
      CEPH_DEMO_UID: "someuid"
      CEPH_DEMO_ACCESS_KEY: "somekey"
      CEPH_DEMO_SECRET_KEY: "somesecret"
    volumes:
      - ceph-data:/var/lib/ceph
      - ceph-etc:/etc/ceph
```

This works really well when we want to fire up a simple-to-use Ceph instance for development, however on closing and restarting our Ceph docker instance we get: 

```
ceph_1   | 2019-09-10 06:48:11  /opt/ceph-container/bin/entrypoint.sh: I can
see existing Ceph files, please remove them!
ceph_1   | 2019-09-10 06:48:11  /opt/ceph-container/bin/entrypoint.sh: To run the demo container, remove the content of /var/lib/ceph/ and /etc/ceph/
ceph_1   | 2019-09-10 06:48:11  /opt/ceph-container/bin/entrypoint.sh: Before doing this, make sure you are removing any sensitive data.
```

I've tried to be __really__ witty and do shenanigans like this (look away if hacky ideas make you queasy):

```
RUN sed -i 's/\-d \/var\/lib\/ceph/\-d \/var\/lib\/ceph-fake/g' /opt/ceph-container/bin/common_functions.sh
RUN sed -i 's/\-d \/etc\/ceph/\-d \/etc\/ceph-fake/g' /opt/ceph-container/bin/common_functions.sh
```

(Okay, yeah, I could probably just touch `/etc/ceph/I_AM_DEMO`, I had some issues and went this route, probably overkill)

To basically strip out the checks, but then our Ceph instance just hangs:

```
ceph_1   | monmaptool: monmap file /etc/ceph/monmap-ceph
ceph_1   | monmaptool: set fsid to 03abcb1f-3da3-43e3-b007-3dc3b35dc4d9
ceph_1   | monmaptool: writing epoch 0 to /etc/ceph/monmap-ceph (1 monitors)
ceph_1   | importing contents of /var/lib/ceph/bootstrap-osd/ceph.keyring into /etc/ceph/ceph.mon.keyring
ceph_1   | importing contents of /var/lib/ceph/bootstrap-mds/ceph.keyring into /etc/ceph/ceph.mon.keyring
ceph_1   | importing contents of /var/lib/ceph/bootstrap-rgw/ceph.keyring into /etc/ceph/ceph.mon.keyring
ceph_1   | importing contents of /etc/ceph/ceph.client.admin.keyring into /etc/ceph/ceph.mon.keyring
ceph_1   | 2019-09-16 07:27:01  /opt/ceph-container/bin/entrypoint.sh: /etc/ceph/ceph.conf is already memory tuned
ceph_1   | ownership of '/etc/ceph/I_AM_DEMO' retained as ceph:ceph
ceph_1   | ownership of '/etc/ceph/I_AM_DEMO\r' retained as ceph:ceph
ceph_1   | ownership of '/etc/ceph/ceph.client.admin.keyring' retained as ceph:ceph
ceph_1   | ownership of '/etc/ceph/ceph.conf' retained as ceph:ceph
ceph_1   | ownership of '/etc/ceph/ceph.mon.keyring' retained as ceph:ceph
ceph_1   | ownership of '/etc/ceph/rbdmap' retained as ceph:ceph
ceph_1   | 2019-09-16 07:32:02.211 7ff862c9d700  0 monclient(hunting): authenticate timed out after 300
```

So obviously I'm missing something that the Demo instance does that isn't friendly with what is going on.

I've started looking at setting up mon/mgr/osd/mds/rgw through docker-compose, but it just seems a lot "heavier" than the nicer setup we had before.

So:

1) Is this useful to anyone else to have a "simple, ready-to-go docker setup for dev"?
2) Am I missing some other configuration that isn't demo or the full mon/mgr/osd/mds/rgw setup that will meet my needs?
3) Should I just suck it up, throw it all out and restart with a full stack?
4) ~https://github.com/ceph/cn gets _almost_ there but is command-heavy, could maybe modify it to fill the gap?~ Nix this,  cn just runs the demo instance.

**Comment by elemental-lf** [comment]
I'd find it useful. I'm currently preparing a small Ceph training and I want participants to run a small Ceph cluster to be able to try out some of the commands and the demo fits perfectly. But the demo could use some love. Restarts seem to work for me sometimes. I get different messages from `entrypoint.sh`:
```
ceph_1  | 2019-10-18 19:07:51  /opt/ceph-container/bin/entrypoint.sh: Found residual files of a demo container.
ceph_1  | 2019-10-18 19:07:51  /opt/ceph-container/bin/entrypoint.sh: This looks like a restart, processing.
ceph_1  | 2019-10-18 19:07:51  /opt/ceph-container/bin/entrypoint.sh: Existing mon, trying to rejoin cluster...
```
Apart from that:
* The demo could use a working dashboard (I've got patches for that). 
* The rbd pool is missing the rbd application tag, so that it will be recognized by the dashboard as an rbd pool (easily patched).
* I have a problem with the `rbd_support` mgr module which for some reason can't be loaded which I still need to figure out. Without it the dashboard goes haywire when accessing rbd related stuff.

One alternative to the demo is running Rook in a KIND (https://github.com/kubernetes-sigs/kind) Kubernetes cluster which works with Docker CE on Linux. This should also work with Docker on Windows if you're using real Linux containers and not LCOW. But I wouldn't consider it lightweight and Rook is not Ceph.

**Comment by CodeSteele** [comment]
Yeah, I've been poking at this a bit off and on, it seems to randomly do it if the container is abruptly shut down (only thing I can guess it is), we've just been instructing devs to destroy all volumes and redeploy from `docker-compose`.

Not an _ideal_ situation but has unstuck us.

**Comment by vansante** [comment]
I would definitely find this useful as well :+1:

**Comment by CodeSteele** [comment]
Hey, reopen this.

**Comment by lebedevsergey** [comment]
Yeah, for us this is also an issue, please make some simple to setup DEV mode which is similar to DEMO mode but keeps  ceph storage data in volumes when Docker container is stopped and then restarted again

**Comment by igorbach** [comment]
Please, reopen this
