### ISSUE TITLE
log_file is always null

### ISSUE THREAD

**Issue by seahero520** [ceph/ceph-container#1479]
Is this a bug report or feature request?
* Bug Report

**Bug Report**

What happened:
In my /etc/ceph/ceph.conf, I configured log file = /var/log/ceph/$cluster-$name.log in [global] section 
then I use docker run -d --net=host \ -v /etc/ceph:/etc/ceph \ -v /var/lib/ceph/:/var/lib/ceph/ \ -v /var/log/ceph/:/var/log/ceph/ \ .... ceph/daemon:latest-luminous mon

and enter the mon container:  ceph daemon  asok config show  log file is always "" null?
What you expected to happen:
in asok  log file = /var/log/ceph/ceph.mon.log

How to reproduce it (minimal and precise):

**Environment**: 
* OS (e.g. from /etc/os-release): Ubuntu 16.04
* Kernel (e.g. `uname -a`): 4.8.0-36-generic
* Docker version (e.g. `docker version`): 19.03.2
* Ceph version (e.g. `ceph -v`): luminous v12.2.12(stable)

**Comment by dsavineau** [comment]
Did you try to also set `mon cluster log file` in the ceph configuration ?

**Comment by seahero520** [comment]
> Did you try to also set `mon cluster log file` in the ceph configuration ?

yes, I have already set mon cluster log file in [mon] section. It works.
So I don't quite understand why `log file` doesn't work, but `mon cluster log file` work.

**Comment by guits** [comment]
it will be fixed by ceph/ceph-container#1574
