### ISSUE TITLE
build development containers with branches that aren't 'wip-*'

### ISSUE THREAD

**Issue by liewegas** [ceph/ceph-container#1512]
We need to build development containers from git with branch names like ``master``, ``nautilus``, ``fix-12345``, etc., since not all branches begin with ``wip-*``.

**Comment by dmick** [comment]
This should be mostly "select behavior by environment variable, not branch name" from my experiments with the CI builds; I think it's mostly about the tests in the template files

**Comment by dmick** [comment]
Still need to evaluate this.  maybe it's been fixed.

**Comment by YiannisGkoufas** [comment]
Was wondering also how to build containers from a ceph fork in another repository. Currently is not possible, would love to work on that functionality if there are no plans

**Comment by dsavineau** [comment]
> Still need to evaluate this. maybe it's been fixed.

I think this has been fixed by https://github.com/ceph/ceph-container/commit/f289d4901fcfb7884c69c5b8919476b430d81bfe
