### ISSUE TITLE
Missing Python Packages in Manager Container

### ISSUE THREAD

**Issue by KingJ** [ceph/ceph-container#1523]
Is this a bug report or feature request?
* Bug Report

**Bug Report**

What happened:
When activating the diskprediction_local manager module, the health of the cluster transitions to Critical and the following error is logged;

```
Health check failed: Module 'diskprediction_local' has failed: No module named sklearn.svm.classes (MGR_MODULE_ERROR)
```

This prevents the usage of diskprediction_local module for device life expectancy predictions from device health monitoring, which is now possible following the merger of #1396 which added the `smartctl` and `nvme` binaries to OSD containers.

What you expected to happen:
The manager module to load and process collected OSD device health information.

How to reproduce it (minimal and precise):

1. Deploy a containerised manager using `ceph/daemon:latest-nautilus`.
1. Enable the diskprediction_local manager module
1. Observe cluster health transition to Critical and log messages regarding Python import failures. 

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 18.04.3 LTS
* Kernel (e.g. `uname -a`): 5.0.0-36-generic #39~18.04.1-Ubuntu SMP
* Docker version (e.g. `docker version`): 18.09.7
* Ceph version (e.g. `ceph -v`): ceph version 14.2.4 (75f4de193b3ea58512f204623e6c5a16e6c1e1ba) nautilus (stable)

**Comment by dsavineau** [comment]
I think this is more a ceph mgr dependency issue (from ceph/ceph project) than a ceph-container issue because I'm pretty sure that it's also present on non containerized deployment.

**Comment by KingJ** [comment]
Ah, my apologies. Thanks to your pointer I can see how each of the mgr module dependencies are now defined. Interestingly, for diskprediction_local, there's a requirements.txt file in the [master](https://github.com/ceph/ceph/tree/master/src/pybind/mgr/diskprediction_local) branch, but not in the [v14.2.4 tag](https://github.com/ceph/ceph/tree/v14.2.4/src/pybind/mgr/diskprediction_local). Presumably this is the root of the issue i'm facing.

Thanks for the pointer, i'll close this out now and follow up on the main Ceph bug tracker.

**Comment by KingJ** [comment]
Following the merger of https://github.com/ceph/ceph-container/pull/1821 I can confirm that on a freshly-pulled `ceph/daemon:latest-octopus` container running as a Manager, the diskprediction_local module can now be enabled and successfully returns failure predictions.
