### ISSUE TITLE
Containers restart causes lot of unnecessary IO

### ISSUE THREAD

**Issue by gfidente** [ceph/ceph-container#1536]
It takes ~4 minutes in upgrades PER container restart and when deploying, it stops all containers and restart ALL of them at the same time so 

find -L /var/lib/ceph/ -mindepth 1 -maxdepth 3 -exec chown ceph. {}  is running, in this case 16x in parallel and causing lots of IOs.

**Comment by gfidente** [comment]
@dsavineau @guits not sure if you guys can help get this going and backported in stable-3 ?

**Comment by dsavineau** [comment]
> It takes ~4 minutes in upgrades PER container restart and when deploying, it stops all containers and restart ALL of them at the same time so

Do you have some logs to see what directories/files are the root cause ?

Because each OSD container has only access to its own OSD data even if the /var/lib/ceph directory is bind mount for every container (ie: each container mount its OSD partition inside the container).

**Comment by david-hill** [comment]
Customer was using 3-37 which is the latest available.   We do see a chown for all ceph containers on each deploy/update.

**Comment by david-hill** [comment]
I can easily reproduce this issue by simply running "openstack overcloud deploy" in this customer environment.  It'll stop all ceph containers on a node and then restart all of them .   They will appear as "down" in "ceph -s" for about 4 minutes and if we login that node while this is happening, we can see the chown running for those ~4 minutes.   I can ask the customer to provide the logs if we need this...

**Comment by dsavineau** [comment]
> They will appear as "down" in "ceph -s" for about 4 minutes and if we login that node while this is happening, we can see the chown running for those ~4 minutes.

Even if I agree with the fix on the find/chown command to speed up the restart, I really want to understand what's the underlying issue instead of just hidde it.

So it would be nice too see what's the output of `find -L /var/lib/ceph/ -mindepth 1 -maxdepth 3 -ls`

**Comment by dsavineau** [comment]
@david-hill any news on this ?

**Comment by david-hill** [comment]
I have to find back the case ...

**Comment by gfidente** [comment]
@dsavineau it looks to me that in a few places, including daemon startup scripts, we are calling the `create_mandatory_directories` function as a safety measure to make sure the directories are all there and owned by `ceph:` ... as a side effect, we run `chown` against a directory which is already populated with lots of files (data) for example when containers are restarted

**Comment by dsavineau** [comment]
> as a side effect, we run chown against a directory which is already populated with lots of files (data) for example when containers are restarted

@gfidente the `create_mandatory_directories` function is called **before** the OSD data partition are mounted so we're not running the chown command on OSD data.
Also depending on the objectstore (filestore vs bluestore) the actual data isn't mounted at all because we're using a raw device (bluestore), only the "metadata" are mounted.

Again, I completely agree with the fix provided but we need to understand the real issue because that could be a different issue.

Note that the files in the ` /var/lib/ceph/` directory are stored on the root disk (unless using a dedicated partition).
