### ISSUE TITLE
Stdout log handling about docker

### ISSUE THREAD

**Issue by PrometheusYu** [ceph/ceph-container#1560]
Hi, all:
    As we know, we can easily run any components of ceph cluster with one docker image(ceph/daemon:latest-luminous, e.g.), docker run -d --net=host --name=xxx -v /etc/localtime:/etc/localtime -v /etc/ceph:/etc/ceph -v /var/lib/ceph:/var/lib/ceph -e MON_IP=xxx.xxx.xxx.xxx -e CEPH_PUBLIC_NETWORK=xxx.xxx.xxx.xxx/24 ceph/daemon:latest-luminous {mon,osd,mds}. And we are able to check logs by command "docker logs -f xxx". 
    But as time flies, 1 month, for example, sizes of these stdout may take to much under directory /var/lib/docker/containers/CONTAINER ID/CONTAINER ID-json.log, may reach 10G+. It is not so easy to control the size of them.  
    I know there is one ENTRYPOINT in Dockerfile: [/opt/ceph-container/bin/entrypoint.sh], and when running docker, we can add CMD like 'mon','osd','mgr' .etc. To setup different componets and check log. 
    So are there any ways(bring in new Env parameter or bring in new option following behind the scripts entrypoint.sh) to define one switch which controls or restrains stdout log and redirect the stdout log to one directory inside the container, so that we can mount the directory outside to the host directory, and handle the logs easily? 

BR

**Comment by PrometheusYu** [comment]
![problem](https://user-images.githubusercontent.com/33949077/71434447-8bbb5180-271f-11ea-9cf9-38d8f92ef4e3.png)
We can see that size of logs is increasing rapidly. This may be a potential risk if there is no limitation about stdout.

**Comment by hex43ver** [comment]
Years ago I have similar issue, can you try if below parameters still work:

```
            --log-opt max-size=100M \
            --log-opt max-file=3 \
            -v /srv/ceph/ceph_var_log/osd2:/var/log/ceph \
```
