### ISSUE TITLE
container is missing /usr/lib/systemd directory

### ISSUE THREAD

**Issue by liewegas** [ceph/ceph-container#1571]
See https://tracker.ceph.com/issues/43609

The container image has the systemd-239-18.el8_1.1.x86_64 package installed, which contains a few dozen files in /usr/lib/systemd, but that directory is missing.

The end result is that the 'udevadm' command fails:

```
[ceph: root@gnit /]# udevadm
udevadm: error while loading shared libraries: libsystemd-shared-239.so: cannot open shared object file: No such file or directory
```

**Comment by dsavineau** [comment]
This has already been fixed by https://github.com/ceph/ceph-container/pull/1569
