### ISSUE TITLE
Bug in common_functions.sh?

### ISSUE THREAD

**Issue by frans42** [ceph/ceph-container#1579]
In the image tagged "v3.2.10-stable-3.2-mimic-centos-7-x86_64" (mimic 13.2.8) in the script common_functions.sh:278-279 I believe the code block

```
  if [[ ${OSD_BLUESTORE} -eq 1 ]]; then
    dev_real_path=$(resolve_symlink "$OSD_BLUESTORE_BLOCK_WAL" "$OSD_BLUESTORE_BLOCK_DB")
    for partition in $(list_dev_partitions "$OSD_DEVICE" "$dev_real_path"); do
```

should be something like this:

```
  if [[ ${OSD_BLUESTORE} -eq 1 ]]; then
    dev_real_path=( $(resolve_symlink "$OSD_BLUESTORE_BLOCK_WAL" "$OSD_BLUESTORE_BLOCK_DB") )
    for partition in $(list_dev_partitions "$OSD_DEVICE" "${dev_real_path[@]}"); do
```

The expansion `"$dev_real_path"` seems not to provide the desired result.

**Comment by dsavineau** [comment]
> I believe the code block should be something like this

Do you just believe or did you ran into a real error ?

**Comment by frans42** [comment]
I run into an error a long time ago, when trying to deploy co-located bluestore devices where WAL and DB are actually co-located instead of separate partitions on the same disk as was deployed in older versions by default. This has been fixed recently here:

```
  if [[ ${OSD_BLUESTORE} -eq 1 ]]; then
    CEPH_DISK_CLI_OPTS+=(--bluestore)
    if [[ "${OSD_BLUESTORE_BLOCK_WAL}" != "${OSD_DEVICE}" ]]; then
      CEPH_DISK_CLI_OPTS+=(--block.wal "${OSD_BLUESTORE_BLOCK_WAL}" --block.wal-uuid "${OSD_BLUESTORE_BLOCK_WAL_UUID}")
    fi
    if [[ "${OSD_BLUESTORE_BLOCK_DB}" != "${OSD_DEVICE}" ]]; then
      CEPH_DISK_CLI_OPTS+=(--block.db "${OSD_BLUESTORE_BLOCK_DB}" --block.db-uuid "${OSD_BLUESTORE_BLOCK_DB_UUID}")
    fi
    ceph-disk -v prepare "${CEPH_DISK_CLI_OPTS[@]}" \
    --block-uuid "${OSD_BLUESTORE_BLOCK_UUID}" \
    "${OSD_DEVICE}"
```

and what I report is a follow-up error that is silently ignored in the script if WAL and DB devices are indeed different from the bluestore data device.

I was debugging this part some time ago and the loop runs into an error. The expansion "$dev_real_path" gives a space-separated string instead of to different ones for each device.

"Believe" here means that the code I substituted does probably what is intended, however, I don't know what is actually intended so my modification might still be doing something wrong. I'm using the modified script in my deployments.

**Comment by frans42** [comment]
Is there anything else required?

**Comment by frans42** [comment]
I provided additional information. Could someone please look at this? It affects our deployment.

**Comment by dsavineau** [comment]
Could you provide a step by step reproducer ?

**Comment by frans42** [comment]
I found some time to go through the scripts again. Here are my findings (point 3 on how to reproduce):


1. The problematic code fragment is in common_functions.h, which is included by all scripts. The function in question is referred to in multiple places:

```
[root@gnosis v3.2.10-stable-3.2-mimic-centos-7-x86_64]# grep -n apply_ceph_ownership_to_disks *.sh
common_functions.sh:267:function apply_ceph_ownership_to_disks {
disk_list.sh:69:    # because apply_ceph_ownership_to_disks will determine the partitions
osd_disk_activate.sh:71:    # Get the device used for block db and wal otherwise apply_ceph_ownership_to_disks will fail
osd_disk_activate.sh:80:  apply_ceph_ownership_to_disks
osd_disk_prepare.sh:79:  apply_ceph_ownership_to_disks
```


2. What I report is an inappropriate bash semantics, which is incorrect independently of what the code is intended to do:

The code fragment in question:

```
    dev_real_path=$(resolve_symlink "$OSD_BLUESTORE_BLOCK_WAL" "$OSD_BLUESTORE_BLOCK_DB")
    for partition in $(list_dev_partitions "$OSD_DEVICE" "$dev_real_path"); do
      part_code=$(get_part_typecode "$partition")
```

has the form

```
var1=$(cmd1 A B)
for p in $(cmd2 "$O" "$var1"); do
  var2=$(cmd3 "$p")
```

which will lead to an incorrect expansion of "$var1" in the for loop as follows: `cmd1 A B` outputs a space separated string, say, "A1 B1", which is assigned to `var1`. The subsequent expansion of `"$var1"` will now result in a *single* loop item containing "A1 B1" *instead* of *two* separate loop items for each of the inputs `A` and `B` to `cmd1`. The command `cmd3 "$p"` fails for this loop item and the error is silently ignored. As a consequence, a later `chown` command is *not* applied to the WAL and BD partitions, if both are specified and different.

This semantics is incorrect independently of what the code is supposed to do.


3. How to reproduce?

If you want to see this in action:

- insert "set -x" in the function `apply_ceph_ownership_to_disks` and
- run the ceph disk prepare scenario with a bluestore OSD and both, WAL and DB partitions defined as different partitions (3-device scenario, DATA, WAL and BD on different devices).

You will see an incorrect argument being passed to get_part_typecode in the second iteration of the for loop.


4. Why is this not detected during CI testing?

If this scenario is not part of the CI testing, this might be an undiscovered bug.

However, I'm pretty sure this part of the CI test run for every release. If so, the question is, why is this not detected? The erroneous second loop is ignored and the `chown` command is not applied. Here I don't really know the answer because I do not run with WAL and DB partitions. It is possible that `ceph-disk` does it already.


5. How to patch?

I simply provided a modification that changes the incorrect to correct bash semantics. On the other hand, if this is already done by `ceph-disk`, the bluestore branch in the function `apply_ceph_ownership_to_disks` is redundant. I cannot do a test with WAL and DB partitions, I don't have a test environment. Therefore, I cannot say if the branch of code can be removed antirely, or is required and needs fixing.

**Comment by dsavineau** [comment]
> * run the ceph disk prepare scenario with a bluestore OSD and both, WAL and DB partitions defined as different partitions (3-device scenario, DATA, WAL and BD on different devices).

I'm not sure to understand correctly. Are you using:
- Bluestore data on /dev/sdx and DB/WAL on /dev/sdy (with 2 different partitions)
- Bluestore data on /dev/sdx, DB on /dev/sdy and WAL on /dev/sdz

**Comment by frans42** [comment]
It doesn't matter, either will do. What matters is that OSD_DEVICE, OSD_BLUESTORE_BLOCK_WAL and OSD_BLUESTORE_BLOCK_DB contain a different value each.

**Comment by dsavineau** [comment]
```console
/dev/sdb :
 /dev/sdb1 ceph data, active, cluster ceph, osd.0, block /dev/sdb2, block.db /dev/sdd1, block.wal /dev/sde1
 /dev/sdb2 ceph block, for /dev/sdb1
/dev/sdc :
 /dev/sdc1 ceph data, prepared, cluster ceph, osd.1, block /dev/sdc2, block.db /dev/sdd2, block.wal /dev/sde2
 /dev/sdc2 ceph block, for /dev/sdc1
/dev/sdd :
 /dev/sdd1 ceph block.db, for /dev/sdb1
 /dev/sdd2 ceph block.db, for /dev/sdc1
/dev/sde :
 /dev/sde1 ceph block.wal, for /dev/sdb1
 /dev/sde2 ceph block.wal, for /dev/sdc1
```

So both DB and WAL devices don't have the right owner/group permission.

```console
# ls -hl /dev/sd{b,c,d,e}*
brw-rw----. 1 root disk 8, 16 May  4 15:18 /dev/sdb
brw-rw----. 1 ceph ceph 8, 17 May  4 15:18 /dev/sdb1
brw-rw----. 1 ceph ceph 8, 18 May  4 15:18 /dev/sdb2
brw-rw----. 1 root disk 8, 32 May  4 15:18 /dev/sdc
brw-rw----. 1 ceph ceph 8, 33 May  4 15:18 /dev/sdc1
brw-rw----. 1 ceph ceph 8, 34 May  4 15:18 /dev/sdc2
brw-rw----. 1 root disk 8, 48 May  4 15:18 /dev/sdd
brw-rw----. 1 root disk 8, 49 May  4 15:18 /dev/sdd1
brw-rw----. 1 root disk 8, 50 May  4 15:18 /dev/sdd2
brw-rw----. 1 root disk 8, 64 May  4 15:18 /dev/sde
brw-rw----. 1 root disk 8, 65 May  4 15:34 /dev/sde1
brw-rw----. 1 root disk 8, 66 May  4 15:34 /dev/sde2
```

I guess this still works because the ceph-osd process is started with the `ceph` user and `disk` group. That's probably why this hasn't been reported before.

```
/usr/bin/ceph-osd --cluster ceph -f -i 0 --setuser ceph --setgroup disk
```

Now the interesting part is that there's another issue before the `apply_ceph_ownership_to_disks` call.

```console
+osd_disk_activate.sh:70: osd_activate(): [[ 1 -eq 1 ]]
++osd_disk_activate.sh:72: osd_activate(): resolve_symlink block.db
++common_functions.sh:95: resolve_symlink(): readlink -f block.db
+osd_disk_activate.sh:72: osd_activate(): OSD_BLUESTORE_BLOCK_DB_TMP=/block.db
+osd_disk_activate.sh:74: osd_activate(): OSD_BLUESTORE_BLOCK_DB=/block.d
++osd_disk_activate.sh:76: osd_activate(): resolve_symlink block.wal
++common_functions.sh:95: resolve_symlink(): readlink -f block.wal
+osd_disk_activate.sh:76: osd_activate(): OSD_BLUESTORE_BLOCK_WAL_TMP=/block.wal
+osd_disk_activate.sh:78: osd_activate(): OSD_BLUESTORE_BLOCK_WAL=/block.wa
```

So `OSD_BLUESTORE_BLOCK_DB` and `OSD_BLUESTORE_BLOCK_WAL` are set with the associated device but due a missing variable (`OSD_PATH`) then the variables are set with a wrong value.
Also if those variables are already set on container start then this will override them.

https://github.com/ceph/ceph-container/blob/stable-3.2/src/daemon/osd_scenarios/osd_disk_activate.sh#L70-L79

**Comment by frans42** [comment]
Glad you could reproduce it and even found another issue.

> So both DB and WAL devices don't have the right owner/group permission.

Exactly. The corresponding loop items are incorrect in the snippet of `apply_ceph_ownership_to_disks` I quoted above.

> Now the interesting part is that there's another issue ...

This one I didn't observe. Back when I worked with this, the code for using `OSD_BLUESTORE_BLOCK_DB` and `OSD_BLUESTORE_BLOCK_WAL` was different (I copied the diff in my second comment above). I didn't check where this comes from in the updated version. Kind of funny that so much works just by coincidence.

I think you are right, this hasn't been reported because somehow the OSD daemon can still access the disk. I only found it because I reviewed the for me relevant code before using it in production and saw strange error messages/warnings in the log.

**Comment by dsavineau** [comment]
So the fix for the right owner/group is to use `${dev_real_path}` but without the quotes.
Using `"${dev_real_path[@]}"` doesn't work unless you remove the quotes too.

Using quotes will preserve the blank spaces inside the `$dev_real_path` variable.

**Comment by frans42** [comment]
Well, I wouldn't expand anything without quotes. I have seen really bad things happening.

It is easy to overlook, the fix I proposed actually changes two lines:

1. Place parentheses "`( )`" around `$(resolve_symlink ...` to make `dev_real_path` an array as in

        dev_real_path=( $(resolve_symlink "$OSD_BLUESTORE_BLOCK_WAL" "$OSD_BLUESTORE_BLOCK_DB") )

2. Use `@` expansion for quoted expansion of each element as in `"${dev_real_path[@]}"`. This will not expand to a single quoted string, but into a quoted string for each element in the array. These quoted strings are then secure to be passed to commands later (also quoted), for example, the `chown`.

With the additional modification (1), `"${dev_real_path[@]}"` will not preserve spaces between different paths in `dev_real_path`.
