### ISSUE TITLE
python-saml missing

### ISSUE THREAD

**Issue by pavels** [ceph/ceph-container#1589]
**Bug Report**

What happened:

`ceph dashboard sso status` -> `Error EPERM: Required library not found: python-saml`

Looks liek the conainer images are missing `python-saml` library, would it be possible to add it, so SSO for dashboard can be set?

What you expected to happen:

Be able to setup SSO for Dashboard

**Environment**:
Docker Image: ceph/ceph:v14.2.1-20190430
ceph version 14.2.6 (f0aa067ac7a02ee46ea48aa26c6e298b5ea272e9) nautilus (stable)

**Comment by dsavineau** [comment]
> Looks liek the conainer images are missing `python-saml` library, would it be possible to add it, so SSO for dashboard can be set?

It would be possible if the package was available in the CentOS 7 distribution or EPEL 7 but it's not.

**Comment by pavels** [comment]
Would it be possible to install it from pip? - all dependencies are in repository, just the python library is not

**Comment by dsavineau** [comment]
We're not insllating anything from pip only rpm packages

**Comment by pavels** [comment]
And i assume you don't accept third-party RPM repositories either, right?

**Comment by dsavineau** [comment]
Right, we only using three sources

- CentOS base repositories (*.centos.org)
- EPEL repositories (download.fedoraproject.org)
- Ceph repositories (*.ceph.com)

**Comment by pavels** [comment]
Ok, that's clear

Thank you

**Comment by LeoQuote** [comment]
hi, I'm currently using `ceph/daemon:v5.0.2-stable-5.0-octopus-centos-8` , but still expirencing this issue, I can see https://github.com/ceph/ceph-container/pull/1646 is merged and release, why is this still happenning?

**Comment by LeoQuote** [comment]
```
$ sudo docker run --rm -it --entrypoint=bash ceph/daemon:v5.0.2-stable-5.0-octopus-centos-8
[root@cd1c60c45e00 /]# python3
Python 3.6.8 (default, Apr 16 2020, 01:36:27)
[GCC 8.3.1 20191121 (Red Hat 8.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from onelogin.saml2.auth import OneLogin_Saml2_Auth
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'onelogin'
[root@cd1c60c45e00 /]# ceph -v
ceph version 15.2.3 (d289bbdec69ed7c1f516e0a093594580a76b78d0) octopus (stable)
```

**Comment by dsavineau** [comment]
> hi, I'm currently using `ceph/daemon:v5.0.2-stable-5.0-octopus-centos-8` , but still expirencing this issue, I can see #1646 is merged and release, why is this still happenning?

The python saml has been merged only for ubi8 container which means container image for Red Hat Ceph Storage 4 (because this package is available there).
This package is still not present in either CentOS or EPEL so it's not present for the upstream images.

**Comment by LeoQuote** [comment]
@dsavineau Thanks for your explanation!

**Comment by rkachach** [comment]
@dsavineau bumping this thread up: is this still the case in 2023?

**Comment by guits** [comment]
@rkachach I see there's a `python3-saml` in EPEL 8 but nothing for el9

**Comment by tchaikov** [comment]
i haven't got a chance to build it for epel9. if it's urgent, please feel free to co-maintain with me.

**Comment by rkachach** [comment]
@tchaikov it's not urgent. I ended up here coming from this Rook issue https://github.com/rook/rook/issues/5392 where somebody is asking for dashboard sso support in Rook. It turns out it depends on `python3-saml` package.

**Comment by tchaikov** [comment]
i see. the reason why i started maintaining this package was Ceph's SSO. just don't have enough bandwidth working on it recently.

**Comment by pavels** [comment]
> @tchaikov it's not urgent. I ended up here coming from this Rook issue [rook/rook#5392](https://github.com/rook/rook/issues/5392) where somebody is asking for dashboard sso support in Rook. It turns out it depends on `python3-saml` package.

I am currently running 2 different version through rook: 16.2.7 and 18.2.0

Respective images:
quay.io/ceph/ceph:v16.2.7
quay.io/ceph/ceph:v18.2.0

On both of these images, SSO works as expected without problems

**Comment by rkachach** [comment]
Thank you @pavels I thought that sso is not supported on Rook because the issue/ticket has been open for a while! I'll double check with team to see if we can close it.

**Comment by dsavineau** [comment]
This was fixed in https://github.com/ceph/ceph-container/commit/b682658663b616b89b39a9ca47531211813a550f almost 3 years ago

**Comment by rkachach** [comment]
> > @tchaikov it's not urgent. I ended up here coming from this Rook issue [rook/rook#5392](https://github.com/rook/rook/issues/5392) where somebody is asking for dashboard sso support in Rook. It turns out it depends on `python3-saml` package.
> 
> I am currently running 2 different version through rook: 16.2.7 and 18.2.0
> 
> Respective images: quay.io/ceph/ceph:v16.2.7 quay.io/ceph/ceph:v18.2.0
> 
> On both of these images, SSO works as expected without problems

Hi Pavel, 

Awesome, please, can you share what documentation did you follow to setup the SSO for Rook?

Thanks.

**Comment by pavels** [comment]
> > > @tchaikov it's not urgent. I ended up here coming from this Rook issue [rook/rook#5392](https://github.com/rook/rook/issues/5392) where somebody is asking for dashboard sso support in Rook. It turns out it depends on `python3-saml` package.
> > 
> > 
> > I am currently running 2 different version through rook: 16.2.7 and 18.2.0
> > Respective images: quay.io/ceph/ceph:v16.2.7 quay.io/ceph/ceph:v18.2.0
> > On both of these images, SSO works as expected without problems
> 
> Hi @pavels
> 
> Please, can you share what documentation did you follow to setup the SSO for rook?
> 
> Thanks.

Official one

https://docs.ceph.com/en/quincy/mgr/dashboard/#dashboard-sso-support

I did all the steps through `toolbox` container - https://rook.io/docs/rook/v1.12/Troubleshooting/ceph-toolbox/.

**Comment by rkachach** [comment]
I see, thank you very much @pavels :+1:

**Comment by tchaikov** [comment]
FWIW, i just pushed python3-saml to EPEL9. it will be in stable in a week.

**Comment by rkachach** [comment]
Thanks @tchaikov
