### ISSUE TITLE
Web Gui for ceph dockerized

### ISSUE THREAD

**Issue by bd8392** [ceph/ceph-container#1608]
Yes
Is this a bug report or feature request?
* Feature Request

**Feature Request**

Are there any similar features already existing:
Monitoring guis mentioned on the web
What should the feature do:
Setup and monitor a ceph cluster via webgui which is in a docker container
What would be solved through this feature:
Ceph would become easier to monitor and setup
Does this have an impact on existing features:
Yes, ceph would become more versatile
**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Docker version (e.g. `docker version`):
* Ceph version (e.g. `ceph -v`):

I don't know if this feature already exists...I didn't find anything useful I'm the web...if so, I'm sorry to open this.

**Comment by dsavineau** [comment]
https://docs.ceph.com/docs/master/mgr/dashboard/

But this dashboard is for managing and monitoring the ceph cluster. Note that everything is already part of the current ceph container image (on release >= nautilus). The grafana and prometheus part aren't included in this image, you need to do the integration by yourself.
This won't provide you anything to deploy/configure new nodes. You still need to use something else to setup your infrastructure.

**Comment by bd8392** [comment]
Okay big thanks :-) I just want to use it for pool setup :-) thanks for your help :-)
