### ISSUE TITLE
How do I use a custom version of ceph to build images

### ISSUE THREAD

**Issue by zhifei92** [ceph/ceph-container#1631]
hi，all. How do I use a custom version of ceph to build images

**Comment by dsavineau** [comment]
What do you mean by a custom version of ceph ?

**Comment by zhifei92** [comment]
@dsavineau hi, how do I use the local ceph binary package for building images instead of the ceph official package

**Comment by dsavineau** [comment]
There's actually no support of using local ceph packages instead of the official ceph repositories.
