### ISSUE TITLE
don't create osd pod by using k8s example which is ceph-osd-v1-ds.yaml

### ISSUE THREAD

**Issue by saltFisher** [ceph/ceph-container#1633]
executing kubectl --namespace=ceph create -f ceph-osd-v1-ds.yaml, can't create osd pod, it shows below:
[root@CephOnK8S kubernetes]# kubectl --namespace=ceph get all
NAME                                  READY   STATUS             RESTARTS   AGE
pod/ceph-mds-5bcdc59bf7-qc6tk         1/1     Running            17         125m
pod/ceph-mon-5948644cbf-7gfq4         1/1     Running            0          68m
pod/ceph-mon-5948644cbf-q5bmg         1/1     Running            0          68m
pod/ceph-mon-5948644cbf-r2flc         1/1     Running            0          68m
pod/ceph-mon-check-7678c9f659-7d96p   1/1     Running            0          123m
pod/ceph-osd-lfnmk                    0/1     CrashLoopBackOff   15         56m
pod/ceph-osd-vt2mj                    0/1     Completed          16         56m

check pod logs,  kubectl --namespace=ceph logs ceph-osd-vt2mj, it shows below:
[root@CephOnK8S kubernetes]# kubectl --namespace=ceph logs ceph-osd-vt2mj
chown: changing ownership of '/var/lib/ceph/bootstrap-rbd': Read-only file system
chown: changing ownership of '/var/lib/ceph/bootstrap-rbd/..data': Read-only file system
chown: changing ownership of '/var/lib/ceph/bootstrap-rbd/..data/ceph.keyring': Read-only file system
chown: changing ownership of '/var/lib/ceph/bootstrap-rbd/ceph.keyring': Read-only file system
chown: changing ownership of '/var/lib/ceph/bootstrap-rbd/..2020_03_26_17_37_45.589567710': Read-only file system
chown: changing ownership of '/var/lib/ceph/bootstrap-rbd/..2020_03_26_17_37_45.589567710/ceph.keyring': Read-only file system
chown: changing ownership of '/var/lib/ceph/bootstrap-rgw': Read-only file system
chown: changing ownership of '/var/lib/ceph/bootstrap-rgw/..data': Read-only file system
chown: changing ownership of '/var/lib/ceph/bootstrap-rgw/..data/ceph.keyring': Read-only file system
chown: changing ownership of '/var/lib/ceph/bootstrap-rgw/ceph.keyring': Read-only file system
chown: changing ownership of '/var/lib/ceph/bootstrap-rgw/..2020_03_26_17_37_45.094986176': Read-only file system
chown: changing ownership of '/var/lib/ceph/bootstrap-rgw/..2020_03_26_17_37_45.094986176/ceph.keyring': Read-only file system
chown: changing ownership of '/var/lib/ceph/bootstrap-mds': Read-only file system
chown: changing ownership of '/var/lib/ceph/bootstrap-mds/..data': Read-only file system
chown: changing ownership of '/var/lib/ceph/bootstrap-mds/..data/ceph.keyring': Read-only file system
chown: changing ownership of '/var/lib/ceph/bootstrap-mds/ceph.keyring': Read-only file system
chown: changing ownership of '/var/lib/ceph/bootstrap-mds/..2020_03_26_17_37_45.092897445': Read-only file system
chown: changing ownership of '/var/lib/ceph/bootstrap-mds/..2020_03_26_17_37_45.092897445/ceph.keyring': Read-only file system
chown: changing ownership of '/var/lib/ceph/bootstrap-osd': Read-only file system
chown: changing ownership of '/var/lib/ceph/bootstrap-osd/..data': Read-only file system
chown: changing ownership of '/var/lib/ceph/bootstrap-osd/..data/ceph.keyring': Read-only file system
chown: changing ownership of '/var/lib/ceph/bootstrap-osd/ceph.keyring': Read-only file system
chown: changing ownership of '/var/lib/ceph/bootstrap-osd/..2020_03_26_17_37_45.750944799': Read-only file system
chown: changing ownership of '/var/lib/ceph/bootstrap-osd/..2020_03_26_17_37_45.750944799/ceph.keyring': Read-only file system
2020-03-26 18:34:40  /opt/ceph-container/bin/entrypoint.sh: k8s: config is stored as k8s secrets.
2020-03-26 18:34:40  /opt/ceph-container/bin/entrypoint.sh: k8s: does not generate the admin key. Use Kubernetes secrets instead.
ceph-5: /usr/bin/ceph-osd --cluster ceph -f -i 5 --osd-journal /var/lib/ceph/osd/ceph-5//journal -k /var/lib/ceph/osd/ceph-5//keyring
2020-03-26 18:34:40  /opt/ceph-container/bin/entrypoint.sh: SUCCESS
exec: PID 82: spawning /usr/local/bin/forego start -f /etc/forego/ceph/Procfile
exec: Waiting 82 to quit
forego   | starting ceph-5.1 on port 5000
ceph-5.1 | 2020-03-26T18:34:40.606+0000 7f450acceec0 -1 missing 'type' file and unable to infer osd type
teardown: managing teardown after SIGCHLD
teardown: Waiting PID 82 to terminate
teardown: Process 82 is terminated
teardown: Bye Bye, container will die with return code 0

what means of this " missing 'type' file and unable to infer osd type", does anyone knows how to fix it ?

**Comment by ne0h** [comment]
I have the same issue.

**Comment by Rob4579** [comment]
Same here. Someone had this resolved?

**Comment by dsavineau** [comment]
The kubernetes example are unmaintained and untested.

For running ceph on k8s you should take a look at the rook operator which uses the container image generated by this project.

https://rook.io/
https://github.com/rook/rook
https://rook.io/docs/rook/v1.3/ceph-storage.html

**Comment by ne0h** [comment]
That's really too bad. No chance to revive the kubernetes examples?
Or could you please remove them at least and point directly to rook?
