### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by frans42** [ceph/ceph-container#1660]
It looks like issues are ignored since about 1-2 months now. The stale bot closed basically everything, but I can't see any communication going on. Is there a new place for reporting bugs now?

What happened:

I opened a ticket (#1579).
Further information was requested and the label "needs info" was added.
I provided further information.
Since then nothing happened.
At some point the stale bot added the label won't fix.
I added a request for clarification.
Still nothing happened.

What you expected to happen:

That someone looks at information provided and a meaningful dialogue happens or at least some information is released about how to report issues in case this list is no longer relevant.

In case this project is dead users should be informed not to use these containers in production any more.

**Comment by mykaul** [comment]
Looking at https://github.com/ceph/ceph-container/graphs/contributors , doesn't look like it's dead.
But no, not all issues are always attended for. Sometimes even with the information provided. Sometimes a patch helps, not just reporting an issue - and I believe you are not far off from it (from the 1st comment at least on #1579 ).

**Comment by frans42** [comment]
Hmm, OK. I will try to figure out how to do a pull request (never done that before). Was hoping it would be easier to report it as its only a two-liner.

I was mainly surprised that the stale bot was let loose on all issues and they dropped from several hundred to less than 20 due to that. Probably quite a few of those for nothing else than not responding to a comment by a user. Not sure if all issues that were closed in this way were really not worth looking at and it might also not really send the best message to the users.

To me it was a bit like "feedback not appreciated". A comment from my side was requested, I spent quite a bit of time on providing it and as a result I get ghosted and a mindless bot takes over?

Thanks for your response :)

**Comment by mykaul** [comment]
The stale bot does exactly what it is meant to do - it either lets irrelevant issues die, or forces someone who cares to actually handle them. The alternative, of them rotting in the backlog, is worse, IMHO.

**Comment by frans42** [comment]
Firstly: Thanks for taking time for this on a Sunday. Please don't get me wrong in the text below. I'm seriously concerned if I need to change product.

Before opening this case, I looked at the complete issue list and saw that for the last 2-3 months literally everything was closed by the stale bot, as if it was decided to abandon this list. I have seen reports about critical issues that disappeared in stale bot space. Some of these were probably just on a backlog, not everything is easy to fix. My issue was clearly minor compared with others closed by the stale bot.

I understand the function of the stale bot and it is used everywhere to close *inactive* cases. Inactive as defined by: last comment is by a developer and the user did not respond in time. This is very clearly not the case for my issue and also not for many others I have skimmed through. Just look at these comment dates:

frans42 commented on Jan 30
<someone> commented on Jan 30
frans42 commented on Jan 30
frans42 commented on Mar 9
stale bot commented 18 days ago
frans42 commented 17 days ago

I can hardly call this inactive from my side and I actually do find this somewhat insulting if this is intentional. If your statement about caring is correct, than my observation would imply that developers stopped caring about basically everything in the issue list.

I would rather hope that this observation is just the result of a misconfigured stale bot.

In essence, the question I'm interested in is, does it make sense to submit cases to this list in the future? Will I get more than a game of stale bot ping pong?

Well, at least in this case I did. It was nice to talk to a human for a change. Thanks for taking the time for this on a Sunday. Best regards!

**Comment by dsavineau** [comment]
> It looks like issues are ignored since about 1-2 months now. The stale bot closed basically everything, but I can't see any communication going on. Is there a new place for reporting bugs now?

No, that's still the right place for reporting issues. As mentioned earlier, the stalebot does exactly what it should do.

> What you expected to happen:
> 
> That someone looks at information provided and a meaningful dialogue happens or at least some information is released about how to report issues in case this list is no longer relevant.

That's true, there was no more discussion on your issue for several reasons:

This project is currently maintained by only one guy (me).
The issue is considered as low priority because
- It's related to ceph-disk which is depreacted in Mimic [1] then removed in Nautilus so ceph users should use ceph-volume instead.
- There's no clear reproducer

Note that any contribution is welcomed.

> In case this project is dead users should be informed not to use these containers in production any more.

The project isn't dead. As long as Ceph has new releases then we will need new container images.
We're still providing new container images for luminous, mimic, nautilus and octopus releases.

As all open source projects, you should use this project at your own risk.

**Comment by frans42** [comment]
I think I got the answers and there is no need to go on here. I will focus on the actual case. Please bear with me, I'm extremely busy right now and will need a bit of time.
