### ISSUE TITLE
Please add zabbix_sender package to ceph base image which is required for enabling zabbix module in MGR

### ISSUE THREAD

**Issue by udayjalagam** [ceph/ceph-container#1671]
Is this a bug report or feature request?
* Feature Request

**Feature Request**

Are there any similar features already existing: might be

What should the feature do: Install zabbix_sender /zabbix_agent package in base Image 
https://docs.ceph.com/docs/nautilus/mgr/zabbix/

What would be solved through this feature: We can send metrics to zabbix using ceph manager module without building our own images. 

Does this have an impact on existing features: No

**Environment**:
* OS (e.g. from /etc/os-release):Ubuntu 
* Kernel (e.g. `uname -a`):  4.15.0-91-generic
* Docker version (e.g. `docker version`):19.03.8
* Ceph version (e.g. `ceph -v`):14.2.3

**Comment by dsavineau** [comment]
Please see https://github.com/ceph/ceph-container/issues/1651
