### ISSUE TITLE
Documentation Issue regarding DNS + Kubernetes

### ISSUE THREAD

**Issue by elsonrodriguez** [ceph/ceph-container#1675]
Originally I had documented this DNS pattern in the examples:

https://github.com/ceph/ceph-container/tree/master/examples/kubernetes#skydns-resolution
```
domain <EXISTING_DOMAIN>
search <EXISTING_DOMAIN>

search svc.cluster.local #Your kubernetes cluster ip domain

nameserver 10.96.0.10     #The cluster IP of skyDNS
nameserver <EXISTING_RESOLVER_IP>
```
Unfortunately this won't work reliably, it'll just round robin the two DNS servers, causing resolution errors 50% of the time.

I'm not active with Ceph any more, but another solution would need to be put in place to get things working (like dnsmasq).

**Comment by dancer1325** [comment]
has somebody tried to overcome this issue? -- and even more since SkyDns is deprecated in favor of CoreDns --
