### ISSUE TITLE
Latest update of docker images broken?

### ISSUE THREAD

**Issue by dp4-ms** [ceph/ceph-container#1677]
**Bug Report**

What happened:
We deploy ceph clusters using ceph-ansible. We switched to the latest version of ceph/daemon:v4.0.8-stable-4.0-nautilus-centos-7  (image ID: cc3e177e8486) and `docker run` commands terminate with an error instantly rather than starting a container instance:

> docker run -d --net=host -v /etc/ceph:/etc/ceph -v /var/lib/ceph/:/var/lib/ceph/ cc3e177e8486 mgr
6dfd324ceeb3e3b7c0f5730c14f1bd28a7fd28e721e57ee7ef87c62317989442
docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"mgr\": executable file not found in $PATH": unknown.

Running `docker inspect` on the container image shows no Entrypoint:

docker inspect cc3e177e8486
[
    {
        "Id": "sha256:cc3e177e8486c0d169d4b011c6eeae5b494117186ffa913abc1addbe4f3c7058",
        "RepoTags": [
            "ceph/daemon:v4.0.8-stable-4.0-nautilus-centos-7"
        ],
        "RepoDigests": [
            "ceph/daemon@sha256:c9c193fb59dfaa1c14c85fb3f2eea8cdf67d6452174c6358cbfc969651b49b92"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2019-12-18T17:06:56.871791616Z",
        "Container": "e390e80742a2b7286b4662d15f03228d5ab0f0fe423c570e5aa32e17f4441598",
        "ContainerConfig": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "CEPH_VERSION=nautilus",
                "CEPH_POINT_RELEASE="
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "yum install -y epel-release && yum install -y jq && bash -c '   if [ -n \"nfs-ganesha nfs-ganesha-ceph nfs-ganesha-rgw nfs-ganesha-rados-grace\" ]; then     echo \"[ganesha]\" > /etc/yum.repos.d/ganesha.repo ;     echo \"name=ganesha\" >> /etc/yum.repos.d/ganesha.repo ;     if [[ \"${CEPH_VERSION}\" =~ master|^wip* ]]; then       REPO_URL=$(curl -s \"https://shaman.ceph.com/api/search/?project=nfs-ganesha&distros=centos/7&flavor=ceph_master&ref=next&sha1=latest\" | jq -a \".[0] | .url\");       echo \"baseurl=$REPO_URL/\\$basearch/\" >> /etc/yum.repos.d/ganesha.repo ;     elif [[ \"${CEPH_VERSION}\" == nautilus ]]; then       echo \"baseurl=http://download.ceph.com/nfs-ganesha/rpm-V2.8-stable/$CEPH_VERSION/\\$basearch/\" >> /etc/yum.repos.d/ganesha.repo ;     else       echo \"baseurl=http://download.ceph.com/nfs-ganesha/rpm-V2.7-stable/$CEPH_VERSION/\\$basearch/\" >> /etc/yum.repos.d/ganesha.repo ;     fi ;     echo \"gpgcheck=0\" >> /etc/yum.repos.d/ganesha.repo ;     echo \"enabled=1\" >> /etc/yum.repos.d/ganesha.repo  ;   fi ;   if [ -n \"tcmu-runner ceph-iscsi python-rtslib\" ]; then     for repo in tcmu-runner python-rtslib; do       curl -L https://shaman.ceph.com/api/repos/$repo/master/latest/centos/7/repo > /etc/yum.repos.d/$repo.repo ;     done ;     if [[ \"${CEPH_VERSION}\" =~ master|^wip* ]]; then       curl -L https://shaman.ceph.com/api/repos/ceph-iscsi/master/latest/centos/7/repo > /etc/yum.repos.d/ceph-iscsi.repo ;     elif [[ \"${CEPH_VERSION}\" == nautilus ]]; then       curl -L https://download.ceph.com/ceph-iscsi/3/rpm/el7/ceph-iscsi.repo -o /etc/yum.repos.d/ceph-iscsi.repo ;     else       curl -L https://download.ceph.com/ceph-iscsi/2/rpm/el7/ceph-iscsi.repo -o /etc/yum.repos.d/ceph-iscsi.repo ;     fi ;   fi' && yum update -y && rpm --import 'https://download.ceph.com/keys/release.asc' && bash -c '   if [[ \"${CEPH_VERSION}\" =~ master|^wip* ]]; then     REPO_URL=$(curl -s \"https://shaman.ceph.com/api/search/?project=ceph&distros=centos/7&flavor=default&ref=${CEPH_VERSION}&sha1=latest\" | jq -a \".[0] | .url\");     RELEASE_VER=0 ;  else     RELEASE_VER=1 ;    REPO_URL=\"http://download.ceph.com/rpm-${CEPH_VERSION}/el7/\";   fi &&   rpm -Uvh \"$REPO_URL/noarch/ceph-release-1-${RELEASE_VER}.el7.noarch.rpm\" ' && yum install -y         ca-certificates         e2fsprogs         ceph-common          ceph-mon          ceph-osd         ceph-mds         rbd-mirror          ceph-mgr ceph-mgr-dashboard ceph-mgr-diskprediction-local ceph-mgr-k8sevents ceph-mgr-rook        ceph-grafana-dashboards         kmod         lvm2         gdisk \tsmartmontools \tnvme-cli \tlibstoragemgmt         ceph-radosgw libradosstriper1         nfs-ganesha nfs-ganesha-ceph nfs-ganesha-rgw nfs-ganesha-rados-grace         tcmu-runner ceph-iscsi python-rtslib &&     INITIAL_SIZE=\"$(bash -c 'sz=\"$(du -sm --exclude=/proc /)\" ; echo \"${sz%*/}\"')\" &&     echo 'Postinstall cleanup' &&  (rm -rf \"/usr/bin/hyperkube /usr/bin/etcd /usr/bin/systemd-analyze /usr/share/hwdata/{iab.txt,oui.txt} /etc/profile.d/lang.sh\" &&    yum clean all &&    rpmdb --rebuilddb &&    rpm -q         ca-certificates         e2fsprogs         ceph-common          ceph-mon          ceph-osd         ceph-mds         rbd-mirror          ceph-mgr ceph-mgr-dashboard ceph-mgr-diskprediction-local ceph-mgr-k8sevents ceph-mgr-rook        ceph-grafana-dashboards         kmod         lvm2         gdisk \tsmartmontools \tnvme-cli \tlibstoragemgmt         ceph-radosgw libradosstriper1         nfs-ganesha nfs-ganesha-ceph nfs-ganesha-rgw nfs-ganesha-rados-grace         tcmu-runner ceph-iscsi python-rtslib) && sed -i -e 's/udev_rules = 1/udev_rules = 0/' -e 's/udev_sync = 1/udev_sync = 0/' -e 's/obtain_device_list_from_udev = 1/obtain_device_list_from_udev = 0/' /etc/lvm/lvm.conf && grep -sqo \"udev_sync = 0\" /etc/lvm/lvm.conf && grep -sqo \"udev_rules = 0\" /etc/lvm/lvm.conf && grep -sqo \"obtain_device_list_from_udev = 0\" /etc/lvm/lvm.conf &&     rm -rf         /etc/{selinux,systemd,udev}         /lib/{lsb,udev}         /tmp/*         /usr/lib{,64}/{locale,systemd,udev,dracut}         /usr/share/{doc,info,locale,man}         /usr/share/{bash-completion,pkgconfig/bash-completion.pc}         /var/log/*         /var/tmp/* &&     find  / -xdev -name \"*.pyc\" -o -name \"*.pyo\" -exec rm -f {} \\; &&     if [ -f /usr/bin/ceph-dencoder ]; then gzip -9 /usr/bin/ceph-dencoder; fi &&     bash -c '       function ifstrip () { if compgen -g \"$1\"; then strip -s \"$1\"; fi } &&       ifstrip /usr/lib{,64}/ceph/erasure-code/* &&       ifstrip /usr/lib{,64}/rados-classes/* &&       ifstrip /usr/lib{,64}/python*/{dist,site}-packages/{rados,rbd,rgw}.*.so &&       ifstrip /usr/bin/{crushtool,monmaptool,osdmaptool}' &&     rm -f /usr/lib/ceph/mgr/dashboard/static/AdminLTE-*/plugins/datatables/extensions/TableTools/images/psd/* &&     find /var/log/ -type f -exec truncate -s 0 {} \\; &&     FINAL_SIZE=\"$(bash -c 'sz=\"$(du -sm --exclude=/proc /)\" ; echo \"${sz%*/}\"')\" &&     REMOVED_SIZE=$((INITIAL_SIZE - FINAL_SIZE)) &&     echo \"Cleaning process removed ${REMOVED_SIZE}MB\" &&     echo \"Dropped container size from ${INITIAL_SIZE}MB to ${FINAL_SIZE}MB\" &&     rpm -q         ca-certificates         e2fsprogs         ceph-common          ceph-mon          ceph-osd         ceph-mds         rbd-mirror          ceph-mgr ceph-mgr-dashboard ceph-mgr-diskprediction-local ceph-mgr-k8sevents ceph-mgr-rook        ceph-grafana-dashboards         kmod         lvm2         gdisk \tsmartmontools \tnvme-cli \tlibstoragemgmt         ceph-radosgw libradosstriper1         nfs-ganesha nfs-ganesha-ceph nfs-ganesha-rgw nfs-ganesha-rados-grace         tcmu-runner ceph-iscsi python-rtslib && echo 'Packages verified successfully'"
            ],
            "Image": "sha256:ca31a3810698bf549e113f685f90b9d791e8e91076d601a7e21a3bc546ef213b",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "CEPH_POINT_RELEASE": "",
                "GIT_BRANCH": "HEAD",
                "GIT_CLEAN": "False",
                "GIT_COMMIT": "1257ef51b5b30406696860224274011fa5f0d130",
                "GIT_REPO": "https://github.com/ceph/ceph-container.git",
                "RELEASE": "v4.0.8-stable-4.0",
                "maintainer": "Dimitri Savineau <dsavinea@redhat.com>",
                "org.label-schema.build-date": "20191001",
                "org.label-schema.license": "GPLv2",
                "org.label-schema.name": "CentOS Base Image",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.vendor": "CentOS"
            }
        },
        "DockerVersion": "19.03.5",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "CEPH_VERSION=nautilus",
                "CEPH_POINT_RELEASE="
            ],
            "Cmd": [
                "/bin/bash"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:ca31a3810698bf549e113f685f90b9d791e8e91076d601a7e21a3bc546ef213b",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "CEPH_POINT_RELEASE": "",
                "GIT_BRANCH": "HEAD",
                "GIT_CLEAN": "False",
                "GIT_COMMIT": "1257ef51b5b30406696860224274011fa5f0d130",
                "GIT_REPO": "https://github.com/ceph/ceph-container.git",
                "RELEASE": "v4.0.8-stable-4.0",
                "maintainer": "Dimitri Savineau <dsavinea@redhat.com>",
                "org.label-schema.build-date": "20191001",
                "org.label-schema.license": "GPLv2",
                "org.label-schema.name": "CentOS Base Image",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.vendor": "CentOS"
            }
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 778306740,
        "VirtualSize": 778306740,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/home/.docker_data/overlay2/89bc40ef3ba26fcf2cb445210ea951ea1bdf04154c55baee9a73e9bbd1127ecd/diff",
                "MergedDir": "/home/.docker_data/overlay2/e63ef55bc3917a05677f416cf338530f1219f69b69d48cdccbdf3ea00cca93a1/merged",
                "UpperDir": "/home/.docker_data/overlay2/e63ef55bc3917a05677f416cf338530f1219f69b69d48cdccbdf3ea00cca93a1/diff",
                "WorkDir": "/home/.docker_data/overlay2/e63ef55bc3917a05677f416cf338530f1219f69b69d48cdccbdf3ea00cca93a1/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:77b174a6a187b610e4699546bd973a8d1e77663796e3724318a2a4b24cb07ea0",
                "sha256:39e6ce720a2b46e0396ff90221429fe6642229cc4eddc13c3cda31ed49f7d91f"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]

What you expected to happen:
Containers continue to deploy with `docker run`.

> docker run -d --net=host -v /etc/ceph:/etc/ceph -v /var/lib/ceph/:/var/lib/ceph/ 8d42f9c8f4ae mgr
e84b4f8136f4a30f88fe99036fc0720fcbc4f7f3cbbcae53c14b0b67140f47cb
>

 `docker inspect` lists /opt/ceph-container/bin/entrypoint.sh as an entrypoint.

How to reproduce it (minimal and precise):
docker pull ceph/daemon:v4.0.8-stable-4.0-nautilus-centos-7
docker run -d --net=host -v /etc/ceph:/etc/ceph -v /var/lib/ceph/:/var/lib/ceph/ cc3e177e8486 mgr

**Comment by dsavineau** [comment]
Looks like I wrongly updated the manifest when I tried to fix the variant v8 for arm64 build.

Because the ceph/daemon:v4.0.8-stable-4.0-nautilus-centos-7 manifest is referencing the ceph/daemon-base images not ceph/daemon so you only have the ceph binaries and not all the shell scripts

BTW v4.0.12 is the latest nautilus tag available.

**Comment by dsavineau** [comment]
This is better now https://hub.docker.com/r/ceph/daemon/tags?page=1&name=v4.0.8

```console
# docker inspect docker.io/ceph/daemon:v4.0.8-stable-4.0-nautilus-centos-7 | jq .[].Config.Entrypoint
[
  "/opt/ceph-container/bin/entrypoint.sh"
]
```

Thanks for reporting this.

**Comment by dp4-ms** [comment]
Awesome, thanks :)
