### ISSUE TITLE
operations stuck after docker pause/unpause

### ISSUE THREAD

**Issue by freedge** [ceph/ceph-container#1682]
Is this a bug report or feature request?
* Bug Report

**Bug Report**

What happened:

After enabling the v1 messenger protocol (only one supported by libceph kernel module according to https://tracker.ceph.com/issues/40996?issue_count=1&issue_position=1), mapping a block device and doing IOs on it works just fine. However when performing a docker pause, then an IO, then 10 seconds later a docker unpause on the ceph-container,  half of the time the IO gets stuck in flight. To unblock the IOs I have to restart the whole container.

What you expected to happen:

Expecting operations to "unstuck" themselves following the docker unpause. I am new to ceph and did not expect anything to be honest! docker pause is probably not the thing you run everyday in production, but we do have VMs that experience multiple-seconds freeze in some conditions. What do you think?

How to reproduce it (minimal and precise):
```
# docker  image is ceph/daemon:latest aka 34f50f75d7ef, based on latest commit f0a1ab7ab391aabcf4089445b4123447eab85200
# start the container as documented
docker run -d --name demo -e MON_IP=10.0.2.15 -e CEPH_PUBLIC_NETWORK=10.0.2.15/24 --net=host -v /var/lib/ceph:/var/lib/ceph -v /etc/ceph:/etc/ceph -e CEPH_DEMO_UID=qqq -e CEPH_DEMO_ACCESS_KEY=qqq -e CEPH_DEMO_SECRET_KEY=qqq -e CEPH_DEMO_BUCKET=qqq ceph/daemon demo

# activate messenger v1 protocol..
ceph mon set-addrs localhost [v2:10.0.2.15:3300/0,v1:10.0.2.15:6789]

rbd create foo --size 12 --image-feature layering
 
# map it. This requires the v1 protocol:
sed -e 's@v2:10.0.2.15:3300/0@v1:10.0.2.15:6789@' /etc/ceph/ceph.conf > ceph.conf
rbd -c ceph.conf map foo --name client.admin 
 
# create a file system and mount it..
mkfs.ext4 /dev/rbd0
mkdir /mnt/myceph
mount /dev/rbd0 /mnt/myceph

docker pause demo
echo foo > /mnt/myceph/newfile.1
# in a different window after a dozen of seconds
docker unpause demo
```

After a couple of tries, the IO stays stuck following the unpause, and we observe errors like this on client side:
```
[23161.027100] rbd: rbd0: encountered watch error: -107
```
in the docker image we see stuck operations like:
```
        {
            "description": "osd_op(client.94144.0:77 1.1a 1:5a78ce23:::rbd_data.3712fa39c4c.0000000000000002:head [read 266240~1024] snapc 0=[] ondisk+read+known_if_redirected e188)",
            "initiated_at": "2020-06-07T13:11:06.624621+0000",
            "age": 4571.6001195460003,
```
and logs like
```
2020-06-07T14:27:39.279+0000 7fb029216700  0 log_channel(cluster) log [WRN] : slow request osd_op(client.94144.0:77 1.1a 1:5a78ce23:::rbd_data.3712fa39c4c.0000000000000002:head [read 266240~1024] snapc 0=[] ondisk+read+known_if_redirected e188) initiated 2020-06-07T13:11:06.624621+0000 currently delayed
```

**Environment**:
* OS (e.g. from /etc/os-release): openSUSE Tumbleweed 20200413
* Kernel (e.g. `uname -a`): 5.6.2-1
* Docker version (e.g. `docker version`): 19.03.5
* Ceph version (e.g. `ceph -v`): docker image: ceph version 15.2.3 (d289bbdec69ed7c1f516e0a093594580a76b78d0) octopus (stable)
Client side:
ceph version 15.2.0-108-g8cf4f02b08 (8cf4f02b0814fc5dc803ae5923cb310bb08de967) octopus (stable)

**Comment by dsavineau** [comment]
> Expecting operations to "unstuck" themselves following the docker unpause. I am new to ceph and did not expect anything to be honest! docker pause is probably not the thing you run everyday in production, but we do have VMs that experience multiple-seconds freeze in some conditions. What do you think?

I think you should try this on a real cluster instead of the demo.
For me it doesn't make sense to try to do some IO operation if everything is in pause. That said I've never played with pause/unpause with ceph containers but I'm pretty sure things would be different with a real cluster (mutliple mons and osds).

**Comment by freedge** [comment]
I checked a bit deeper what is happening, wondering if there is any problem below that could have impact on a real cluster... you can reproduce with the ceph master branch with the vstart with one monitor and one OSD "in", by killing the osd with "kill -STOP" and "kill -CONT" to pause/unpause it :D

what is happening:
- when the OSD resumes, it finds it laggy and logs:
```
2020-06-18T23:03:29.671+0200 7f14f6fd0700 10 osd.2 pg_epoch: 34 pg[2.1e( v 34'128 (0'0,34'128] local-lis/les=33/34 n=1 ec=20/20 lis/c=33/29 les/c/f=34/30/0 sis=33 pruub=8.070274459s) [2] r=0 lpr=33 pi=[29,33)/1 crt=34'128 lcod 34'127 mlcod 34'127 active+undersized+degraded mbc={}] 
check_laggy mnow 244.552199518s > readable_until 242.580374009
...
2020-06-18T23:03:29.671+0200 7f14f6fd0700 10 osd.2 pg_epoch: 34 pg[2.1e( v 34'128 (0'0,34'128] local-lis/les=33/34 n=1 ec=20/20 lis/c=33/29 les/c/f=34/30/0 sis=33 pruub=8.070274459s) [2] r=0 lpr=33 pi=[29,33)/1 crt=34'128 lcod 34'127 mlcod 34'127 active+undersized+degraded+laggy mbc={}] check_laggy not readable
2020-06-18T23:03:29.671+0200 7f14f6fd0700 10 osd.2 34 dequeue_op 0x7f152c189d70 finish
```
It is therefore put into a specify queue of operations, "waiting_for_readable"
https://github.com/ceph/ceph/blob/f717065cc8674d67c71a149e4903c2a4740dc624/src/osd/PrimaryLogPG.cc#L820

This queue of operations is supposed to be dequeued by for example, this logic:
https://github.com/ceph/ceph/blob/f717065cc8674d67c71a149e4903c2a4740dc624/src/osd/PeeringState.cc#L1210-L1216

a call to recheck_readable in the case that recalc_readable_until actually finds a change in readable_until. However when there is a single OSD, as it is the case here, the recalc_readable_until will never change the readable_until (that seems to be the min of some value across OSDs).
In that case you get logs like:

```
2020-06-18T23:03:37.675+0200 7f14f5fce700 20 osd.2 pg_epoch: 34 pg[2.1b( empty local-lis/les=33/34 n=0 ec=20/20 lis/c=33/30 les/c/f=34/31/0 sis=33 pruub=9.010799328s) [2] r=0 lpr=33 pi=[30,33)/1 crt=0'0 mlcod 0'0 active+undersized mbc={}] recalc_readable_until readable_until[_ub] 268.558034690s (sent 268.558034690s)
```
that is, there is no change in readable_until, and the ops are never dequeued....

There is another place where the readable_until can change:
```
diff --git a/src/osd/PeeringState.h b/src/osd/PeeringState.h
index 5a765e0301..994faceb53 100644
--- a/src/osd/PeeringState.h
+++ b/src/osd/PeeringState.h
@@ -2014,6 +2014,7 @@ public:
     readable_until_ub_sent = now + readable_interval;
     if (was_min) {
       recalc_readable_until();
+      pl->recheck_readable(); // TODO
     }
   }
```
but in that case, nothing triggers the waiting_for_readable operations to be processed, so I forced a recheck there. So far it seems operations do not get stuck anymore.

I don't know if this could affect any real cluster, but maybe there is something to polish in the single-osd docker container :D feedback is much appreciated.

**Comment by dsavineau** [comment]
> I don't know if this could affect any real cluster, but maybe there is something to polish in the single-osd docker container :D feedback is much appreciated.

That's part of the problem. Using a singe osd in a cluster isn't a good idea.

Also it probably depends on your pg/pool configuration (like pg num, size, etc...) because if you're using the default pool size (3) with a single osd then it doesn't make sense at all
