### ISSUE TITLE
Upgrade to Octopus

### ISSUE THREAD

**Issue by ro0p** [ceph/ceph-container#1695]
Upgrading containers from Nautilus to Octopus fail with the following error:

<pre>mon      | 2020-06-17 01:53:05  /opt/ceph-container/bin/entrypoint.sh: Existing mon, trying to rejoin cluster...
mon      | global_init: error reading config file.</pre>

docker-compose:
<pre>version: '2.1'
services:
  mon:
    image: 'ceph/daemon:latest-[version]'
    container_name: 'mon'
    restart: always
    network_mode: 'host'
    environment:
      - CLUSTER=ceph
      - MON_IP=10.0.241.71
      - CEPH_PUBLIC_NETWORK=10.0.241.0/24
      - CEPH_CLUSTER_NETWORK=10.0.240.0/24
      - NETWORK_AUTO_DETECT=0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/shared/ceph/etc:/etc/ceph
      - /srv/shared/ceph/lib:/var/lib/ceph/
      - /srv/shared/ceph/log:/var/log
    command: ["mon"]</pre>

ceph.conf:
<pre># minimal ceph.conf for a0e84f01-bea6-4785-932b-c7ea2a5fe436
[global]
	fsid = a0e84f01-bea6-4785-932b-c7ea2a5fe436
	mon_host = [v2:10.0.241.71:3300/0,v1:10.0.241.71:6789/0] [v2:10.0.241.72:3300/0,v1:10.0.241.72:6789/0] [v2:10.0.241.73:3300/0,v1:10.0.241.73:6789/0] [v2:10.0.241.74:3300/0,v1:10.0.241.74:6789/0] [v2:10.0.241.75:3300/0,v1:10.0.241.75:6789/0]
	auth_client_required = cephx
	cluster_network = 10.0.240.0/24
	err_to_stderr = true
	err_to_syslog = false
	log_file = /var/log/$cluster-$name.log
	log_flush_on_exit = false
	log_to_sdterr = true
	log_to_syslog = false
	mon_clock_drift_allowed = .15
	mon_cluster_log_file = /var/log/$cluster.log
	mon_cluster_log_to_syslog = false
	osd_journal_size = 100
	public_network = 10.0.241.0/24

[mon]
  mgr_initial_modules = balancer iostat restful status zabbix dashboard
  mon_warn_on_legacy_crush_tunables = false

    [mon.ceph-n01]
      host = ceph-n01
      mon_addr = 10.0.241.71
    [mon.ceph-n02]
      host = ceph-n02
      mon_addr = 10.0.241.72
    [mon.ceph-n03]
      host = ceph-n03
      mon_addr = 10.0.241.73
    [mon.ceph-n04]
      host = ceph-n04
      mon_addr = 10.0.241.74
    [mon.ceph-n05]
      host = ceph-n05
      mon_addr = 10.0.241.75

[client]
    rbd cache = true
    rbd cache writethrough until flush = true

[client.rgw.ceph-n01]
        key = AQCbkPlaus/KGRAA//zuuGsIQFkZqnDwU3eXQg==

[client.rgw.ceph-n02]
        key = AQCbkPla41+SIhAANwpBF9uqwZJRoUEWtHOq5Q==

[client.rgw.ceph-n03]
        key = AQCbkPlajsxRJBAAJfwgg55m1XgBB9BuHb0lYw==

[client.rgw.ceph-n04]
        key = AQCbkPladgkbExAAx6onSJobOYvqbpMBHdVv5Q==

[client.rgw.ceph-n05]
        key = AQCbkPlaQeRuIxAApd15hk3yiYPoFKUkEk2JFQ==

osd_memory_target = 4242538496
osd_memory_base = 2147483648
osd_memory_cache_min = 3195011072</pre>

ceph.conf permissions:
<pre># ls -al ceph.conf
-rw-r--r-- 1 root root 1781 jún   11 09.52 ceph.conf</pre>

All type of containers fail with the same error, switching back to Nautilus everything work fine.
Please lead me the right way how to solve this.

Thank you

**Environment**:
* OS (e.g. from /etc/os-release):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
* Kernel (e.g. `uname -a`):
Linux ceph-n01.mgmt.hu.sic.local 5.7.2-1.el7.elrepo.x86_64 #1 SMP Tue Jun 9 15:37:42 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux

* Docker version (e.g. `docker version`):
Client: Docker Engine - Community
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        42e35e61f3
 Built:             Mon Jun  1 09:13:48 2020
 OS/Arch:           linux/amd64
 Experimental:      false
Server: Docker Engine - Community
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       42e35e61f3
  Built:            Mon Jun  1 09:12:26 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
* Ceph version (e.g. `ceph -v`):
ceph version 14.2.9 (581f22da52345dba46ee232b73b990f06029a2a0) nautilus (stable)

**Comment by dsavineau** [comment]
> Upgrading containers from Nautilus to Octopus fail with the following error:

Could you explain your upgrade procedure ?

**Comment by ro0p** [comment]
Simply changing image name from 'ceph/daemon:latest-nautilus' to 'ceph/daemon:latest-octopus'.
There are no required steps in documentations before upgrading daemons:
https://docs.ceph.com/docs/octopus/install/ceph-deploy/upgrading-ceph/
https://docs.ceph.com/docs/octopus/releases/octopus/

**Comment by dsavineau** [comment]
> Simply changing image name from 'ceph/daemon:latest-nautilus' to 'ceph/daemon:latest-octopus' in compose file

Does that mean you're changing the container image for all nodes at the same time ? because this is supposed to be done serially.

> There are no required steps in documentations before upgrading daemons

There are additional steps for at least OSD and MDS

**Comment by ro0p** [comment]
Of course not. One by one on all nodes in the following order: mon, mgr, osd, all other. The process stucked with the first mon daemon on the first node.

This error message is printed because _conf.parse_config_files_ function fails in _global_pre_init_ function which is called by all daemons at the very beginning, so all my containers fail to start when changing to octopus. Thats why I think something has changed in config file handling, but cannot find any information about it.

**Comment by ro0p** [comment]
Ahhh... There were mixed spaces and tabs in the ceph.conf and wrong indents. My cluster is upgrading now.
Thank you.
