### ISSUE TITLE
jenkins build failure

### ISSUE THREAD

**Issue by ideepika** [ceph/ceph-container#1705]
seeing jenkins build failure for lvm-osd tests not related to PR:

```
[ceph-container-prs-ceph_ansible-lvm_osds] $ /bin/bash /tmp/jenkins4518271555143310014.sh
/tmp/jenkins4518271555143310014.sh: line 5: cd: /home/jenkins-build/build/workspace/ceph-container-prs-ceph_ansible-lvm_osds/ceph-ansible/tests/functional: No such file or directory
Setting status of b27f8f71d6e3d9ae9799e8c0674bccdbf917c83e to FAILURE with url https://2.jenkins.ceph.com/job/ceph-container-prs-ceph_ansible-lvm_osds/198/ and message: 'FAIL - ceph_ansible-lvm_osds
 '
Using context: Testing: ceph_ansible-lvm_osds
Finished: FAILURE
```

**Comment by dsavineau** [comment]
Do you have the full log file ?

`/home/jenkins-build/build/workspace/ceph-container-prs-ceph_ansible-lvm_osds/ceph-ansible/tests/functional: No such file or directory`

This probably means that ceph-ansible project hasn't been cloned correctly

**Comment by ideepika** [comment]
@dsavineau  I am seeing this failure in recent PR: https://github.com/ceph/ceph-container/pull/1704 you can find failure in console logs for it.
