### ISSUE TITLE
smartmontools version < 7.0 osd health check error

### ISSUE THREAD

**Issue by gdtiti** [ceph/ceph-container#1707]
dashboard disk health check tip error
Warning
Smartctl has received an unknown argument (error code -22). You may be using an incompatible version of smartmontools. Version >= 7.0 of smartmontools is required to successfully retrieve data.

osd pod smartmontools is 6.6

**Comment by dsavineau** [comment]
Which container image tag are you using ?

**Comment by gdtiti** [comment]
rook/master   15.2.4

**Comment by dsavineau** [comment]
So the octopus container image is based on CentOS 8 which only provides smartmontools 6.6

I know that some health check using smartmontools requires >= 7.0 but it's not yet available on CentOS 8 whereas it is on CentOS 7.

There an RFE for this targeted for RHEL 8.3 [1] that will be part of CentOS 8.3 but until this happen we can't do anything else.

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1671154
