### ISSUE TITLE
no daemons active

### ISSUE THREAD

**Issue by shanfengbao** [ceph/ceph-container#1710]
Hello ,I deployed the cluster using ceph version 15.2.4 Octopus released.
Now my Mgr service is in active state, but when I execute ceph - s,
"mgr: no daemons active" is still displayed.

`
# systemctl status ceph-mgr@host1
● ceph-mgr@host1.service - Ceph cluster manager daemon
   Loaded: loaded (/usr/lib/systemd/system/ceph-mgr@host1.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2020-07-14 23:05:37 CST; 35min ago
 Main PID: 14819 (ceph-mgr)
   CGroup: /system.slice/system-ceph\x2dmgr.slice/ceph-mgr@host1.service
           └─14819 /usr/bin/ceph-mgr -f --cluster ceph --id host1 --setuser ceph --setgroup ceph

Jul 14 23:05:37 host1 systemd[1]: Started Ceph cluster manager daemon.
Jul 14 23:09:14 host1 systemd[1]: [/usr/lib/systemd/system/ceph-mgr@host1.service:14] Unknown lvalue 'LockPersonality' in section 'Service'
Jul 14 23:09:14 host1 systemd[1]: [/usr/lib/systemd/system/ceph-mgr@host1.service:18] Unknown lvalue 'MemoryDenyWriteExecute' in section 'Service'
Jul 14 23:09:14 host1 systemd[1]: [/usr/lib/systemd/system/ceph-mgr@host1.service:22] Unknown lvalue 'ProtectControlGroups' in section 'Service'
Jul 14 23:09:14 host1 systemd[1]: [/usr/lib/systemd/system/ceph-mgr@host1.service:24] Unknown lvalue 'ProtectKernelModules' in section 'Service'
Jul 14 23:09:14 host1 systemd[1]: [/usr/lib/systemd/system/ceph-mgr@host1.service:25] Unknown lvalue 'ProtectKernelTunables' in section 'Service'

# ceph -s
  cluster:
    id:     8ce01489-b1f8-4d8b-b3d8-9385d1f558fc
    health: HEALTH_OK
 
  services:
    mon: 1 daemons, quorum host1 (age 6h)
    mgr: no daemons active
    osd: 4 osds: 4 up (since 6h), 4 in (since 8h)
 
  data:
    pools:   0 pools, 0 pgs
    objects: 0 objects, 0 B
    usage:   0 B used, 0 B / 0 B avail
    pgs:     
`

**Comment by dsavineau** [comment]
Closing in favor of https://github.com/ceph/ceph-ansible/issues/5549
