### ISSUE TITLE
Ceph Octopus 15.2.4 and iSCSI gateways problem.

### ISSUE THREAD

**Issue by serjponomarev** [ceph/ceph-container#1711]
After installing a clean cluster based on CentOS 8.2 minimal and podman, and adding iscsi gateways, gateways allows you to connect but does not export images.
Also, tcmu-runner does not start in the container and tcmu-runner daemons are not displayed in the cluster status

On the same cluster, iscsi gateways without containers with the same settings and system work without problems.

The iscsi_target_mod module has been added to autoload in both cases.

Test cluster setup:
5 VMs, 2 networks (public/cluster), 3 OSD, 3 mon, 3 mgr, 2 iscsi gw.
Centos 8.2 with the latest updates 
podman version 1.6.4
Ceph 15.2.4 (docker.io/ceph/ceph:v15)
Ceph repo http://download.ceph.com/rpm-15.2.4/el8/
iSCSI repo http://download.ceph.com/ceph-iscsi/3/rpm/el8/
tcmu-runner repo https://3.chacra.ceph.com/r/tcmu-runner/master/9c84f7a4348ac326ac269fbdda507953dba6ec2c/centos/8/flavors/default/$basearch

If you need any logs from cluster - let me know.

**Comment by dsavineau** [comment]
How did you deploy your cluster ?
Are you using any automation tooling ?
Are you currently using the custom entrypoints from ceph-container for starting the services ?

> Also, tcmu-runner does not start in the container
Can you elaborate ?

> tcmu-runner daemons are not displayed in the cluster status
ceph-iscsi (including the api, gw and tcmu-runner services) aren't part of the ceph cluster (ie: it's not a core ceph services) as it's a separate project so it's normal to not see them in the cluster status.

**Comment by serjponomarev** [comment]
> How did you deploy your cluster ?

1. I deployed a mini cluster through cephadm.
2. Added hosts via ceph orch
3. Used the specification for mon and mgr deployment.
4. Added osd via cephadm.
5. Deployed the rbd pool.
6. Used the specification to deploy two iscsi gw.

> Are you using any automation tooling ?

No, only cephadm

> Are you currently using the custom entrypoints from ceph-container for starting the services ?

No
> Can you elaborate ?

I ran / bin/bash in running containers through podman exec -it and did not find the tcmu-runner process (ps aux | grep tcmu) there.
> ceph-iscsi (including the api, gw and tcmu-runner services) aren't part of the ceph cluster (ie: it's not a core ceph services) as it's a separate project so it's normal to not see them in the cluster status.

Yes, I know, but in the "working" configuration, tcmu-runner appears in the output of ceph -s

**Comment by dsavineau** [comment]
> No, only cephadm

So that's not a problem from ceph-container but cephadm.

> I ran / bin/bash in running "iscsi-gw" containers through podman exec -it and did not find the tcmu-runner process (ps aux | grep tcmu) there

Because cephadm doesn't use tcmu-runner (as opposed to ceph-ansible).

> Yes, I know, but in the "working" configuration, tcmu-runner appears in the output of ceph -s

I don't understand what the "working configuration mean but I've never seen tcmu-runner and iscsi services reported in the ceph status.

**Comment by serjponomarev** [comment]
> I don't understand what the "working configuration mean but I've never seen tcmu-runner and iscsi services reported in the ceph status.

A “working” configuration is a containerless configuration.

> I don't understand what the "working configuration mean but I've never seen tcmu-runner and iscsi services reported in the ceph status.

here is an example of my working cluster with ceph -s output

`ceph version 14.2.7 (3d58626ebeec02d8385a4cefb92c6cbc3a45bfe8) nautilus (stable)`

ceph -s
```
  cluster:
    id:     00000000-0000-0000-0000-000000000000
    health: HEALTH_OK
 
  services:
    mon:         3 daemons, quorum ceph-mon-01,ceph-mon-02,ceph-mon-03 (age 7d)
    mgr:         ceph-mon-03(active, since 7d), standbys: ceph-mon-02, ceph-mon-01
    osd:         20 osds: 20 up (since 7d), 20 in (since 10M)
    tcmu-runner: 20 daemons active (ceph-igw-01:rbd/storage-01, ceph-igw-01:rbd/storage-02, ceph-igw-01:rbd/storage-03, ceph-igw-01:rbd/storage-04, ceph-igw-01:rbd/storage-05, ceph-igw-01:rbd/storage-06, ceph-igw-01:rbd/storage-07, ceph-igw-01:rbd/storage-08, ceph-igw-01:rbd/storage-09, ceph-igw-01:rbd/storage-10, ceph-igw-02:rbd/storage-01, ceph-igw-02:rbd/storage-02, ceph-igw-02:rbd/storage-03, ceph-igw-02:rbd/storage-04, ceph-igw-02:rbd/storage-05, ceph-igw-02:rbd/storage-06, ceph-igw-02:rbd/storage-07, ceph-igw-02:rbd/storage-08, ceph-igw-02:rbd/storage-09, ceph-igw-02:rbd/storage-10)
```

**Comment by dsavineau** [comment]
> A “working” configuration is a containerless configuration.

Again, it's not coming from the container image itself but the automation tool consuming it, in your case cephadm.

So I'll suggest you to open a bug on the ceph tracker for this.

https://tracker.ceph.com/projects/orchestrator

Because cephadm doesn't start tcmu-runner when scheduling a iscsi service, only the rbd-target-api daemon.
