### ISSUE TITLE
missing 'type' file and unable to infer osd type

### ISSUE THREAD

**Issue by caihexin** [ceph/ceph-container#1715]
# docker run -it --net=host --name=osd --privileged=true --pid=host -e OSD_TYPE=directory -v `pwd`/etc/ceph:/etc/ceph -v `pwd`/var/lib/ceph/:/var/lib/ceph  ceph/daemon osd_directory

2020-08-02 11:32:13  /opt/ceph-container/bin/entrypoint.sh: static: does not generate config
ceph-6: /usr/bin/ceph-osd --cluster ceph -f -i 6 --osd-journal /var/lib/ceph/osd/ceph-6//journal -k /var/lib/ceph/osd/ceph-6//keyring
2020-08-02 11:32:13  /opt/ceph-container/bin/entrypoint.sh: SUCCESS
exec: PID 105097: spawning /usr/local/bin/forego start -f /etc/forego/ceph/Procfile
exec: Waiting 105097 to quit
forego   | starting ceph-6.1 on port 5000
ceph-6.1 | 2020-08-02T11:32:14.058+0000 7f76a8b01f40 -1 missing 'type' file and unable to infer osd type
teardown: managing teardown after SIGCHLD
teardown: Waiting PID 105097 to terminate 
teardown: Process 105097 is terminated
teardown: Bye Bye, container will die with return code 0

**Comment by ChaosD** [comment]
So sad. I have the same problem when I deploy ceph cluster manully.

**Comment by darxkies** [comment]
The following command in file /opt/ceph-container/bin/osd_directory.sh fails:
`
ceph-osd --cluster "${CLUSTER}" -i "${OSD_ID}" --mkfs --osd-uuid "${UUID}" --mkjournal --osd-journal "${OSD_J}" --setuser ceph --setgroup ceph
`

The command switches to user ceph and group ceph and it can not access the file /var/lib/ceph/osd/ceph-0/keyring which can be accessed only by the user root.

`
-rw------- 1 ceph ceph 56 Aug 17 18:16 /var/lib/ceph/osd/ceph-0/keyring
`

**Comment by dsavineau** [comment]
> The command switches to user ceph and group ceph and it can not access the file /var/lib/ceph/osd/ceph-0/keyring which can be accessed only by the user root.
> 
> `-rw------- 1 ceph ceph 56 Aug 17 18:16 /var/lib/ceph/osd/ceph-0/keyring`

The keyring is 600 with ceph:ceph user/group so why only the root user could have access to this file ? I don't see why the ceph user isn't able to use this.

**Comment by darxkies** [comment]
You are right. It should be working and my statement about the root user is wrong. 

I get this error:

`
-1 auth: unable to find a keyring on /var/lib/ceph/osd/ceph-0/keyring: (13) Permission denied
`

**Comment by darxkies** [comment]
Changing the permissions of the keyring file or removing --setuser ceph --setgroup ceph prevents the error.

**Comment by darxkies** [comment]
The whole osd_directory.sh script basically boils down to this and the keyring is owned by root:

```
[root@single-node bin]# export OSD_BOOTSTRAP_KEYRING=/var/lib/ceph/bootstrap-osd/ceph.keyring

[root@single-node bin]# export CLUSTER=ceph

[root@single-node bin]# export UUID=$(uuidgen)

[root@single-node bin]# export OSD_SECRET=$(ceph-authtool --gen-print-key)

[root@single-node bin]# export OSD_ID=$(echo "{\"cephx_secret\": \"${OSD_SECRET}\"}" | ceph --cluster "${CLUSTER}" osd new "${UUID}" -i - -n client.bootstrap-osd -k "$OSD_BOOTSTRAP_KEYRING")
2020-08-19T04:47:49.019+0000 7f7e38fcd700 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.bootstrap-osd.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory
2020-08-19T04:47:49.019+0000 7f7e38fcd700 -1 AuthRegistry(0x7f7e34058f08) no keyring found at /etc/ceph/ceph.client.bootstrap-osd.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,, disabling cephx

[root@single-node bin]# export OSD_PATH="/var/lib/ceph/osd/ceph-$OSD_ID/"

[root@single-node bin]# export OSD_J="$OSD_PATH/journal"

[root@single-node bin]# export OSD_KEYRING="${OSD_PATH}"/keyring

[root@single-node bin]# 

[root@single-node bin]# mkdir -p "$OSD_PATH"

[root@single-node bin]# chown ceph. "$OSD_PATH"

[root@single-node bin]# ceph-authtool --create-keyring "${OSD_PATH}"/keyring --name osd."${OSD_ID}" --add-key "${OSD_SECRET}"
creating /var/lib/ceph/osd/ceph-13//keyring
added entity osd.13 auth(key=AQD0rjxfYWQCORAANw1ibzhzZZ9iqOHsTzzlkg==)

[root@single-node bin]# ls -l $OSD_KEYRING
-rw------- 1 root root 57 Aug 19 04:47 /var/lib/ceph/osd/ceph-13//keyring

[root@single-node bin]# 

[root@single-node bin]# ceph-osd --cluster "${CLUSTER}" -i "${OSD_ID}" --mkfs --osd-uuid "${UUID}" --mkjournal --osd-journal "${OSD_J}" --setuser ceph --setgroup ceph
2020-08-19T04:47:49.235+0000 7fb6bfd8af00 -1 auth: unable to find a keyring on /var/lib/ceph/osd/ceph-13/keyring: (13) Permission denied
2020-08-19T04:47:49.235+0000 7fb6bfd8af00 -1 auth: unable to find a keyring on /var/lib/ceph/osd/ceph-13/keyring: (13) Permission denied
2020-08-19T04:47:49.235+0000 7fb6bfd8af00 -1 auth: unable to find a keyring on /var/lib/ceph/osd/ceph-13/keyring: (13) Permission denied
2020-08-19T04:47:49.235+0000 7fb6bfd8af00 -1 monclient: keyring not found
failed to fetch mon config (--no-mon-config to skip)

[root@single-node bin]# ls -l $OSD_KEYRING
-rw------- 1 root root 57 Aug 19 04:47 /var/lib/ceph/osd/ceph-13//keyring

[root@single-node bin]# 

[root@single-node bin]# /usr/bin/ceph-osd --cluster ceph -f -i ${OSD_ID} --osd-journal ${OSD_J} -k $OSD_KEYRING
2020-08-19T04:47:49.255+0000 7fa09f5f2f00 -1 missing 'type' file and unable to infer osd type

[root@single-node bin]# ls -l $OSD_KEYRING
-rw------- 1 root root 57 Aug 19 04:47 /var/lib/ceph/osd/ceph-13//keyring
```

**Comment by darxkies** [comment]
According to strace, in Ceph 14.2.9 setuid and setgid are called after the keyring file is read (3 times). In Ceph 15.2.3 the setuid and setgid are read before the keyring is opened, and as only root can access the file, ceph-osd fails.

The ownership of the keyring is changed by create_mandatory_directories. If the directory /var/lib/ceph is mounted by all containers, as suggested by the README file, then some other container changes the osd keyring ownership probably in the last line of the function create_mandatory_directories, which is pretty confusing.

I think the easiest way of fixing this is to add `chown ceph:ceph "${OSD_PATH}"/keyring` here: https://github.com/ceph/ceph-container/blob/master/src/daemon/osd_scenarios/osd_directory.sh#L43
