### ISSUE TITLE
docker ceph/daemon demo mode gone?

### ISSUE THREAD

**Issue by oxy-gendotmobi** [ceph/ceph-container#1716]
The docker image mentioned here does not seem to have the demo option anymore?
https://hub.docker.com/r/ceph/daemon

as mentioned for example here:
https://javiermunhoz.com/blog/2018/03/23/ceph-rgw-s3-demo-container-technical-notes.html 

Or how should I start it in demo mode since there is no log created nor output generated besides the docker hash after "start" and running for 2 seconds.

**Comment by dsavineau** [comment]
As far as I know the demo entrypoint is still present. That's what we use in the CI for testing PR.

> Or how should I start it in demo mode since there is no log created nor output generated besides the docker hash after "start" and running for 2 seconds.

How do you start the container ?

If you want an exemple you can check [1]

[1] https://github.com/ceph/ceph-container/blob/master/.travis.yml#L25

**Comment by oxy-gendotmobi** [comment]
Ok, and the main idea is the docker container only runs processes with the root user and no "normal users" are able to ssh into the docker container(s) and execute commands?

**Comment by dsavineau** [comment]
> Ok, and the main idea is the docker container only runs processes with the root user and no "normal users" are able to ssh into the docker container(s) and execute commands?

I'm not sure to understand what you mean but there's no ssh involved in the ceph container.

**Comment by oxy-gendotmobi** [comment]
Ok, I close this one since it seems the demo option is present and in the running container only one user "root" is used.
