### ISSUE TITLE
I started Ceph mon with Docker, but did not generate a configuration file

### ISSUE THREAD

**Issue by zhangtiedong0912** [ceph/ceph-container#1719]
Is this a bug report or feature request?
* Bug Report

**Bug Report**

What happened:
`docker run -itd --net=host  --name=mon -v /private/etc/ceph:/private/etc/ceph -v /private/var/lib/ceph/:/private/var/lib/ceph -e MON_IP=192.168.0.100 -e CEPH_PUBLIC_NETWORK=192.168.0.0/24 ceph/daemon mon
`
`docker logs mon`
`creating /etc/ceph/ceph.client.admin.keyring
creating /etc/ceph/ceph.mon.keyring
monmaptool: monmap file /etc/ceph/monmap-ceph
monmaptool: set fsid to 3c58b8a0-da7b-4293-b3cd-1fb2062d543e
monmaptool: writing epoch 0 to /etc/ceph/monmap-ceph (1 monitors)`

**No files are generated under this path /etc/ceph/**
What you expected to happen:

How to reproduce it (minimal and precise):

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`): Darwin ITCN000360-MAC 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 18 20:50:10 PDT 2020; root:xnu-4903.278.43~1/RELEASE_X86_64 x86_64
* Docker version (e.g. `docker version`):Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
* Ceph version (e.g. `ceph -v`):

**Comment by dsavineau** [comment]
```console
docker run -itd --net=host --name=mon -v /private/etc/ceph:/private/etc/ceph -v /private/var/lib/ceph/:/private/var/lib/ceph -e MON_IP=192.168.0.100 -e CEPH_PUBLIC_NETWORK=192.168.0.0/24 ceph/daemon mon
```

Why are you using the target bindmount in /private inside the container ?

This should be more something like `-v /private/etc/ceph:/etc/ceph -v /private/var/lib/ceph/:/var/lib/ceph`

**Comment by zhangtiedong0912** [comment]
`sudo docker run -itd --net=host --name=mon -v /private/etc/ceph:/etc/ceph -v /private/var/lib/ceph/:/var/lib/ceph -e MON_IP=192.168.0.100 -e CEPH_PUBLIC_NETWORK=192.168.0.0/24 ceph/daemon mon`
I generated the configuration file the way you did, but there was a new error，

`creating /etc/ceph/ceph.client.admin.keyring
creating /etc/ceph/ceph.mon.keyring
monmaptool: monmap file /etc/ceph/monmap-ceph
monmaptool: set fsid to b651bc3b-967b-47c2-b2d5-091d96125f63
monmaptool: writing epoch 0 to /etc/ceph/monmap-ceph (1 monitors)
importing contents of /etc/ceph/ceph.client.admin.keyring into /etc/ceph/ceph.mon.keyring
2020-09-03T06:58:45.061+0000 7fda841d8700 -1 unable to find any IP address in networks '192.168.0.0/24' interfaces ''`

**Comment by dsavineau** [comment]
Do you have the ip address `192.168.0.100` present on the host ?

**Comment by zhangtiedong0912** [comment]
`ifconfig | grep "inet"`
`
	inet 127.0.0.1 netmask 0xff000000
	inet6 ::1 prefixlen 128
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1
	inet6 fe80::aede:48ff:fe00:1122%en5 prefixlen 64 scopeid 0x8
	inet6 fe80::10e1:e336:54b3:cdce%en0 prefixlen 64 secured scopeid 0xe
	inet 192.168.0.100 netmask 0xffffff00 broadcast 192.168.0.255
	inet6 fe80::487:a3ff:fec5:8889%awdl0 prefixlen 64 scopeid 0x10
	inet6 fe80::b4c5:4df9:2e95:7352%utun0 prefixlen 64 scopeid 0x12
	inet 10.6.25.137 --> 10.6.25.137 netmask 0xfffffc00`


`cat /etc/hosts`
`##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost
192.168.0.100   localhost`

Is that right?
