### ISSUE TITLE
Generating ssh key fail

### ISSUE THREAD

**Issue by bamboox** [ceph/ceph-container#1720]
Is this a bug report or feature request?
* Bug Report
/usr/bin/ssh-keygen -C ceph-ff5bdd70-ecfa-11ea-9bbd-00163e022a22 -N '' -f /tmp/key 
Failed to seed from getrandom: Function not implemented

**Bug Report**

What happened:

What you expected to happen:

How to reproduce it (minimal and precise):

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Docker version (e.g. `docker version`):
* Ceph version (e.g. `ceph -v`):

**Comment by dsavineau** [comment]
So how is this related to the ceph-container project ?

Because this issue lacks of information.
