### ISSUE TITLE
Sending SIGHUP to Ceph process

### ISSUE THREAD

**Issue by clwluvw** [ceph/ceph-container#1734]
Is this a bug report or feature request?
* Bug Report

**Bug Report**
Can't send `SIGHUP` to Ceph process to reopen logs in `log-to-file` mode.
What happened:
`entrypoint.sh` is PID 1 and `docker kill` sends signal to entrypoint script.
What you expected to happen:
Sending SIGHUP signal to container to reopen logs.

**Environment**:
* Ceph version (e.g. `ceph -v`): `14.2.9`

**Comment by clwluvw** [comment]
unstale please

**Comment by clwluvw** [comment]
unstale please

**Comment by nakato** [comment]
This sounds similar to an issue I had at #1470

**Comment by clwluvw** [comment]
unstale please
