### ISSUE TITLE
Define required capabilities

### ISSUE THREAD

**Issue by nazar-pc** [ceph/ceph-container#174]
It is dangerous to run containers as privileged. I understand that this is easy and straightforward, but this is eventually wrong way in many cases.
Often you just need some capabilities from the list here: https://docs.docker.com/engine/reference/run/#runtime-privilege-linux-capabilities-and-lxc-configuration, but not the privileged mode.
Would be nice if you can define which capabilities are necessary and specify them in readme instead of `--privileged`.

**Comment by leseb** [comment]
Thanks for the input, we really need to give it a try.

**Comment by galexrt** [comment]
For usage on Kubernetes, the `privileged` option should be replaced with [Kubernetes Capabilites](https://kubernetes.io/docs/api-reference/v1/definitions/#_v1_capabilities) in the `securityContext` in the manifests.
