### ISSUE TITLE
[mgr/prometheus] ENGINE Error in HTTPServer.tick

### ISSUE THREAD

**Issue by krisstoffe** [ceph/ceph-container#1748]
**Bug Report**

In a large Ceph cluster with a number of OSDs > 1000, the Prometheus module in MGR loops with a Python3 "cheroot" error :

```
ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/lib/python3.6/dist-packages/cheroot/server.py", line 1770, in serve
    self.tick()
  File "/usr/lib/python3.6/dist-packages/cheroot/server.py", line 1993, in tick
    conn = self.connections.get_conn(self.socket)
  File "/usr/lib/python3.6/dist-packages/cheroot/connections.py", line 142, in get_conn
    rlist, _, _ = select.select(list(socket_dict), [], [], 0.1)
ValueError: filedescriptor out of range in select()
```
Dashboard and Prometheus in MGR hanged while the above error loops at a very high rate.

Updating "cheroot" with a more recent version (>= 8.4.0 with a pip3 one-liner inside the container) solves the issue (dashboard and prometheus modules have to be disabled and re-enabled). Of course, the fix does not survive a container restart.

Related [cheroot issue](https://github.com/cherrypy/cheroot/issues/249).

I tried to make a [bug report on ceph tracker](https://tracker.ceph.com/issues/47875) without success so far.

**Environment**:
* Ceph container image : ceph/daemon:v5.0.3-stable-5.0-octopus-centos-8

**Comment by dsavineau** [comment]
If the issue is coming from cheroot python library then we need to wait until a more recent version is available in EPEL 8 (8.2.1 at the moment).

There's nothing we can do in ceph-container because we don't use pip inside the container, only packages.

I can see from the cheroot issue reported that some people have tried a workaround by reducing the max opened file limit (soft).

By default, containers (either via docker or podman) are using high ulimit values (espcially nofile) without could cause that issue.

```console
$ docker run --rm  centos:8 ulimit -Sn
1048576
$ docker run --rm  centos:8 ulimit -Hn
1048576
```

When using ceph via the packages then the default ulimit nofile values are lower (1024:4096) than the one from the container (depending on the OS).

If you're able to reproduce the issue easily then I would suggest to try using the ulimit parameter with your container engine on the ceph mgr container.

```console
$ docker run --rm --name ceph-mgr --ulimit nofile=1024:4096 ....
```

**Comment by ormandj** [comment]
This also impacts us, and the mgr container stops emitting logs entirely (this goes beyond just impacting prometheus/dashboard functionality). The workaround does not appear to work (attempting to set ulimit with --ulimit for Rodman for NOFILE to 1024 via the unit.run file) as the ulimit seems to be overridden during the spawning of the container, at least with podman.

I don't have the ability to submit reports for RHEL, that I am aware of, so have no way to get this corrected (back ported) upstream into RHEL8, even though the bug in cheroot 8.2.1 (or anything less than 8.4.0) is relatively severe and breaking. Perhaps the container build can be updated to account for this issue until upstream is fixed? We've seen this on a cluster with 504 OSDs, so it's not just very large clusters, and running without prometheus metrics isn't really an option for production clusters, unfortunately.

**Comment by dsavineau** [comment]
> This also impacts us. The workaround does not appear to work (attempting to set ulimit with --ulimit for podman for NOFILE to 1024 via the unit.run file) as the ulimit seems to be overridden during the spawning of the container, at least with podman.

As you mentioned unit.run file then I assume you're using cephadm but anyway this shouldn't impact the ulimit option.

```console
# grep 'Max open files' /proc/$(pgrep ceph-mgr)/limits 
Max open files            1048576              1048576              files
# vi /var/lib/ceph/3192df2c-38c9-11eb-a153-fa163ed0319a/mgr.cephaio.yiclmq/unit.run
(adding --ulimit nofile=1024:4096 in the unit)
# grep ulimit /var/lib/ceph/3192df2c-38c9-11eb-a153-fa163ed0319a/mgr.cephaio.yiclmq/unit.run
/bin/podman run --rm --ulimit nofile=1024:4096 --net=host --ipc=host --name ceph-3192df2c-38c9-11eb-a153-fa163ed0319a-mgr.cephaio.yiclmq -e CONTAINER_IMAGE=docker.io/ceph/ceph:v15 -e NODE_NAME=cephaio -v /var/run/ceph/3192df2c-38c9-11eb-a153-fa163ed0319a:/var/run/ceph:z -v /var/log/ceph/3192df2c-38c9-11eb-a153-fa163ed0319a:/var/log/ceph:z -v /var/lib/ceph/3192df2c-38c9-11eb-a153-fa163ed0319a/crash:/var/lib/ceph/crash:z -v /var/lib/ceph/3192df2c-38c9-11eb-a153-fa163ed0319a/mgr.cephaio.yiclmq:/var/lib/ceph/mgr/ceph-cephaio.yiclmq:z -v /var/lib/ceph/3192df2c-38c9-11eb-a153-fa163ed0319a/mgr.cephaio.yiclmq/config:/etc/ceph/ceph.conf:z --entrypoint /usr/bin/ceph-mgr docker.io/ceph/ceph:v15 -n mgr.cephaio.yiclmq -f --setuser ceph --setgroup ceph --default-log-to-file=false --default-log-to-stderr=true --default-log-stderr-prefix="debug "
# systemctl restart ceph-3192df2c-38c9-11eb-a153-fa163ed0319a@mgr.cephaio.yiclmq.service
# grep 'Max open files' /proc/$(pgrep ceph-mgr)/limits 
Max open files            1024                 4096                 files
```

Also it was a suggested workaround, I'm not even sure this will prevent to hit the issue.

> I don't have the ability to submit reports for RHEL, that I am aware of, so have no way to get this corrected (back ported) upstream into RHEL8, even though the bug in cheroot 8.2.1 (or anything less than 8.4.0) is relatively severe and breaking. 

RHEL and underlying products like RHCS (for ceph) don't ship cheroot package so they aren't exposed to the issue for either Nautilus (RHCS 4) and Pacific (RHCS 5) releases.
That's because they are still shipping cherrypy 8.9 (compared to 18.4 on EPEL) so it was before the split between cherrypy and cheroot components.

> Perhaps the container build can be updated to account for this issue until upstream is fixed? We've seen this on a cluster with 504 OSDs, so it's not just very large clusters, and running without prometheus metrics isn't really an option for production clusters, unfortunately.

As I mentioned earlier, this could only happen if the package in EPEL is updated, we don't use pip at all. But nothing is preventing you to rebuild the current image and update the cheroot version on your own.

**Comment by ormandj** [comment]
@dsavineau I was able to confirm the option as you listed worked for the ceph-mgr process. We will try this out, and see if it resolves things. I would still make a strong case this has broken ceph deployed via cephadm in containers as metrics are a core function of a production cluster, and if EPEL8 isn't updated (yet - see Ceph-users mailing list re: movement there) then there should be some form of fix deployed for these containers as released to the public until the upstream EPEL8 package is updated. Again, thank you for your efforts and time on this issue.

**Comment by ormandj** [comment]
We implemented this change last night, and on our test cluster of 504 OSDs, being polled by the internal prometheus and our external instance, the mgrs stopped responding and dropped out of the cluster entirely. This is impacting not just metrics, but the mgr itself.

**Comment by dimm0** [comment]
Still no fix? Has anyone built a temporary fixed container?

**Comment by ormandj** [comment]
Yes, we built containers for ours based on the existing containers but with the newer cheroot package in the PR mentioned above, and it resolved the issue.

**Comment by ormandj** [comment]
The updated cheroot package has been pushed to EPEL8 stable: https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2021-e204b1c101

@dsavineau Will this be included in the next container build?

**Comment by dsavineau** [comment]
Yes the updated cheerot package will be automatically included during the next container rebuild (probably 15.2.9)

**Comment by dsavineau** [comment]
BTW until `ceph/ceph:v15.2.9` container tag you can use `ceph/daemon-base:latest-octopus`

```console
$ docker run --rm ceph/daemon-base:latest-octopus ceph --version
ceph version 15.2.8 (bdf3eebcd22d7d0b3dd4d5501bee5bac354d5b55) octopus (stable)
$ docker run --rm ceph/daemon-base:latest-octopus rpm -q python3-cheroot
python3-cheroot-8.5.1-1.el8.noarch
```

The only thing you need to know is that latest-octopus tag could change over the time so be careful.

**Comment by ormandj** [comment]
Thank you for the helpful tip. We're waiting on 15.2.9 since it will (hopefully) include our [patch](https://github.com/ceph/ceph/pull/38677) for the threading/GIL deadlock situation, as well. We'll keep this in our back pocket in the future vs. building our own containers.
