### ISSUE TITLE
Accessing dashboard SSO via reverse proxy

### ISSUE THREAD

**Issue by samsonhyt** [ceph/ceph-container#1759]
What happened:

I have set up a Ceph cluster on Kubernetes with Rook, we have SSL offloading outside Kubernetes so we config the Ceph dashboard with SSL false.

After we enable SSO with the following command
```sh
ceph dashboard sso setup saml2 https://<hostname> <metadata.xml>
```
ceph successfully redirect to our SAML server, but the RelayState of the SAML request is `http://<hostname>/auth/saml2/login` instead of `https://<hostname>/auth/saml2/login` 
As the result, SAML login failed with message 
```json
{"is_authenticated": false, "errors": ["invalid_response"], "reason": "The response was received at http://<hostname>/auth/saml2 instead of https://<hostname>/auth/saml2"}
```

I have also try tho setup saml2 with hostname http://<hostname>, but the SAML server (ADFS) don't allow us the use http for login endpoint.

What you expected to happen:

Able to tell Ceph to set the RelayState protocol to HTTPS

How to reproduce it (minimal and precise):

Dockerfile I use to install python3-saml to the container

```Dockerfile
FROM ceph/ceph:v15.2.5
RUN dnf install -y python3-xmlsec
RUN yes | pip3 install python3-saml
```

**Environment**:
* OS (e.g. from /etc/os-release): Red Hat Enterprise Linux Atomic Host 7.7.2
* Kernel (e.g. `uname -a`): 3.10.0-1062.4.1.el7.x86_64
* Docker version (e.g. `docker version`): 1.13.1
* Ceph version (e.g. `ceph -v`): 15.2.5

**Comment by dsavineau** [comment]
I dont think this is related to container at all so you should open this bug on the ceph tracker.

However, note that python3-saml is now present in EPEL 8 and will be included by default starting 15.2.6.
No need to install it via pip anymore.
