### ISSUE TITLE
Deploy an OSD on LVM

### ISSUE THREAD

**Issue by R-omk** [ceph/ceph-container#177]
LVM very handy tool with small overhead.
It seems to me a good idea to integrate the ability to deploy journal and storage on specified volume 
`-e OSD_DEVICE=/dev/mapper/vg1-lvosd`
This can be useful to share the resources of one disk for different containers, but ceph does not support deploy on lvm out of box

**Comment by Ulexus** [comment]
While we could add a feature for this, that's definitely not a recommended use-case.  The journal should be separate from the OSD for a reason (performance).

**Comment by r-omk** [comment]
I know it, but I plan to use  vg group on SSD for journal  and other vg group  for data  on SATA drive.
My servers have two of each type of drive (ssd & sata), I just want to wisely allocate resources between different containers.

**Comment by r-omk** [comment]
lvm makes it very convenient to dynamically add disk size, it is very useful
just  
```
lvresize -L+20G /dev/mapper/vgname-lvname
resize2fs /dev/mapper/vgname-lvname    (or xfs_growfs for xfs)

```

**Comment by Ulexus** [comment]
The journal to SSD and the data to SATA is a common plan, and I wouldn't find fault with that.  Using the disks as shared between other uses is where I have a problem, and at that point, I fail to see the value of throwing LVM into the mix.  Logical abstractions and on-the-fly resizings don't have much value when you're using the entire disk to begin with, and spanning multiple disks is better achieved with separate OSDs.

Again, your use case is your thing; it just isn't a recommended practice I would want to formalize in the tooling.

**Comment by leseb** [comment]
You can always keep the journal on a raw device and use `sgdisk` to create tiny partitions. As for the VG for the OSD data, I don't understand the use case, unless you do some kind of hyperconverged/collocation on those disks. I believe you can still use the `osd_directory` scenario and prepare your LV manually before that. What do you think?

**Comment by R-omk** [comment]
I have no raw drives at all.  I have several host servers with vg groups for kvm virtualization, LVM works very well.
I did it manually couple years ago, something like :

```
(Drive RAW host machine) -> VG(vgSSD & vgSATA) ( for all guests and hosts root partition) -> lv (for KVM )  -> raw|vg -> lv (in KVM for OSD)
```

It's work! Lvm do it very flexible.

So, I still do it manually with docker, but it's DOCKER =) It may just work.
I'll have to mix KVM virtualization and docker on the same machine. And I won't give up the convenience of using LVM.

**Comment by Ulexus** [comment]
Yes, LVM is useful for that kind dynamic abstraction.  It doesn't really make sense for an OSD, though.  Ceph is very sensitive to multiple access on disks.  You will destroy your performance by trying to share the physical drive with anything else.  An OSD's relationship to the underlying disk is very different from that of a nicely cached and abstracted OS or KVM store.

You'll see mentioned everywhere in the Ceph documentation to separate your OSDs from everything else.  Dedicated boxes for OSDs are highly recommended.

Anyway, what you're assembling will probably "work", but no one anywhere is going to recommend it.

**Comment by leseb** [comment]
All I've read is valid. I'm not really again another scenario to deploy OSDs on LVM. However, currently time is what I miss the most, so this might happen eventually but definitely not this year...

**Comment by timmjd** [comment]
With a LVM parititon:
`Could not locate appropriate symlink for partition 1 of /dev/vgroot/ceph`
Any workaround for this? How to get the OSD container running with an LVM?

**Comment by leseb** [comment]
@timmjd once we implement the support for ceph-volume. We will work on that soon.
