### ISSUE TITLE
What is the difference between ceph/ceph and ceph/daemon repositories on hub.docker.com?

### ISSUE THREAD

**Issue by opengers** [ceph/ceph-container#1774]
On https://hub.docker.com:
Description of `ceph/ceph` ：Images containing all Ceph binaries.
Description of `ceph/daemon`: Image containing all the Ceph daemons 

On https://github.com/ceph/ceph-container/blob/master/README.md:
> Core Components
> - ceph/daemon-base: Base container image containing Ceph core components.
> - ceph/daemon: All-in-one container containing all Ceph daemons.

I want to figure out what is the difference between them, thanks

**Comment by dsavineau** [comment]
> Description of ceph/ceph ：Images containing all Ceph binaries.

You only have the ceph binaries

> Description of ceph/daemon: Image containing all the Ceph daemons

You have the ceph binaries + custom bash scripts

https://github.com/ceph/ceph/blob/master/doc/install/containers.rst
