### ISSUE TITLE
Build octopus image based on centos7 instead of centos8

### ISSUE THREAD

**Issue by yanchicago** [ceph/ceph-container#1784]
Is this a bug report or feature request?
* Feature Request

**Feature Request**

CentOS 8 has been declared the last downstream release that will be supported until December 2021.
Could octopus be bulit upon centos7?

Are there any similar features already existing:

What should the feature do:
Support centos7 based Octopus image

What would be solved through this feature:

Does this have an impact on existing features:

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Docker version (e.g. `docker version`):
* Ceph version (e.g. `ceph -v`):

**Comment by dsavineau** [comment]
CentOS 7 is not fully supported with Octopus due to missing python3 dependencies.

The decision hasn't been made yet but I think there's more chance to switch to either CentOS stream or UBI 8 container images rather than using CentOS 7 unless alternative like AlmaLinux or RockyLinux are available.

**Comment by yanchicago** [comment]
It seems a discussion is ongoing related to continued centos8 support. Any tentative date with a decision made? 
Is it possible to pulling python3 dependencies to build centos7 based image?
