### ISSUE TITLE
Rook Ceph image vulnerabilities

### ISSUE THREAD

**Issue by damiancahill** [ceph/ceph-container#1791]
Hi Product Security Team,
I have recently used [Harbor](https://goharbor.io/) to perform a security scan on the Rook Ceph image rook/ceph:v1.5.4. 
 
The Harbor scan reported a total of 227 vulnerabilities in the image. The following is a breakdown of these by severity
4 Critical
5 High
118 Medium
100 Low
 
The complete list of CVEs is attached. [rook_ceph_v1_5_4.zip](https://github.com/ceph/ceph-container/files/5842055/rook_ceph_v1_5_4.zip)
 
Is there a plan to have these addressed in upcoming releases? Can you share details of this?
One of our customers is pushing to have all Critical and High vulnerabilities addressed before going live with the solution. They are using rook ceph as their storage option.
 
Running the scan on ceph/ceph:v15.2.8 reveals the same set of vulnerabilities.

**Comment by dsavineau** [comment]
> The Harbor scan reported a total of 227 vulnerabilities in the image. The following is a breakdown of these by severity

Harbor uses Trivy as vulnerability scan tool.

See my comment on that at [1]

[1] https://github.com/ceph/ceph-container/issues/1779#issuecomment-758014623
