### ISSUE TITLE
OSD failed after docker upgrade

### ISSUE THREAD

**Issue by mkools** [ceph/ceph-container#1805]
Is this a bug report or feature request?
* Bug Report

**Bug Report**

I've updated my system which had a minor docker version upgrade. Docker restarted and now the CEPH OSDs don't want to come back up again. The other CEPH services (crash, mds and node exporter) are running fine. All OSDs (8 of them) fail and can't be started.

What you expected to happen: CEPH OSDs to start.

How to reproduce it (minimal and precise):

OSD log attached. Docker was upgraded with apt upgrade. Minor version upgrade. Downgrading docker again didn't fix the issue. See the attached log for the OSD start log.

[osdlog.txt](https://github.com/ceph/ceph-container/files/5924386/osdlog.txt)

**Environment**:
* OS (e.g. from /etc/os-release): Debian 10.7
* Kernel (e.g. `uname -a`): Linux osd07 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux
* Docker version (e.g. `docker version`): Docker version 20.10.3, build 48d30b5
* Ceph version (e.g. `ceph -v`): ceph version 15.2.8 (bdf3eebcd22d7d0b3dd4d5501bee5bac354d5b55) octopus (stable)

**Comment by dsavineau** [comment]
> I've updated my system which had a minor docker version upgrade.

So only docker was updated or other stuff on the system like the kernel ?

> Docker version 20.10.3, build 48d30b5

Is it the docker-ce version ? because the docker.io package from the Debian Buster repository is 18.09. Any chance to test that one ?

What was the docker version prior and after the update ?

I'll try to replicate this on my own.

How are you starting the OSD containers ?

**Comment by mkools** [comment]
Hi yes it's Docker CE. Previous was Docker 20.10.1 so a really minor upgrade. I'm not sure if it's related.

I just do systemctl stop ceph.target and then start ceph.target. But same happens when I try to start the individual OSDs.

**Comment by dsavineau** [comment]
So you're using systemd to start the ceph containers right ?

How were deploying the containers ? manually, ceph-ansible, cephadm or other ?

What's the content of the systemd unit for the ceph OSD daemons ?

**Comment by mkools** [comment]
Hello,

I'm happy to report this issue has been fixed. I also posted this on the CEPH bug tracker and they noticed I had a custom size for bdev_block_size which was 32768 (default 4096). I removed the global value did a systemctl restart ceph.target and boom everything was back online again!

This can be closed. Thanks!
