### ISSUE TITLE
Ceph mgr module zabbix call exception

### ISSUE THREAD

**Issue by aeoluswing** [ceph/ceph-container#1812]
Is this a bug report or feature request?

* Bug Report
* Feature Request

**Bug Report**

What happened:
mgr module enable zabbix but call exception
```
$ ceph zabbix config-show
Error EINVAL: unrecognized command
$ which zabbix_sender
/usr/bin/zabbix_sender
$ ceph mgr module ls
{
    "enabled_modules": [
        "balancer",
        "dashboard",
        "restful",
        "selftest",
        "status",
        "zabbix"
    ],
    "disabled_modules": [
        "influx",
        "localpool",
        "prometheus",
        "telemetry"
    ]
}
$ ceph zabbix config-set zabbix_host 10.66.199.1
Error EINVAL: unrecognized command
```

What you expected to happen:
`ceph zabbix` commands run normally.

How to reproduce it (minimal and precise):

```
docker run -d --restart always --pid=host --name ceph-mgr --network host -v mgr-conf:/etc/ceph -v mgr-data:/var/lib/ceph -e KV_TYPE=etcd -e KV_IP=10.66.199.1 -e MON_IP=10.66.199.1 -e CEPH_PUBLIC_NETWORK=10.66.199.0/26 ceph/daemon:v3.2.14-stable-3.2-luminous-centos-7-x86_64 mgr
```

**Feature Request**

Are there any similar features already existing:

What should the feature do:

What would be solved through this feature:

Does this have an impact on existing features:

**Environment**:
* OS (e.g. from /etc/os-release): CentOS7
* Kernel (e.g. `uname -a`): Linux ceph-node1 4.15.0-135-generic #139-Ubuntu SMP Mon Jan 18 17:38:24 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Docker version (e.g. `docker version`): 19.03.15
* Ceph version (e.g. `ceph -v`): ceph version 12.2.13 (584a20eb0237c657dc0567da126be145106aa47e) luminous (stable)

**Comment by dsavineau** [comment]
That's weird but it doesn't seem related to the container itself but something in the ceph core.

Any chance to test this without containers ?

Also it would be great to rerun the command with some verbose/debug to see what's going on.

I'll try to reproduce on my own but that's a bug on the ceph core side then you won't have any fix since luminous is EOL since last year.

**Comment by dsavineau** [comment]
I'm not able to reproduce the issue.

```console
[root@cephaio ~]# ceph --version
ceph version 12.2.13 (584a20eb0237c657dc0567da126be145106aa47e) luminous (stable)
[root@cephaio ~]# ceph mgr module enable zabbix
[root@cephaio ~]# ceph mgr module ls

{
    "enabled_modules": [
        "status",
        "zabbix"
    ],
    "disabled_modules": [
        "balancer",
        "dashboard",
        "influx",
        "localpool",
        "prometheus",
        "restful",
        "selftest",
        "telemetry"
    ]
}
[root@cephaio ~]# ceph zabbix config-show
{"zabbix_port": 10051, "zabbix_host": null, "identifier": "", "zabbix_sender": "/usr/bin/zabbix_sender", "interval": 60}
```

Are you executed the ceph command from the container ?

**Comment by aeoluswing** [comment]
@dsavineau I did run the command inside the container.Any commands prefixed with `ceph zabbix` would encounter this error:
```
$ ceph --version
ceph version 12.2.13 (584a20eb0237c657dc0567da126be145106aa47e) luminous (stable)
$ ceph mgr module enable zabbix
$ ceph mgr module ls
{
    "enabled_modules": [
        "balancer",
        "dashboard",
        "prometheus",
        "restful",
        "selftest",
        "status",
        "zabbix"
    ],
    "disabled_modules": [
        "influx",
        "localpool",
        "telemetry"
    ]
}
$ ceph zabbix
no valid command found; 4 closest matches:
zabbix config-set <key> <value>
zabbix config-show
zabbix self-test
zabbix send
Error EINVAL: invalid command
$ ceph zabbix config-show
Error EINVAL: unrecognized command
```
This error message makes me very confused

**Comment by aeoluswing** [comment]
@dsavineau I did run the command inside the container.Any commands prefixed with `ceph zabbix` would encounter this error:
```
$ ceph --version
ceph version 12.2.13 (584a20eb0237c657dc0567da126be145106aa47e) luminous (stable)
$ ceph mgr module enable zabbix
$ ceph mgr module ls
{
    "enabled_modules": [
        "balancer",
        "dashboard",
        "prometheus",
        "restful",
        "selftest",
        "status",
        "zabbix"
    ],
    "disabled_modules": [
        "influx",
        "localpool",
        "telemetry"
    ]
}
$ ceph zabbix
no valid command found; 4 closest matches:
zabbix config-set <key> <value>
zabbix config-show
zabbix self-test
zabbix send
Error EINVAL: invalid command
$ ceph zabbix config-show
Error EINVAL: unrecognized command
```
This error message makes me very confused

**Comment by tchaikov** [comment]
@aeoluswing i think this is more likely a bug in ceph instead of in ceph-container. but luminous is EOL already. we don't backport fixes to luminous anymore. could you try a newer release, for instance, octopus or pacific?

**Comment by aeoluswing** [comment]
@tchaikov thx for reply.
In fact, I have successfully called prometheus module, but the zabbix module call failed.I will look into the mentioned source code for solutions.
So far, the current issue should be closed, thanks again.
