### ISSUE TITLE
Publish ceph image on quay.io or registry without rate limits

### ISSUE THREAD

**Issue by ibotty** [ceph/ceph-container#1834]
Is this a bug report or feature request?
* Bug Report

**Bug Report**

When (my kubernetes) is trying to pull ceph/ceph:v15.2.10 it fails due to docker's rate limits.

```
  Warning  Failed          27s                  kubelet            Failed to pull image "ceph/ceph:v15.2.10": rpc error: code = Unknown desc = Error initializing source docker://ceph/ceph:v15.2.10: Error reading manifest v15.2.10 in docker.io/ceph/ceph: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

It would be great to publish the image on registries that don't enforce these limits.

**Comment by dsavineau** [comment]
> It would be great to publish the image on registries that don't enforce these limits.

Using a public registries for free without rate limit is a dream, they don't have unlimited ressources.
Also quay.io registry have a rate limit policy.

At least users can mitigate the rate limit by using authentication or you can also setup a registry mirror on your side.

That said, I just discovered that we can ask for whitelisting a namespace used by open source projects. So we could give it a try (this would remove the rate limit on the docker.io/ceph namespace) [1][2].

@liewegas would you be able to take look on this ? I have very limited time available.

[1] https://www.docker.com/blog/expanded-support-for-open-source-software-projects/
[2] https://www.docker.com/community/open-source/application

**Comment by liewegas** [comment]
I've already talked to docker about the open source project rate limit bump, but no dice (yet); I'll ping them again.

That said, I agree that we should push our release images to quay.io/ceph/ceph as well as docker.io/ceph/ceph.  Do you have any information on quay.io rate limits? I haven't found nay

**Comment by liewegas** [comment]
Also, note that docker's open source status is not without strings attached:

```
While the Publisher retains the Open Source project status, the Publisher agrees to -

- Become a Docker public reference for press releases, blogs, webinars, etc
- Create joint blogs, webinars and other marketing content 
- Create explicit links to their Docker Hub repos, with no ‘wrapping’ or hiding sources of their images
- Include information about Docker on the website and in documentation  
```

I suspect it is in Ceph's best interests to make the 'default' release container repository (i.e., the one used by cephadm and rook) quay.io instead of docker.io.

**Comment by dsavineau** [comment]
> That said, I agree that we should push our release images to quay.io/ceph/ceph as well as docker.io/ceph/ceph. Do you have any information on quay.io rate limits? I haven't found nay

it's not the same rate limit than docker but could be still annoying for users.

```
In addition, quay.io does not restrict anonymous pulls against its repositories (either public or private) and
only rate limits in the most severe circumstances to maintain service levels (e.g. tens of requests per
second from the same IP address).
```

https://access.redhat.com/articles/5531191
https://docs.quay.io/issues/429.html#:~:text=Quay%20has%20a%20maximum%20capacity,you%20have%20exceeded%20this%20capacity.

**Comment by ibotty** [comment]
That's quiet a difference!  I have been shut off for days from docker hub.  That's just not happening with quay.io.

**Comment by ibotty** [comment]
When updating to the new ceph I ran into it again.

```
Warning  Failed          4m21s (x4 over 5m50s)  kubelet            Failed to pull image "rook/ceph:v1.6.1": rpc error: code = Unknown desc = Error reading manifest v1.6.1 in docker.io/rook/ceph: manifest unknown: manifest unknown
Warning  Failed          4m21s (x4 over 5m50s)  kubelet            Error: ErrImagePull
```

**Comment by ibotty** [comment]
I just ran into it again today.  I would really appreciate that being fixed.

```
Warning  Failed          83s (x2 over 2m43s)  kubelet            Failed to pull image "ceph/ceph:v15.2.11": rpc error: code =   Unknown desc = Error reading manifest v15.2.11 in docker.io/ceph/ceph: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
  Warning  Failed          83s (x2 over 2m43s)  kubelet            Error: ErrImagePull
  Normal   BackOff         68s (x2 over 2m43s)  kubelet            Back-off pulling image "ceph/ceph:v15.2.11"
```

**Comment by ibotty** [comment]
Is there any movement?  I always run into these limits when updating to a newer ceph.

**Comment by liewegas** [comment]
> Is there any movement? I always run into these limits when updating to a newer ceph.

@dmick @dsavineau

**Comment by dsavineau** [comment]
that's on the top of my todo list since I'm back.

As I said earlier in the thread, you can probably avoid the rate limits by using an authenticate user.

**Comment by dsavineau** [comment]
https://quay.io/repository/ceph/ceph?tab=tags

Note that's only a manual sync of Nautilus, Octopus and Pacific images. I don't think we need pre Nautilus images at this point (as those releases are EOL).

The only work left in this project is modifying the build and push scripts for adding the quay.io registry in addition of docker.io (and at some point in the futur maybe drop docker.io registry).

Again, publishing images to quay.io will probably avoid to be rate limited like docker.io at the moment. If quay.io decides to change the rules (like docker.io did) then we will have the same situation and I don't think moving again and again to another registry is the right decision.
Users still need to deal with those constraints.

**Comment by dsavineau** [comment]
Just to add some information.

Users only need to change docker.io/ceph/ceph:tag by quay.io/ceph/ceph:tag

Container image tags are the same.
Container image ID / Digest are the same.

So pulling the image from the quay.io registry if already downloaded from docker.io won't download the image again.

```console
$ podman images
REPOSITORY                TAG       IMAGE ID      CREATED       SIZE
docker.io/ceph/ceph       v16.2     8d91d370c2b8  6 weeks ago   1.15 GB
docker.io/ceph/ceph       v16.2.4   8d91d370c2b8  6 weeks ago   1.15 GB
quay.io/ceph/ceph         v16.2.4   8d91d370c2b8  6 weeks ago   1.15 GB
quay.io/ceph/ceph         v16.2     8d91d370c2b8  6 weeks ago   1.15 GB
```

@liewegas do you want me to shoot and email to the ceph-dev and/or ceph-users list for that or do you want to wait until the scripts are updated ?
