### ISSUE TITLE
ceph ansible containerized deployment

### ISSUE THREAD

**Issue by themonaminor** [ceph/ceph-container#1848]
i am trying to install ceph in using ansible with containerized strategy.
i am getting docker registry authentication error.
i have provided ACR user and password
whether only publicly available registry is supported?

**Comment by dsavineau** [comment]
> i am trying to install ceph in using ansible with containerized strategy.

Are you using the ceph-ansible project ?

If yes, then this is more a question for that project rather the ceph-container project.

That said, ceph-ansible supports public or private registries with or without authentication [1][2].

If the answer is no then could you give more information about your error ?

[1] https://docs.ceph.com/projects/ceph-ansible/en/latest/installation/containerized.html#custom-container-image
[2] https://docs.ceph.com/projects/ceph-ansible/en/latest/installation/containerized.html#container-registry-authentication
