### ISSUE TITLE
ceph image support for windows node

### ISSUE THREAD

**Issue by themonaminor** [ceph/ceph-container#1870]
i wanted to run ceph image on windows nodes. i have checked that its running fine on linux nodes as the image is built on linux flavours as base os. is it possible to run the ceph image on windows node or is it possible to create ceph image on top of windows as base os

**Comment by dsavineau** [comment]
As far as I know ceph isn't supported to run on windows nodes for the server side.

There's an initiative to be able to use RBD and cephfs on windows but on as a client.
