### ISSUE TITLE
disable weak dependencies in all images

### ISSUE THREAD

**Issue by ktdreyer** [ceph/ceph-container#1874]
We disabled weak dependencies in the ubi8 image in https://github.com/ceph/ceph-container/pull/1798

It would be great to make this same change in all images so that upstream matches downstream.

**Comment by dsavineau** [comment]
Idealy yes, but the weak dependencies are enabled explicitly for rhel and not for centos in the ceph spec file.

https://github.com/ceph/ceph/blob/master/ceph.spec.in#L103-L105

**Comment by dsavineau** [comment]
weird then I don't understand how the weak deps aren't enabled on CentOS 8 compared to RHEL 8.

Any idea ?

Do we have the same spec file downstream ?
