### ISSUE TITLE
zabbix_sender is absent in mgr container

### ISSUE THREAD

**Issue by phsm** [ceph/ceph-container#1891]
Is this a bug report or feature request?
* Bug Report

**Bug Report**

What happened:
Ceph mgr provides zabbix module out of the box. However, this module requires zabbix_sender binary to be present on the system that runs ceph-mgr daemon. 
The container doesn't have zabbix_sender installed, and I have to enter the container and install it manually. After the container gets updated or redeployed, this operation has to be done again.

What you expected to happen:
Since zabbix module comes out of the box with ceph-mgr, the zabbix_sender binary should also be present in the container to make the module work out of the box.

How to reproduce it (minimal and precise):

1. Install ceph cluster using cephadm bootstrap.
2. Enable zabbix module: `ceph mgr module enable zabbix`
3. Make some initial configuration of the module: 
```
ceph zabbix config-set zabbix_host zabbix.localdomain
ceph zabbix config-set identifier ceph.eu-ams02.local
```
4. Check the logs of active mgr container, it will show periodic exceptions about /usr/bin/zabbix_sender not being found.

P.S. I can create a PR myself if someone can tell me where it would be better to place zabbix repo, install the package, and remove the repo snippet.

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 20.04
* Kernel (e.g. `uname -a`): 5.4.0-72-generic
* Docker version (e.g. `docker version`): 20.10.6
* Ceph version (e.g. `ceph -v`): 16.2.1

**Comment by dsavineau** [comment]
See #1651
