### ISSUE TITLE
Ceph dashboard GUI doesn't redirect correctly to API docs page - error: "status": "415 Unsupported Media Type"

### ISSUE THREAD

**Issue by alejo091** [ceph/ceph-container#1906]
**Bug Report**

What happened:

In the Ceph dashboard GUI, if clic in Help -> API gives this response:

`{"status": "415 Unsupported Media Type", "detail": "Expected an entity of content type application/json, text/javascript", "request_id": "30e96b79-717a-4098-9f7e-49379996ddbe"}`

What you expected to happen:

Redirect to API page (ceph_ip/docs)

How to reproduce it (minimal and precise):

1. Install Ceph
2. Login to the dashboard
3. Clic in Help-> API

**Environment**:
* OS: CentOS-8
* Kernel: 5.4.0-74-generic
* Docker version: 20.10.2
* Ceph version: 16.2.4

**Comment by dsavineau** [comment]
is it really related to the container setup?

Do you have the same behaviour with non container deployment?

**Comment by dsavineau** [comment]
So that's not a ceph-container issue but a ceph mgr dashboard isssue.

https://tracker.ceph.com/issues/50855

A fix has already been merged and backported to the pacific branch so the issue will probably be fixed in the next Pacific release (16.2.5)
