### ISSUE TITLE
how to choose version of  ceph docker image

### ISSUE THREAD

**Issue by kiddingl** [ceph/ceph-container#1963]
What happened:
镜像的版本应该怎样选择？，太多了

**Comment by cks2015** [comment]
确定大版本，然后最新最新的

**Comment by kiddingl** [comment]
> 确定大版本，然后选择最新的。
> 
> 你可以去研究一下：https://telemetry-public.ceph.com/ 里面有版本当前使用的情况

Thank your reply ,I will close the issue
