### ISSUE TITLE
Instruction on building ceph container from source code

### ISSUE THREAD

**Issue by Jiawei0227** [ceph/ceph-container#1976]
It would be nice to have a documentation on how to build ceph container from source code of ceph.

It seems currently we can only build ceph out of specific version or latest or some wip-* branch. However, it would be useful if a developer have some ceph change locally and he want to test e2e by building the ceph container images from local ceph repo and test it.

I would really appreciate it if anyone can point me to the correct doc for this.

**Comment by Jiawei0227** [comment]
Gentile Ping. Any help is really appreciate!

**Comment by levi-pl** [comment]
Ceph binaries as well as deb and rpm packages can be built from ceph/ceph project. Ceph-container is a project that builds container out of existing components - base OS container and packages from https://download.ceph.com/
