### ISSUE TITLE
Ceph Ubuntu images

### ISSUE THREAD

**Issue by albzha** [ceph/ceph-container#1994]
Is this a bug report or feature request?
* Feature Request

**Feature Request**

Are there any similar features already existing:
No

What should the feature do:
Support docker Ubuntu Ceph image

What would be solved through this feature:
Using ceph components with an Ubuntu base image

Does this have an impact on existing features:
No

**Environment**:
* OS: Ubuntu focal
* Docker version: 19
* Ceph version: Octopus

Hello,

Let me explain the situation; we are currently running multiple Openstack platforms, each with their own Ceph, hosting thousands of vms in total. Recently we switched one platform from a non containerized deployment to a containerized one using Ansible Kolla and Ceph Ansible (Octopus) in an Ubuntu focal environment. 
Our support's contract terms are only valid for Ubuntu and all applications running on it. Even though the host OS is running on Ubuntu, we didn't find any Ubuntu docker images for Ceph components. This violate our support contract since Ceph is running on a non-Ubuntu container. For this reason we would like to use Ceph Ubuntu docker images.

There are support for Ubuntu images on Kolla, is there any reason why there is no longer any support for Ceph Ubuntu docker images ?
Anyone else encountering a similar issue ?

**Comment by Alt-Shivam** [comment]
Hey @albzha 
We are also working in the same domain as you do,
Openstack deployments and all that stuff.
Is there any other way I can contact you.

**Comment by albzha** [comment]
Hello @Alt-Shivam
Yes sure, feel free to contact me by mail: albzha@gmail.com

**Comment by Jiawei0227** [comment]
+1

We are also interested in ubuntu based ceph image
