### ISSUE TITLE
Where can I get an image of the ARM version?

### ISSUE THREAD

**Issue by fantastic2085** [ceph/ceph-container#2017]
Is this a bug report or feature request?
* Feature Request

**Feature Request**

Are there any similar features already existing: NO

What should the feature do:
Hope to release an ARM version of the image

What would be solved through this feature:
How can I compile the ARM version of the image

Does this have an impact on existing features: NO

**Environment**:
* OS (e.g. from /etc/os-release):
*NAME="Kylin Linux Advanced Server"
VERSION="V10 (Sword)"
ID="kylin"
VERSION_ID="V10"
PRETTY_NAME="Kylin Linux Advanced Server V10 (Sword)"
ANSI_COLOR="0;31"

* Kernel (e.g. `uname -a`): Linux controller 4.19.90-25.14.v2101.ky10.aarch64 #1 SMP Fri Apr 15 11:21:31 CST 2022 aarch64 aarch64 aarch64 GNU/Linux
* Docker version (e.g. `docker version`):
Client:
 Version:           18.09.0
 EulerVersion:      18.09.0.202
 API version:       1.39
 Go version:        go1.13.15
 Git commit:        ff5c04c
 Built:             Wed Sep  8 02:04:49 2021
 OS/Arch:           linux/arm64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.0
  EulerVersion:     18.09.0.202
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       ff5c04c
  Built:            Wed Sep  8 02:04:10 2021
  OS/Arch:          linux/arm64
  Experimental:     false

* Ceph version (e.g. `ceph -v`): 
Ceph is not installed because I do not know where to get the arm version of the image. However, I want to get the ceph image of the ARM version 16.2.7

**Comment by Madhu-1** [comment]
The images are manifests in Quay.io which will pull amd64 or arm64 images automatically based on the architecture of the host system.

**Comment by fantastic2085** [comment]
Thank you very much
