### ISSUE TITLE
Update images to resolve CVEs

### ISSUE THREAD

**Issue by cjohnston1158** [ceph/ceph-container#2061]
**Bug Report**

Is it possible to update the ceph-csi images to resolve the security vulnerabilities in the images?

Security scan can be seen at:
https://quay.io/repository/ceph/ceph?tab=tags

What you expected to happen:

Outstanding CVEs to be resolved.

**Comment by mohag** [comment]
I'm [attempting to see](https://bugzilla.redhat.com/show_bug.cgi?id=2166562) if we can convince CentOS to update the images more regularly...

**Comment by cjohnston1158** [comment]
@mohag It was reported yesterday that a new image has been released and should now be done weekly.
