### ISSUE TITLE
Do package definition update on base images before building image to reduce Vulnerability

### ISSUE THREAD

**Issue by Rajpratik71** [ceph/ceph-container#2073]
Is this a bug report or feature request?
* Feature Request

**Feature Request**

**What should the feature do:**

Update the package definition update on base images before building image to install latest available package.

**What would be solved through this feature:**

Updating and installing latest package will help to reduce Vulnerability

**Does this have an impact on existing features:**

This shouldn't as ceph related package will install their required dependencies.

Ceph tracker https://tracker.ceph.com/issues/57933

**Comment by Rajpratik71** [comment]
There are many known linux package with known Vulnerability and fixes.

![image](https://user-images.githubusercontent.com/12658912/197991911-2eb14406-0a18-4434-a812-0fb80bb73e72.png)


![image](https://user-images.githubusercontent.com/12658912/197992249-1bd10c2d-4d26-4e50-a01b-ea77ff8bd8e4.png)

**Comment by mohag** [comment]
Rebuilding the images now should do a lot better as well - Red Hat rebuilt the base image...
