### ISSUE TITLE
Update the quay.io/ceph/daemon image

### ISSUE THREAD

**Issue by ginkel** [ceph/ceph-container#2112]
Is this a bug report or feature request?
* Feature Request

**Feature Request**

We are using the `quay.io/ceph/daemon` Docker image from within our CI pipeline for integration tests of our software against an ad-hoc single-node Ceph cluster.

ATM, `quay.io/ceph/daemon:v7.0.1-stable-7.0-quincy-centos-stream8` seems to be the most recent version and contains Ceph 17.2.4.

Are there any plans to release a new version of that image that features the current Ceph Quincy release (17.2.6 at the time of this writing)?

Thanks,
Thilo

**Comment by jnemeiksis** [comment]
Daemon image builder is already deprecated as I know
https://lists.ceph.io/hyperkitty/list/ceph-users@ceph.io/thread/FID3SF5C6CRFKUKGYPSDQ5UOD5CCDAHF/#BZUYFURAFML5ZRX4Q2U26GAWC6LDG4WI

It would be really nice to continue providing images until quay.io/ceph/ceph will be ready for ceph-ansible.

@guits what do you think?:))

**Comment by jnemeiksis** [comment]
I think it would be very helpful until we'll migrate to ceph/ceph :)  
Thanks!

**Comment by guits** [comment]
v7.0.3-stable-7.0-quincy-centos-stream8-x86_64 is available

```console
$ podman run --rm --entrypoint=ceph quay.io/ceph/daemon:v7.0.3-stable-7.0-quincy-centos-stream8 --version
ceph version 17.2.6 (d7ff0d10654d2280e08f1ab989c7cdf3064446a5) quincy (stable)
```

**Comment by jnemeiksis** [comment]
@guits Maybe you could build a latest Pacific version container? Thanks!
