### ISSUE TITLE
Build image with centos8 failed

### ISSUE THREAD

**Issue by zhucan** [ceph/ceph-container#2113]
Is this a bug report or feature request?
* Bug Report

**Bug Report**

What happened:
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist

What you expected to happen:
Build successfully

How to reproduce it (minimal and precise):

**Environment**:
* OS (e.g. from /etc/os-release): 
* Kernel (e.g. `uname -a`):
* Docker version (e.g. `docker version`): 20.10.23
* Ceph version (e.g. `ceph -v`): 16.2.12

**Comment by zhucan** [comment]
```
[root@rook-node01 ceph-container]# git diff
diff --git a/ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__ b/ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
index 92931d0b..6d7b7278 100644
--- a/ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
+++ b/ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__
@@ -1,3 +1,5 @@
+#sed -i -e "s|mirrorlist=|#mirrorlist=|g" /etc/yum.repos.d/CentOS-* && \
+#sed -i -e "s|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g" /etc/yum.repos.d/CentOS-* && \
 yum install -y epel-release && \
 yum install -y jq && \
 bash -c ' \
```
add it to  "ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__" is ok

**Comment by saranyareddy24** [comment]
I have also hit the same issue. Should someone fix this issue?

**Comment by zhucan** [comment]
@saranyareddy24 you can try use the "CentOS Stream release 8"

**Comment by zhucan** [comment]
@saranyareddy24 https://github.com/zhucan/ceph-doc/blob/master/Build%20ceph.md there is a doc for it and 
ignore the Chinese part.

**Comment by saranyareddy24** [comment]
It worked. Thanks.
