### ISSUE TITLE
add ceph-mgr-callhome to IBM downstream container

### ISSUE THREAD

**Issue by ktdreyer** [ceph/ceph-container#2147]
IBM's new Call Home feature will be a new RPM sub-package, `ceph-mgr-callhome`. We'll need to ship this in the IBM Storage Ceph downstream container and omit it in the RH Ceph Storage container.

CC @jmolmo and @yaarith , the engineers working on this feature.

**Comment by yaarith** [comment]
@ktdreyer @guits please make sure we add the encrypted keys from https://github.ibm.com/ceph/callhome (see https://github.ibm.com/ceph/callhome/pull/2 as it's not merged yet) in the container build.

The encrypted API keys file `ceph_call_home_keys` should be copied into the Ceph container image to `/ceph_call_home_keys`.

**Comment by jmolmo** [comment]
@ktdreyer @guits :  https://github.ibm.com/ceph/callhome/pull/2 merged. Everything ready to build the container

**Comment by ktdreyer** [comment]
The `ceph-mgr-callhome` RPM is available starting with Brew's `ceph-18.2.0-42.el9cp` build.
