### ISSUE TITLE
Include cephfs-shell 

### ISSUE THREAD

**Issue by abh** [ceph/ceph-container#2211]
It'd be helpful to have cephfs-shell for some debugging or diagnostic tasks included in the container image.

(see also https://github.com/rook/rook/issues/10731 and #2072 from 2022 that was closed by the GitHub action)

**Comment by abh** [comment]
Not stale

**Comment by abh** [comment]
Not stale

**Comment by guits** [comment]
@abh this would be valid only for Debian-based images, right? As I realize we don't build the RPM by default, see [1][2]

[1] https://github.com/ceph/ceph/blob/main/ceph.spec.in#L1238
[2] https://download.ceph.com/rpm-reef/el9/

**Comment by abh** [comment]
Hi @guits!

Rook is using centos 8 based images I think, so from that perspective it'd be better to have on the RPM-based systems too if possible; but the Debian image would be a start. 

If it's added there I can take this back to the Rook project to see why they are using the CentOS based image if the Debian based one is "more supported". :-)

**Comment by guits** [comment]
The Debian-based image is not the most supported one; it's quite the opposite to be honest.
However, I've seen some recent efforts to make the project support Debian-based images again.
In any case, I think we should check why that RPM package isn't built first. Let me ping some people and try to get some details about that. I'll update this issue then.

**Comment by abh** [comment]
Not stale, bad bot.

**Comment by abh** [comment]
not stale, bad bot.

**Comment by oliver-ni** [comment]
Not stale
