### ISSUE TITLE
Error in playbook while installing Ceph with help of ceph-ansilbe

### ISSUE THREAD

**Issue by aryanmamania** [ceph/ceph-container#2237]
I have cloned github repository of ceph-ansible and now trying to deploy my ceph in my browser. 
But I am facing an error while running ceph-ansible playbook ( I have attached the ss)
![Screenshot from 2024-09-09 18-33-16](https://github.com/user-attachments/assets/15a2ff3c-b325-4b56-903f-94768b73c71a)

**Environment**:
* OS ( Ubuntu20.04 (focal)):
*Ceph repository =  5.0 (stable)

**Comment by guits** [comment]
1/ You are using a deprecated version of ceph-ansible
2/ This is definitely lacking details (ansible version, full log, ansible host inventory, etc...)
3/ This has nothing to do with `ceph-container` (see https://github.com/ceph/ceph-ansible instead)

**Comment by aryanmamania** [comment]
host file = 

[mons]
ceph3 ansible_host=192.xxx.xxx.xxx ansible_user=ceph3 ansible_ssh_private_key_f>
aryanceph ansible_host=192.xxxxxx.xxx ansible_user=aryanceph ansible_ssh_priva>
mamaniaceph ansible_host=192.xxx.xxx.xxx ansible_user=mamaniaceph ansible_ssh_p>

[osds]
ceph3 ansible_host=192.xxx.xxx.xxx.ansible_user=ceph3 ansible_ssh_private_key_f>
aryanceph ansible_host=192.xxx.xxx.xxx ansible_user=aryanceph ansible_ssh_priva>
mamaniaceph ansible_host=192.xxx.xxx.xxx ansible_user=mamaniaceph ansible_ssh_p>

[mgrs]
aryan2 ansible_connection=local
-----------------------------------------------------------
ansible version = ansible 2.9.
--------------------------------------------------------

**Comment by aryanmamania** [comment]
this is the full output = aryan2@aryan2:/opt/ceph-ansible$ ansible-playbook site.yml --ask-become-pass
BECOME password: 
[WARNING]: Could not match supplied host pattern, ignoring: mdss
[WARNING]: Could not match supplied host pattern, ignoring: rgws
[WARNING]: Could not match supplied host pattern, ignoring: nfss
[WARNING]: Could not match supplied host pattern, ignoring: rbdmirrors
[WARNING]: Could not match supplied host pattern, ignoring: clients
[WARNING]: Could not match supplied host pattern, ignoring: iscsigws
[WARNING]: Could not match supplied host pattern, ignoring: iscsi-gws
[WARNING]: Could not match supplied host pattern, ignoring: grafana-server
[WARNING]: Could not match supplied host pattern, ignoring: rgwloadbalancers
[WARNING]: Skipping plugin (/home/aryan2/.local/lib/python3.8/site-
packages/ansible/plugins/filter/core.py) as it seems to be invalid: cannot
import name 'environmentfilter' from 'jinja2.filters'
(/home/aryan2/.local/lib/python3.8/site-packages/jinja2/filters.py)
[WARNING]: Skipping plugin (/home/aryan2/.local/lib/python3.8/site-
packages/ansible/plugins/filter/mathstuff.py) as it seems to be invalid: cannot
import name 'environmentfilter' from 'jinja2.filters'
(/home/aryan2/.local/lib/python3.8/site-packages/jinja2/filters.py)

PLAY [mons,osds,mdss,rgws,nfss,rbdmirrors,clients,mgrs,iscsigws,iscsi-gws,grafana-server,rgwloadbalancers] ***

TASK [check for python] ********************************************************
Monday 09 September 2024  21:37:03 +0530 (0:00:00.036)       0:00:00.036 ****** 
ok: [aryan2] => (item=/usr/bin/python)
ok: [ceph3] => (item=/usr/bin/python)
ok: [mamaniaceph] => (item=/usr/bin/python)
ok: [aryanceph] => (item=/usr/bin/python)
ok: [ceph3] => (item=/usr/bin/python3)
ok: [aryan2] => (item=/usr/bin/python3)
ok: [ceph3] => (item=/usr/libexec/platform-python)
[DEPRECATION WARNING]: Distribution Ubuntu 20.04 on host ceph3 should use 
/usr/bin/python3, but is using /usr/bin/python for backward compatibility with 
prior Ansible releases. A future Ansible release will default to using the 
discovered platform python for this host. See https://docs.ansible.com/ansible/
2.9/reference_appendices/interpreter_discovery.html for more information. This 
feature will be removed in version 2.12. Deprecation warnings can be disabled 
by setting deprecation_warnings=False in ansible.cfg.
ok: [mamaniaceph] => (item=/usr/bin/python3)
ok: [aryanceph] => (item=/usr/bin/python3)
ok: [aryan2] => (item=/usr/libexec/platform-python)
ok: [aryanceph] => (item=/usr/libexec/platform-python)
ok: [mamaniaceph] => (item=/usr/libexec/platform-python)

TASK [check for dnf-3 package manager (RedHat/Fedora/CentOS)] ******************
Monday 09 September 2024  21:37:04 +0530 (0:00:01.293)       0:00:01.330 ****** 
skipping: [ceph3]
skipping: [aryanceph]
skipping: [mamaniaceph]
skipping: [aryan2]

TASK [check for yum package manager (RedHat/Fedora/CentOS)] ********************
Monday 09 September 2024  21:37:05 +0530 (0:00:00.100)       0:00:01.430 ****** 
skipping: [ceph3]
skipping: [aryanceph]
skipping: [mamaniaceph]
skipping: [aryan2]

TASK [check for apt package manager (Debian/Ubuntu)] ***************************
Monday 09 September 2024  21:37:05 +0530 (0:00:00.085)       0:00:01.515 ****** 
skipping: [ceph3]
skipping: [aryanceph]
skipping: [mamaniaceph]
skipping: [aryan2]

TASK [check for zypper package manager (SUSE/OpenSUSE)] ************************
Monday 09 September 2024  21:37:05 +0530 (0:00:00.086)       0:00:01.602 ****** 
skipping: [ceph3]
skipping: [aryanceph]
skipping: [mamaniaceph]
skipping: [aryan2]

TASK [install python for RedHat based OS - dnf] ********************************
Monday 09 September 2024  21:37:05 +0530 (0:00:00.088)       0:00:01.691 ****** 
skipping: [ceph3]
skipping: [aryanceph]
skipping: [mamaniaceph]
skipping: [aryan2]

TASK [install python for debian based OS] **************************************
Monday 09 September 2024  21:37:05 +0530 (0:00:00.087)       0:00:01.778 ****** 
skipping: [ceph3]
skipping: [aryanceph]
skipping: [mamaniaceph]
skipping: [aryan2]

TASK [install python for SUSE/OpenSUSE] ****************************************
Monday 09 September 2024  21:37:05 +0530 (0:00:00.077)       0:00:01.856 ****** 
skipping: [ceph3]
skipping: [aryanceph]
skipping: [mamaniaceph]
skipping: [aryan2]

TASK [install python-xml for opensuse only if python2 is installed already] ****
Monday 09 September 2024  21:37:05 +0530 (0:00:00.107)       0:00:01.963 ****** 
skipping: [ceph3] => (item={'invocation': {'module_args': {'checksum_algorithm': 'sha1', 'get_checksum': True, 'follow': False, 'path': '/usr/bin/python', 'get_md5': False, 'get_mime': True, 'get_attributes': True}}, 'stat': {'charset': 'binary', 'uid': 0, 'exists': True, 'attr_flags': '', 'lnk_target': 'python2', 'woth': True, 'isreg': False, 'device_type': 0, 'mtime': 1586947544.0, 'block_size': 4096, 'inode': 704329, 'isgid': False, 'size': 7, 'executable': True, 'isuid': False, 'readable': True, 'version': None, 'pw_name': 'root', 'gid': 0, 'ischr': False, 'wusr': True, 'writeable': True, 'mimetype': 'inode/symlink', 'blocks': 0, 'xoth': True, 'islnk': True, 'nlink': 1, 'issock': False, 'rgrp': True, 'gr_name': 'root', 'path': '/usr/bin/python', 'xusr': True, 'atime': 1725822271.9679122, 'lnk_source': '/usr/bin/python2.7', 'isdir': False, 'ctime': 1725622957.3343372, 'isblk': False, 'wgrp': True, 'xgrp': True, 'dev': 64517, 'roth': True, 'isfifo': False, 'mode': '0777', 'rusr': True, 'attributes': []}, 'changed': False, 'ansible_facts': {'discovered_interpreter_python': '/usr/bin/python'}, 'failed': False, 'failed_when_result': False, 'item': '/usr/bin/python', 'ansible_loop_var': 'item'}) 
skipping: [ceph3] => (item={'invocation': {'module_args': {'checksum_algorithm': 'sha1', 'get_checksum': True, 'follow': False, 'path': '/usr/bin/python3', 'get_md5': False, 'get_mime': True, 'get_attributes': True}}, 'stat': {'charset': 'binary', 'uid': 0, 'exists': True, 'attr_flags': '', 'lnk_target': 'python3.8', 'woth': True, 'isreg': False, 'device_type': 0, 'mtime': 1725454775.169889, 'block_size': 4096, 'inode': 656373, 'isgid': False, 'size': 9, 'executable': True, 'isuid': False, 'readable': True, 'version': None, 'pw_name': 'root', 'gid': 0, 'ischr': False, 'wusr': True, 'writeable': True, 'mimetype': 'inode/symlink', 'blocks': 0, 'xoth': True, 'islnk': True, 'nlink': 1, 'issock': False, 'rgrp': True, 'gr_name': 'root', 'path': '/usr/bin/python3', 'xusr': True, 'atime': 1725897846.1, 'lnk_source': '/usr/bin/python3.8', 'isdir': False, 'ctime': 1725454775.169889, 'isblk': False, 'wgrp': True, 'xgrp': True, 'dev': 64517, 'roth': True, 'isfifo': False, 'mode': '0777', 'rusr': True, 'attributes': []}, 'changed': False, 'failed': False, 'failed_when_result': False, 'item': '/usr/bin/python3', 'ansible_loop_var': 'item'}) 
skipping: [ceph3] => (item={'invocation': {'module_args': {'checksum_algorithm': 'sha1', 'get_checksum': True, 'follow': False, 'path': '/usr/libexec/platform-python', 'get_md5': False, 'get_mime': True, 'get_attributes': True}}, 'stat': {'exists': False}, 'changed': False, 'failed': False, 'failed_when_result': False, 'item': '/usr/libexec/platform-python', 'ansible_loop_var': 'item'}) 
skipping: [aryanceph] => (item={'changed': False, 'stat': {'exists': False}, 'invocation': {'module_args': {'path': '/usr/bin/python', 'follow': False, 'get_md5': False, 'get_checksum': True, 'get_mime': True, 'get_attributes': True, 'checksum_algorithm': 'sha1'}}, 'ansible_facts': {'discovered_interpreter_python': '/usr/bin/python3'}, 'failed': False, 'failed_when_result': False, 'item': '/usr/bin/python', 'ansible_loop_var': 'item'}) 
skipping: [aryanceph] => (item={'changed': False, 'stat': {'exists': True, 'path': '/usr/bin/python3', 'mode': '0777', 'isdir': False, 'ischr': False, 'isblk': False, 'isreg': False, 'isfifo': False, 'islnk': True, 'issock': False, 'uid': 0, 'gid': 0, 'size': 9, 'inode': 394232, 'dev': 64517, 'nlink': 1, 'atime': 1725861450.3874316, 'mtime': 1725452138.0728326, 'ctime': 1725452138.0728326, 'wusr': True, 'rusr': True, 'xusr': True, 'wgrp': True, 'rgrp': True, 'xgrp': True, 'woth': True, 'roth': True, 'xoth': True, 'isuid': False, 'isgid': False, 'blocks': 0, 'block_size': 4096, 'device_type': 0, 'readable': True, 'writeable': True, 'executable': True, 'lnk_source': '/usr/bin/python3.8', 'lnk_target': 'python3.8', 'pw_name': 'root', 'gr_name': 'root', 'mimetype': 'inode/symlink', 'charset': 'binary', 'version': None, 'attributes': [], 'attr_flags': ''}, 'invocation': {'module_args': {'path': '/usr/bin/python3', 'follow': False, 'get_md5': False, 'get_checksum': True, 'get_mime': True, 'get_attributes': True, 'checksum_algorithm': 'sha1'}}, 'failed': False, 'failed_when_result': False, 'item': '/usr/bin/python3', 'ansible_loop_var': 'item'}) 
skipping: [mamaniaceph] => (item={'changed': False, 'stat': {'exists': False}, 'invocation': {'module_args': {'path': '/usr/bin/python', 'follow': False, 'get_md5': False, 'get_checksum': True, 'get_mime': True, 'get_attributes': True, 'checksum_algorithm': 'sha1'}}, 'ansible_facts': {'discovered_interpreter_python': '/usr/bin/python3'}, 'failed': False, 'failed_when_result': False, 'item': '/usr/bin/python', 'ansible_loop_var': 'item'}) 
skipping: [mamaniaceph] => (item={'changed': False, 'stat': {'exists': True, 'path': '/usr/bin/python3', 'mode': '0777', 'isdir': False, 'ischr': False, 'isblk': False, 'isreg': False, 'isfifo': False, 'islnk': True, 'issock': False, 'uid': 0, 'gid': 0, 'size': 9, 'inode': 265983, 'dev': 64517, 'nlink': 1, 'atime': 1725897816.968, 'mtime': 1725513961.1904278, 'ctime': 1725513961.1904278, 'wusr': True, 'rusr': True, 'xusr': True, 'wgrp': True, 'rgrp': True, 'xgrp': True, 'woth': True, 'roth': True, 'xoth': True, 'isuid': False, 'isgid': False, 'blocks': 0, 'block_size': 4096, 'device_type': 0, 'readable': True, 'writeable': True, 'executable': True, 'lnk_source': '/usr/bin/python3.8', 'lnk_target': 'python3.8', 'pw_name': 'root', 'gr_name': 'root', 'mimetype': 'inode/symlink', 'charset': 'binary', 'version': None, 'attributes': [], 'attr_flags': ''}, 'invocation': {'module_args': {'path': '/usr/bin/python3', 'follow': False, 'get_md5': False, 'get_checksum': True, 'get_mime': True, 'get_attributes': True, 'checksum_algorithm': 'sha1'}}, 'failed': False, 'failed_when_result': False, 'item': '/usr/bin/python3', 'ansible_loop_var': 'item'}) 
skipping: [aryanceph] => (item={'changed': False, 'stat': {'exists': False}, 'invocation': {'module_args': {'path': '/usr/libexec/platform-python', 'follow': False, 'get_md5': False, 'get_checksum': True, 'get_mime': True, 'get_attributes': True, 'checksum_algorithm': 'sha1'}}, 'failed': False, 'failed_when_result': False, 'item': '/usr/libexec/platform-python', 'ansible_loop_var': 'item'}) 
skipping: [mamaniaceph] => (item={'changed': False, 'stat': {'exists': False}, 'invocation': {'module_args': {'path': '/usr/libexec/platform-python', 'follow': False, 'get_md5': False, 'get_checksum': True, 'get_mime': True, 'get_attributes': True, 'checksum_algorithm': 'sha1'}}, 'failed': False, 'failed_when_result': False, 'item': '/usr/libexec/platform-python', 'ansible_loop_var': 'item'}) 
skipping: [aryan2] => (item={'changed': False, 'stat': {'exists': False}, 'invocation': {'module_args': {'path': '/usr/bin/python', 'follow': False, 'get_md5': False, 'get_checksum': True, 'get_mime': True, 'get_attributes': True, 'checksum_algorithm': 'sha1'}}, 'failed': False, 'failed_when_result': False, 'item': '/usr/bin/python', 'ansible_loop_var': 'item'}) 
skipping: [aryan2] => (item={'changed': False, 'stat': {'exists': True, 'path': '/usr/bin/python3', 'mode': '0777', 'isdir': False, 'ischr': False, 'isblk': False, 'isreg': False, 'isfifo': False, 'islnk': True, 'issock': False, 'uid': 0, 'gid': 0, 'size': 9, 'inode': 263170, 'dev': 64517, 'nlink': 1, 'atime': 1725896696.54, 'mtime': 1725532190.21014, 'ctime': 1725532190.21014, 'wusr': True, 'rusr': True, 'xusr': True, 'wgrp': True, 'rgrp': True, 'xgrp': True, 'woth': True, 'roth': True, 'xoth': True, 'isuid': False, 'isgid': False, 'blocks': 0, 'block_size': 4096, 'device_type': 0, 'readable': True, 'writeable': True, 'executable': True, 'lnk_source': '/usr/bin/python3.8', 'lnk_target': 'python3.8', 'pw_name': 'root', 'gr_name': 'root', 'mimetype': 'inode/symlink', 'charset': 'binary', 'version': None, 'attributes': [], 'attr_flags': ''}, 'invocation': {'module_args': {'path': '/usr/bin/python3', 'follow': False, 'get_md5': False, 'get_checksum': True, 'get_mime': True, 'get_attributes': True, 'checksum_algorithm': 'sha1'}}, 'failed': False, 'failed_when_result': False, 'item': '/usr/bin/python3', 'ansible_loop_var': 'item'}) 
skipping: [aryan2] => (item={'changed': False, 'stat': {'exists': False}, 'invocation': {'module_args': {'path': '/usr/libexec/platform-python', 'follow': False, 'get_md5': False, 'get_checksum': True, 'get_mime': True, 'get_attributes': True, 'checksum_algorithm': 'sha1'}}, 'failed': False, 'failed_when_result': False, 'item': '/usr/libexec/platform-python', 'ansible_loop_var': 'item'}) 

TASK [gather facts] ************************************************************
Monday 09 September 2024  21:37:05 +0530 (0:00:00.282)       0:00:02.246 ****** 
fatal: [ceph3]: FAILED! => 
  msg: |-
    The conditional check 'not delegate_facts_host | bool or inventory_hostname in groups.get(client_group_name, [])' failed. The error was: No filter named 'bool' found.
  
    The error appears to be in '/opt/ceph-ansible/site.yml': line 33, column 7, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
        - name: gather facts
          ^ here
fatal: [aryanceph]: FAILED! => 
  msg: |-
    The conditional check 'not delegate_facts_host | bool or inventory_hostname in groups.get(client_group_name, [])' failed. The error was: No filter named 'bool' found.
  
    The error appears to be in '/opt/ceph-ansible/site.yml': line 33, column 7, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
        - name: gather facts
          ^ here
fatal: [mamaniaceph]: FAILED! => 
  msg: |-
    The conditional check 'not delegate_facts_host | bool or inventory_hostname in groups.get(client_group_name, [])' failed. The error was: No filter named 'bool' found.
  
    The error appears to be in '/opt/ceph-ansible/site.yml': line 33, column 7, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
        - name: gather facts
          ^ here
fatal: [aryan2]: FAILED! => 
  msg: |-
    The conditional check 'not delegate_facts_host | bool or inventory_hostname in groups.get(client_group_name, [])' failed. The error was: No filter named 'bool' found.
  
    The error appears to be in '/opt/ceph-ansible/site.yml': line 33, column 7, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
        - name: gather facts
          ^ here

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
aryan2                     : ok=1    changed=0    unreachable=0    failed=1    skipped=8    rescued=0    ignored=0   
aryanceph                  : ok=1    changed=0    unreachable=0    failed=1    skipped=8    rescued=0    ignored=0   
ceph3                      : ok=1    changed=0    unreachable=0    failed=1    skipped=8    rescued=0    ignored=0   
mamaniaceph                : ok=1    changed=0    unreachable=0    failed=1    skipped=8    rescued=0    ignored=0   


Monday 09 September 2024  21:37:06 +0530 (0:00:00.111)       0:00:02.358 ****** 
=============================================================================== 
check for python -------------------------------------------------------- 1.30s
install python-xml for opensuse only if python2 is installed already ---- 0.28s
gather facts ------------------------------------------------------------ 0.11s
install python for SUSE/OpenSUSE ---------------------------------------- 0.11s
check for dnf-3 package manager (RedHat/Fedora/CentOS) ------------------ 0.10s
check for zypper package manager (SUSE/OpenSUSE) ------------------------ 0.09s
check for apt package manager (Debian/Ubuntu) --------------------------- 0.09s
install python for RedHat based OS - dnf -------------------------------- 0.09s
check for yum package manager (RedHat/Fedora/CentOS) -------------------- 0.08s
install python for debian based OS -------------------------------------- 0.08s
aryan2@aryan2:/opt/ceph-ansible$

**Comment by guits** [comment]
@aryanmamania as said, this isn't the right place to report this.
See my previous comment.
