### ISSUE TITLE
TODO - Ceph disk creation cleanup/improvements

### ISSUE THREAD

**Issue by dang** [ceph/ceph-container#258]
The disk creation needs to be cleaned up and improved a bit to allow proper hooking into the ceph-ansible framework for creation of the disk/journal.  I believe that the only true issue is the journal size, but there may be more.

**Comment by leseb** [comment]
That's interesting. When bootstrapping containers with ansible Ceph-ansible should probably be responsible for a couple of things. Leaving the job to ansible will allow us to only use the directory scenario with Ceph-docker so no more privileged containers. 
We should keep the current logic though so we don't disrupt existing deployments/platform orchestration.

**Comment by leseb** [comment]
Oh and we need to extend this to monitors as well. :)

**Comment by leseb** [comment]
I've started to look into that it looks quite easy to do. `ceph-docker` already has the necessary bits to skip configuration steps and go straight to the daemon startup.

**Comment by leseb** [comment]
@dang did you draft something already?

**Comment by dang** [comment]
No, this was a place-holder for me to not forget.  Jim asked me to create it.  I've been sidetracked by intermediate blockers so far.

**Comment by leseb** [comment]
Ok, I'll let you handle it then, but if you want to discuss it let me know :).
