### ISSUE TITLE
Replace Sigil in Kubernetes Example with more common tool

### ISSUE THREAD

**Issue by elsonrodriguez** [ceph/ceph-container#338]
Sigil is a bit of a barrier to entry, need to either replace the generation of the templates with a more common pattern, perhaps based on bash:

https://github.com/kubernetes/kubernetes/blob/master/cluster/aws/config-default.sh
https://www.gnu.org/software/gettext/manual/html_node/envsubst-Invocation.html

**Comment by leseb** [comment]
@elsonrodriguez good idea
