### ISSUE TITLE
ceph/daemon mon fails silently when it cannot connect to a kv store

### ISSUE THREAD

**Issue by notslang** [ceph/ceph-container#344]
When I start up a monitor with:

```
sudo docker run -d --net=host \
-v /var/lib/ceph:/var/lib/ceph \
-e MON_IP=192.168.1.175 \
-e CEPH_PUBLIC_NETWORK=192.168.1.0/24 \
-e KV_TYPE=etcd \
-e KV_IP=127.0.0.1 \
--name mon \
ceph/daemon mon
```

I get this output from `docker logs`:

```
key already exists
key already exists
key already exists
key already exists
key already exists
key already exists
Adding Mon Host - coreos3
```

Before it dies with exit code `2`. I'm pretty sure that the issue on my end is that I'm not running etcd on the legacy port `4001`, but the issue that I'm reporting is the fact that https://github.com/ceph/ceph-docker/blob/3970cdaef33aed7aaae19a826fcba195a09de429/ceph-releases/jewel/ubuntu/14.04/daemon/config.kv.sh#L36 lets the script fail silently, which makes this more of a pain to debug than it should be.

**Comment by leseb** [comment]
Right, I don't mind removing all the `> /dev/null 2>&1` as this will help debugging.
Do you doing a PR for such change?

**Comment by immesys** [comment]
This is related to #365. The correct fix is actually upstream, for kviator to have different exit codes for different failure modes. I opened an issue but I don't think kviator is very active.

**Comment by leseb** [comment]
@immesys yes perhaps we should think of another alternative...

**Comment by leseb** [comment]
@hunter any take on this?

**Comment by hunter** [comment]
Sorry, just getting back from holidays. I'll see if we can queue up a fix for kviator.

**Comment by leseb** [comment]
@hunter thanks!
