### ISSUE TITLE
Missing some sane defaults to run in directory mode from coreos etcd

### ISSUE THREAD

**Issue by pierreozoux** [ceph/ceph-container#350]
Since yesterday, I was trying to mount a ceph cluster on CoreOS backed by etcd.

There was 3 things missing to run it from a directory:
- the directory wasn't created [here](https://github.com/ceph/ceph-docker/blob/master/ceph-releases/jewel/ubuntu/14.04/daemon/entrypoint.sh#L321) why not creating it?
- I also hit [this bug](https://github.com/ceph/ceph-docker/pull/311)
  - why demo is not using standard entrypoint? (then this bug would have been fix in `daemon` also)
  - I used this workaround to make my cluster running from directoy:

```
etcdctl set /ceph-config/ceph/osd/osd_max_object_namespace_len "64"
etcdctl set /ceph-config/ceph/osd/osd_max_object_name_len "256"
```

**Comment by leseb** [comment]
@pierreozoux we expect this dir to exist: https://github.com/ceph/ceph-docker/blob/master/ceph-releases/jewel/ubuntu/14.04/daemon/entrypoint.sh#L321
So it will never get created.

About https://github.com/ceph/ceph-docker/pull/311 do you mind creating a PR for this?
