### ISSUE TITLE
NFS Ganesha

### ISSUE THREAD

**Issue by hunter** [ceph/ceph-container#384]
I've been doing some work on enabling NFS with ceph-docker and kubernetes. The RGW backend seems to mostly work with a few hacks but it seems that the CEPH (FS) backend is missing (raising: `Error:/usr/lib64/ganesha/libfsalceph.so: cannot open shared object file: No such file or directory`).

I'm assuming that packages are missing or not built for the various base images (tested Ubuntu, Centos and Fedora). Before diving into the fun world of packages I thought I might file a ticket to see if anyone (Redhatters?) had better luck or knew of the correct packages.

**Comment by dang** [comment]
Downstream Ceph does not yet support the CephFS backend for Ganesha, so it's not packaged downstream.  Upstream (Centos and Fedora) should have packages for it.

**Comment by hunter** [comment]
I should have been more clear, I realise that downstream does not have support. Is `nfs-ganesha-ceph` the best package to be using for Centos/Fedora? No Ubuntu packages yet?

**Comment by dang** [comment]
The Debian packages should be up.  The Ubuntu packages were being build yesterday, so they may be up by now.

**Comment by dang** [comment]
And yes, nfs-ganesha-ceph should be the correct package for centos/fedora.

**Comment by hunter** [comment]
Thanks @dang!

Are there debian/ubuntu packages that I'm not aware of other than the gluster ppa? I can't see any indication in the repo or build logs that ceph is being built as part of `nfs-ganesha-fsal`

**Comment by dang** [comment]
The Gluster PPA is what I was thinking of.  It's possible that they're not making nfs-ganesha-ceph packages as part of that, I'll check.  If so, then I'm no aware of any other packages available for Ubuntu/Debian.

**Comment by dang** [comment]
According to the Gluster PPA owner, it doesn't but it maybe could, depending on the Ceph versions available.  You may have to build Ganesha yourself to proceed on Ubuntu in the near future.

**Comment by ktdreyer** [comment]
We need Ubuntu to ship Ceph v10.2.5 in Xenial so that nfs-ganesha 2.4 can build a working RGW FSAL.

**Comment by ktdreyer** [comment]
Ubuntu is shipping [v10.2.5 in Xenial now](http://packages.ubuntu.com/xenial-updates/ceph), with [v10.2.6 coming very shortly](https://bugs.launchpad.net/bugs/1671117). I take this to mean that the Gluster PPA should be able to build with the RGW and CephFS FSALs enabled.
