### ISSUE TITLE
demo Dockerfile installs .deb from http

### ISSUE THREAD

**Issue by kpcyrd** [ceph/ceph-container#435]
The demo Dockerfile downloads s3cmd from `http://mirrors.kernel.org/ubuntu/pool/universe/s/s3cmd/s3cmd_1.6.1-1_all.deb` and then proceeds to install it using `dpkg -i`.

If I'm not mistaken this bypasses signature verification and just installs whatever was downloaded over http.

**Comment by ktdreyer** [comment]
You're not mistaken, and we should fix this.

**Comment by leseb** [comment]
Not sure how to address this in the Dockerfile itself since we can't really do any condition.
Isn't `mirrors.kernel.org` a trusted source? :p

**Comment by kpcyrd** [comment]
@leseb The file is downloaded over an unauthenticated connection. Usually this isn't an issue because apt is verifying signatures, but this step is skipped when using `dpkg -i` directly.

I'm not sure what's the best way to fix this (and I would appreciate a better solution), but at least downloading from `https://mirrors.kernel.org/ubuntu/pool/universe/s/s3cmd/s3cmd_1.6.1-1_all.deb` reduces the risk.

**Comment by ktdreyer** [comment]
If there is a critical bug in Trusty's s3cmd, we should file that in Trusty's launchpad tracker for the Ubuntu package maintainer to fix it. If the Ubuntu maintainer won't ship an update for that, it sounds like it's time to move our Demo container to Xenial

**Comment by leseb** [comment]
Well we already have a demo container using Xenial if needed.

**Comment by ktdreyer** [comment]
@leseb, In that case, would you mind deleting the Trusty container entirely? It's a root-level compromise for any attacker who can intercept this download and replace it with something.

**Comment by leseb** [comment]
@ktdreyer It's not straighforward, I'll have a look soon.

**Comment by ktdreyer** [comment]
@leseb would you please let me know what keeps us from deleting the Trusty container?

**Comment by leseb** [comment]
@ktdreyer nothing in particular, I just need to redo *all* the symlinks, that's all :)

**Comment by leseb** [comment]
I'm also always also concerned about removing things as people are likely running on it.
Trusty was the initial container, so most of the deployments are probably using it, which makes it pretty tricky to remove.
