### ISSUE TITLE
Provide examples for PV/PVC for Ceph on Kubernetes

### ISSUE THREAD

**Issue by sajal** [ceph/ceph-container#450]
I am very new to Kubernetes and this is the first time I'm looking into ceph planing a bare-metal + coreos deployment. Your Kubernetes examples are very helpful.

I would like the examples expanded to include `PersistentVolume`, `PersistentVolumeClaim` and `StorageClass`.

**Comment by intlabs** [comment]
@sajal I have an example of using the above in the Helm based deployment of Ceph (for Kubernetes 1.5 and above) that I'm working on, that may be of use? It is heavily based on the work in the examples folder: https://github.com/portdirect/marina

**Comment by sajal** [comment]
thanks @intlabs 
I don't know/understand helm yet, but your project looks like a good starting point. I will begin attempting to dissect it tomorrow.

**Comment by intlabs** [comment]
@sajal I've refactored this work which is now located at https://github.com/portdirect/ceph-helm, I'd recommend looking there instead of my `marina` repo now.

**Comment by jimcurtis** [comment]
The new GKE example that Ivan Font @font and I just added at https://github.com/ceph/ceph-docker/tree/master/examples/kubernetes/gke shows how to use PVs and PVCs to do static provisioning with both RBD and CephFS.  We are still looking into how we can do dynamic provisioning with StorageClass.

**Comment by sajal** [comment]
@jimcurtis I ported the StorageClass portion of @intlabs helm project to plain vanilla kubernetes and it works fine. Only thing i had some trouble with was realizing that each namespace that wants to make use of the `StorageClass` needs the secret associated with it. Once setup all namespaces with the secret available can do dynamic provisioning using PV/PVC. 

I will try to isolate the required example and update the documentation here.

**Comment by font** [comment]
@sajal Please have a look at the most recent updates to the Kubernetes example documentation. It discusses dynamic provisioning using storageclass/pvc and a test pod to consume it. You can get more details here https://github.com/ceph/ceph-docker/tree/master/examples/kubernetes/gce.

**Comment by jamstar** [comment]
@sajal so im having issues as well with the same thing.  Can you post what you did, especially your storage class? Im using vanilla k8s.  if you can post your pvc as well, that would be great.

**Comment by sajal** [comment]
@jamstar I decided to not go forward on bare-metal(or ceph) and don't have detailed notes anymore. You might find [rook](https://github.com/rook/rook/) easier to use. Its basically a tool to manage various ceph components inside kubernetes.

**Comment by jamstar** [comment]
@sajal thanks for replying. i avoid things in alpha state as ive had some very bad experiences.
