### ISSUE TITLE
How do you use ceph-docker?

### ISSUE THREAD

**Issue by leseb** [ceph/ceph-container#472]
Hi contributors,
@galindro ,@pokoli ,@ibotty ,@jimcurtis ,@sajal ,@jayconroy ,@alanmeadows ,@coffeepac ,@linuxwind ,@danielin917 ,@dang ,@clinta ,@ivotron ,@mainboy ,@a-nldisr ,@bnoon ,@mbessler ,@walkerlee ,@theanalyst ,@rjfd ,@minshenglin ,@osixia ,@tobilg ,@nazar-pc ,@rochaporto ,@tobegit3hub ,@BugRoger ,@mkkie ,@ohmystack ,@xcompass ,@lorieri ,@Raboo ,@CoRfr ,@slang800 ,@yxwzaxns ,@untoreh ,@immesys ,@deviantintegral ,@hookenz ,@TelanJ ,@elsonrodriguez ,@fmeppo ,@chaosaffe ,@h0tbird ,@cornelius-keller ,@rootfs ,@andrewschoen ,@font ,@streamnsight ,@dmitryint

Here's a poll that will help us understanding how ceph-docker is being used :)

https://goo.gl/QjAzbD

Results can be seen here: https://goo.gl/Kbykke
Once you responded please put  a smiley on this message so I can get notification :).
Thanks for taking the time!

**Comment by leseb** [comment]
Someone I couldn't highlight everyone in a single message so I'm adding: @alfredodeza ,@hunter ,@Ulexus

**Comment by streamnsight** [comment]
:-)

Voted. 
let me add that I originally looked at Ceph in Docker to use in Kubernetes, to supply storage to the cluster. At the time k8s didn't have DaemonSets or any easy way to statically assign a pod to a machine. 
Ceph being a service that is very much dependent on the underlying hardware, I realize it doesn't really make sense to deploy it in the same k8s cluster as the rest. I still see a point in deploying with k8s, but deploying as a separate cluster is IMO more appropriate. 
All this to say that all in all, k8s deployment to me is more a matter of preference than the initial need to use ceph as storage for services in k8s.

**Comment by osixia** [comment]
Voted too :)
like @streamnsight i wanted to deploy it in kubernetes but it's not suitable for now as you can't use local storage for petsets as discussed here: https://github.com/kubernetes/features/issues/121 
so i use etcd and fleet to run it on the cluster.

**Comment by hunter** [comment]
Voted!

We've gone with a few variants to the current Kubernetes examples.

Firstly we've switched away from the etcd/consul KV store and are using standard ConfigMaps/Secrets for configuration. We found it easier than running a dedicated etcd/consul cluster in K8s.

We've also been testing out 3 independent MON deployments to mimic PetSet/StatefulSets (locking down Pod hostname and locking to a host) and using a hostNetwork to keep IP consistent for external services. The kubernetes/features#121 mentioned by @osixia would help here.

We've also created a DaemonSet assigned to a drive (eg. a DS for `/dev/sdc` with a label of type `ssd` across all storage nodes in the cluster, another DS for `/dev/sdd` of type `hdd`, etc) to make OSD/CRUSH management slightly easier with a larger number of OSDs (we have 12 drive servers we're testing). Not perfect but does give better granularity to manage OSDs.

There is a ceph-exporter deployment that we've been testing too for integration with Kubernetes Prometheus.

Finally, we'd started on a helm chart to make everything a little more standardised. https://github.com/portdirect/ceph-helm also has one too (/cc @intlabs). It would be good to get something working together to simplify the deployment and configuration.

**Comment by leseb** [comment]
Thanks everyone for your comments.

@hunter a few questions:

1. Should we consider using ConfigMaps/Secrets for configuration or as an alternative?
2. What's the ceph-exporter project?
3. I've been discussing this with @intlabs to get the ceph-helm in proper shape so ultimately we can ship it to the Kubernetes repo. I still need to go through this repo, I have a couple of changes to propose.

Thanks!

**Comment by immesys** [comment]
I would also vote in favor of ConfigMaps and Secrets. It makes it much easier to deploy services that consume ceph, and it has been quite reliable for me.

I would love a daemonset solution to deploying ceph on machines. I didn't really get mine working (different machines have different names for their drives) so I had to manually deploy unit files on my machines. 

If someone spearheads the work to get the ceph-docker and kubernetes integration more smooth and reliable, I will contribute development and testing time.

**Comment by hunter** [comment]
Our preference is for ConfigMaps/Secrets since they don't require additional services but not sure how that will effect others who've deployed with etcd/consul

(ceph-exporter)[https://github.com/digitalocean/ceph_exporter] publishes metrics to Prometheus so fits well into the Kubernetes/CNCF monitoring tools.

Some of our changes have been published (here)[https://github.com/AcalephStorage/ceph-docker/tree/more-kube-examples/examples/kubernetes/host] including the ConfigMaps, ceph-exporter and a small convenience script (warning: it's a horrible mess of experiments).

The (rook)[https://github.com/rook/rook] project has been doing some interesting work with (ThirdPartyResources/Operators)[https://github.com/rook/rook/pull/359]. That approach may actually make sense for Ceph generally too for encapsulating best practice Ceph deployment and management (although that would make a heap of overlap between the projects)

**Comment by alanmeadows** [comment]
We are using helm to orchestrate ceph as a foundational Kubernetes Persistent Volume provider for [openstack-helm](https://github.com/att-comdev/openstack-helm).  We are rallying support around operationalizing this as we want to start with one well supported and production ready storage backend.

We use a ceph helm chart that is contained within this project very similar to @intlabs to deploy ceph, using a `DaemonSet` for the OSDs, and StatefulSets for the MONs.  We are working through some challenges there and also trying to determine the best path to expose a Kubernetes deployed ceph cluster externally (as direct OSD access is required, which may mean `hostNetwork` or there could be other options yet unexplored) as well as support operators being able to describe host disk topology in via helm values (as overrides).  It is our belief that the correct way to do this would be one OSD `DaemonSet` per disk as opposed to feeding in several physical disks into a single OSD container and letting entrypoint manage this which means using helm and the ceph chart to provide a reliable way to orchestrate not only one OSD per disk, but also support hosts of varying disk capacity in a single environment.

Some of those thoughts are captured in one of our [issues](https://github.com/att-comdev/openstack-helm/pull/158)

- I am a fan of ConfigMaps/Secrets - this is our ideal for managing all configuration overlay and how we do most of this work in our helm chart today.
- We have experienced a number of issues with entrypoint.sh network detection.  This seems to be improving.
- We have issues with handling "all lights out scenarios" - we had to do work to ensure the MONs could all survive going offline at the same time.
- For operationalizing, there needs to be a better way to handle OSD or MON errors to allow operations oriented teams to debug -- it requires a real conjoined set of _both_ Kubernetes and Ceph skills to exam crashlooping ceph issues today and I fear this will be unpalatable.

**Comment by timcharper** [comment]
I used for the Ceph Scheduler for Apache Mesos:

https://github.com/vivint-smarthome/ceph-on-mesos

I generate all the secrets in the scheduler itself, and distribute them when launching the nodes.

https://github.com/vivint-smarthome/ceph-on-mesos/blob/master/src/main/scala/com/vivint/ceph/JobBehavior.scala#L151

**Comment by leseb** [comment]
How does ConfigMaps work with the ceph.conf? In the Ceph team, we are currently working on implementing a KV interface natively on the daemons so they can fetch their config options from a kv store (e.g: etcd). With that we don't need to have confd anymore, well no ceph.conf flat file at all. I'm not sure to understand how ConfigMaps will fit into the picture.

Can someone clarify that? Is our proposal valid to you (ceph daemon native kv)?
Thanks!

**Comment by elsonrodriguez** [comment]
@leseb ConfigMaps can be exposed as file to an application in Kubernetes,so you can put the whole ceph.conf file in a ConfigMap, and then expose that ConfigMap to a ceph-component running in k8s.

ConfigMaps can also store key-value pairs, and in your second scenario could be the kv store that the ceph components natively talk to to get/set their config options.

**Comment by alanmeadows** [comment]
I think the paradigm that shifts is if you need configuration data orchestrated to several containers, Kubernetes can handle that with ConfigMaps.  It becomes even easier with a layer above such as helm (under the kubernetes/ umbrella itself so a safe horse to bet on).

Letting Kubernetes handle distributing the configuration means:

- The orchestrator becomes the first class citizen.  You can pair down the complexity to just the clustering state your application needs to communicate during run-time.  There is no need to maintain a resilient KV as part of ceph in this scenario to distribute configuration.
- (Rolling) Updates get handled by Kubernetes itself when those configuration files change.
- The images and their pre-requisite service requirements become simpler -- at the expense of asking Kubernetes to do more.

**Comment by immesys** [comment]
While we are on the subject of kubernetes, can we try get upstream to include rbd in their kubernetes-controller-manager container? That way RBD PV's actually work out of the box, unless you guys are doing it differently?

**Comment by font** [comment]
@immesys you mean without requiring installing Ceph and RBD utilities on the controller nodes?

**Comment by elsonrodriguez** [comment]
@immesys On a related note, I did this for clusters that use kube-up: https://github.com/kubernetes/kubernetes/pull/40764

**Comment by immesys** [comment]
I don't mind having ceph and rbd utilities on the controlling nodes, but I use kubeadm and even though ceph was installed on the master, the rbd utility wasn't in the container they used so I had to roll my own replacement controller container

**Comment by intlabs** [comment]
Sorry I've been somewhat mute over the last week, I'd totally missed this thread. @hunter do you have a link to the chart you've been working on? - it would be great to see if we could combine efforts.

**Comment by intlabs** [comment]
@immesys I've had some brief chats regarding getting RBD included in the controller manager image with some of the people in sig-storage, and think it may be possible to do so. But as k8s moves towards external provisioners based around FlexVolume for all PVCs I think this will become much easier, as we will only need the RBD binary in the Ceph provisioner AFAIK.

**Comment by hunter** [comment]
@intlabs We haven't published anything publicly yet. I'll double check if there is anything sensitive, clean up and share.

We ended up using the CoreOS hyperkube images (even for a kubeadm install) to get around the missing Ceph binaries

@leseb is the `ceph daemon native kv` similar to how Rook is doing it? They seem to store config along with OSD devices (and state) although they bundle/manage etcd transparently along with the combined Ceph binaries.

**Comment by leseb** [comment]
@hunter the idea is now to bootstrap initial monitors, get a quorum and then let all other Ceph daemons getting their Ceph config from the monitor kv store. With that, we don't need any etcd to store anything and everything is self-managed by Ceph. We will start working on this pretty soon.

I'm not of what Rook is doing at the moment, I just know everything is embedded into a single Go binary.

**Comment by hunter** [comment]
I just noticed that CoreOS is working on a project for storage management on Kubernetes named Quartermaster - https://www.meetup.com/Containers-and-persistent-storage/events/234808295/?a=socialmedia

I thought it may be useful (although perhaps slightly premature) to loop in @lpabon to see if there may be areas in which to collaborate.

**Comment by lpabon** [comment]
@hunter Thanks for bringing it up. Here is a document describing it: http://bit.ly/2kikXpF Tell me what you think.

**Comment by leseb** [comment]
@hunter yes, @lpabon and I were actually discussing this project to see how we can potentially benefit from it :).
