### ISSUE TITLE
osd daemon doesn't work with block partition device

### ISSUE THREAD

**Issue by alanv72** [ceph/ceph-container#501]
```
root@opcs1:/etc/ceph# docker run -d --net=host --pid=host --privileged=true -v /etc/ceph:/etc/ceph -v /var/lib/ceph:/var/lib/ceph -v /dev/:/dev/ -e OSD_DEVICE=/dev/sda7 -e OSD_JOURNAL=/dev/md1 -e OSD_BLUESTORE=1 -e OSD_TYPE=activate ceph/daemon osd
f725713cf5623e6d45cde4e3d70310248de6b1a1d484f4692349446caae0183b

root@opcs1:/etc/ceph# docker logs f725713cf562
2017-02-19 07:33:32  /entrypoint.sh: static: does not generate config
main_activate: path = /dev/sda7p1
Traceback (most recent call last):
  File "/usr/sbin/ceph-disk", line 9, in <module>
    load_entry_point('ceph-disk==1.0.0', 'console_scripts', 'ceph-disk')()
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 5230, in run
    main(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 5181, in main
    args.func(args)
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 3511, in main_activate
    raise Error('%s does not exist' % args.path)
ceph_disk.main.Error: Error: /dev/sda7p1 does not exist
root@opcs1:/etc/ceph#
```

It appears that the script is looking for device "/dev/sda7p1" when it should be "/dev/sda7".

**Comment by alanv72** [comment]
Seemed to find a work around by creating symlink to the /dev/sdx7 with name /dev/sdx7p1

**Comment by leseb** [comment]
Can you run this manually?

1. `docker run -ti --entrypoint=/bin/bash --privileged=true -v /dev/:/dev/ -v /etc/ceph:/etc/ceph -v /var/lib/ceph:/var/lib/ceph daemon``
2. `export OSD_DEVICE=/dev/sda7 OSD_JOURNAL=/dev/md1 OSD_BLUESTORE=1 OSD_TYPE=activate`
3. `bash -x entrypoint.sh`

We might have a function that expand the OSD_DEVICE incorrectly.

**Comment by alanv72** [comment]
Below are the results...

root@opcs1:/var/lib/docker/containers# docker run -ti --entrypoint=/bin/bash --privileged=true -v /dev/:/dev/ -v /etc/ceph:/etc/ceph -v /var/lib/ceph:/var/lib/ceph ceph/daemon
root@c15b8082d60c:/# export OSD_DEVICE=/dev/sda7 OSD_JOURNAL=/dev/md1 OSD_BLUESTORE=1 OSD_TYPE=activate
root@c15b8082d60c:/# bash -x entrypoint.sh
+ set -e
+ source variables_entrypoint.sh
++ : ceph
++ :
++ :
++ : 0
++ : c15b8082d60c
++ : c15b8082d60c
++ : /var/lib/ceph/mon/ceph-c15b8082d60c
++ : 0
++ : mds-c15b8082d60c
++ : 0
++ : 100
++ : 1
++ : 0
+++ uuidgen
++ : 61af7e8e-3815-496c-b7e5-7ed9e71e9c09
+++ uuidgen
++ : cdddf659-96f3-4b54-8697-60453b6e5850
++ : root=default host=c15b8082d60c
++ : 0
++ : cephfs
++ : cephfs_data
++ : 8
++ : cephfs_metadata
++ : 8
++ : c15b8082d60c
++ :
++ :
++ : 8080
++ : 0
++ : 9000
++ : 0.0.0.0
++ : cephnfs
++ : 0.0.0.0
++ : 5000
++ : /api/v0.1
++ : warning
++ : /var/log/ceph/ceph-restapi.log
++ : none
++ : 127.0.0.1
++ : 4001
++ :
++ :
++ '[' '!' -z '' ']'
++ CEPH_OPTS='--cluster ceph'
++ MOUNT_OPTS='-t xfs -o noatime,inode64'
+ source common_functions.sh
++ set -e
+ case "$KV_TYPE" in
+ source /config.static.sh
++ set -e
++ echo
++ tr '[:upper:]' '[:lower:]'
+ CEPH_DAEMON=
+ case "$CEPH_DAEMON" in
+ '[' '!' -n '' ']'
+ log 'ERROR- One of CEPH_DAEMON or a daemon parameter must be defined as the name '
+ '[' -z 'ERROR- One of CEPH_DAEMON or a daemon parameter must be defined as the name ' ']'
++ date '+%F %T'
+ TIMESTAMP='2017-02-21 20:14:24'
+ echo '2017-02-21 20:14:24  entrypoint.sh: ERROR- One of CEPH_DAEMON or a daemon parameter must be defined as the name '
2017-02-21 20:14:24  entrypoint.sh: ERROR- One of CEPH_DAEMON or a daemon parameter must be defined as the name
+ return 0
+ log 'of the daemon you want to deploy.'
+ '[' -z 'of the daemon you want to deploy.' ']'
++ date '+%F %T'
+ TIMESTAMP='2017-02-21 20:14:24'
+ echo '2017-02-21 20:14:24  entrypoint.sh: of the daemon you want to deploy.'
2017-02-21 20:14:24  entrypoint.sh: of the daemon you want to deploy.
+ return 0
+ log 'Valid values for CEPH_DAEMON are MON, OSD, OSD_DIRECTORY, OSD_CEPH_DISK, OSD_CEPH_DISK_PREPARE, OSD_CEPH_DISK_ACTIVATE, OSD_CEPH_ACTIVATE_JOURNAL, MDS, RGW, RGW_USER, RESTAPI, ZAP_DEVICE, RBD_MIRROR, NFS'
+ '[' -z 'Valid values for CEPH_DAEMON are MON, OSD, OSD_DIRECTORY, OSD_CEPH_DISK, OSD_CEPH_DISK_PREPARE, OSD_CEPH_DISK_ACTIVATE, OSD_CEPH_ACTIVATE_JOURNAL, MDS, RGW, RGW_USER, RESTAPI, ZAP_DEVICE, RBD_MIRROR, NFS' ']'
++ date '+%F %T'
+ TIMESTAMP='2017-02-21 20:14:24'
+ echo '2017-02-21 20:14:24  entrypoint.sh: Valid values for CEPH_DAEMON are MON, OSD, OSD_DIRECTORY, OSD_CEPH_DISK, OSD_CEPH_DISK_PREPARE, OSD_CEPH_DISK_ACTIVATE, OSD_CEPH_ACTIVATE_JOURNAL, MDS, RGW, RGW_USER, RESTAPI, ZAP_DEVICE, RBD_MIRROR, NFS'
2017-02-21 20:14:24  entrypoint.sh: Valid values for CEPH_DAEMON are MON, OSD, OSD_DIRECTORY, OSD_CEPH_DISK, OSD_CEPH_DISK_PREPARE, OSD_CEPH_DISK_ACTIVATE, OSD_CEPH_ACTIVATE_JOURNAL, MDS, RGW, RGW_USER, RESTAPI, ZAP_DEVICE, RBD_MIRROR, NFS
+ return 0
+ log 'Valid values for the daemon parameter are mon, osd, osd_directory, osd_ceph_disk, osd_ceph_disk_prepare, osd_ceph_disk_activate, osd_ceph_activate_journal, mds, rgw, rgw_user, restapi, zap_device, rbd_mirror, nfs'
+ '[' -z 'Valid values for the daemon parameter are mon, osd, osd_directory, osd_ceph_disk, osd_ceph_disk_prepare, osd_ceph_disk_activate, osd_ceph_activate_journal, mds, rgw, rgw_user, restapi, zap_device, rbd_mirror, nfs' ']'
++ date '+%F %T'
+ TIMESTAMP='2017-02-21 20:14:24'
+ echo '2017-02-21 20:14:24  entrypoint.sh: Valid values for the daemon parameter are mon, osd, osd_directory, osd_ceph_disk, osd_ceph_disk_prepare, osd_ceph_disk_activate, osd_ceph_activate_journal, mds, rgw, rgw_user, restapi, zap_device, rbd_mirror, nfs'
2017-02-21 20:14:24  entrypoint.sh: Valid values for the daemon parameter are mon, osd, osd_directory, osd_ceph_disk, osd_ceph_disk_prepare, osd_ceph_disk_activate, osd_ceph_activate_journal, mds, rgw, rgw_user, restapi, zap_device, rbd_mirror, nfs
+ return 0
+ exit 1
root@c15b8082d60c:/#

**Comment by alanv72** [comment]
Add the CEPH_DAEMON in the export command...

root@b8f3b3632619:/# export OSD_DEVICE=/dev/sda7 OSD_JOURNAL=/dev/md1p1 OSD_BLUESTORE=1 OSD_TYPE=activate CEPH_DAEMON=OSD
root@b8f3b3632619:/# bash -x entrypoint.sh
+ set -e
+ source variables_entrypoint.sh
++ : ceph
++ :
++ : OSD
++ : 0
++ : b8f3b3632619
++ : b8f3b3632619
++ : /var/lib/ceph/mon/ceph-b8f3b3632619
++ : 0
++ : mds-b8f3b3632619
++ : 0
++ : 100
++ : 1
++ : 0
+++ uuidgen
++ : 24b54f30-909a-48e0-a0d4-8310cb29e98a
+++ uuidgen
++ : 46e6b3f4-31e2-4c78-9fe8-d766c56fee93
++ : root=default host=b8f3b3632619
++ : 0
++ : cephfs
++ : cephfs_data
++ : 8
++ : cephfs_metadata
++ : 8
++ : b8f3b3632619
++ :
++ :
++ : 8080
++ : 0
++ : 9000
++ : 0.0.0.0
++ : cephnfs
++ : 0.0.0.0
++ : 5000
++ : /api/v0.1
++ : warning
++ : /var/log/ceph/ceph-restapi.log
++ : none
++ : 127.0.0.1
++ : 4001
++ :
++ :
++ '[' '!' -z '' ']'
++ CEPH_OPTS='--cluster ceph'
++ MOUNT_OPTS='-t xfs -o noatime,inode64'
+ source common_functions.sh
++ set -e
+ case "$KV_TYPE" in
+ source /config.static.sh
++ set -e
++ echo OSD
++ tr '[:upper:]' '[:lower:]'
+ CEPH_DAEMON=osd
+ case "$CEPH_DAEMON" in
+ source start_osd.sh
++ set -e
+ start_osd
+ get_config
+ log 'static: does not generate config'
+ '[' -z 'static: does not generate config' ']'
++ date '+%F %T'
+ TIMESTAMP='2017-02-21 21:19:40'
+ echo '2017-02-21 21:19:40  entrypoint.sh: static: does not generate config'
2017-02-21 21:19:40  entrypoint.sh: static: does not generate config
+ return 0
+ check_config
+ [[ ! -e /etc/ceph/ceph.conf ]]
+ create_socket_dir
+ mkdir -p /var/run/ceph
+ chown ceph. /var/run/ceph
+ '[' 0 -eq 1 ']'
+ case "$OSD_TYPE" in
+ source osd_disk_activate.sh
++ set -e
+ osd_activate
+ [[ -z /dev/sda7 ]]
+ mkdir -p /var/lib/ceph/osd
+ chown ceph. /var/lib/ceph/osd
++ readlink -f /dev/sda7
+ ACTUAL_OSD_DEVICE=/dev/sda7
+ [[ ! -z /dev/md1p1 ]]
+ timeout 10 bash -c 'while [ ! -e /dev/sda7 ]; do sleep 1; done'
+ chown ceph. /dev/md1p1
+ [[ 0 -eq 1 ]]
++ dev_part /dev/sda7 1
++ [[ -L /dev/sda7 ]]
++ [[ 7 == [0-9] ]]
++ echo /dev/sda7p1
+ ceph-disk -v --setuser ceph --setgroup disk activate --no-start-daemon /dev/sda7p1
main_activate: path = /dev/sda7p1
get_dm_uuid: get_dm_uuid /dev/sda7p1 uuid path is /sys/dev/block/8:7/dm/uuid
command: Running command: /sbin/blkid -o udev -p /dev/sda7p1
command: Running command: /sbin/blkid -p -s TYPE -o value -- /dev/sda7p1
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_mount_options_btrfs
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_fs_mount_options_btrfs
mount: Mounting /dev/sda7p1 on /var/lib/ceph/tmp/mnt.G_BOzf with options noatime,user_subvol_rm_allowed
command_check_call: Running command: /bin/mount -t btrfs -o noatime,user_subvol_rm_allowed -- /dev/sda7p1 /var/lib/ceph/tmp/mnt.G_BOzf
activate: Cluster uuid is c707f1d3-0efa-49c2-ab5f-1fabc540ac5a
command: Running command: /usr/bin/ceph-osd --cluster=ceph --show-config-value=fsid
activate: Cluster name is ceph
activate: OSD uuid is 3cb9c180-0421-4068-8b19-8d471943f6c1
activate: OSD id is 21
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup init
command: Running command: /usr/bin/ceph-detect-init --default sysvinit
activate: Marking with init system systemd
command: Running command: /bin/chown -R ceph:ceph /var/lib/ceph/tmp/mnt.G_BOzf/systemd
activate: ceph osd.21 data dir is ready at /var/lib/ceph/tmp/mnt.G_BOzf
move_mount: Moving mount to final location...
command_check_call: Running command: /bin/mount -o noatime,user_subvol_rm_allowed -- /dev/sda7p1 /var/lib/ceph/osd/ceph-21
command_check_call: Running command: /bin/umount -l -- /var/lib/ceph/tmp/mnt.G_BOzf
++ awk '{print $2}'
+++ dev_part /dev/sda7 1
+++ [[ -L /dev/sda7 ]]
+++ [[ 7 == [0-9] ]]
+++ echo /dev/sda7p1
++ grep -oh '[0-9]*'
++ grep /dev/sda7p1 /proc/mounts
+ OSD_ID=
root@b8f3b3632619:/#

**Comment by leseb** [comment]
So that's an issue with the `dev_part` function.

**Comment by alanv72** [comment]
Somewhere here you have logical that isn't detecting the partition correctly.

[[ 0 -eq 1 ]]
++ dev_part /dev/sda7 1
++ [[ -L /dev/sda7 ]]
++ [[ 7 == [0-9] ]]
++ echo /dev/sda7p1
ceph-disk -v --setuser ceph --setgroup disk activate --no-start-daemon /dev/sda7p1
main_activate: path = /dev/sda7p1

It seems like creating symlinks for /dev/sda7p1 to dev/sda7 got me further down the road, but my docker OSD daemon isn't coming up after run.

root@opcs1:/var/lib/docker/containers# docker run -d --net=host --pid=host --privileged=true -v /etc/ceph:/etc/ceph -v /var/lib/ceph:/var/lib/ceph -v /dev/:/dev/ -e OSD_DEVICE=/dev/sda7 -e OSD_JOURNAL=/dev/md1p1 -e OSD_BLUESTORE=1 ceph/daemon osd
765df3f8f40e9f08ce4b25ee3f7a3865d6bd76586b27d466ee0a4abab15c0709
root@opcs1:/var/lib/docker/containers# docker ps -a
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS                     PORTS               NAMES
765df3f8f40e        ceph/daemon         "/entrypoint.sh osd"   7 seconds ago       Exited (1) 4 seconds ago                       loving_nobel
root@opcs1:/var/lib/docker/containers# docker logs 765df3f8f40e
2017-02-21 21:27:44  /entrypoint.sh: static: does not generate config
2017-02-21 21:27:44  /entrypoint.sh: Device detected, assuming ceph-disk scenario is desired
2017-02-21 21:27:44  /entrypoint.sh: Preparing and activating /dev/sda7
2017-02-21 21:27:44.462922 7f62a5877700 -1 WARNING: the following dangerous and experimental features are enabled: bluestore
2017-02-21 21:27:44.470584 7f62a5877700 -1 WARNING: the following dangerous and experimental features are enabled: bluestore
HEALTH_ERR 64 pgs are stuck inactive for more than 300 seconds; 64 pgs stuck inactive; 64 pgs stuck unclean
command: Running command: /usr/bin/ceph-osd --cluster=ceph --show-config-value=fsid
get_dm_uuid: get_dm_uuid /dev/sda7 uuid path is /sys/dev/block/8:7/dm/uuid
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup bluestore_block_size
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup bluestore_block_db_size
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup bluestore_block_wal_size
get_dm_uuid: get_dm_uuid /dev/sda7 uuid path is /sys/dev/block/8:7/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sda7 uuid path is /sys/dev/block/8:7/dm/uuid
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_mkfs_type
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_mkfs_options_btrfs
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_fs_mkfs_options_btrfs
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_mount_options_btrfs
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_fs_mount_options_btrfs
get_dm_uuid: get_dm_uuid /dev/sda7 uuid path is /sys/dev/block/8:7/dm/uuid
set_data_partition: OSD data device /dev/sda7 is a partition
get_dm_uuid: get_dm_uuid /dev/sda7 uuid path is /sys/dev/block/8:7/dm/uuid
command: Running command: /sbin/blkid -o udev -p /dev/sda7
set_data_partition: incorrect partition UUID: 0x83, expected ['4fbd7e29-9d25-41b8-afd0-5ec00ceff05d', '4fbd7e29-9d25-41b8-afd0-062c0ceff05d', '4fbd7e29-8ae0-4982-bf9d-5a8d867af560', '4fbd7e29-9d25-41b8-afd0-35865ceff05d']
populate_data_path_device: Creating btrfs fs on /dev/sda7
command_check_call: Running command: /sbin/mkfs -t btrfs -f -m single -l 32768 -n 32768 -- /dev/sda7
WARNING: --leafsize is deprecated, use --nodesize
btrfs-progs v4.4
See http://btrfs.wiki.kernel.org for more information.

Label:              (null)
UUID:               a39632a8-1441-4394-990b-8d67642d3953
Node size:          32768
Sector size:        4096
Filesystem size:    449.12GiB
Block group profiles:
  Data:             single            8.00MiB
  Metadata:         single            8.00MiB
  System:           single            4.00MiB
SSD detected:       yes
Incompat features:  extref, skinny-metadata
Number of devices:  1
Devices:
   ID        SIZE  PATH
    1   449.12GiB  /dev/sda7

mount: Mounting /dev/sda7 on /var/lib/ceph/tmp/mnt.PUhM6M with options noatime,user_subvol_rm_allowed
command_check_call: Running command: /bin/mount -t btrfs -o noatime,user_subvol_rm_allowed -- /dev/sda7 /var/lib/ceph/tmp/mnt.PUhM6M
populate_data_path: Preparing osd data dir /var/lib/ceph/tmp/mnt.PUhM6M
command: Running command: /bin/chown -R ceph:ceph /var/lib/ceph/tmp/mnt.PUhM6M/ceph_fsid.20789.tmp
command: Running command: /bin/chown -R ceph:ceph /var/lib/ceph/tmp/mnt.PUhM6M/fsid.20789.tmp
command: Running command: /bin/chown -R ceph:ceph /var/lib/ceph/tmp/mnt.PUhM6M/magic.20789.tmp
command: Running command: /bin/chown -R ceph:ceph /var/lib/ceph/tmp/mnt.PUhM6M/type.20789.tmp
command: Running command: /bin/chown -R ceph:ceph /var/lib/ceph/tmp/mnt.PUhM6M
unmount: Unmounting /var/lib/ceph/tmp/mnt.PUhM6M
command_check_call: Running command: /bin/umount -- /var/lib/ceph/tmp/mnt.PUhM6M
get_dm_uuid: get_dm_uuid /dev/sda7 uuid path is /sys/dev/block/8:7/dm/uuid
main_activate: path = /dev/sda7p1
get_dm_uuid: get_dm_uuid /dev/sda7p1 uuid path is /sys/dev/block/8:7/dm/uuid
command: Running command: /sbin/blkid -o udev -p /dev/sda7p1
command: Running command: /sbin/blkid -p -s TYPE -o value -- /dev/sda7p1
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_mount_options_btrfs
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_fs_mount_options_btrfs
mount: Mounting /dev/sda7p1 on /var/lib/ceph/tmp/mnt.ZKRQ9X with options noatime,user_subvol_rm_allowed
command_check_call: Running command: /bin/mount -t btrfs -o noatime,user_subvol_rm_allowed -- /dev/sda7p1 /var/lib/ceph/tmp/mnt.ZKRQ9X
activate: Cluster uuid is c707f1d3-0efa-49c2-ab5f-1fabc540ac5a
command: Running command: /usr/bin/ceph-osd --cluster=ceph --show-config-value=fsid
activate: Cluster name is ceph
activate: OSD uuid is 318b607c-8122-4bea-ad7c-9c2c71cba155
allocate_osd_id: Allocating OSD id...
command: Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring osd create --concise 318b607c-8122-4bea-ad7c-9c2c71cba155
command: Running command: /bin/chown -R ceph:ceph /var/lib/ceph/tmp/mnt.ZKRQ9X/whoami.20855.tmp
activate: OSD id is 23
activate: Initializing OSD...
command_check_call: Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring mon getmap -o /var/lib/ceph/tmp/mnt.ZKRQ9X/activate.monmap
2017-02-21 21:27:45.718759 7fa4c5827700 -1 WARNING: the following dangerous and experimental features are enabled: bluestore
2017-02-21 21:27:45.724562 7fa4c5827700 -1 WARNING: the following dangerous and experimental features are enabled: bluestore
got monmap epoch 3
command: Running command: /usr/bin/timeout 300 ceph-osd --cluster ceph --mkfs --mkkey -i 23 --monmap /var/lib/ceph/tmp/mnt.ZKRQ9X/activate.monmap --osd-data /var/lib/ceph/tmp/mnt.ZKRQ9X --osd-uuid 318b607c-8122-4bea-ad7c-9c2c71cba155 --keyring /var/lib/ceph/tmp/mnt.ZKRQ9X/keyring --setuser ceph --setgroup ceph
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup init
command: Running command: /usr/bin/ceph-detect-init --default sysvinit
activate: Marking with init system systemd
command: Running command: /bin/chown -R ceph:ceph /var/lib/ceph/tmp/mnt.ZKRQ9X/systemd
activate: Authorizing OSD key...
command_check_call: Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring auth add osd.23 -i /var/lib/ceph/tmp/mnt.ZKRQ9X/keyring osd allow * mon allow profile osd
2017-02-21 21:27:47.611310 7f3953f76700 -1 WARNING: the following dangerous and experimental features are enabled: bluestore
2017-02-21 21:27:47.620934 7f3953f76700 -1 WARNING: the following dangerous and experimental features are enabled: bluestore
added key for osd.23
command: Running command: /bin/chown -R ceph:ceph /var/lib/ceph/tmp/mnt.ZKRQ9X/active.20855.tmp
activate: ceph osd.23 data dir is ready at /var/lib/ceph/tmp/mnt.ZKRQ9X
move_mount: Moving mount to final location...
command_check_call: Running command: /bin/mount -o noatime,user_subvol_rm_allowed -- /dev/sda7p1 /var/lib/ceph/osd/ceph-23
command_check_call: Running command: /bin/umount -l -- /var/lib/ceph/tmp/mnt.ZKRQ9X
root@opcs1:/var/lib/docker/containers#

from monitor:
root@opcm1:/etc/ceph# docker exec bec1806a80f6 ceph -w
    cluster c707f1d3-0efa-49c2-ab5f-1fabc540ac5a
     health HEALTH_ERR
            64 pgs are stuck inactive for more than 300 seconds
            64 pgs stuck inactive
            64 pgs stuck unclean
     monmap e3: 2 mons at {opcm1=10.100.45.113:6789/0,opcm2=10.100.45.114:6789/0}
            election epoch 8, quorum 0,1 opcm1,opcm2
        mgr no daemons active
     osdmap e25: 24 osds: 0 up, 0 in
            flags sortbitwise,require_jewel_osds,require_kraken_osds
      pgmap v26: 64 pgs, 1 pools, 0 bytes data, 0 objects
            0 kB used, 0 kB / 0 kB avail
                  64 creating

2017-02-21 21:27:47.712778 mon.0 [INF] from='client.? 10.100.45.107:0/2657854337' entity='client.bootstrap-osd' cmd='[{"prefix": "auth add", "entity": "osd.23", "caps": ["osd", "allow *", "mon", "allow profile osd"]}]': finished

**Comment by leseb** [comment]
A couple of things:

* bluestore support is not optimal at the moment so we have a really limited set of functionality
* `OSD_JOURNAL=/dev/md1` won't work since this is only for filestore
* we do not support already partitioned devices (as you noticed), I opened https://github.com/ceph/ceph-docker/issues/512

I'm currently trying to bootstrap a bluestore OSD, without luck, I'll keep you posted.

**Comment by alanv72** [comment]
Thanks for tracking this Sébastien.

I'll drop the bluestore option for now and do the traditional filestore.

In theory, I should be able to make a md devices in raid0 with the partition of the sd device and use the md devices for the data disk and journals. I'm going to try this as a work around for the limitation noted in #512.

**Comment by alanv72** [comment]
tried to failback to manually creating OSD dir and symlink jorunal and using the OSD_TYPE=directory

Getting this error..
root@opcs1:/etc/ceph# docker run -d --privileged=true --net=host -v /etc/ceph:/etc/ceph/ -v /var/lib/ceph/:/var/lib/ceph/ -v /dev/:/dev/ -e OSD_Type=directory ceph/daemon osd
260f0b5f0e384170b55e82ee79d71b6d7a84b05384a50a6bfb9f87734e124578
root@opcs1:/etc/ceph# docker ps -a
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS                       PORTS               NAMES
260f0b5f0e38        ceph/daemon         "/entrypoint.sh osd"   5 seconds ago       Exited (127) 4 seconds ago                       infallible_elion
b17d60fd9988        ceph/daemon         "/entrypoint.sh osd"   3 minutes ago       Exited (127) 3 minutes ago                       fervent_mestorf
root@opcs1:/etc/ceph# docker logs 2
2017-02-25 05:42:47  /entrypoint.sh: static: does not generate config
2017-02-25 05:42:47  /entrypoint.sh: Bootstrapped OSD(s) found; using OSD directory
common_functions.sh: line 89: osd_directory: command not found
root@opcs1:/etc/ceph#

**Comment by leseb** [comment]
Make sure you have the last version of the image, I recently pushed a fix for that.

**Comment by alanv72** [comment]
Same error after verifying that i have the latest image...

root@opcs1:/etc/ceph# docker images ceph/daemon
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
ceph/daemon         latest              de25f619ac92        10 days ago         1.149 GB
root@opcs1:/etc/ceph# docker pull ceph/daemon
Using default tag: latest
latest: Pulling from ceph/daemon
Digest: sha256:c4debf06c5e7e58d7424de7e37bd2b3802aa2ca82cd426bba339aeabba537852
Status: Image is up to date for ceph/daemon:latest
root@opcs1:/etc/ceph# docker run -d --privileged=true --net=host -v /etc/ceph:/etc/ceph/ -v /var/lib/ceph/:/var/lib/ceph/ -v /dev/:/dev/ -e OSD_Type=directory ceph/daemon osd
0662a2ee5ef6501576be22ffe8c5866e863743cbce576c0d19d9f07db468706e
root@opcs1:/etc/ceph# docker logs
0662a2ee5ef6501576be22ffe8c5866e863743cbce576c0d19d9f07db468706e  sad_hawking
root@opcs1:/etc/ceph# docker logs 0662a2ee5ef6501576be22ffe8c5866e863743cbce576c0d19d9f07db468706e
2017-03-01 03:11:11  /entrypoint.sh: static: does not generate config
2017-03-01 03:11:11  /entrypoint.sh: Bootstrapped OSD(s) found; using OSD directory
common_functions.sh: line 89: osd_directory: command not found
root@opcs1:/etc/ceph#

**Comment by alanv72** [comment]
Finally have an OSD up on SD partition and journal on MD partition... Here was the work around... Manually created the ceph disk..

Point the journal manually..
$ rm /var/lib/ceph/osd/ceph-1/journal
$ ln -s /dev/sde1 /var/lib/ceph/osd/ceph-1/journal

### Create new journal
$ ceph-osd --mkjournal -i 1

Then running this:
docker run -d --privileged=true --net=host -v /etc/ceph:/etc/ceph/ -v /var/lib/ceph/:/var/lib/ceph/ -v /dev/:/dev/ -e OSD_Type=directory ceph/daemon osd_directory_single

root@opcs1:/etc/ceph# docker logs 9006f73f0453a7294d7064debaa4053341e9c94131e3dd5364e51956773cf072
2017-03-01 03:24:11  /entrypoint.sh: static: does not generate config
2017-03-01 03:24:11  /entrypoint.sh: Looks like OSD: 1 is not started, starting it...
2017-03-01 03:24:11  /entrypoint.sh: SUCCESS
starting osd.1 at - osd_data /var/lib/ceph/osd/ceph-1 /var/lib/ceph/osd/ceph-1/journal
2017-03-01 03:24:11.880076 7f780b501a40 -1 osd.1 0 log_to_monitors {default=true}

From monitor using ceph -w:
2017-03-01 03:24:11.871370 mon.0 [INF] from='osd.1 10.100.50.110:6800/1' entity='osd.1' cmd=[{"prefix": "osd crush create-or-move", "id": 1, "weight":0.4386, "args": ["host=opcs1", "root=default"]}]: dispatch
2017-03-01 03:24:11.872192 mon.0 [INF] from='osd.1 10.100.50.110:6800/1' entity='osd.1' cmd=[{"prefix": "osd create", "id": 1, "uuid": "db10d3b5-3d69-4d1c-a99d-1f30593b194e"}]: dispatch
2017-03-01 03:24:11.934509 mon.0 [INF] from='osd.1 10.100.50.110:6800/1' entity='osd.1' cmd='[{"prefix": "osd create", "id": 1, "uuid": "db10d3b5-3d69-4d1c-a99d-1f30593b194e"}]': finished
2017-03-01 03:24:11.936404 mon.0 [INF] osdmap e7: 2 osds: 0 up, 1 in
2017-03-01 03:24:11.936974 mon.0 [INF] from='osd.1 10.100.50.110:6800/1' entity='osd.1' cmd=[{"prefix": "osd crush create-or-move", "id": 1, "weight":0.4386, "args": ["host=opcs1", "root=default"]}]: dispatch
2017-03-01 03:24:11.939969 mon.0 [INF] pgmap v8: 64 pgs: 64 creating; 0 bytes data, 0 kB used, 0 kB / 0 kB avail
2017-03-01 03:24:12.939030 mon.0 [INF] from='osd.1 10.100.50.110:6800/1' entity='osd.1' cmd='[{"prefix": "osd crush create-or-move", "id": 1, "weight":0.4386, "args": ["host=opcs1", "root=default"]}]': finished
2017-03-01 03:24:12.940759 mon.0 [INF] osdmap e8: 2 osds: 0 up, 1 in
2017-03-01 03:24:12.949186 mon.0 [INF] pgmap v9: 64 pgs: 64 creating; 0 bytes data, 0 kB used, 0 kB / 0 kB avail
2017-03-01 03:24:13.950839 mon.0 [INF] osd.1 10.100.50.110:6800/1 boot
2017-03-01 03:24:13.954585 mon.0 [INF] osdmap e9: 2 osds: 1 up, 1 in
2017-03-01 03:24:13.963956 mon.0 [INF] pgmap v10: 64 pgs: 64 creating; 0 bytes data, 0 kB used, 0 kB / 0 kB avail
2017-03-01 03:24:14.965852 mon.0 [INF] osdmap e10: 2 osds: 1 up, 1 in
2017-03-01 03:24:14.975024 mon.0 [INF] pgmap v11: 64 pgs: 64 creating; 0 bytes data, 0 kB used, 0 kB / 0 kB avail
2017-03-01 03:24:17.925931 mon.0 [INF] pgmap v12: 64 pgs: 64 undersized+degraded+peered; 0 bytes data, 1037 MB used, 448 GB / 449 GB avail
2017-03-01 03:24:22.923234 mon.0 [INF] pgmap v13: 64 pgs: 64 undersized+degraded+peered; 0 bytes data, 1037 MB used, 448 GB / 449 GB avail
2017-03-01 03:24:46.046308 mon.0 [INF] HEALTH_ERR; 64 pgs are stuck inactive for more than 300 seconds; 64 pgs degraded; 64 pgs stuck inactive; 64 pgs stuck unclean; 64 pgs undersized

**Comment by leseb** [comment]
I pretty sure this issue is solved here: https://github.com/ceph/ceph-docker/blob/master/ceph-releases/kraken/ubuntu/16.04/daemon/common_functions.sh#L111-L112

If you go into your container image do you see these lines?

**Comment by hamid80386** [comment]
> I pretty sure this issue is solved here: https://github.com/ceph/ceph-docker/blob/master/ceph-releases/kraken/ubuntu/16.04/daemon/common_functions.sh#L111-L112
> 
> If you go into your container image do you see these lines?

The link is broken :-\

**Comment by dsavineau** [comment]
> The link is broken :-\

Because that's the old project repository which doesn't exist anymore.

You can still retrieve the information here : https://github.com/ceph/ceph-container/blob/26e3d0325026105e033522b6bf12c8820e96f87c/ceph-releases/kraken/ubuntu/16.04/daemon/common_functions.sh#L111-L112
