### ISSUE TITLE
It's still too complex to init a ceph cluster. Maybe a docker-swarm.yml would help a lot.

### ISSUE THREAD

**Issue by cailiang9** [ceph/ceph-container#523]
Then users will only need to specify no of each kinds of nodes and 1-2 env variable.

**Comment by leseb** [comment]
I don't know anything about Docker Swarm. What's the issue? Where is the stuggle?

**Comment by cailiang9** [comment]
I just hope there's a one-line command to start the ceph cluster. users just need to specify the storage location and running nodes .

**Comment by leseb** [comment]
Well we currently have one command line per Ceph daemon.

**Comment by sepich** [comment]
Unfortunately Swarm deployment doesn't look so easy:
https://github.com/sepich/ceph-swarm

**Comment by pascalandy** [comment]
If this can help, this is how a docker swarm users would like to try ceph on his docker swarm. https://firepress.org/blog/the-complete-guide-to-attach-a-docker-volume-with-minio-on-your-docker-swarm-cluster/

**Comment by xirius** [comment]
@pascalandy Unfortunately your link is not accessible anymore :(

**Comment by pascalandy** [comment]
Just updated the link :)

**Comment by xirius** [comment]
@pascalandy Thanks for the re-post.  Minio is excellent for Object Storage but unfortunately MinFS was deprecated and I was not able to find a decent alternative :(
