### ISSUE TITLE
Using PPA ?

### ISSUE THREAD

**Issue by ErwanAliasr1** [ceph/ceph-container#558]
On build https://jenkins.ceph.com/job/ceph-docker-prs-ceph_ansible-kraken-xenial_cluster/179/console, we fail because of

The following packages have unmet dependencies:
 nfs-ganesha-fsal : Depends: glusterfs-common (>= 3.8.8) but it is not going to be installed: Unable to correct problems, you have held broken packages

The packages are coming from a PPA. Is it safe to build our containers against a PPA which is pretty unsupported ? Can't we find a more reliable stream of package ?

**Comment by ktdreyer** [comment]
At this point I think we should stop using the PPA and use Shaman (I've done this for CentOS 7 in https://github.com/ceph/ceph-docker/pull/539). The RGW FSAL is under heavy development today, and there are some bugfixes that introduce strict dependencies on the very latest `LIBRGW_FILE_VER` from Ceph. Maybe in six months this will be more stable and flexible.

**Comment by andrewschoen** [comment]
@ktdreyer I think using the nfs-ganesha repo from shaman is fine, but if we plan to use it like this we'll need to add some config to chacra to ensure that we always have a nfs-ganesha repo available in shaman. I think it's built often enough we wont have to worry, but better safe than sorry.

We do something similar for a few other projects: https://github.com/ceph/chacra/blob/master/deploy/playbooks/roles/common/templates/prod.py.j2#L126
