### ISSUE TITLE
Kubernetes-Ceph Issues

### ISSUE THREAD

**Issue by J-Ha** [ceph/ceph-container#587]
I'm deploying Ceph by the Kubernetes Helm Example.

The default configuration with 
values.yaml |
  daemon: docker.io/ceph/daemon:latest issues with  [Issue #573](https://github.com/ceph/ceph-docker/issues/573)

values.yaml |
 daemon: docker.io/ceph/daemon:tag-build-master-jewel-ubuntu-14.04 starts up the Cluster.

Next Issue, when i stop the Ceph Cluster and start it again, the OSD's keeps rebooting in Crashloop with [Issue #510 ](https://github.com/ceph/ceph-docker/issues/510)

disabling the Auth will solve the Issue.
But when auth is disabled, my Ceph-Mons arent able to connect by PV/C to my containers. 

So im not able to set-up a persistent CephFS storage for my cluster.

**Comment by leseb** [comment]
I need to build a k8s env to reproduce that, every installers I've found failed for me... Any hint on how to install k8s with vagrant + libvirt?
Thanks!

**Comment by osixia** [comment]
@leseb alternativley to quickly set up a testing kubernetes single node cluster you can use https://github.com/kubernetes/minikube it comes with dns and dashboard

**Comment by leseb** [comment]
@osixia I'll give a try, thanks!

**Comment by yu-yang2** [comment]
@J-Ha Did you solve the problem? I have met the same problem.
