### ISSUE TITLE
Getting started instructions

### ISSUE THREAD

**Issue by lgleim** [ceph/ceph-container#592]
Why isn't there a simple to follow getting started tutorial for ceph-docker similar to the regular version (http://ceph.com/install/)? If there is one (I wasn't able to find it), could you please link to it from the Readme?

**Comment by leseb** [comment]
We have a README here: https://github.com/ceph/ceph-docker/tree/master/ceph-releases/jewel/ubuntu/14.04/daemon

We also have a supported deployment with ceph-ansible.
I know we need to improve the "getting started instructions". It just depends on how you want to deploy it.
