### ISSUE TITLE
ceph docker ansible setup

### ISSUE THREAD

**Issue by gator1** [ceph/ceph-container#600]
Could anyone tell me in this project's ansible setup video, how were the containers started?

In the video he has five containers running already. I think the container is ceph-daemon. 

What arguments that he uses to run it? docker run -d options ceph-daemon?

What are the options? 

what make the ansible node talk to the other nodes? I know sshd is not running on the containers.

**Comment by gator1** [comment]
@leseb you could just provide a little bit more info and your project would be so much easier to use. Thanks!

**Comment by leseb** [comment]
We are currently building a documentation to help out.
@alfredodeza what's the URL again?

Thanks!

**Comment by gator1** [comment]
My goal is to run multiple dockers on a single physical server to run a ceph cluster, no VMs. 
In this project's manual setup video (not sound, only commands live) he used three different machines (I assume they are VMs), each running a docker container for ceph monitor. This has its value but not what I want; I already setup ceph using a bunch of VMs. 

I am hoping to set up a ceph cluster with docker containers on a single PC. I know this is doable since Kolla did it for its openstack in docker. 

So I want to follow the ansible setup video. 
My current issues are:
1. I assume that I would need to have containers running first without ceph. ceph/daemon has all the ceph daemon installed already so I thought we should use ceph/base. I think ceph-ansible is smart so it won't re-install stuff so maybe ceph/daemon is ok. But ceph/daemon needs its role to run and I really need to see how each node is started. 

2 I assume ceph-ansible needs to ssh to each node to work (I could be wrong but this is how I set ceph up on VMs). ceph/daemon doesn't run sshd. So how does this work?

@leseb those are simple questions and if you could  just answer them, I am on my merry way, thanks!

**Comment by alfredodeza** [comment]
@leseb for ceph-docker we don't have anything yet, for ceph-ansible we are working on getting sections for testing at http://docs.ceph.com/ceph-ansible

**Comment by gator1** [comment]
@leseb @alfredodeza 
If you can just clarify what the ansible video demo's initial setup is, it would be great help. I gained enough knowledge in the last month setting up ceph on vm. If I can get the five containers up and running I probably could make a ceph cluster and I will write a step by step instruction afterwards.

**Comment by gator1** [comment]
Or maybe with ansible the five nodes are VMs and ansible can ssh to the VM and set them up to run ceph/daemon. If that's how the ansible demo was set up, my assumption would be wrong.

**Comment by gator1** [comment]
I am able to set up a test ceph cluster with docker containers. Here is a step by step guide. 

I like to post a pull request to make it part of ceph docker so that newbies like me can have an easier time to set ceph up with containers.

https://github.com/gator1/jepsen/tree/master/ceph-docker
