### ISSUE TITLE
ceph-mon on Kubernetes v1.6.1 stuck in CrashLoopBackOff

### ISSUE THREAD

**Issue by garberg** [ceph/ceph-container#607]
I followed the guide at https://github.com/ceph/ceph-docker/tree/master/examples/kubernetes to deploy ceph on Kubernetes v1.6.1 and after the initial ```kubectl create```, ```kubectl get all --namespace=ceph``` returns the following:
```
$ kubectl get all --namespace=ceph
NAME                                 READY     STATUS             RESTARTS   AGE
po/ceph-mds-2188600605-hb0rs         0/1       Pending            0          23h
po/ceph-mon-2373451478-26kh8         0/1       CrashLoopBackOff   280        23h
po/ceph-mon-2373451478-bcwlh         0/1       CrashLoopBackOff   280        23h
po/ceph-mon-2373451478-tmj8c         0/1       CrashLoopBackOff   280        23h
po/ceph-mon-check-2529003130-w3s1r   1/1       Running            0          23h

NAME           CLUSTER-IP   EXTERNAL-IP   PORT(S)    AGE
svc/ceph-mon   None         <none>        6789/TCP   23h

NAME                    DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/ceph-mds         1         1         1            0           23h
deploy/ceph-mon         3         3         3            0           23h
deploy/ceph-mon-check   1         1         1            1           23h

NAME                           DESIRED   CURRENT   READY     AGE
rs/ceph-mds-2188600605         1         1         0         23h
rs/ceph-mon-2373451478         3         3         0         23h
rs/ceph-mon-check-2529003130   1         1         1         23h
```

Examining why ceph-mon fails to start with ```kubectl logs``` returns the following:
```
$ kubectl logs po/ceph-mon-2373451478-26kh8 --namespace=ceph
Error from server (Forbidden): User "system:serviceaccount:ceph:default" cannot list pods in the namespace "ceph". (get pods)
```

**Comment by flemzord** [comment]
Use env var : 

- name: NETWORK_AUTO_DETECT
   value: "4"

**Comment by ReSearchITEng** [comment]
@garberg : it's due to rbac of 1.6.x
If you want to get over it (in the unsecured way), before deploying ceph, give all perms like this:
```kubectl create -f https://github.com/ReSearchITEng/kubeadm-playbook/raw/master/allow-all-all-rbac.yml```

Passing that, and few other issues with the helm chart in the examples section, I reached another issue (resulting again in CrashLoopBackOff).
@flemzord
Tried two options, none worked :
1.  NETWORK_AUTO_DETECT=0, and CEPH_PUBLIC_NETWORK="10.244.0.0/16"  (I am using flannel)
2. NETWORK_AUTO_DETECT=4 (and no CEPH_PUBLIC_NETWORK var).
I tried on k8s 1.7.0-alpha2 and 3
It crashes and logs are empty:
```
ks logs po/ceph-mon-0
No resources found.
No resources found.
No resources found.
No resources found.
No resources found.
No resources found.
No resources found.
No resources found.
No resources found.
No resources found.
```
I tried most of the images of docker.io/ceph/daemon available, both old and new:
latest, tag-build-master-luminous-centos-7, tag-build-master-kraken-centos-7, etc.

**Comment by erinboyd** [comment]
Is this still an issue?

**Comment by pokoli** [comment]
I can reproduce it on kubernetes 1.7.1. I think we should create RBAC rules for kubernetes to enable the role list the required resources.

I applied the rules posted by @ReSearchITEng and everything worked well. Having said that, the all-all scares my a little bit. Don't kwow if more fine grained rules can be provided.

**Comment by JrCs** [comment]
@pokoli i have create a rolebinding to allow a ceph serviceaccount to have admin privileged only on the same namespace the serviceaccount is defined:
```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ceph
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: ceph-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: ceph
  namespace: ceph
```

**Comment by pokoli** [comment]
@JrCs great. Then it will be great to include it on the examples folder. You should create a Pull Request for it.
