### ISSUE TITLE
helm charts out of sync with kubernetes deployment

### ISSUE THREAD

**Issue by ReSearchITEng** [ceph/ceph-container#639]
helm charts out of sync with k8s deployment
This should not be the case as helm chart is mainly a packager for k8s.
IMHO, we need:
1. sync helm with existing k8s deployment - one time, manual effort
2. a solution to keep them in sync long term
    Suggestion for point 2: if we always update the helm charts, the k8s artifacts can be generated by `helm install --dry-run --debug` and output released to be consumed for non-helm users.

Comments, suggestions, ideas?

**Comment by leseb** [comment]
Is it something we should automate through CI?

**Comment by ReSearchITEng** [comment]
for solving 2, yes, it is required to run that helm command which would create from the helm package the kubernetes ready yamls, with all values resolved.

**Comment by IronhandedLayman** [comment]
The main thing to fix for this latest deploy is the switch from `storage.k8s.io/v1beta1` to `storage.k8s.io/v1`. I think there are other issues too (my deploy's getting a lot of CrashLoopBackOff errors), but that change at least lets the helm chart run. It'd be cool if there were some automatic scanning tool that could automatically migrate API spaces between k8s versions.

**Comment by pokoli** [comment]
I'm wondering if it won't be better to base the development on helm (which will remove the templating part) and then remove the generated yamls in favour of the helm packages.
