### ISSUE TITLE
Afaik, jinja2 cli is "j2" (instead of jinja2) I changed it to j2 and it works.

### ISSUE THREAD

**Issue by ReSearchITEng** [ceph/ceph-container#640]
@timn
```
./generate_secrets.sh: line 15: jinja2: command not found
```
jinja2 cli is "j2" (instead of jinja2)
I changed it to j2 and it works.
With regards to "Merge pull request #618 from timn/master"

**Comment by timn** [comment]
On Fedora it's jinja2 indeed. There seems to be https://pypi.python.org/pypi/j2cli and https://pypi.python.org/pypi/jinja2-cli. I have used the latter as it is readily available on Fedora. Is it available on your system, too?

Otherwise I can extend it to check for both and pick what is found.

**Comment by ReSearchITEng** [comment]
Yes @timn, please extend it to support j2 as well.
