### ISSUE TITLE
rbd: image  is locked by other nodes

### ISSUE THREAD

**Issue by ReSearchITEng** [ceph/ceph-container#642]
All examples (both the ones in readme and or pv/pvs) that I am trying, fail with the same error:
rbd: image ... is locked by other nodes
I checked with rbd lock list, and there are no locks.
Strange is that the error comes even when there are no rbd images yet...
I am testing on k8s 1.6.3 and also tried on 1.7.0-alpha.3.
Any suggestions?
```
  4m            1m              2       kubelet,  machine1                     Warning         FailedMount     Unable to mount volumes for pod "task-pv-pod_ceph(daef8169-3a2e-11e7-a3a3-0050569120ff)": timeout expired waiting for volumes to attach/mount for pod "ceph"/"task-pv-pod". list of unattached/unmounted volumes=[task-pv-storage]
  4m            1m              2       kubelet,  machine1                     Warning         FailedSync      Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "ceph"/"task-pv-pod". list of unattached/unmounted volumes=[task-pv-storage]
  6m            1s              11      kubelet,  machine1                     Warning         FailedMount     MountVolume.SetUp failed for volume "kubernetes.io/rbd/daef8169-3a2e-11e7-a3a3-0050569120ff-cephpv1" (spec.Name: "cephpv1") pod "daef8169-3a2e-11e7-a3a3-0050569120ff" (UID: "daef8169-3a2e-11e7-a3a3-0050569120ff") with: rbd: image c1 is locked by other nodes
```

**Comment by dpwanjala** [comment]
Experiencing the same issue with k8s 1.6.1

**Comment by kokhang** [comment]
@dpwanjala did you install ceph-common package on all the nodes? Sometimes this error shows when the rbd command is not installed on the node

**Comment by dpwanjala** [comment]
@kokhang .Yes I have,I am using the kubernetes with coreos example and therefore using the image provided for the tools.Everything works well and I can create volumes and mount file systems as long as I don't restart my node.This error occurs immediately I do restart any node in the cluster

**Comment by likunbyl** [comment]
If you access mon using domain name, you may encounter this error. try to use ip instead .

**Comment by mossinfan** [comment]
@likunbyl 
I use the ip address to access the mon , but still meet the same problem
Have you solve it ?

**Comment by leseb** [comment]
Are you using Ceph as a driver to provide persistent storage to container? Like PVC?

**Comment by PellePedro** [comment]
I ran into this issue "rbd: image is locked by other nodes",  when connecting to an external ceph cluster with dynamic provisioning (storage classes) in kubernetes.

The findings is that if the rbd command is executed with the -m flag e.g. "rbd lock list -m <mon ip> --id <id> ..." , and there is no configuration file (ceph.conf) under /etc/ceph  .... then the rbd command will print out information that the configuration file is not used  e.g. "7f27de2517c0 -1 did not load config file, using default settings."  This is the normal case as the ceps-common does not install a ceph.conf file.

The rbd Volume Attach logic in kubernetes is building up a command string and execute the "raw" command "rbd lock list ..." (https://raw.githubusercontent.com/kubernetes/kubernetes/master/pkg/volume/rbd/rbd_util.go). 

The logic in rbdLock() function assumes the image is locked if there is a response to the "lock list" command.

As the rbd command print out "... did not load config file, using default settings." this will cause the error "rbd: image is locked by other nodes". 

A work around for this is to create a ceph.conf under /etc/ceph on each kubernetes node.
```
cd /etc/ceph
cat > ceph.conf << EOF
[global]
mon_host = xx.xx.xx.xx:6789
auth_cluster_required = cephx
auth_service_required = cephx
auth_client_required = cephx
EOF
```
Another cause for "rbd: image is locked by other nodes" might be if the userId (as provided in the StorageClass) does not have enough permission to list or set locks.

As the k8s kublet calls the "raw" rbd command, the sequence can be debugged by renaming the rbd command (e.g. rbdd) and create a bash wrapper (/usr/bin/rbd) that logs kubernetes commands and responses from the rbd (ceps-common) library.
 
```
#!/bin/bash
# wrapper script /usr/bin/rbd
logfile=/root/logging
# log commands from kubernetes
echo "rbdd $*" >> $logfile
# log responses from rbd binary (renamed to rbdd)
rbdd $*  > >(tee -a $logfile) 2> >(tee -a $logfile >&2)
```

**Comment by rouja** [comment]
Hi,

Which version of ceph are you using ? Because with Jewel, it's seems that it need a recent kernel to use new features. In my testing environment I have : 

Ubuntu 16.04.2 LTS \n \l
ceph version 10.2.9
hyperkube:v1.6.4_coreos.0

At the beginning I created the ceph volume with : 
sudo rbd create ceph-image 
And I got an error like "rbd: image is locked by other nodes" when I tried to use it in pod.

I fixed the issue with : 
sudo rbd remove ceph-image
sudo rbd create --size 2G --image-feature layering ceph-image

Then kubelet was abble to mount the rbd volume.

**Comment by PellePedro** [comment]
Hi roula,

My scenario is using dynamic provisioning (Storage Classes). In this case it's the rbd volume plugin in kubernetes that is creating a unique rbd image for each pvc. 

The current code in kubernetes (as of release release v1.7.2) commit  "922a86c" is hardcoding the rbd image format to "1" (line 360) in: 
https://github.com/kubernetes/kubernetes/blob/922a86cfcd65915a9b2f69f3f193b8907d741d9c/pkg/volume/rbd/rbd_util.go 

Issue https://github.com/kubernetes/kubernetes/pull/45805 , will add support to rbd image format "2" once implemented in a kubernetes release.

**Comment by jamstar** [comment]
@PellePedro your bash wrapper worked great. it helped me figure out that i needed to use ip address.

**Comment by lenguyen89** [comment]
Thanks @PellePedro for the wrapper and the insight into kubelet and rbd

I ran into similar issue "rbd: image is locked by other nodes". In my case, it was slightly different. 

I found this in the syslog

```
kubelet[2560]: I0914 13:25:24.753813    2560 rbd_util.go:164] remove orphaned locker kubelet_lock_magic_den-node-10 from client client.15078: err exit status 13, output: 2017-09-14 13:25:24.635740 7f32dec450c0 -1 did not load config file, using default settings.
...
...
kubelet[2560]: rbd: releasing lock failed: (13) Permission denied
kubelet[2560]: 2017-09-14 13:25:24.712882 7f32dec450c0 -1 librbd: unable to blacklist client: (13) Permission denied
```

Turn out, the real problem is on the line "(13) Permission denied". The secret that I supplied to my storage class doesn't seem to have permission to remove the lock on the image.

**Comment by PellePedro** [comment]
Hi,
To give an update, I've started to build a custom rbd provisioner based on  (https://github.com/kubernetes-incubator/external-storage/tree/master/ceph/rbd), packaged with the ceph libraries, and deployed as a pod (in namespace kube-system). With this the storage provisioning works fine, and the morning/attachment of the volume is done by the (default) kubelet process. 
The update of ceph.conf (as I mentioned earlier) is not needed.

**Comment by kokhang** [comment]
@PellePedro can you explain how this solves the `lock` issue? The lock issue happens during attach/detach. The external provisioner just focusses on the create/delete.

**Comment by mschaefers** [comment]
I also experienced this behavior and I had the same "(13) Permission denied" error @lenguyen89 already reported.

I could solve this issue by updating the ceph permissions of the appropriate client user (the one used by kubernetes/openshift).

My old permissioins:

```
client.ose
	key: [...]
	caps: [mon] allow r
	caps: [osd] allow rwx pool=ose
```
Adding _write permissions_ to the `[mon]` section helped:

`ceph auth caps client.ose osd 'allow rwx pool=ose' mon 'allow rw'`

**Comment by lenartj** [comment]
This is not a kubernetes bug. Kubelet is using the client key that is specified in the storageclass (userId/userSecretName **not** admin*). That client needs to have permissions to lock/unlock/etc.

The precise permission needed depends on the ceph release. For luminous you need for mon `allow r, allow command "osd blacklist"` and for osd `allow rwx pool=yourpool`. A better way to of specifying the permissions is via profiles.

To change a client to the proper permissions:

    ceph auth caps client.myclient mon "profile rbd" osd "profile rbd pool=mypool"

I recommend closing this issue.
