### ISSUE TITLE
Stable docker images for ceph releases

### ISSUE THREAD

**Issue by maxmanuylov** [ceph/ceph-container#675]
Hi,

So far there are only images with the latest builds for each ceph version on docker hub.

It would be much better to have fixed version tags like "10.2.4", "10.2.5", "11.0.2", "11.2.0", "12.0.0", etc. with released ceph builds and to not update the images under those tags. So one could fix dependency on ceph and upgrade it manually when needed instead of pulling a new image each time, which could lead to unpredictable results.

Thanks!

**Comment by jamstar** [comment]
yes, please start doing this.

**Comment by MikaelCluseau** [comment]
In the mean time, here what I have cron'ed:
```shell
#! /bin/bash

base_image="ceph/daemon"
target_image="my.registry/ceph"

set -ex

update() {
    serie=$1

    img="$base_image:tag-build-master-$serie-ubuntu-16.04"

    docker pull $img
    version=$(docker run --rm --entrypoint=/usr/bin/ceph $img -v |cut -d' ' -f 3)
    target=$target_image:$version
    docker tag $img $target
    docker push $target
}

update luminous
#update kraken
update jewel
```

**Comment by Raboo** [comment]
I created my own mirror on docker hub.

To create a own mirror.

1. fork ceph-docker
2. git clone your fork locally
3. `git reset --hard [COMMIT]`
4. `git push origin HEAD --force`

After that create a automated build in docker hub and link it to your fork.
In build settings in your docker hub repo, set it to build with following settings.
```
Type: Branch
Name: master
Dockerfile Location: /ceph-releases/[RELEASE]/[OS]/[OS_VERSION]/daemon
Docker Tag Name: tag-build-master-[RELEASE]-[OS]-[OS_VERSION]
```
Then trigger a build, after a few minutes you will have a mirror of that specific commit you choose.

**Comment by Raboo** [comment]
It looks like there are stable images. Nothing documented anywhere except some mention in some issues.
So I really can't say anything about the thoughts of how they are intended to work.
```
tag-stable-3.0-luminous-centos-7
tag-stable-3.0-luminous-ubuntu-16.04
tag-stable-3.0-jewel-ubuntu-16.04
tag-stable-3.0-jewel-ubuntu-14.04
tag-stable-3.0-jewel-centos-7
```
Well I know that `tag-stable-3.0-jewel-ubuntu-14.04` doesn't work for me, while `tag-stable-3.0-jewel-centos-7` does. But it's a pain switching from ubuntu to centos cause I have to zap all disks and reshuffle the data.

**Comment by leseb** [comment]
@Raboo why do you have to zap all disks if you move from ubuntu container image to centos?
Permissions? leveldb file extensions? This is handled here: https://github.com/ceph/ceph-ansible/blob/master/infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml#L92-L119

**Comment by Raboo** [comment]
I don't have the logs anymore and can't remember exactly, I think it was permission problems.
It was different UID, tried chown, then it were more problems.
But `tag-stable-3.0-jewel-ubuntu-16.04` worked for me without any problems for the OSD. But `tag-stable-3.0-jewel-ubuntu-16.04` MON nodes didn't work, so for MON I needed to run `tag-stable-3.0-jewel-ubuntu-14.04`

@leseb if you are interested I can reproduce the error.

**Comment by leseb** [comment]
If possible, yes please.

**Comment by monaminor** [comment]
ceph octopus is having some (HIGH,CRITICAL) vulnerability.
can anyone let me know which version of ceph is not vulnerable.

**Comment by dsavineau** [comment]
> ceph octopus is having some (HIGH,CRITICAL) vulnerability.
> can anyone let me know which version of ceph is not vulnerable.

@monaminor  Could you open a dedicated issue with some useful information about your concern instead of adding a comment in an unrelated issue ?
