### ISSUE TITLE
ceph-disk: osd fails to mount dmcrypt blockdevice (luminous)

### ISSUE THREAD

**Issue by Blackclaws** [ceph/ceph-container#697]
I've run into an issue when creating osds for luminous.

Basically when --dmcrypt is enabled it works fine for creating the devices but not for unlocking them afterwards.

This appears to be because luminous uses bluestore by default now. That means there is an encrypted blockdevice that needs to be decrypted. 

However ceph-disk doesn't handle that case at all. This is an upstream problem which we could handle locally in the image by mounting the blockdevice manually ( replicating behaviour that ceph-disk should have) or fix upstream (which probably makes more sense). 

I do have fixes locally. I can create a pull request if you would like me to.

**Comment by leseb** [comment]
Please create a pull request to workaround this for now. Also please link the upstream bug too.
Thanks!

**Comment by alikhajeh1** [comment]
@Blackclaws any idea if this is still an issue?
