### ISSUE TITLE
Converting osd  from bare metal to docker fails

### ISSUE THREAD

**Issue by alitvak69** [ceph/ceph-container#703]
I am trying to convert a test  cluster with hammer so I can later upgrade it to jewel.
I managed to get to this point but osd fails.

The trace is below.  Bare metal osd stopped and osd file system has been unmounted.  It looks that osd attempt to start twice ???

```
`[root@ceph-docker-1` ~]# docker -D run  -i -d --net=host --pid=host --name=ceph-osd-ceph-docker-1-devsdb --privileged=true -v /etc/ceph:/etc/ceph -v /var/lib/ceph/:/var/lib/ceph -v /dev/:/dev/ -v /run:/run -v /etc/localtime:/etc/localtime -e OSD_DEVICE=/dev/sdb -e CEPH_DAEMON=osd -e CEPH_PUBLIC_NETWORK=10.0.72.0/22 -e CEPH_CLUSTER_NETWORK=10.0.40.0/23 -e CLUSTER=ceph ceph/daemon:tag-build-master-hammer-centos-7

680b749cfcf5a62b0bfe7b30f4e4335ea8d5b62522870a669e4f199da0bf136d

[root@ceph-docker-1 ~]# docker logs 680b749cfcf5a62b0bfe7b30f4e4335ea8d5b62522870a669e4f199da0bf136d
static: does not generate config
Bootstrapped OSD(s) found; using /dev/sdb
INFO:ceph-disk:Running command: /sbin/blkid -p -s TYPE -ovalue -- /dev/sdb1
INFO:ceph-disk:Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_mount_options_xfs
INFO:ceph-disk:Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_fs_mount_options_xfs
DEBUG:ceph-disk:Mounting /dev/sdb1 on /var/lib/ceph/tmp/mnt.BKBLxZ with options noatime,inode64
INFO:ceph-disk:Running command: /usr/bin/mount -t xfs -o noatime,inode64 -- /dev/sdb1 /var/lib/ceph/tmp/mnt.BKBLxZ
DEBUG:ceph-disk:Cluster uuid is c775051a-188a-4914-b2fe-eaef78885f0c
INFO:ceph-disk:Running command: /usr/bin/ceph-osd --cluster=ceph --show-config-value=fsid
DEBUG:ceph-disk:Cluster name is ceph
DEBUG:ceph-disk:OSD uuid is 37a74985-5be0-4bd1-b227-bd0c470a3ae3
DEBUG:ceph-disk:OSD id is 0
INFO:ceph-disk:Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup init
DEBUG:ceph-disk:Marking with init system sysvinit
DEBUG:ceph-disk:ceph osd.0 data dir is ready at /var/lib/ceph/tmp/mnt.BKBLxZ
DEBUG:ceph-disk:Moving mount to final location...
INFO:ceph-disk:Running command: /bin/mount -o noatime,inode64 -- /dev/sdb1 /var/lib/ceph/osd/ceph-0
INFO:ceph-disk:Running command: /bin/umount -l -- /var/lib/ceph/tmp/mnt.BKBLxZ
DEBUG:ceph-disk:Starting ceph osd.0...
INFO:ceph-disk:Running command: /usr/sbin/service ceph --cluster ceph start osd.0
=== osd.0 === 
create-or-move updating item name 'osd.0' weight 0.02 at location {host=ceph-docker-1,root=default} to crush map
Starting Ceph osd.0 on ceph-docker-1...
starting osd.0 at :/0 osd_data /var/lib/ceph/osd/ceph-0 /var/lib/ceph/osd/ceph-0/journal
create-or-move updating item name 'osd.0' weight 0.02 at location {host=ceph-docker-1.siptalk.com,root=default} to crush map
SUCCESS
2017-07-03 23:03:00.447376 7f0b07898880  0 ceph version 0.94.10 (b1e0532418e4631af01acbc0cedd426f1905f4af), process ceph-osd, pid 10561
starting osd.0 at :/0 osd_data /var/lib/ceph/osd/ceph-0 /var/lib/ceph/osd/ceph-0/journal
2017-07-03 23:03:00.485076 7f0b07898880 -1 asok(0x411c000) AdminSocketConfigObs::init: failed: AdminSocket::bind_and_listen: failed to bind the UNIX domain socket to '/var/run/ceph/ceph-osd.0.asok': (17) File exists
2017-07-03 23:03:00.495989 7f0b07898880  0 filestore(/var/lib/ceph/osd/ceph-0) lock_fsid failed to lock /var/lib/ceph/osd/ceph-0/fsid, is another ceph-osd still running? (11) Resource temporarily unavailable
2017-07-03 23:03:00.496008 7f0b07898880 -1 osd.0 0 OSD::pre_init: object store '/var/lib/ceph/osd/ceph-0' is currently in use. (Is ceph-osd already running?)
2017-07-03 23:03:00.496011 7f0b07898880 -1  ** ERROR: osd pre_init failed: (16) Device or resource busy`

```

**Comment by alitvak69** [comment]
One more thing, after osd fails to start, I see the orphaned file.
/var/lib/ceph/tmp/ceph-disk.activate.loc on the host.

Deleting the file makes no difference when new container is being run.

**Comment by leseb** [comment]
What happens if you delete `/var/run/ceph/ceph-osd.0.asok` and run the container?

**Comment by alitvak69** [comment]
I tried to run container in interactive mode.  Container goes up for duration of start and exits without any new errors beside that were mentioned.  How can I debug further, any suggestions?

**Comment by alitvak69** [comment]
For whatever it worth, I believe that ceph-disk detects init on the system and starts osd .

INFO:ceph-disk:Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup init
DEBUG:ceph-disk:Marking with init system sysvinit
DEBUG:ceph-disk:ceph osd.0 data dir is ready at /var/lib/ceph/tmp/mnt.ctQxXY
DEBUG:ceph-disk:Moving mount to final location...
INFO:ceph-disk:Running command: /bin/mount -o noatime,inode64 -- /dev/sdb1 /var/lib/ceph/osd/ceph-0
INFO:ceph-disk:Running command: /bin/umount -l -- /var/lib/ceph/tmp/mnt.ctQxXY
DEBUG:ceph-disk:Starting ceph osd.0...
INFO:ceph-disk:Running command: /usr/sbin/service ceph --cluster ceph start osd.0
=== osd.0 ===

I couldn't find an option in ceph-disk in hammer that prevents it from doing so.  Needless to say that hammer image is getting very little attention for obvious reasons but I do need it to transition to jewel.
 
It is interesting that when I tried to run  ceph-docker version of hammer based on ubuntu 16.04 it worked!  So there is a difference in behavior  may be due to ceph-disk not detecting sysvinit in xenial? But this is a very unscientific guess on my part.  There was another old post where el7 image detected systemd and started osd before exec, and Sebastian mentioned about needed change for entrypoint.sh, however there was no update since the last year.

**Comment by leseb** [comment]
Why not upgrading your cluster to Jewel and then switch to containers?
We are about to drop hammer support and yes as you noticed we haven't done much work on hammer recently. ceph-docker is a really bleeding edge project, so we are mostly following newer LTS (jewel and luminous).

**Comment by alitvak69** [comment]
I cannot upgrade safely as my nodes are on centos 6 and I am a 1000 miles
away.
Besides it is all build on the zoo of hardware. The docker works for me as
I can get it working together with 4.x kernel.  With some changes I managed
to move containers to hammer on centos 7 with osd on directory and then
migrate to jewel on my test cluster.
