### ISSUE TITLE
Ceph-docker osd scenarious

### ISSUE THREAD

**Issue by alitvak69** [ceph/ceph-container#708]
I noticed that at least hammer release assumes OSD to be on the first partition of the block device, i.e. if I have /dev/sdb, it wants {{DEVICE_NAME}}1.

I am trying to convert my cluster to docker and some of the nodes have following setup

/dev/sdc -- OSD
/dev/sdb1 -- Journal

Also some other smaller nodes have journals in the directory of the  separate  partitioned disk 
/dev/sdc on /var/lib/ceph/osd/ceph-26 type xfs 
/var/lib/ceph/osd/ceph-26-journal/journal  is on /dev/sda

I know that this is not a pretty picture but I had hardware limitations and the cluster was put together over the couple of years.  

Since the OSD code seems to have strong opinion about disk layout, is there a chance,  making ceph-docker  work in this environment at all ?

**Comment by leseb** [comment]
Are you transitioning from Hammer non-containerized to Hammer containerized?
If so, I'd suggest to upgrade to Jewel first and then do the transition.
The transition is possible but expect a lot of manual configuration :).
