### ISSUE TITLE
Allow For Alternate kubectl Binary

### ISSUE THREAD

**Issue by markramach** [ceph/ceph-container#721]
Firstly, I love the work that has been done with this project. 

However, I've run into situations where I'm running ceph/daemon:latest on clusters that have not yet been upgraded to reflect the version of the kubectl binary that is present in the image file system. This results in monitors that run into a crash loop because of a mismatch in the versions. That being said, it would be great if you could allow the location of the kubectl binary to be defined during container execution via `-e KUBECTL_HOME=/path/to/kubectl`. I would prefer to mount the node's kubectl binary in the container during execution. This would allow me to control the version of the binary outside of the image.

**Comment by leseb** [comment]
That's a good idea, let me see what I can do, thanks!

**Comment by leseb** [comment]
But wait, can't you just run `-v /path/to/kubectl:/usr/local/bin/kubectl` already?

**Comment by markramach** [comment]
I've never actually attempted to mount a file directly previously. I've tested with a standard ubuntu container and a simple binary without success. There also seems to be some ongoing issues with that strategy as defined in this issue over the past few years https://github.com/docker/compose/issues/424.

**Comment by leseb** [comment]
Well, this can be worked around I suppose. Please close this if this is not an issue anymore. I believe the right way to use a different binary is to bindmount.
