### ISSUE TITLE
recurring confusion about releases and clarification

### ISSUE THREAD

**Issue by Raboo** [ceph/ceph-container#757]
Hi,

I'm wondering why there are so many distros involved?

- hammer has centos/7, fedora/23, ubuntu/14.04
- infernalis has centos/7, ubuntu/14.04, ubuntu/16.04
- jewel has centos/7, fedora/24, opensuse/Leap_42.2, rhel/7.3, ubuntu/14.04, ubuntu/16.04
- kraken has centos/7, ubuntu/16.04
- luminous has centos/7, rhel/7.3, ubuntu/16.04

Why not just one Ceph release paired with one Linux distro? Doesn't this make this harder to maintain and submit patches? And also since this is a docker project, I don't see a reason for all the different distros for each Ceph release.

Are all distros equally supported and maintained?

Also the root README.md links to jewel/ubuntu-14.04. Is that the "stable/preferred" release?
How do I know when kraken is stable for instance? And are both the centos and ubuntu release equally stable/usable?

I think it would be good in the root README to have links each Ceph release and their current status and linked to the distro that is the preferred default. Something like this:

| Release | EOL | Status | Maintained | Image |
|--|:--:|--|--:|:--:|
| [infernalis](ceph-releases/infernalis/ubuntu/14.04/daemon/) | 2016-xx-xx | old/stable | N | ceph/daemon:tag-build-master-infernalis-ubuntu-14.04 |
| [jewel](ceph-releases/jewel/ubuntu/14.04/daemon/) | 2018-xx-xx | stable | Y | ceph/daemon:tag-build-master-jewel-ubuntu-14.04 |
| [kraken](ceph-releases/kraken/ubuntu/16.04/daemon/) | 2019-xx-xx | testing | Y | ceph/daemon:tag-build-master-kraken-ubuntu-16.04 |

**Comment by Raboo** [comment]
Also is the kraken/ubuntu-16.04 ready for use? 😃

**Comment by leseb** [comment]
Short answer, companies providing supports on containers (e.g: Red Hat, Suse) can not support a running container on let's say an Ubuntu image. That's why we provide multiple distributions. It's not so hard to maintain with the help of the symlinks.

Our testing focuses on CentOS 7 and we have one scenario testing Ubuntu Xenial but most of the testing is on CentOS 7.

At the moment, we haven't started using stable releases yet. Soon we will start tagging and releasing releases.
Also most the testing is done on LTS releases, but inter-releases (e.g: Kraken) are not left behind since they are always getting bug fixes.

So I'd say yes kraken/ubuntu-16.04 is ready to use.

**Comment by Raboo** [comment]
Well I don't care about which distro is running inside the docker container.
So would you say that it's better to use the CentOS 7 image rather than the Ubuntu 16.04?

**Comment by leseb** [comment]
Nop, both work the same.

**Comment by ktdreyer** [comment]
I agree @Raboo it would be a good idea to simplify here. The complexity is overwhelming to me.

**Comment by leseb** [comment]
@ktdreyer, to be honest, I don't see the complexity but I'll let you guys elaborate.

**Comment by leseb** [comment]
What's overwhelming?
I need more precise argument otherwise I'll close this again :-). Ken, you know we cannot go without this for RHCS right?

**Comment by Raboo** [comment]
Hmm,
I have some ideas on how to improve new user experience.

In root README.md split away how developers should contribute into a CONTRIBUTIONS.md or such and link it from README.md

Perhaps a table linking to different versions like the one above.
Some information about how to deploy and that you should install docker images according to the table based on what version of Ceph you want to install.
And a text saying something like find out more information about deployment and about that specific version in that table(and the table links to README for jewel, kraken, etc..).

What do you guys think about this?
Cause usually if you get more people to use the project, you get more bug reports and in turn more interest and contributions.

**Comment by ktdreyer** [comment]
We have several different axes on our support matrix:
- Ceph Version (jewel, luminous)
- OS type (CentOS, RHEL, Ubuntu, SUSE)
- OS version (7, 14.04, 16.04)
- Container type (demo vs daemon)

We will probably need to add more axes in the future:
- architecture (currently we only support x86_64, eventually we'll need to add aarch64 and ppc64le)
- arbitrary ceph branches (eg. "wip-foo")

One way to reduce the complexity would be to only build CentOS-based containers. The majority of QE effort is happening on RHEL/CentOS as far as I can tell.
