### ISSUE TITLE
Can't seem to override CRUSH_LOCATION

### ISSUE THREAD

**Issue by azenk** [ceph/ceph-container#781]
I'm trying to set the CRUSH_LOCATION for an osd, but it seems that it must be passed in as an array, or else I'm missing something stupidly easy.  I've tried passing in just about every variety of plain string (e.g. "root=default row=23 rack=134 host=foo-23-134-00") that I can think of, they all result in some variant of:

```
Invalid command:  invalid chars   in root=default row=23 rack=134 host=foo-23-134-00
osd crush create-or-move <osdname (id|osd.id)> <float[0.0-]> <args> [<args>...] :  create entry or move existing entry for <name> <weight> at/to location <args>
```

As far as I can tell passing arrays to environment variables isn't supported by docker:
[Docker CLI docs](https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e-env-env-file)
Someone else trying to pass an array in via env: https://github.com/moby/moby/issues/20169

[I see that it's been an array since about 5 months ago](https://github.com/ceph/ceph-docker/commit/628764b52ce0547d7bd6f47f128476b7f490aae0#diff-d08225d6b769cdf75f08910cbb592f8dR64).  How are people setting CRUSH_LOCATION if they need to override the default?

**Comment by leseb** [comment]
Sorry, @azenk I think no one is really using this feature, and it's still broken apparently. We can rollback to not use an array and add a shellcheck exception.
