### ISSUE TITLE
Unable to find OSD partuuid in Jewel Ubuntu 14.04

### ISSUE THREAD

**Issue by mkkie** [ceph/ceph-container#822]
In my environment, I used Jewel & ubuntu:14.04.
After pulled the latest codes, I couldn't activate any OSD.

In osd_scenarios/osd_disk_activate.sh [line25](https://github.com/ceph/ceph-docker/blob/9d4e488ada94be4deeb1a8d8e5db80630b6126f4/ceph-releases/jewel/ubuntu/14.04/daemon/osd_scenarios/osd_disk_activate.sh#L25),
the variable **JOURNAL_UUID** got nothing because the command **blkid** failed.

The function [**get_part_uuid**](https://github.com/ceph/ceph-docker/blob/9d4e488ada94be4deeb1a8d8e5db80630b6126f4/ceph-releases/jewel/ubuntu/14.04/daemon/common_functions.sh#L280) used the command `blkid -o value -s PARTUUID "${1}"`. And I found in ubuntu:14.04 blkid couldn't get the right partuuid.

I also tried blkid in both ubuntu:14.04 & ubuntu:16.04.

```
root@ubuntu14-04:/# blkid -v
blkid from util-linux 2.20.1 (libblkid 2.20.0, 19-Oct-2011)

root@ubuntu14-04:/# blkid -o value -s PARTUUID /dev/sdb2

root@ubuntu14-04:/# echo $?
2
```
```
root@ubuntu16-04:/# blkid -v
blkid from util-linux 2.27.1  (libblkid 2.27.0, 02-Nov-2015)

root@ubuntu16-04:/# blkid -o value -s PARTUUID /dev/sdb2
6beb16bc-1de5-4a1d-b4e3-3ff883ff0eea
```

Here is my log
[ceph-docker-osd-blkid.log](https://github.com/ceph/ceph-docker/files/1394041/ceph-docker-osd-blkid.log)

Please fix this issue.

Thanks

**Comment by leseb** [comment]
Look like an Ubuntu issue to me, why don't you go with 16.04 instead?
