### ISSUE TITLE
ceph osd not running, using kubernetes v1.8.1

### ISSUE THREAD

**Issue by hailong226** [ceph/ceph-container#829]
2017-10-27 07:28:47  /entrypoint.sh: k8s: config is stored as k8s secrets.
2017-10-27 07:28:47  /entrypoint.sh: k8s: does not generate the admin key. Use Kubernetes secrets instead.
ceph-0: /usr/bin/ceph-osd --cluster ceph -f -i 0 --osd-journal /var/lib/ceph/osd/ceph-0//journal -k /var/lib/ceph/osd/ceph-0//keyring
2017-10-27 07:28:47  /entrypoint.sh: SUCCESS
forego   | starting ceph-0.1 on port 5000
ceph-0.1 | starting osd.0 at - osd_data /var/lib/ceph/osd/ceph-0 /var/lib/ceph/osd/ceph-0//journal
ceph-0.1 | 2017-10-27 07:28:47.176307 7f31d46f9e00 -1 osd.0 0 log_to_monitors {default=true}
ceph-0.1 | 2017-10-27 07:28:47.180999 7f31d46f9e00 -1 osd.0 0 init authentication failed: (1) Operation not permitted

**Comment by hailong226** [comment]
using kubernetes v1.8.1

**Comment by leseb** [comment]
SELinux?

**Comment by nareshtank** [comment]
@leseb I encountered the similar problem on 1.8.1. With same logs.
I have SELinux is Disabled.

**Comment by danelowe** [comment]
Took me a long time to find, but I believe it may be solved by #819

**Comment by saltFisher** [comment]
@danelowe , Hi Dane, how do fix this issue, i still meet agian in kubernetes 1.17

**Comment by danelowe** [comment]
@saltFisher  Sorry I don't use k8s any more. I haven't got a clue what this issue is about any more either.
