### ISSUE TITLE
Bootstrap Ceph cluster with previously prepared and activated OSD disks

### ISSUE THREAD

**Issue by maxmanuylov** [ceph/ceph-container#842]
Hi,

I have Ceph cluster with 3 MONs+MGRs and 5 OSDs with attached disks. All nodes have CoreOS as host OS, Ceph daemons run in Docker (luminous, ubuntu 16.04, bluestore, etcd). Ceph reports HEALTH_OK and I have some data stored on OSDs.

Imagine then (intentionally or due to some failure) almost simultaneously I destroy all the cluster nodes keeping just OSD disks. Now I want to recreate the cluster keeping all my OSD data. I recreate all the nodes and all of them get some new IP address. MONs and MGRs start without any problem, form a quorum (I see all mons in "ceph -s") and I see "/ceph-config/ceph/monSetupComplete" flag in etcd (etcd is redeployed as well so the flag is for sure newly added). While OSDs fail to start stucking on "start_boot" step. And "ceph osd tree" shows all the OSDs in "down" state.

What are the correct steps to bootstrap a Ceph cluster with existing (prepared and activated) OSD disks? One thing I figured out is that I should not regenerate cluster "fsid" so I patched the "ceph/daemon" image to pass my own "fsid". But seems it is not enough because OSDs still stuck. My guess is every OSD tries to connect to peers using previous osdmap and old OSD IP addresses. If it is so, is there any way to reset the osdmap keeping my data stored on OSD? What else should I do?

**Comment by taemon1337** [comment]
Max, please let me know if you find a resolution for this, I'm in the same boat.

**Comment by maxmanuylov** [comment]
@taemon1337, the main problem here is that Ceph expects MONs state to be kept even between cluster redeploys. So keeping just your data (OSD disks) is not enough to keep your data :) The second problem is that this "ceph-container" image does not support booting on existing data at all, even with restored MONs state.

Some more details I was able to investigate:

OSD map has version (they call it "epoch") that is incremented on every OSD-related change. When OSDs are booting they read own local copy of the OSD map and compare its version with the version received from MONs. If local map is newer then OSD waits for the same OSD map version is reached in the cluster (which never happens unless you perform sufficient number of configuration changes).  That is why OSDs look like they are stuck. And if you do not keep MONs state then every MON starts with an empty OSD map having initial version, which of course leads to the case above.

They have though some procedure to recover MONs state basing on the OSDs: https://github.com/ceph/ceph/blob/luminous/doc/rados/troubleshooting/troubleshooting-mon.rst#recovery-using-osds. But it looks more like one-time manual administrative task than like a normal way to bootstrap the cluster.

So, summarizing, you need to keep your MONs state, reuse cluster "fsid" and rewrite the scripts from this repo for your needs.
