### ISSUE TITLE
typo in zap_device.sh ?

### ISSUE THREAD

**Issue by JrCs** [ceph/ceph-container#849]
Hi,
in [zap_device.sh#L14](https://github.com/ceph/ceph-container/blob/ed68feafd41ef34ad58334d2b5b373980ad6c698/ceph-releases/luminous/ubuntu/16.04/daemon/zap_device.sh#L14) the names of the partition are `data, journal, block, wal, db` prefix with the `ceph` prefix but on my luminous OSD i have:

```
Disk /dev/sde: 268435456 sectors, 128.0 GiB
Logical sector size: 512 bytes
Disk identifier (GUID): 3DF780F4-9499-450F-8E93-19EEEB2AE3DE
Partition table holds up to 128 entries
First usable sector is 34, last usable sector is 268435422
Partitions will be aligned on 2048-sector boundaries
Total free space is 2014 sectors (1007.0 KiB)
 
Number  Start (sector)    End (sector)  Size       Code  Name
    1            2048          206847   100.0 MiB   FFFF  ceph data
    2         3483648       268435422   126.3 GiB   FFFF  ceph block
    3          206848         2303999   1024.0 MiB  FFFF  ceph block.db
    4         2304000         3483647   576.0 MiB   FFFF  ceph block.wal
```

so the names is ok for `data` & `block` but must be `block.db` & `block.wal` for the others in the script ?

**Comment by leseb** [comment]
@JrCs you're right, that's a bug. Fix here: https://github.com/ceph/ceph-container/pull/862/commits/c910fb6fe8a1bfed4d319f2c1abf6a0b71b3d75b
