### ISSUE TITLE
Key not found (/ceph-config/ceph/bootstrapRbdKeyring)

### ISSUE THREAD

**Issue by Etherous** [ceph/ceph-container#855]
I just pulled the latest image for ceph/daemon:tag-build-master-luminous-ubuntu-16.04

When I try to start either an existing OSD or a new one, I get a "Key not found" error. When I realized it's a missing key in etcd, I followed the instructions on the docker hub page to populate the keystore, but it was still missing. Do I need to insert the key manually? If so, what are the instructions for generating it? Googling for "bootstrapRbdKeyring" returns literally nothing.

Here's what gets logged:
true
2017-12-03T15:09:55-07:00 socrates confd[2143]: INFO Backend set to etcd
2017-12-03T15:09:55-07:00 socrates confd[2143]: INFO Starting confd
2017-12-03T15:09:55-07:00 socrates confd[2143]: INFO Backend nodes set to http://10.0.1.1:2379
2017-12-03 15:09:55  /entrypoint.sh: Adding bootstrap keyrings.
Error:  100: Key not found (/ceph-config/ceph/bootstrapRbdKeyring) [254]

**Comment by qrpike** [comment]
I get this error as well trying to upgrade a OSD from kraken to luminous.

**Comment by leseb** [comment]
The issue is that from Kraken to Luminous there is no bootstrap-rbd key. Luminous introduced that key so when we try to import it 's not present. So as part of the upgrade process, you should create and import that key.
Thanks.

Feel free to re-open if you have any more concerns.
