### ISSUE TITLE
docker images for arm64

### ISSUE THREAD

**Issue by IoanaCiornei** [ceph/ceph-container#861]
I am interested in running the ceph-container demo on a arm64v8 platform running Ubuntu. For this to happen, I have to build the docker images with a base such as 'FROM arm64v8/ubuntu:16.04'. Would you be interested in supporting multiple architectures (multiple Dockerfiles)? I would be more than happy to help with this.

**Comment by leseb** [comment]
I guess we need to add another directory level named "arch". The repository supports this so feed free to send a PR.
Thanks!
