### ISSUE TITLE
ceph/daemon:build-master-luminous-centos-7: rgw RGW_NAME is not set in /etc/ceph/"${CLUSTER}".conf

### ISSUE THREAD

**Issue by andmn** [ceph/ceph-container#903]
I started with https://github.com/ceph/ceph-container/tree/master/ceph-releases/luminous/centos/7/daemon as cookbook.

Image: CEPH_IMAGE=ceph/daemon:tag-stable-3.0-luminous-centos-7

After the "Deploy a Rados Gateway" I had no change to create a bucket with s3cmd or DragonDisk, I alway got the response

`<?xml version='1.0' encoding='UTF-8'?>`
`<Error>`
` <Code>MethodNotAllowed</Code>`
` <RequestId>tx000000000000000000005-005a8084e5-107d-default</RequestId>`
` <HostId>107d-default-default</HostId>`
`</Error>`

Finally I modified start_rgw.sh inside of the container and added these lines:
`     36   log "configure rgw dns name"`
`     37     cat <<ENDHERE >>/etc/ceph/"${CLUSTER}".conf`
`     38 [client.rgw.${RGW_NAME}]`
`     39 rgw_dns_name = ${RGW_NAME}`
`     40 `
`     41 [client.radosgw.${RGW_NAME}]    # from demo.sh looks like invalid radosgw is called with client.rgw."${RGW_NAME}"`
`     42 rgw_dns_name = ${RGW_NAME}`
`     43 ENDHERE`

I restarted the named container (use --name at first docker run) and everything works. Please fix the container.

**Comment by leseb** [comment]
This is weird.
The container as is does not need this section. [cn](https://github.com/ceph/cn) is good example and uses `s3cmd` under the hood.
