### ISSUE TITLE
 start_nfs.sh is ignoring ganesha.nfsd exit code

### ISSUE THREAD

**Issue by tombarron** [ceph/ceph-container#909]
Description of problem:
the start_nfs.sh [1] script inside the container image is ignoring the ganesha.nfsd exit code, consequently systemd returns success when the deamon inside the container did not start instead

1. https://github.com/ceph/ceph-container/blob/master/ceph-releases/luminous/ubuntu/16.04/daemon/start_nfs.sh#L35

**Comment by tombarron** [comment]
proposed https://github.com/ceph/ceph-container/pull/910

**Comment by tombarron** [comment]
With the above change I rebuilt the docker container, pushed it to a local docker repository, pulled it to an OpenStack controller node, and ran it there with a configuration known to cause the ganesha daemon to exit.  The container runs and exits with an error code as one would like and the logs go to STDOUT and are visible in journalctl afterwards:

[root@overcloud-controller-0 ~]# /usr/bin/docker run --rm --net=host -v /var/lib/ceph:/var/lib/ceph -v /etc/ceph:/etc/ceph -v /var/lib/nfs/ganesha:/var/lib/nfs/ganesha -v /etc/ganesha:/etc/ganesha --privileged -v /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket -v /etc/localtime:/etc/localtime:ro -e CLUSTER=ceph -e CEPH_DAEMON=NFS --name=ceph-nfs-pacemaker 192.168.24.1:8787/ceph/daemon:latest
2018-02-18 15:04:56  /entrypoint.sh: static: does not generate config
2018-02-18 15:04:56  /entrypoint.sh: SUCCESS
exec: PID 94: spawning /usr/bin/ganesha.nfsd  -F -L STDOUT 
18/02/2018 15:04:56 : epoch 5a899618 : overcloud-controller-0 : ganesha.nfsd-94[main] main :MAIN :EVENT :ganesha.nfsd Starting: Ganesha Version /builddir/build/BUILD/nfs-ganesha-2.5.5-0.1.1-Source, built at Feb 12 2018 22:29:08 on 
18/02/2018 15:04:56 : epoch 5a899618 : overcloud-controller-0 : ganesha.nfsd-94[main] nfs_set_param_from_conf :NFS STARTUP :EVENT :Configuration file successfully parsed
18/02/2018 15:04:56 : epoch 5a899618 : overcloud-controller-0 : ganesha.nfsd-94[main] init_server_pkgs :NFS STARTUP :EVENT :Initializing ID Mapper.
18/02/2018 15:04:56 : epoch 5a899618 : overcloud-controller-0 : ganesha.nfsd-94[main] init_server_pkgs :NFS STARTUP :EVENT :ID Mapper successfully initialized.
18/02/2018 15:04:56 : epoch 5a899618 : overcloud-controller-0 : ganesha.nfsd-94[main] main :NFS STARTUP :WARN :No export entries found in configuration file !!!
18/02/2018 15:04:56 : epoch 5a899618 : overcloud-controller-0 : ganesha.nfsd-94[main] lower_my_caps :NFS STARTUP :EVENT :CAP_SYS_RESOURCE was successfully removed for proper quota management in FSAL
18/02/2018 15:04:56 : epoch 5a899618 : overcloud-controller-0 : ganesha.nfsd-94[main] lower_my_caps :NFS STARTUP :EVENT :currenty set capabilities are: = cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_module,cap_sys_rawio,cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_boot,cap_sys_nice,cap_sys_time,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap+eip
18/02/2018 15:04:56 : epoch 5a899618 : overcloud-controller-0 : ganesha.nfsd-94[main] Bind_sockets_V6 :DISP :WARN :Cannot bind NFS udp6 socket, error 99 (Cannot assign requested address)
18/02/2018 15:04:56 : epoch 5a899618 : overcloud-controller-0 : ganesha.nfsd-94[main] Bind_sockets :DISP :FATAL :Error binding to V6 interface. Cannot continue.
exec: PID 94: exit 2
[root@overcloud-controller-0 ~]#

**Comment by tombarron** [comment]
Shouldn't this be closed as fixed rather than won't fix?  IIUC https://github.com/ceph/ceph-container/pull/910 was merged.

**Comment by dsavineau** [comment]
This should have been close automaticaly if the commit message had the right fixes/closes statement
