### ISSUE TITLE
Dockerfile VOLUME declaration may be unnecessary

### ISSUE THREAD

**Issue by BlaineEXE** [ceph/ceph-container#917]
From this discussion https://github.com/ceph/ceph-container/pull/905#discussion_r170556756,
`VOLUME ["/etc/ceph","/var/lib/ceph", "/etc/ganesha"]` may no longer be necessary.

**Comment by ErwanAliasr1** [comment]
@leseb Can you confirm this ?

**Comment by leseb** [comment]
Yes, it is not needed.
I guess this is just needed when running the container standalone and want to survive reboot.

Normally the flag should be added as `-v` at runtime and not hardcoded in the Dockerfile.
