### ISSUE TITLE
Need to figure out Dockerfile LABELs

### ISSUE THREAD

**Issue by BlaineEXE** [ceph/ceph-container#924]
This is not a fully-fledged idea yet. I'd like to have a discussion about this at some point, and I want to note it here before I forget.

https://docs.docker.com/engine/reference/builder/#label

Dockerfile's `MAINTAINER` id deprecated. We should use `LABEL maintainer=MMMMM` instead. We should also try to populate as many labels as makes sense. Shall we version the project as well for this?

**Comment by leseb** [comment]
+1, there are a couple of info we should embed as LABEL in the container image. I'll build a list for this with @ErwanAliasr1.

**Comment by BlaineEXE** [comment]
Docker label best practices https://docs.docker.com/config/labels-custom-metadata/#key-format-recommendations

Notes:
- Must be lower case


Label schema project: http://label-schema.org/rc1/
