### ISSUE TITLE
start_mgr.sh and the undocumented ENABLE_MODULES need an overhaul

### ISSUE THREAD

**Issue by dmick** [ceph/ceph-container#928]
I don't remember why it is the way it is, but these days, the monitor stores a list of enabled modules and its persistent state should be used.  We still may want some way to change the default enabled module list (which is in mgr_initial_modules) but on later restarts the mon store should be the source.

**Comment by pcuzner** [comment]
I removed the whole section in startup script that deals with the ENABLED_MODULES env variable, and committed the updated container locally. Now the container starts up with the enabled mgr modules correctly. Perhaps that's what we need to do

**Comment by dmick** [comment]
How do you express your preferences for which modules are enabled on first bringup?

**Comment by pcuzner** [comment]
When I deployed with ceph-ansible, I used the variable ceph_mgr_modules variable defined in group_vars/mgrs.yml.

**Comment by dmick** [comment]
Right.  I guess the question would be "how would one do that without Ansible".

**Comment by pcuzner** [comment]
Good question. We know that mgr stores it's enabled modules list correctly, so once the container is deployed users that don't use ansible would need to enable the relevant module manually, or update their systems config tool of choice to perform that task separately. Having code in the startup to 2nd guess the configuration in the mgr is prone to the issue we've seen here.

**Comment by dmick** [comment]
Nothing I've seen so far attempts to use mgr_initial_modules and I just don't want it ignored unless it's useless, in which case we should probably remove it from Ceph proper

**Comment by leseb** [comment]
@dmick sorry for getting late on that topic, this refactor came from helm, I did a quick resync based on @alram's work.
