### ISSUE TITLE
Ceph-calamari docker image

### ISSUE THREAD

**Issue by hookenz** [ceph/ceph-container#93]
I'd be good to get calamari working inside docker.

I tried to once get it working by following all the instructions but got stuck in the ruby frameworks and couldn't get it going.

**Comment by leseb** [comment]
Not sure the benefit we get from Calamari at the moment but it's probably a good thing to add.
IMHO `ceph-rest-api` does the job just fine.

**Comment by ktdreyer** [comment]
`ceph-rest-api` is deprecated and we want to remove it eventually :)

**Comment by leseb** [comment]
Yes I've heard that but the direction of Calamari is not really clear at the moment. :)
But right we shouldn't bother doing anything with `ceph-rest-api` then.

**Comment by hookenz** [comment]
@ktdreyer - I didn't realise ceph-rest-api has been deprecated.  What replaces it?

**Comment by leseb** [comment]
@hookenz Calamari API.
