### ISSUE TITLE
Revisit cleanup operations to make sure we aren't being too aggressive

### ISSUE THREAD

**Issue by BlaineEXE** [ceph/ceph-container#936]
revisit cleanup operations to make sure we aren't shooting ourselves in the foot by being too aggressive 

If I start a brand new base container (I tested opensuse:42.3) and do nothing but delete files, I was happy to notice that the image size didn't grow larger. It probably did a tiny bit because of inode differences between the layers, but I don't think fussing over a few kb is worth it. If we have files that we don't need, we can feel free to delete them without much concern, even if those files exist in previous layers. We might especially want to delete files/packages that are security risks. As much as it would make debugging difficult, removing package manager and bash will make the containers more secure.

I think we really want to revisit the binaries we are stripping and/or compressing (or totally deleting) to make sure we aren't cleaning too much.

We might also want to consider whether debug versions of containers are a good idea (without binaries stripped) and how we might do deep debugging on a cluster, but maybe that's a totally new topic.

**Comment by ktdreyer** [comment]
If we remove the package manager and bash, how will we debug the container or install debuginfo packages?
