### ISSUE TITLE
CEPH_VERSION_NUMBER container env var

### ISSUE THREAD

**Issue by BlaineEXE** [ceph/ceph-container#937]
Idea to introduce an environment variable like CEPH_VERSION_NUMBER in case we want to execute code paths conditionally for Ceph versions lt/gt rather than just by name. This will help us avoid the situation we have with jewel/kraken where we have unique, slightly modified source files in the ceph-releases tree. I see this as something we want to do for luminous+ but needn't refactor jewel/kraken.

Simple example will not execute a code path for earlier Ceph versions that don't support some ganesha feature:
```sh
if [ $CEPH_VERSION -ge 12 ]; then
    # do stuff with ganesha if ceph version is luminous or above
fi
```

**Comment by ErwanAliasr1** [comment]
I'd also love having something like

if [ "$CEPH_NAME" = "luminous" ]; 

That would be more generic than the release itself.

**Comment by BlaineEXE** [comment]
The `CEPH_VERSION` variable is the named ceph release. We could rename `CEPH_VERSION` to `CEPH_VERSION_NAME` for more clarity as part of this.

**Comment by ErwanAliasr1** [comment]
CEPH_CODENAME & CEPH_VERSION ?

**Comment by BlaineEXE** [comment]
I think we should be very specific. Already as-is, `CEPH_VERSION` is unspecific about whether it means number or name. I would use `CEPH_VERSION_NAME` and `CEPH_VERSION_NUMBER` for maximum clarity.
