### ISSUE TITLE
Staging blacklist is unnecessary?

### ISSUE THREAD

**Issue by BlaineEXE** [ceph/ceph-container#938]
Do we want to remove the blacklist functionality? It might be unnecessary.

**Comment by ErwanAliasr1** [comment]
I honestly think that was over-engineered. I had the feeling that it would be useful but by the end, we do manage this case by handling the directories properly.

I would even say this could be very misleading as it add a new source of configuration which is not obvious at all.

So backlist seems counterproductive for me  so +1 for removing it.
