### ISSUE TITLE
Add PR template so we don't forget to do things when adding changes

### ISSUE THREAD

**Issue by BlaineEXE** [ceph/ceph-container#939]
Add a pull request template with a checklist that includes things like: update list of all flavors in Makefile if applicable, update readme if applicable, update script help text if applicable, update tests, passes linting tests, etc.

**Comment by galexrt** [comment]
@BlaineEXE Would something like https://raw.githubusercontent.com/rook/rook/master/.github/PULL_REQUEST_TEMPLATE.md from Rook repo be applicable to be used as a template for this repo?

**Comment by BlaineEXE** [comment]
That's the basic idea yeah. We have CI for the lint tests now, so that checkbox isn't necessary.
