### ISSUE TITLE
Adding make push.latest

### ISSUE THREAD

**Issue by ErwanAliasr1** [ceph/ceph-container#943]
When building images for dockerhub we need to push the latest tag.
It's usually a human choice of selecting latest ceph-release with ubuntu but that could change over time.

Why not defining the first FLAVORS_TO_BUILD as the one to be tagged as latest & implement the required push command to be part of the makefile to get something like :+1: 

make push.latest

This way the CI script is much more lighter and avoid redefining or extracting content from the makefile.

**Comment by leseb** [comment]
```
  daemon_base=ceph/daemon-base:$current_branch-$latest_commit_sha-luminous-ubuntu-16.04-amd64
  daemon=ceph/daemon:$current_branch-$latest_commit_sha-luminous-ubuntu-16.04-amd64

  docker tag $daemon_base ceph/daemon-base:latest
  docker tag $daemon ceph/daemon:latest
  docker push ceph/daemon-base:latest
  docker push ceph/daemon:latest
```
