### ISSUE TITLE
What is the purpose of the etcd packages in images?

### ISSUE THREAD

**Issue by BlaineEXE** [ceph/ceph-container#949]
Beyond supporting the etcd KV type, what are the etcd packages used for? It occurs to me that if I know I am building containers that are going to be used for kubernetes and etcd is not needed, I can make my containers smaller by removing etcd.

While on the topic of KV types, what are thoughts about deprecating support for non-k8s KV's and focus ceph-container purely on k8s? I'm not sure how many users we have that are using ceph-container outside of k8s or manually-connected docker containers. If no one is using etcd (or other features), I think we can simplify some of ceph-container's complexity by deprecating support for things that aren't frequently used that add unnecessary complexity.

Edit: I think dropping support for an etcd backend would also allow us to eliminate the `confd` package from the daemon. That's more code we might not have to support, and our container image size would be further reduced a bit.

**Comment by leseb** [comment]
You said it, the purpose of the `etcd` package is to support KV_TYPE. If you look at the issues, you will see that people are using it (and hitting issues...). I've been thinking of deprecating a bunch of things for mimic (osd directory + forego) and this was one of them.

I think we can run a poll and see who's actually using KV_TYPE for etcd and then decide whether or not to keep it.

How does that sound?

**Comment by BlaineEXE** [comment]
I think that sounds great. =)

**Comment by leseb** [comment]
Adding a bunch of contributors:

,@foreverhex ,@tombarron ,@wedged ,@Riptawr ,@bassam ,@jprovaznik ,@prymitive ,@kpcyrd ,@zmc ,@dmick ,@djgalloway ,@xakep139 ,@dmonakhov ,@mgibula ,@bzub ,@galindro ,@ibotty ,@jimcurtis ,@sajal ,@jayconroy ,@alanmeadows ,@ganeshmaharaj ,@coffeepac ,@linuxwind ,@mgilham ,@danielin917 ,@dang ,@clinta ,@ivotron ,@mainboy ,@a-nldisr ,@bnoon ,@mbessler ,@walkerlee ,@xingjiudong ,@nickjanus ,@pokoli ,@onyiny-ang ,@theanalyst ,@rjfd ,@minshenglin ,@tobilg ,@nazar-pc ,@rochaporto ,@tobegit3hub ,@BugRoger ,@JrCs ,@qrpike ,@adamwg ,@AlessandroLorenzi

**Comment by leseb** [comment]
@ohmystack ,@xcompass ,@lorieri ,@hrchu ,@GregMeno ,@CoRfr ,@Raboo ,@mkkie ,@slang800 ,@yxwzaxns ,@untoreh ,@liewegas ,@ktdreyer ,@galexrt ,@ReSearchITEng ,@immesys ,@timn ,@deviantintegral ,@hookenz ,@TelanJ ,@elsonrodriguez ,@fmeppo ,@BertrandGouny ,@h0tbird ,@cornelius-keller ,@rootfs ,@streamnsight ,@font ,@dmitryint ,@guits ,@andrewschoen ,@alfredodeza ,@BlaineEXE ,@Ulexus ,@hunter ,@ErwanAliasr1

**Comment by timn** [comment]
We are using k8s for [rcll-sim-cluster](https://github.com/timn/rcll-sim-cluster).

Even if etcd support was to be continued there would be no need to have it included in the ceph-container image. It can just be deployed as a few more containers elsewhere.

**Comment by Raboo** [comment]
I'm using etcd currently, removing support for etcd would force me to stop using ceph-container.
Was using consul, but support was removed..
I guess one could use curl to get and set keys instead, but then again this perhaps increases complexity compared to using etcdctl.

In the best of worlds I would like to see Consul support again 👍. Consul IMO is much easier to setup and maintain than a etcd cluster.

**Comment by adamwg** [comment]
We are using etcd, but run it in separate containers. We'd prefer to use consul, since we have consul running for other purposes.

We currently use ceph in containers only for ephemeral test environments, so we can adapt relatively easily to whatever kv store is supported. That said, supporting k8s only would be a little difficult for us since we typically run these test environments on developer machines.

**Comment by Raboo** [comment]
@adamwg 
> We are using etcd, but run it in separate containers. We'd prefer to use consul, since we have consul running for other purposes.

@BlaineEXE is not refereeing to running etcd server inside ceph-container, he's talking about the client inside ceph-container that is used to set and read values from the etcd K/V.

**Comment by xcompass** [comment]
etcd for me

**Comment by ErwanAliasr1** [comment]
So looks like many use it.

While speaking about it, I offer to bump etcd from 2.2.4 to 3.2.18.
Is there any reason not doing so ? 
Can the interested people in can join #994 to give a go/no go ?

Note #994 is also considering bumping kubectl & confd.

**Comment by BlaineEXE** [comment]
Further question @leseb. The ceph mons have a KV store. Would it be possible to instead use this KV store and eliminate the need for users to have a different KV store altogether?

What kind of information is stored in the KV store?

**Comment by Raboo** [comment]
@BlaineEXE There is a already a proposal/blog post about this https://ceph.com/planet/containerize-ceph-store-config-options-in-monitor-kv-store/ from @leseb.
The KV store is for us that want the Ceph containers to be stateless as possible and have a way to distribute the configs (via a KV store) and not have to manage config files.

@BlaineEXE why would you want to run Ceph inside a container if you are going to treat it like a regular full OS installed Ceph?
Or do you want this project to be limited to Kubernetes? Then that is a completely different project, it's no longer `ceph-container`. And what if you want to use Ceph as a storage backend for Kubernetes? Should you deploy a k8s cluster using local storage, then deploy a Ceph cluster inside k8s, then deploy a new k8s cluster with Ceph as storage backend?

I just don't understand your reasoning here.
First you can't deprecate something until you have a replacement or better solution. And even then you need to give time for users to adapt the new solution. But first implement the replacement solution.

Secondly you are using a software to build a distributed storage cluster, and you want to save ~170MB...? I'm not using the k8s stuff, should we drop the kubectl so I can save a few MB and a couple of lines of code?
Sarcasm aside, I believe the idea is to have `ceph-container` as generic as possible so it works in Kuberenetes, Mesos, pure Docker, etc.. Not a solution that is locked to one use-case.
And there are ways to reduce image size without dropping features, have a look at https://github.com/ceph/ceph-container/issues/996.

**Comment by zicklag** [comment]
I use Docker Compose very frequently for my development environments for every application I deploy in Docker Containers ( which will include ceph ). In addition I use [Rancher](http://rancher.com) to run Docker in production with Rancher's Cattle orchestration ( i.e. not Kubernetes ). I definitely appreciate the ability to run the Ceph container outside of a Kubernetes cluster. I would be disappointed to see it lose its ability to run on pure Docker.

**Comment by leseb** [comment]
It seems pretty clear that that ceph-container is used in many different ways. We are not planning on disrupting anything. I guess we are just looking at areas where the codebase can be improved/reduced. Thanks a lot to everyone who joined the conversation.
